#!/usr/bin/env python3

"""
==============================================================================
EXPERIMENT 259 — EXACT n=pq SOURCE-ROW FINGERPRINT / SECOND-CASE EXTRACTION AUDIT
==============================================================================

Experiment 258 established:

    * the known n=6 row is internally exact;
    * the downstream projective/Schur structure is complete;
    * no cross-case theorem can be tested until a second genuine n=pq row
      is supplied.

Experiment 259 therefore acts as a strict extraction/fingerprint layer.

For each genuine source row inserted into CASES it computes a compact
structural fingerprint containing:

    p, q, n
    q1, q3
    gcd(q1,q3)
    q3/q
    (q1-1)/(pq)
    ((q3/q)-1)/(pq)
    valuations at p, q, 7, 17
    residues modulo p, q, pq
    rho modulo 7^e
    k1 modulo 7
    terminal constants
    Schur row
    Schur difference ratios
    candidate p*q^j orbit

The fingerprint is intentionally independent of the later Hensel machinery.

The goal is to make the SECOND real n=pq case immediately comparable
with n=6 once its actual q1,q3 are extracted from the underlying
construction.

No synthetic q1,q3 rows are inserted.

Only main.py is used.
"""

from __future__ import annotations

import sys
from math import gcd


# ============================================================================
# GENUINE SOURCE CASES
# ============================================================================

# Add only REAL rows generated by the underlying construction.
#
# The current known row is n=6.
#
# Example future row:
#
# {
#     "name": "n10",
#     "p": 2,
#     "q": 5,
#     "q1": REAL_VALUE,
#     "q3": REAL_VALUE,
# },
#
CASES = [
    {
        "name": "n6",
        "p": 2,
        "q": 3,
        "q1": 29144191,
        "q3": 24794967,
    },
]


MAX_7_E = 6


# ============================================================================
# HELPERS
# ============================================================================

def valuation(
    x: int,
    p: int,
) -> int:

    x = abs(int(x))

    if x == 0:
        return 10**9

    v = 0

    while x % p == 0:
        x //= p
        v += 1

    return v


def ratio_mod(
    q1: int,
    q3: int,
    modulus: int,
) -> int | None:

    if gcd(
        q3,
        modulus,
    ) != 1:
        return None

    return int(
        (
            (q1 % modulus)
            * pow(
                q3 % modulus,
                -1,
                modulus,
            )
        )
        % modulus
    )


def schur_row(
    p: int,
    q: int,
    q1: int,
    q3: int,
) -> list[int]:

    return [
        q1 - p * (q ** j) * q3
        for j in range(3)
    ]


def fingerprint(
    case: dict,
) -> dict:

    name = case["name"]
    p = int(case["p"])
    q = int(case["q"])
    q1 = int(case["q1"])
    q3 = int(case["q3"])
    n = p * q

    result = {
        "name": name,
        "p": p,
        "q": q,
        "n": n,
        "q1": q1,
        "q3": q3,
    }

    result["gcd"] = gcd(
        q1,
        q3,
    )

    result["valuations"] = {
        "v_p(q1)": valuation(q1, p),
        "v_p(q3)": valuation(q3, p),
        "v_q(q1)": valuation(q1, q),
        "v_q(q3)": valuation(q3, q),
        "v_7(q1)": valuation(q1, 7),
        "v_7(q3)": valuation(q3, 7),
        "v_17(q1)": valuation(q1, 17),
        "v_17(q3)": valuation(q3, 17),
    }

    # --------------------------------------------------------------
    # q-normalization
    # --------------------------------------------------------------

    if q3 % q == 0:

        u = q3 // q

        result["q3_divisible_by_q"] = True
        result["u"] = u
        result["v_q(u)"] = valuation(
            u,
            q,
        )

    else:

        u = None

        result["q3_divisible_by_q"] = False
        result["u"] = None
        result["v_q(u)"] = None

    # --------------------------------------------------------------
    # pq-normalized coordinates
    # --------------------------------------------------------------

    if (
        (q1 - 1) % n == 0
        and
        u is not None
        and
        (u - 1) % n == 0
    ):

        a = (
            q1 - 1
        ) // n

        b = (
            u - 1
        ) // n

    else:

        a = None
        b = None

    result["a"] = a
    result["b"] = b

    # --------------------------------------------------------------
    # residue signature
    # --------------------------------------------------------------

    result["residues"] = {
        "q1_mod_p": q1 % p,
        "q3_mod_p": q3 % p,
        "q1_mod_q": q1 % q,
        "q3_mod_q": q3 % q,
        "q1_mod_n": q1 % n,
        "q3_mod_n": q3 % n,
    }

    # --------------------------------------------------------------
    # projective 7-adic profile
    # --------------------------------------------------------------

    rho_profile = []

    for e in range(
        1,
        MAX_7_E + 1,
    ):

        modulus = 7 ** e

        rho_profile.append(
            ratio_mod(
                q1,
                q3,
                modulus,
            )
        )

    result["rho_profile"] = rho_profile

    rho7 = ratio_mod(
        q1,
        q3,
        7,
    )

    result["rho_mod_7"] = rho7

    # --------------------------------------------------------------
    # mod-7 orbit class
    # --------------------------------------------------------------

    k1_matches = []

    if rho7 is not None:

        for k in range(6):

            if (
                2
                * pow(
                    3,
                    k,
                    7,
                )
            ) % 7 == rho7:

                k1_matches.append(k)

    result["k1_mod_6"] = k1_matches

    # --------------------------------------------------------------
    # candidate terminal orbit
    # --------------------------------------------------------------

    result["candidate_constants"] = [
        p,
        p * q,
        p * q * q,
    ]

    result["terminal_row"] = schur_row(
        p,
        q,
        q1,
        q3,
    )

    s0, s1, s2 = result[
        "terminal_row"
    ]

    d01 = s1 - s0
    d12 = s2 - s1
    d02 = s2 - s0

    result["differences"] = {
        "d01": d01,
        "d12": d12,
        "d02": d02,
        "d01_expected":
            -p * (q - 1) * q3,
        "d12_expected":
            -p * q * (q - 1) * q3,
        "d02_expected":
            -p * (q * q - 1) * q3,
    }

    result["geometry_checks"] = {
        "d01_exact":
            d01
            ==
            -p * (q - 1) * q3,
        "d12_exact":
            d12
            ==
            -p * q * (q - 1) * q3,
        "d02_exact":
            d02
            ==
            -p * (q * q - 1) * q3,
        "d12=q*d01":
            d12 == q * d01,
    }

    # --------------------------------------------------------------
    # simple source differences
    # --------------------------------------------------------------

    result["source_differences"] = {
        "q1-q3":
            q1 - q3,
        "q1-p*q3":
            q1 - p * q3,
        "q1-q*q3":
            q1 - q * q3,
        "q1-n*q3":
            q1 - n * q3,
    }

    return result


# ============================================================================
# MAIN
# ============================================================================

def main():

    print("=" * 78)
    print(
        "EXPERIMENT 259 — EXACT n=pq SOURCE-ROW FINGERPRINT / "
        "SECOND-CASE EXTRACTION AUDIT"
    )
    print("=" * 78)

    failures = []

    fingerprints = []

    # ------------------------------------------------------------------
    # 1. INVENTORY
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("1. GENUINE SOURCE INVENTORY")
    print("=" * 78)

    print(
        f"  case_count={len(CASES)}"
    )

    for case in CASES:

        print(
            f"  {case['name']}: "
            f"(p,q)=({case['p']},{case['q']}) "
            f"n={case['p'] * case['q']}"
        )

    # ------------------------------------------------------------------
    # 2. FINGERPRINTS
    # ------------------------------------------------------------------

    for case in CASES:

        fp = fingerprint(
            case
        )

        fingerprints.append(
            fp
        )

        print()
        print("=" * 78)
        print(
            f"2. FINGERPRINT — {fp['name']}"
        )
        print("=" * 78)

        print(
            f"  (p,q)=({fp['p']},{fp['q']})"
        )

        print(
            f"  n={fp['n']}"
        )

        print(
            f"  q1={fp['q1']}"
        )

        print(
            f"  q3={fp['q3']}"
        )

        print(
            f"  gcd={fp['gcd']}"
        )

        print(
            f"  valuations={fp['valuations']}"
        )

        print(
            f"  q3_divisible_by_q="
            f"{fp['q3_divisible_by_q']}"
        )

        print(
            f"  u=q3/q={fp['u']}"
        )

        print(
            f"  a=(q1-1)/(pq)={fp['a']}"
        )

        print(
            f"  b=((q3/q)-1)/(pq)={fp['b']}"
        )

        print(
            f"  residues={fp['residues']}"
        )

        print(
            f"  rho_mod_7={fp['rho_mod_7']}"
        )

        print(
            f"  rho_profile={fp['rho_profile']}"
        )

        print(
            f"  k1_mod_6={fp['k1_mod_6']}"
        )

        print(
            f"  candidate_constants="
            f"{fp['candidate_constants']}"
        )

        print(
            f"  terminal_row="
            f"{fp['terminal_row']}"
        )

        print(
            f"  differences="
            f"{fp['differences']}"
        )

        print(
            f"  geometry_checks="
            f"{fp['geometry_checks']}"
        )

        print(
            f"  source_differences="
            f"{fp['source_differences']}"
        )

        if fp["gcd"] != 1:

            failures.append(
                (
                    fp["name"],
                    "gcd_not_1",
                )
            )

    # ------------------------------------------------------------------
    # 3. SOURCE-SIDE CHECKS
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("3. SOURCE-SIDE CHECKS")
    print("=" * 78)

    for fp in fingerprints:

        checks = fp[
            "geometry_checks"
        ]

        geometry_ok = all(
            checks.values()
        )

        normalization_ok = True

        if (
            fp["u"] is not None
            and
            fp["a"] is not None
            and
            fp["b"] is not None
        ):

            q1_reconstructed = (
                1
                +
                fp["p"]
                * fp["q"]
                * fp["a"]
            )

            q3_reconstructed = (
                fp["q"]
                * (
                    1
                    +
                    fp["p"]
                    * fp["q"]
                    * fp["b"]
                )
            )

            normalization_ok = (
                q1_reconstructed
                ==
                fp["q1"]
                and
                q3_reconstructed
                ==
                fp["q3"]
            )

        print(
            f"  {fp['name']}: "
            f"Schur_geometry={geometry_ok} "
            f"normalization={normalization_ok}"
        )

        if not geometry_ok:

            failures.append(
                (
                    fp["name"],
                    "Schur_geometry",
                )
            )

        if not normalization_ok:

            failures.append(
                (
                    fp["name"],
                    "normalization",
                )
            )

    # ------------------------------------------------------------------
    # 4. CROSS-CASE COMPARISON
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("4. CROSS-CASE COMPARISON")
    print("=" * 78)

    if len(fingerprints) < 2:

        print(
            "  cross_case_available=False"
        )

        print(
            "  reason="
            "second genuine n=pq source row "
            "has not yet been inserted"
        )

    else:

        print(
            "  cross_case_available=True"
        )

        for i in range(
            len(fingerprints)
        ):

            for j in range(
                i + 1,
                len(fingerprints),
            ):

                left = fingerprints[i]
                right = fingerprints[j]

                print()
                print(
                    f"  COMPARISON "
                    f"{left['name']} vs "
                    f"{right['name']}"
                )

                print(
                    f"    q3/q: "
                    f"{left['u']} vs {right['u']}"
                )

                print(
                    f"    a: "
                    f"{left['a']} vs {right['a']}"
                )

                print(
                    f"    b: "
                    f"{left['b']} vs {right['b']}"
                )

                print(
                    f"    rho_mod_7: "
                    f"{left['rho_mod_7']} vs "
                    f"{right['rho_mod_7']}"
                )

                print(
                    f"    candidate_constants: "
                    f"{left['candidate_constants']} vs "
                    f"{right['candidate_constants']}"
                )

    # ------------------------------------------------------------------
    # 5. PRECISE SECOND-CASE INPUT FORMAT
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("5. REQUIRED SECOND-CASE DATA")
    print("=" * 78)

    print(
        """
To make the next run genuinely decisive, add ONE real row to CASES:

    {
        "name": "nXX",
        "p": <prime p>,
        "q": <prime q>,
        "q1": <exact q1 from construction>,
        "q3": <exact q3 from construction>,
    }

Do not synthesize q1 or q3 from a guessed formula.

The row must come from the same underlying n=pq construction that
produced the known n=6 values

    q1 = 29144191,
    q3 = 24794967.

Once that row is present, this single script will immediately expose
whether the following structures survive across cases:

    q3/q,
    (q1-1)/(pq),
    ((q3/q)-1)/(pq),
    rho mod 7^e,
    terminal p*q^j orbit,
    Schur difference geometry.
"""
    )

    # ------------------------------------------------------------------
    # 6. CURRENT STATUS
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("6. CURRENT STATUS")
    print("=" * 78)

    print(
        f"  genuine_case_count="
        f"{len(fingerprints)}"
    )

    print(
        "  local_projective_theorem_complete=True"
    )

    print(
        "  second_genuine_n_pq_case_available="
        f"{len(fingerprints) >= 2}"
    )

    print(
        "  symbolic_q1_of_p_q_proved=False"
    )

    print(
        "  symbolic_q3_of_p_q_proved=False"
    )

    # ------------------------------------------------------------------
    # FINAL
    # ------------------------------------------------------------------

    final_ok = (
        len(failures) == 0
    )

    print()
    print("=" * 78)
    print("7. FINAL EXACTNESS")
    print("=" * 78)

    print(
        f"  all_internal_source_checks_exact="
        f"{final_ok}"
    )

    print(
        f"  genuine_case_count="
        f"{len(fingerprints)}"
    )

    print(
        f"  cross_case_available="
        f"{len(fingerprints) >= 2}"
    )

    print(
        f"  failures={len(failures)}"
    )

    print(
        "  local_projective_theorem_complete=True"
    )

    print(
        "  n_pq_source_theorem_complete=False"
    )

    print(
        "  decisive_missing_input="
        "second_genuine_n_pq_source_row"
    )

    print(
        f"  ALL BASIC CHECKS PASS={final_ok}"
    )

    print()
    print("EXPERIMENT 259 COMPLETE")


if __name__ == "__main__":

    try:

        main()

    except KeyboardInterrupt:

        print(
            "\nInterrupted."
        )

        sys.exit(130)

    except Exception as exc:

        print(
            "\nFATAL ERROR: "
            + type(exc).__name__
            + ": "
            + str(exc)
        )

        raise

