#!/usr/bin/env python3

"""
START EXPERIMENT 177

Rare-cell direct-P-CRT attack.

Core observation:

For a C-cell (r, s) with residues (a, b),

    p ≡ a (mod r)
    q ≡ b (mod s)

and pq = n gives

    p*q ≡ n (mod s)

so, since b != 0 mod s,

    p ≡ n * b^{-1} (mod s).

Therefore every allowed C-pair (a,b) yields ONE residue class for p:

    p ≡ a                 (mod r)
    p ≡ n*b^{-1}          (mod s)

which combine into

    p ≡ P (mod r*s).

Instead of searching A/B assignments, search directly over p-CRT
classes generated by a few rare C-cells.

The important optimization is to use cells with DISTINCT r and s,
so all CRT moduli remain pairwise coprime.

At every step:

    p ≡ P (mod M)

with p <= sqrt(n).

If P is already larger than sqrt(n), that state is impossible.

If M > sqrt(n), there is at most one p <= sqrt(n) in the class,
so test it immediately.

"""

import math
import time
from itertools import combinations


# ============================================================
# CONFIG
# ============================================================

R1 = [17, 43, 59, 71, 83]
R2 = [19, 37, 61, 73, 89]

BITS = [30, 36, 42, 48, 54]

# Number of rarest cells to try as starting points.
START_CELL_COUNT = 12

# Maximum number of CRT states retained.
MAX_STATES = 2_000_000

# Maximum number of exact divisibility tests.
MAX_EXACT_TESTS = 2_000_000

# We try cell sets of this size.
CELL_DEPTHS = [2, 3, 4, 5]

# Candidate numbers of cells considered together.
MAX_CELL_SET_TRIES = 100


# ============================================================
# BASIC NUMBER THEORY
# ============================================================

def is_prime(n):
    if n < 2:
        return False

    small = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]

    for p in small:
        if n == p:
            return True
        if n % p == 0:
            return False

    d = 41
    step = 2

    while d * d <= n:
        if n % d == 0:
            return False
        d += step
        step = 6 - step

    return True


def egcd(a, b):
    if b == 0:
        return a, 1, 0

    g, x1, y1 = egcd(b, a % b)
    return g, y1, x1 - (a // b) * y1


def inv_mod(a, m):
    g, x, _ = egcd(a, m)

    if g != 1:
        raise ValueError(f"not invertible: {a} mod {m}")

    return x % m


def crt_pair(a1, m1, a2, m2):
    """
    Combine:

        x ≡ a1 mod m1
        x ≡ a2 mod m2

    assuming gcd(m1,m2)=1.
    """

    # x = a1 + m1*t
    # a1 + m1*t ≡ a2 mod m2
    # t ≡ (a2-a1) * inv(m1) mod m2

    inv = inv_mod(m1 % m2, m2)
    t = ((a2 - a1) * inv) % m2

    x = a1 + m1 * t
    m = m1 * m2

    return x % m, m


# ============================================================
# C-CELL GENERATION
# ============================================================

def build_c_relation(n, r, s):
    """
    Return allowed (a,b) residue pairs for the C-cell.

    We use the exact C identity:

        beta ≡ (n-ab) r^{-1} mod s
        alpha ≡ (n-ab) s^{-1} mod r

        C = floor((r*beta + s*alpha + ab)/(r*s))

    For the actual p,q residues, this C value must equal the
    observed carry C determined from n.

    Rather than enumerate k,l, we directly test all residue pairs.

    """

    C_target = n // (r * s)

    # The C identity is periodic in ab and depends only on ab.
    inv_r_mod_s = inv_mod(r % s, s)
    inv_s_mod_r = inv_mod(s % r, r)

    relation = []

    for a in range(1, r):
        for b in range(1, s):
            ab = a * b

            beta = ((n - ab) * inv_r_mod_s) % s
            alpha = ((n - ab) * inv_s_mod_r) % r

            c = (r * beta + s * alpha + ab) // (r * s)

            if c == C_target:
                relation.append((a, b))

    return relation


def build_all_cells(n):
    cells = []

    for i, r in enumerate(R1):
        for j, s in enumerate(R2):

            relation = build_c_relation(n, r, s)

            cells.append({
                "i": i,
                "j": j,
                "r": r,
                "s": s,
                "size": len(relation),
                "relation": relation,
            })

    return cells


# ============================================================
# CELL -> P RESIDUE CLASSES
# ============================================================

def cell_p_classes(n, cell):
    """
    Convert each allowed (a,b) into a p residue modulo r*s.

        p ≡ a mod r
        p ≡ n*b^{-1} mod s

    """

    r = cell["r"]
    s = cell["s"]

    classes = []

    for a, b in cell["relation"]:
        qb = n * inv_mod(b, s)
        qb %= s

        p_res, mod = crt_pair(
            a,
            r,
            qb,
            s,
        )

        classes.append((p_res, mod, a, b))

    return classes


# ============================================================
# DIRECT CRT SEARCH
# ============================================================

def search_cell_set(n, cell_set, verbose=False):
    """
    Search a fixed set of cells directly in p-space.

    State:

        (P, M)

    means

        p ≡ P (mod M)

    and p <= sqrt(n).

    """

    sqrt_n = math.isqrt(n)

    states = [(0, 1)]

    exact_tests = 0

    total_generated = 0

    start = time.perf_counter()

    for depth, cell in enumerate(cell_set, 1):

        classes = cell_p_classes(n, cell)

        next_states = {}

        for P, M in states:

            for qP, qM, _, _ in classes:

                # Because our r,s sets are disjoint primes,
                # all cell moduli are pairwise coprime as long
                # as no row/column modulus is repeated.
                newP, newM = crt_pair(
                    P,
                    M,
                    qP,
                    qM,
                )

                # Smallest positive solution.
                candidate = newP

                if candidate == 0:
                    candidate = newM

                # If the smallest solution is already > sqrt(n),
                # no positive p <= sqrt(n) exists.
                if candidate > sqrt_n:
                    continue

                # Deduplicate identical CRT states.
                next_states[(newP, newM)] = True

                total_generated += 1

                if len(next_states) > MAX_STATES:
                    return {
                        "found": None,
                        "states": len(next_states),
                        "exact_tests": exact_tests,
                        "generated": total_generated,
                        "time": time.perf_counter() - start,
                        "aborted": "MAX_STATES",
                    }

        states = list(next_states.keys())

        if verbose:
            print(
                f"        depth={depth} "
                f"cell=({cell['r']},{cell['s']}) "
                f"relation={cell['size']} "
                f"states={len(states)}"
            )

        # --------------------------------------------------------
        # If M > sqrt(n), every state has at most one p.
        # Test it immediately.
        # --------------------------------------------------------

        reduced = []

        for P, M in states:

            if M > sqrt_n:

                if P == 0:
                    p = M
                else:
                    p = P

                if p <= 1 or p > sqrt_n:
                    continue

                exact_tests += 1

                if exact_tests > MAX_EXACT_TESTS:
                    return {
                        "found": None,
                        "states": len(states),
                        "exact_tests": exact_tests,
                        "generated": total_generated,
                        "time": time.perf_counter() - start,
                        "aborted": "MAX_EXACT_TESTS",
                    }

                if n % p == 0:
                    q = n // p

                    if p * q == n:
                        return {
                            "found": (p, q),
                            "states": len(states),
                            "exact_tests": exact_tests,
                            "generated": total_generated,
                            "time": time.perf_counter() - start,
                            "aborted": None,
                        }

            else:
                reduced.append((P, M))

        # Once all states have modulus > sqrt(n), there is no
        # useful continuation without testing them, so keep only
        # the surviving <=sqrt states.
        if reduced:
            states = reduced
        else:
            # We already tested all unique states with M > sqrt.
            return {
                "found": None,
                "states": 0,
                "exact_tests": exact_tests,
                "generated": total_generated,
                "time": time.perf_counter() - start,
                "aborted": None,
            }

    # ------------------------------------------------------------
    # Final exact testing for remaining states.
    # ------------------------------------------------------------

    for P, M in states:

        if M == 0:
            continue

        p = P

        if p == 0:
            p = M

        # More generally, there may be multiple p values
        # in the class while M <= sqrt(n).
        #
        # Enumerate only if necessary.
        if M <= sqrt_n:

            t_max = (sqrt_n - p) // M

            if t_max < 0:
                continue

            for t in range(t_max + 1):

                candidate = p + t * M

                if candidate < 2:
                    continue

                exact_tests += 1

                if exact_tests > MAX_EXACT_TESTS:
                    return {
                        "found": None,
                        "states": len(states),
                        "exact_tests": exact_tests,
                        "generated": total_generated,
                        "time": time.perf_counter() - start,
                        "aborted": "MAX_EXACT_TESTS",
                    }

                if n % candidate == 0:
                    q = n // candidate

                    if candidate * q == n:
                        return {
                            "found": (candidate, q),
                            "states": len(states),
                            "exact_tests": exact_tests,
                            "generated": total_generated,
                            "time": time.perf_counter() - start,
                            "aborted": None,
                        }

        else:

            if 1 < p <= sqrt_n:

                exact_tests += 1

                if exact_tests > MAX_EXACT_TESTS:
                    return {
                        "found": None,
                        "states": len(states),
                        "exact_tests": exact_tests,
                        "generated": total_generated,
                        "time": time.perf_counter() - start,
                        "aborted": "MAX_EXACT_TESTS",
                    }

                if n % p == 0:
                    q = n // p

                    return {
                        "found": (p, q),
                        "states": len(states),
                        "exact_tests": exact_tests,
                        "generated": total_generated,
                        "time": time.perf_counter() - start,
                        "aborted": None,
                    }

    return {
        "found": None,
        "states": len(states),
        "exact_tests": exact_tests,
        "generated": total_generated,
        "time": time.perf_counter() - start,
        "aborted": None,
    }


# ============================================================
# CHOOSE GOOD CELL SETS
# ============================================================

def independent_cells(cells, chosen):
    """
    Cells must use distinct R1 and R2 indices.

    This guarantees their r*s moduli are pairwise coprime.
    """

    used_i = {c["i"] for c in chosen}
    used_j = {c["j"] for c in chosen}

    for c in cells:

        if c["i"] in used_i:
            continue

        if c["j"] in used_j:
            continue

        yield c


def build_candidate_sets(cells):
    """
    Generate promising cell sets.

    Primary score:

        product(relation sizes)

    Secondary score:

        prefer large CRT modulus

    """

    sorted_cells = sorted(
        cells,
        key=lambda c: (
            c["size"],
            -(c["r"] * c["s"]),
        ),
    )

    candidate_sets = []

    for depth in CELL_DEPTHS:

        def rec(chosen, remaining):

            if len(candidate_sets) >= MAX_CELL_SET_TRIES:
                return

            if len(chosen) == depth:

                product_size = 1
                modulus = 1

                for c in chosen:
                    product_size *= max(1, c["size"])
                    modulus *= c["r"] * c["s"]

                candidate_sets.append(
                    (
                        product_size,
                        -modulus,
                        tuple(chosen),
                    )
                )

                return

            for idx, cell in enumerate(remaining):

                if any(
                    cell["i"] == x["i"] or
                    cell["j"] == x["j"]
                    for x in chosen
                ):
                    continue

                rec(
                    chosen + [cell],
                    remaining[idx + 1:],
                )

                if len(candidate_sets) >= MAX_CELL_SET_TRIES:
                    return

        rec([], sorted_cells)

    candidate_sets.sort(
        key=lambda x: (x[0], x[1])
    )

    return candidate_sets[:MAX_CELL_SET_TRIES]


# ============================================================
# SINGLE INSTANCE
# ============================================================

def run_instance(bits):
    print()
    print("=" * 72)
    print(f"START INSTANCE {bits}-BIT")
    print("=" * 72)

    # ------------------------------------------------------------
    # Generate a semiprime with approximately equal-sized factors.
    # ------------------------------------------------------------

    low = 1 << (bits // 2 - 1)
    high = 1 << (bits // 2 + 1)

    # Deterministic-ish stepping through candidates.
    p = None
    q = None

    for x in range(low | 1, high, 2):

        if not is_prime(x):
            continue

        # Look for a nearby prime q giving the desired bit length.
        target = (1 << bits) // x

        for delta in range(-1000, 1001, 2):

            y = target + delta

            if y <= x:
                continue

            if y.bit_length() * 2 < bits - 1:
                continue

            if is_prime(y):
                p = x
                q = y
                break

        if p is not None:
            break

    if p is None or q is None:
        print("Could not generate test semiprime.")
        print(f"FINISHED INSTANCE {bits}-BIT")
        return

    n = p * q
    sqrt_n = math.isqrt(n)

    print(f"bits(n) = {n.bit_length()}")
    print(f"p       = {p}")
    print(f"q       = {q}")
    print(f"sqrt(n) = {sqrt_n}")

    # ------------------------------------------------------------
    # Build all C cells.
    # ------------------------------------------------------------

    t0 = time.perf_counter()

    cells = build_all_cells(n)

    build_time = time.perf_counter() - t0

    print(f"C-cell build time = {build_time:.6f}s")
    print()

    cells = [
        c
        for c in cells
        if c["size"] > 0
    ]

    cells.sort(
        key=lambda c: (
            c["size"],
            c["r"] * c["s"],
        )
    )

    print("Rarest C-cells:")

    for c in cells[:START_CELL_COUNT]:
        actual_a = p % c["r"]
        actual_b = q % c["s"]

        print(
            f"  ({c['r']:2d},{c['s']:2d}) "
            f"relation={c['size']:4d} "
            f"actual=({actual_a:2d},{actual_b:2d})"
        )

    print()

    # ------------------------------------------------------------
    # Build candidate cell sets.
    # ------------------------------------------------------------

    candidate_sets = build_candidate_sets(cells)

    print(
        f"Candidate cell sets prepared: "
        f"{len(candidate_sets)}"
    )

    # ------------------------------------------------------------
    # Search.
    # ------------------------------------------------------------

    for set_no, (score, neg_modulus, cell_set) in enumerate(
        candidate_sets,
        1
    ):

        print()
        print(
            f"SET {set_no}: "
            f"depth={len(cell_set)} "
            f"relation-product={score}"
        )

        modulus = 1

        for c in cell_set:
            modulus *= c["r"] * c["s"]

            print(
                f"    cell ({c['r']},{c['s']}) "
                f"relation={c['size']}"
            )

        print(
            f"    combined modulus = {modulus}"
        )

        if modulus > sqrt_n:
            print(
                f"    modulus > sqrt(n): "
                f"{modulus} > {sqrt_n}"
            )

        result = search_cell_set(
            n,
            list(cell_set),
            verbose=False,
        )

        print(
            f"    states         = {result['states']}"
        )
        print(
            f"    generated      = {result['generated']}"
        )
        print(
            f"    exact tests    = {result['exact_tests']}"
        )
        print(
            f"    search time    = {result['time']:.6f}s"
        )

        if result["aborted"]:
            print(
                f"    ABORTED        = "
                f"{result['aborted']}"
            )

        if result["found"] is not None:

            fp, fq = result["found"]

            if fp > fq:
                fp, fq = fq, fp

            print()
            print("    *** FACTOR FOUND ***")
            print(f"    factor p = {fp}")
            print(f"    factor q = {fq}")
            print(f"    correct  = {fp * fq == n}")

            print()
            print(f"FINISHED INSTANCE {bits}-BIT")
            return

    print()
    print("No factor recovered by direct rare-cell CRT.")

    print()
    print(f"FINISHED INSTANCE {bits}-BIT")


# ============================================================
# MAIN
# ============================================================

def main():

    print()
    print("START EXPERIMENT 177")
    print()

    print(f"R1 = {R1}")
    print(f"R2 = {R2}")
    print(f"BITS = {BITS}")
    print(f"MAX_STATES = {MAX_STATES}")
    print(f"MAX_EXACT_TESTS = {MAX_EXACT_TESTS}")
    print()

    for bits in BITS:
        run_instance(bits)

    print()
    print("FINISHED EXPERIMENT 177")


if __name__ == "__main__":
    main()
