#!/usr/bin/env python3
"""
==============================================================================
EXPERIMENT 177 — EXACT TERMINAL SCHUR ROW / SCALAR p-POLYNOMIAL AUDIT
==============================================================================

Established by Experiments 175-176:

    a_11 = -1
    b_11 = 2

and therefore, exactly,

    K_11,* = C0 - 2 C1.

For the two terminal equations:

    C0 = q_1(0) [1, 0, 0, 1, 0, 1, 0, ..., 0]

    C1 = q_3(0) [1, 0, 0, 3, 0, 9, 0, ..., 0]

so the three active coordinates of the Schur row are exactly

    s_0 = q_1(0) - 2 q_3(0)
    s_1 = q_1(0) - 6 q_3(0)
    s_2 = q_1(0) - 18 q_3(0)

corresponding to

    1, p, p^2.

Experiment 177 audits this exact scalar row.

Questions:

    1. Is the entire K row exactly generated by those three scalar
       combinations?
    2. What are their exact 2-adic valuations?
    3. How do they compare with the earlier C0-C1 valuations?
    4. Which coordinate gives the leading K 2-adic layer?
    5. At which powers of 2 do the three active coordinates separate?
    6. Does the K row admit a simple exact representation as
           q_1(0)[1,p,p^2] - 2 q_3(0)[1,3,9] ?
    7. Are the nonzero K coordinates primitive after removing their
       common 2-adic content?

No SymPy.
No floating point.
No extrapolation.
No recurrence fitting.
No claim about the original (p,q)-kernel.
"""

from __future__ import annotations

import sys


# ============================================================================
# EXACT DATA
# ============================================================================

Q = {
    1: [
        -126258696,
        -11600759760,
        2668721436,
        1764373740,
        -1338089411,
        495451247,
    ],
    3: [
        9955176,
        -1263551016,
        -152369292,
        -128667196,
        421514439,
    ],
    5: [
        -62398,
        4771718,
        16027881,
    ],
    7: [
        1,
    ],
}

D = {
    1: 5,
    3: 4,
    5: 2,
    7: 0,
}

TRANSITIONS = [
    (1, 3),
    (3, 5),
    (5, 7),
]

FULL_N = 14
CORE_N = 12

BOUNDARY_ROWS = (5, 10)
BOUNDARY_COLS = (12, 13)


# ============================================================================
# HELPERS
# ============================================================================

def q0(p):
    return Q[p][-1]


def basis(p, d):
    return [
        1,
        d,
        d * d,
        p,
        p * d,
        p * p,
    ]


def v2(x):
    if x == 0:
        return None

    x = abs(x)
    e = 0

    while x % 2 == 0:
        x //= 2
        e += 1

    return e


def odd_part(x):
    if x == 0:
        return 0

    e = v2(x)

    return x // (2 ** e)


def mod_profile(x, max_e=10):
    return [
        (2 ** e, x % (2 ** e))
        for e in range(1, max_e + 1)
    ]


def assert_rectangular(A, name="matrix"):
    if not A:
        return

    width = len(A[0])

    for i, row in enumerate(A):

        if len(row) != width:
            raise ValueError(
                f"{name}: row {i} width {len(row)}, "
                f"expected {width}."
            )


def to_mod2(A):
    assert_rectangular(A)

    return [
        [int(x) & 1 for x in row]
        for row in A
    ]


def matrix_support(A):
    return [
        (i, j)
        for i in range(len(A))
        for j in range(len(A[0]))
        if A[i][j]
    ]


def vector_support(v):
    return [
        i
        for i, x in enumerate(v)
        if x != 0
    ]


# ============================================================================
# MATRIX HELPERS
# ============================================================================

def matmul(A, B):

    assert_rectangular(A, "left matrix")
    assert_rectangular(B, "right matrix")

    if not A or not B:
        return []

    if len(A[0]) != len(B):
        raise ValueError(
            f"Dimension mismatch: "
            f"{len(A)}x{len(A[0])} times "
            f"{len(B)}x{len(B[0])}."
        )

    out = [
        [0 for _ in range(len(B[0]))]
        for _ in range(len(A))
    ]

    for i in range(len(A)):

        for k in range(len(B)):

            if A[i][k] == 0:
                continue

            for j in range(len(B[0])):
                out[i][j] += (
                    A[i][k] * B[k][j]
                )

    return out


def divide_exact(A, d, name):

    out = []

    for i, row in enumerate(A):

        new_row = []

        for j, x in enumerate(row):

            if x % d != 0:
                raise ArithmeticError(
                    f"{name}[{i}][{j}]={x} "
                    f"is not divisible by {d}."
                )

            new_row.append(x // d)

        out.append(new_row)

    return out


# ============================================================================
# FULL SYSTEM
# ============================================================================

def build_full_system():

    M = []

    for p, _ in TRANSITIONS:

        for r in range(D[p] + 1):

            d = D[p] - r

            q_first = Q[p][r]
            q_second = (
                Q[p][r + 1]
                if r + 1 < len(Q[p])
                else 0
            )

            b = basis(p, d)

            row = [0] * FULL_N

            for j in range(6):
                row[j] = b[j] * q_first

            for j in range(6):
                row[6 + j] = b[j] * q_second

            if d == 0:
                row[12] = 1
                row[13] = p

            M.append(row)

    if len(M) != FULL_N:
        raise ArithmeticError(
            f"Expected {FULL_N} rows, got {len(M)}."
        )

    return M


# ============================================================================
# SCHUR DATA
# ============================================================================

def build_blocks(M):

    retained = [
        i
        for i in range(FULL_N)
        if i not in BOUNDARY_ROWS
    ]

    retained_rows = [
        M[i]
        for i in retained
    ]

    boundary_rows = [
        M[i]
        for i in BOUNDARY_ROWS
    ]

    F = [
        [
            row[j]
            for j in range(CORE_N)
        ]
        for row in retained_rows
    ]

    B = [
        [
            row[j]
            for j in BOUNDARY_COLS
        ]
        for row in retained_rows
    ]

    H = [
        [
            row[j]
            for j in BOUNDARY_COLS
        ]
        for row in boundary_rows
    ]

    C = [
        [
            row[j]
            for j in range(CORE_N)
        ]
        for row in boundary_rows
    ]

    det_H = (
        H[0][0] * H[1][1]
        - H[0][1] * H[1][0]
    )

    if abs(det_H) != 2:
        raise ArithmeticError(
            f"Expected |det(H)|=2, got {det_H}."
        )

    adj_H = [
        [
            H[1][1],
            -H[0][1],
        ],
        [
            -H[1][0],
            H[0][0],
        ],
    ]

    return F, B, H, adj_H, C, det_H


def compute_K(B, adj_H, C, det_H):

    numerator = matmul(
        B,
        matmul(adj_H, C)
    )

    if any(
        x % det_H != 0
        for row in numerator
        for x in row
    ):
        raise ArithmeticError(
            "Schur numerator is not divisible by det(H)."
        )

    return [
        [
            -(x // det_H)
            for x in row
        ]
        for row in numerator
    ]


# ============================================================================
# MOD-2 RANK
# ============================================================================

def rref_mod2(A):

    M = to_mod2(A)

    if not M:
        return [], []

    rows = len(M)
    cols = len(M[0])

    pivots = []
    pivot_row = 0

    for col in range(cols):

        pivot = None

        for r in range(pivot_row, rows):

            if M[r][col]:
                pivot = r
                break

        if pivot is None:
            continue

        M[pivot_row], M[pivot] = (
            M[pivot],
            M[pivot_row],
        )

        for r in range(rows):

            if r == pivot_row:
                continue

            if M[r][col]:

                for j in range(cols):
                    M[r][j] ^= M[pivot_row][j]

        pivots.append(col)
        pivot_row += 1

        if pivot_row == rows:
            break

    return M, pivots


def rank_mod2(A):

    if not A:
        return 0

    return len(
        rref_mod2(A)[1]
    )


# ============================================================================
# MAIN
# ============================================================================

def main():

    print("=" * 78)
    print(
        "EXPERIMENT 177 — EXACT TERMINAL SCHUR ROW / "
        "SCALAR p-POLYNOMIAL AUDIT"
    )
    print("=" * 78)

    M = build_full_system()

    F, B, H, adj_H, C, det_H = build_blocks(M)

    K = compute_K(
        B,
        adj_H,
        C,
        det_H
    )

    # The distinguished Schur row is row 11.
    K_row = K[11]

    # ------------------------------------------------------------------
    # 1. EXACT SCHUR DATA
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("1. EXACT SCHUR DATA")
    print("=" * 78)

    print(
        f"  H={H}"
    )

    print(
        f"  det_H={det_H}"
    )

    print(
        f"  adj_H={adj_H}"
    )

    print(
        f"  K_row_index=11"
    )

    print(
        f"  K_row={K_row}"
    )

    print(
        f"  K_row_support={vector_support(K_row)}"
    )

    # ------------------------------------------------------------------
    # 2. EXACT SCALAR FORMULA
    # ------------------------------------------------------------------

    q1 = q0(1)
    q3 = q0(3)

    s_1 = q1 - 2 * q3
    s_p = q1 - 6 * q3
    s_p2 = q1 - 18 * q3

    formula_row = [
        s_1,
        0,
        0,
        s_p,
        0,
        s_p2,
        0,
        0,
        0,
        0,
        0,
        0,
    ]

    formula_exact = (
        formula_row == K_row
    )

    print()
    print("=" * 78)
    print("2. EXACT SCALAR TERMINAL FORMULA")
    print("=" * 78)

    print(
        f"  q_1(0)={q1}"
    )

    print(
        f"  q_3(0)={q3}"
    )

    print(
        f"  s_1=q1-2*q3={s_1}"
    )

    print(
        f"  s_p=q1-6*q3={s_p}"
    )

    print(
        f"  s_p2=q1-18*q3={s_p2}"
    )

    print(
        f"  formula_row={formula_row}"
    )

    print(
        f"  formula_reconstructs_K_row="
        f"{formula_exact}"
    )

    # ------------------------------------------------------------------
    # 3. 2-ADIC PROFILE
    # ------------------------------------------------------------------

    labels = [
        "1",
        "p",
        "p^2",
    ]

    values = [
        s_1,
        s_p,
        s_p2,
    ]

    valuations = [
        v2(x)
        for x in values
    ]

    print()
    print("=" * 78)
    print("3. EXACT K-ROW 2-ADIC PROFILE")
    print("=" * 78)

    for label, value in zip(
        labels,
        values
    ):

        print(
            f"  coordinate={label}: "
            f"value={value} "
            f"v2={v2(value)} "
            f"odd_part={odd_part(value)}"
        )

    minimum_v2 = min(
        e
        for e in valuations
        if e is not None
    )

    minimum_coordinates = [
        labels[i]
        for i, e in enumerate(valuations)
        if e == minimum_v2
    ]

    print(
        f"  minimum_v2={minimum_v2}"
    )

    print(
        f"  minimum_coordinates="
        f"{minimum_coordinates}"
    )

    # ------------------------------------------------------------------
    # 4. K ROW LAYER BY LAYER
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("4. K-ROW 2-ADIC RESIDUE PROFILE")
    print("=" * 78)

    for label, value in zip(
        labels,
        values
    ):

        print(
            f"  {label}: "
            f"{mod_profile(value, 10)}"
        )

    # ------------------------------------------------------------------
    # 5. FIRST NONZERO K LAYER
    # ------------------------------------------------------------------

    first_layer = [
        (
            value // (2 ** minimum_v2)
        ) % 2
        for value in values
    ]

    print()
    print("=" * 78)
    print("5. FIRST NONZERO K LAYER")
    print("=" * 78)

    print(
        f"  K_active / 2^{minimum_v2} mod 2="
        f"{first_layer}"
    )

    print(
        f"  first_layer_support="
        f"{vector_support(first_layer)}"
    )

    # ------------------------------------------------------------------
    # 6. COMPARISON WITH C0, C1
    # ------------------------------------------------------------------

    C0 = C[0]
    C1 = C[1]

    expected_K = [
        C0[j] - 2 * C1[j]
        for j in range(CORE_N)
    ]

    exact_C_formula = (
        expected_K == K_row
    )

    print()
    print("=" * 78)
    print("6. DIRECT C0 - 2*C1 COMPARISON")
    print("=" * 78)

    print(
        f"  C0={C0}"
    )

    print(
        f"  C1={C1}"
    )

    print(
        f"  C0_minus_2C1={expected_K}"
    )

    print(
        f"  exact_C_formula={exact_C_formula}"
    )

    # ------------------------------------------------------------------
    # 7. COMMON CONTENT
    # ------------------------------------------------------------------

    nonzero_K = [
        abs(x)
        for x in K_row
        if x != 0
    ]

    gcd_value = nonzero_K[0]

    for x in nonzero_K[1:]:

        a = gcd_value
        b = x

        while b:
            a, b = b, a % b

        gcd_value = a

    print()
    print("=" * 78)
    print("7. K-ROW COMMON CONTENT")
    print("=" * 78)

    print(
        f"  gcd_nonzero_K_row="
        f"{gcd_value}"
    )

    print(
        f"  gcd_v2={v2(gcd_value)}"
    )

    print(
        f"  gcd_odd_part="
        f"{odd_part(gcd_value)}"
    )

    # ------------------------------------------------------------------
    # 8. NORMALIZED LEADING LAYER
    # ------------------------------------------------------------------

    primitive_K = [
        x // gcd_value
        for x in K_row
    ]

    print()
    print("=" * 78)
    print("8. PRIMITIVE K-ROW")
    print("=" * 78)

    print(
        f"  primitive_K_row={primitive_K}"
    )

    print(
        f"  primitive_support="
        f"{vector_support(primitive_K)}"
    )

    # ------------------------------------------------------------------
    # 9. CORE RANK
    # ------------------------------------------------------------------

    A = [
        [
            F[i][j] + K[i][j]
            for j in range(CORE_N)
        ]
        for i in range(CORE_N)
    ]

    rank_F = rank_mod2(F)
    rank_K = rank_mod2(
        to_mod2(K)
    )
    rank_A = rank_mod2(A)

    print()
    print("=" * 78)
    print("9. CORE RANK REFERENCE")
    print("=" * 78)

    print(
        f"  rank_F_ret_mod2={rank_F}"
    )

    print(
        f"  rank_K_mod2={rank_K}"
    )

    print(
        f"  rank_A_mod2={rank_A}"
    )

    print(
        f"  rank_drop={rank_F-rank_A}"
    )

    # ------------------------------------------------------------------
    # 10. STRUCTURAL INTERPRETATION
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("10. STRUCTURAL INTERPRETATION")
    print("=" * 78)

    print(
        """
Experiments 175-176 showed that the two terminal boundary equations
enter the Schur correction asymmetrically:

    K = K0 + K1,

with

    K0 = C0 on the distinguished row,
    K1 = -2 C1 on the distinguished row.

Experiment 177 compresses that entire matrix statement into three
exact scalar combinations:

    q1 - 2 q3,
    q1 - 6 q3,
    q1 - 18 q3.

These are the coefficients of

    1,
    p,
    p^2

in the terminal Schur row.

The purpose is to determine whether the enormous exact K entries
contain any additional arithmetic structure once the Schur mechanism
has been completely eliminated.

A low-complexity relation among these three scalar combinations would
be stronger evidence than simply observing their large size.

No general recurrence or formula is inferred from these three values.
"""
    )

    # ------------------------------------------------------------------
    # 11. FINAL
    # ------------------------------------------------------------------

    scalar_data_exact = (
        q1 == 495451247
        and q3 == 421514439
    )

    formula_ok = (
        formula_exact
        and exact_C_formula
    )

    first_layer_ok = (
        first_layer == [
            1 if e == minimum_v2 else 0
            for e in valuations
        ]
    )

    final_ok = (
        abs(det_H) == 2
        and scalar_data_exact
        and formula_ok
        and minimum_v2 == 1
        and rank_F == 4
        and rank_K == 1
        and rank_A == 3
        and len(nonzero_K) == 3
    )

    print()
    print("=" * 78)
    print("11. FINAL EXACTNESS")
    print("=" * 78)

    print(
        f"  abs_det_H_2="
        f"{abs(det_H) == 2}"
    )

    print(
        f"  terminal_q_data_exact="
        f"{scalar_data_exact}"
    )

    print(
        f"  scalar_formula_exact="
        f"{formula_ok}"
    )

    print(
        f"  minimum_K_v2_is_1="
        f"{minimum_v2 == 1}"
    )

    print(
        f"  first_layer_exact="
        f"{first_layer_ok}"
    )

    print(
        f"  K_rank_one="
        f"{rank_K == 1}"
    )

    print(
        f"  F_rank_four="
        f"{rank_F == 4}"
    )

    print(
        f"  A_rank_three="
        f"{rank_A == 3}"
    )

    print(
        f"  three_nonzero_K_coordinates="
        f"{len(nonzero_K) == 3}"
    )

    print(
        f"  failures={0 if final_ok else 1}"
    )

    print(
        f"  ALL BASIC CHECKS PASS={final_ok}"
    )

    print()
    print("EXPERIMENT 177 COMPLETE")


if __name__ == "__main__":

    try:
        main()

    except KeyboardInterrupt:
        print("\nInterrupted.")
        sys.exit(130)

    except Exception as exc:

        print(
            "\nFATAL ERROR: "
            + type(exc).__name__
            + ": "
            + str(exc)
        )
        raise

