#include <algorithm>
#include <array>
#include <cstdint>
#include <iostream>
#include <random>
#include <string>

using u64 = std::uint64_t;
using u128 = unsigned __int128;

constexpr int MAX_DIGITS = 128;

struct Digits {
    std::array<u64, MAX_DIGITS> d{};
    int len = 1;
};

std::string to_string_u128(u128 x) {
    if (x == 0) {
        return "0";
    }

    std::string s;

    while (x > 0) {
        const unsigned digit =
            static_cast<unsigned>(x % 10);

        s.push_back(
            static_cast<char>('0' + digit)
        );

        x /= 10;
    }

    std::reverse(s.begin(), s.end());
    return s;
}

u128 power_u128(
    u128 base,
    unsigned exp
) {
    u128 result = 1;

    while (exp > 0) {
        if (exp & 1u) {
            result *= base;
        }

        base *= base;
        exp >>= 1u;
    }

    return result;
}

Digits to_base_p(
    u128 x,
    u64 p
) {
    Digits out;

    if (x == 0) {
        out.d[0] = 0;
        out.len = 1;
        return out;
    }

    int i = 0;

    while (x > 0) {
        out.d[i++] =
            static_cast<u64>(
                x % static_cast<u128>(p)
            );

        x /= static_cast<u128>(p);
    }

    out.len = i;
    return out;
}

u64 get_digit(
    const Digits& d,
    int i
) {
    if (i < 0 || i >= d.len) {
        return 0;
    }

    return d.d[i];
}

u128 total_miss(
    const Digits& md
) {
    u128 result = 1;

    for (int i = 0; i < md.len; ++i) {
        result *=
            static_cast<u128>(
                md.d[i] + 1
            );
    }

    return result;
}

/*
    Independent MSB-first digit DP reference.

    M_m(y) =
        #{x : 0 <= x <= y and x <=_p m}
*/
u128 miss_prefix_dp(
    u128 m,
    u128 y,
    u64 p
) {
    if (y >= m) {
        return total_miss(
            to_base_p(m, p)
        );
    }

    const Digits md =
        to_base_p(m, p);

    const Digits yd =
        to_base_p(y, p);

    const int len =
        std::max(
            md.len,
            yd.len
        );

    u128 less = 0;
    u128 tight = 1;

    for (int i = len - 1;
         i >= 0;
         --i) {

        const u64 mi =
            get_digit(md, i);

        const u64 yi =
            get_digit(yd, i);

        const u128 from_less =
            less *
            static_cast<u128>(
                mi + 1
            );

        const u128 from_tight =
            tight *
            static_cast<u128>(
                std::min<u64>(
                    mi + 1,
                    yi
                )
            );

        const u128 next_tight =
            yi <= mi
                ? tight
                : 0;

        less =
            from_less +
            from_tight;

        tight =
            next_tight;
    }

    return less + tight;
}

/*
    Correct closed prefix formula.

    For y < m, let h be the most significant digit
    where y_h != m_h.

    Define

        W_i = product_{j<i}(m_j+1).

    Then

        M_m(y)
        =
        sum_{i>h} y_i W_i
        +
        y_h W_h
        +
        M_{m_<h}(y_<h).

    The first summation counts complete lower blocks
    generated by the already-smaller higher prefix.
*/
u128 miss_prefix_closed(
    u128 m,
    u128 y,
    u64 p
) {
    const Digits md =
        to_base_p(m, p);

    if (y >= m) {
        return total_miss(md);
    }

    const Digits yd =
        to_base_p(y, p);

    const int len =
        std::max(
            md.len,
            yd.len
        );

    int h = -1;

    for (int i = len - 1;
         i >= 0;
         --i) {

        if (get_digit(md, i) !=
            get_digit(yd, i)) {

            h = i;
            break;
        }
    }

    if (h < 0) {
        return 1;
    }

    /*
        Compute W_i.
    */
    std::array<u128, MAX_DIGITS + 1> weight{};

    weight[0] = 1;

    for (int i = 0;
         i < len;
         ++i) {

        weight[i + 1] =
            weight[i] *
            static_cast<u128>(
                get_digit(md, i) + 1
            );
    }

    u128 result = 0;

    /*
        Complete blocks from digits above h.
    */
    for (int i = len - 1;
         i > h;
         --i) {

        result +=
            static_cast<u128>(
                get_digit(yd, i)
            ) *
            weight[i];
    }

    /*
        At h:

            x_h = 0,...,y_h-1

        gives y_h complete lower blocks.
    */
    result +=
        static_cast<u128>(
            get_digit(yd, h)
        ) *
        weight[h];

    /*
        Equal h-digit boundary.
    */
    const u128 ph =
        power_u128(
            static_cast<u128>(p),
            static_cast<unsigned>(h)
        );

    const u128 low_m =
        m % ph;

    const u128 low_y =
        y % ph;

    result +=
        miss_prefix_dp(
            low_m,
            low_y,
            p
        );

    return result;
}

struct Stats {
    std::size_t cases = 0;
    std::size_t failures = 0;
    std::size_t printed = 0;
};

void check_case(
    u64 p,
    u128 m,
    u128 y,
    Stats& stats
) {
    ++stats.cases;

    const u128 reference =
        miss_prefix_dp(
            m,
            y,
            p
        );

    const u128 closed =
        miss_prefix_closed(
            m,
            y,
            p
        );

    if (reference == closed) {
        return;
    }

    ++stats.failures;

    if (stats.printed >= 5) {
        return;
    }

    ++stats.printed;

    std::cout
        << "\nFAIL\n";

    std::cout
        << "p="
        << p
        << '\n';

    std::cout
        << "m="
        << to_string_u128(m)
        << '\n';

    std::cout
        << "y="
        << to_string_u128(y)
        << '\n';

    std::cout
        << "reference="
        << to_string_u128(reference)
        << '\n';

    std::cout
        << "closed="
        << to_string_u128(closed)
        << '\n';
}

void small_exhaustive(
    Stats& stats
) {
    const u64 primes[] = {
        2, 3, 5, 7, 11
    };

    for (u64 p : primes) {
        for (u128 m = 0;
             m <= 500;
             ++m) {

            for (u128 y = 0;
                 y <= 500;
                 ++y) {

                check_case(
                    p,
                    m,
                    y,
                    stats
                );
            }
        }
    }
}

void random_tests(
    Stats& stats
) {
    std::mt19937_64 rng(
        0x288288ULL
    );

    const u64 primes[] = {
        2, 3, 5, 7, 11,
        13, 17, 19, 23,
        29, 31, 37, 41, 43
    };

    for (std::size_t i = 0;
         i < 100000;
         ++i) {

        const u64 p =
            primes[
                rng() %
                (sizeof(primes) /
                 sizeof(primes[0]))
            ];

        const u128 m =
            static_cast<u128>(
                rng()
            ) %
            static_cast<u128>(
                1000000000000000000ULL
            );

        const u128 y =
            static_cast<u128>(
                rng()
            ) %
            static_cast<u128>(
                1000000000000000000ULL
            );

        check_case(
            p,
            m,
            y,
            stats
        );
    }
}

int main() {
    std::cout
        << "START EXPERIMENT 288\n";

    std::cout
        << "CORRECTED CLOSED MISS-PREFIX FORMULA\n";

    std::cout
        << "REFERENCE = INDEPENDENT DIGIT DP\n";

    std::cout
        << "RESTORED HIGHER-DIGIT BLOCK CONTRIBUTIONS\n\n";

    Stats exhaustive;
    Stats random;

    small_exhaustive(
        exhaustive
    );

    std::cout
        << "small_exhaustive_cases="
        << exhaustive.cases
        << " fail="
        << exhaustive.failures
        << '\n';

    random_tests(
        random
    );

    std::cout
        << "random_cases="
        << random.cases
        << " fail="
        << random.failures
        << '\n';

    const std::size_t total_cases =
        exhaustive.cases +
        random.cases;

    const std::size_t total_failures =
        exhaustive.failures +
        random.failures;

    std::cout
        << "\nTOTAL\n";

    std::cout
        << "cases="
        << total_cases
        << " fail="
        << total_failures
        << '\n';

    const bool pass =
        total_failures == 0;

    std::cout
        << "\nOVERALL PASS="
        << (pass ? 1 : 0)
        << '\n';

    std::cout
        << "FINISHED EXPERIMENT 288\n";

    return pass ? 0 : 1;
}