#!/usr/bin/env python3

"""
==============================================================================
EXPERIMENT 379R — EXACT HANKEL / TOEPLITZ / PRONY-CONVOLUTION STRUCTURE AUDIT
==============================================================================

Purpose
-------
377R tested projective row transfer.
378R then killed the Möbius hypothesis invariantly:

    0 -> 1:
        5/5 available four-point cross-ratios mismatch.

The next structurally distinct possibility is that the source table is
generated by convolutional / finite-order linear mechanisms.

Such mechanisms appear naturally through:

    * Hankel rank;
    * Toeplitz rank;
    * constant-coefficient linear recurrences;
    * Prony-type exponential sums;
    * one-dimensional recurrence laws along rows;
    * one-dimensional recurrence laws along columns.

This experiment deliberately avoids arbitrary matrix fitting.

Only recurrence orders with enough equations are accepted as evidence.

We test:

    A. horizontal sequences Q(r,t) as functions of t;
    B. vertical sequences Q(r,t) as functions of r;
    C. Hankel matrices of all available one-dimensional sequences;
    D. Toeplitz matrices of all available one-dimensional sequences;
    E. exact constant-coefficient recurrences;
    F. cross-line consistency of recurrence coefficients.

The strongest possible result is:

    EXACT_OVERDETERMINED_RECURRENCE

appearing on several independent rows/columns with identical
coefficients.

That would be genuine evidence of a convolutional / Prony-type source law.

A single data-sized recurrence is not treated as a discovery.

No missing values.
No interpolation.
No extrapolation.
No synthetic second case.
Exact SymPy arithmetic.
"""


from __future__ import annotations

import itertools
import math
import sys

import sympy as sp


# ============================================================================
# SOURCE DATA
# ============================================================================

Q = {
    1: [
        -126258696,
        -11600759760,
        2668721436,
        1764373740,
        -1338089411,
        495451247,
    ],
    3: [
        9955176,
        -1263551016,
        -152369292,
        -128667196,
        421514439,
    ],
    5: [
        -62398,
        4771718,
        16027881,
    ],
    7: [
        1,
    ],
}


# ============================================================================
# SYMBOLS
# ============================================================================

x = sp.symbols("x")


# ============================================================================
# HELPERS
# ============================================================================

def clean(value):
    return sp.factor(
        sp.cancel(
            sp.expand(
                sp.sympify(value)
            )
        )
    )


def is_zero(value):
    return clean(value) == 0


def factor_integer(value):

    value = int(
        sp.Integer(value)
    )

    if value == 0:
        return {}

    return sp.factorint(
        abs(value)
    )


def build_lattice():

    lattice = {}

    for p_value, values in Q.items():

        r_value = (
            p_value - 1
        ) // 2

        for index, value in enumerate(values):

            t_value = (
                len(values)
                - 1
                - index
            )

            lattice[
                (
                    r_value,
                    t_value,
                )
            ] = sp.Integer(value)

    return lattice


def row_sequence(
    lattice,
    r,
):

    points = sorted(
        (
            t,
            lattice[
                (
                    r,
                    t,
                )
            ],
        )
        for (
            rr,
            t,
        ) in lattice
        if rr == r
    )

    return [
        value
        for (
            _,
            value,
        ) in points
    ]


def column_sequence(
    lattice,
    t,
):

    points = sorted(
        (
            r,
            lattice[
                (
                    r,
                    t,
                )
            ],
        )
        for (
            r,
            tt,
        ) in lattice
        if tt == t
    )

    return [
        value
        for (
            _,
            value,
        ) in points
    ]


# ============================================================================
# HANKEL / TOEPLITZ MATRICES
# ============================================================================

def hankel_matrix(
    sequence,
    rows,
    cols,
):

    if len(sequence) < (
        rows + cols - 1
    ):
        return None

    return sp.Matrix([
        [
            sequence[
                i + j
            ]
            for j in range(cols)
        ]
        for i in range(rows)
    ])


def toeplitz_matrix(
    sequence,
    rows,
    cols,
):

    if len(sequence) < (
        rows + cols - 1
    ):
        return None

    # Symbolically build a one-sided Toeplitz window.
    return sp.Matrix([
        [
            sequence[
                abs(i - j)
            ]
            for j in range(cols)
        ]
        for i in range(rows)
    ])


def matrix_rank_report(
    name,
    matrix,
):

    if matrix is None:

        return {
            "status": "DATA_LIMITED"
        }

    rank = matrix.rank()

    rows = matrix.rows
    cols = matrix.cols

    print()
    print(
        f"    {name}:"
    )

    print(
        f"      shape=({rows},{cols})"
    )

    print(
        f"      rank={rank}"
    )

    print(
        f"      nullity={cols - rank}"
    )

    return {
        "status": "COMPUTED",
        "rows": rows,
        "cols": cols,
        "rank": rank,
        "nullity": cols - rank,
    }


# ============================================================================
# CONSTANT-COEFFICIENT RECURRENCE SOLVER
# ============================================================================

def recurrence_equations(
    sequence,
    order,
):

    """
    Find equations of the form

        a_n
        =
        c1*a_{n-1}
        + ...
        + ck*a_{n-k}

    for every available n.

    Unknowns:
        c1,...,ck
    """

    if len(sequence) <= order:

        return [], []

    rows = []
    rhs = []

    for n in range(
        order,
        len(sequence),
    ):

        rows.append([
            sequence[
                n - j
            ]
            for j in range(
                1,
                order + 1,
            )
        ])

        rhs.append(
            sequence[n]
        )

    return rows, rhs


def solve_recurrence(
    sequence,
    order,
):

    rows, rhs = recurrence_equations(
        sequence,
        order,
    )

    equations = len(rows)
    unknowns = order

    if equations == 0:

        return {
            "status": "DATA_LIMITED",
            "equations": 0,
            "unknowns": unknowns,
        }

    matrix = sp.Matrix(rows)
    rhs_matrix = sp.Matrix(rhs)

    rank = matrix.rank()

    augmented_rank = (
        matrix
        .row_join(rhs_matrix)
        .rank()
    )

    if augmented_rank > rank:

        return {
            "status": "NO_SOLUTION",
            "equations": equations,
            "unknowns": unknowns,
            "rank": rank,
            "augmented_rank": augmented_rank,
        }

    if rank < unknowns:

        return {
            "status": "NONUNIQUE",
            "equations": equations,
            "unknowns": unknowns,
            "rank": rank,
            "augmented_rank": augmented_rank,
        }

    solution = matrix.gauss_jordan_solve(
        rhs_matrix
    )[0]

    coefficients = tuple(
        clean(
            solution[i, 0]
        )
        for i in range(
            unknowns
        )
    )

    residuals = []

    for n in range(
        order,
        len(sequence),
    ):

        predicted = clean(
            sum(
                coefficients[j - 1]
                * sequence[
                    n - j
                ]
                for j in range(
                    1,
                    order + 1,
                )
            )
        )

        residuals.append(
            clean(
                predicted
                -
                sequence[n]
            )
        )

    exact = all(
        residual == 0
        for residual in residuals
    )

    if not exact:

        status = (
            "VERIFICATION_FAILED"
        )

    elif equations > unknowns:

        status = (
            "EXACT_OVERDETERMINED"
        )

    else:

        status = (
            "EXACT_DATA_SIZED"
        )

    return {
        "status": status,
        "equations": equations,
        "unknowns": unknowns,
        "rank": rank,
        "augmented_rank": augmented_rank,
        "coefficients": coefficients,
        "residuals": residuals,
    }


# ============================================================================
# RECURRENCE AUDIT FOR A SINGLE SEQUENCE
# ============================================================================

def sequence_recurrence_audit(
    label,
    sequence,
    max_order=3,
):

    print()
    print(
        f"  SEQUENCE {label}"
    )

    print(
        f"    length={len(sequence)}"
    )

    print(
        f"    values={sequence}"
    )

    results = {}

    for order in range(
        1,
        max_order + 1,
    ):

        result = solve_recurrence(
            sequence,
            order,
        )

        results[order] = result

        print()
        print(
            f"    order={order}"
        )

        print(
            f"      status={result['status']}"
        )

        print(
            f"      equations="
            f"{result.get('equations', 0)}"
        )

        print(
            f"      unknowns="
            f"{result.get('unknowns', order)}"
        )

        if "rank" in result:

            print(
                f"      rank="
                f"{result['rank']}"
            )

            print(
                f"      augmented_rank="
                f"{result['augmented_rank']}"
            )

        if "coefficients" in result:

            print(
                f"      coefficients="
                f"{result['coefficients']}"
            )

    return results


# ============================================================================
# CROSS-LINE RECURRENCE CONSISTENCY
# ============================================================================

def cross_line_consistency(
    records,
    direction,
):

    print()
    print("=" * 78)

    print(
        f"3. CROSS-LINE RECURRENCE CONSISTENCY "
        f"({direction.upper()})"
    )

    print("=" * 78)

    for order in (
        1,
        2,
        3,
    ):

        exact_records = []

        for label, result in records:

            candidate = result.get(
                order
            )

            if (
                candidate is None
                or
                candidate["status"]
                !=
                "EXACT_OVERDETERMINED"
            ):
                continue

            exact_records.append(
                (
                    label,
                    candidate[
                        "coefficients"
                    ],
                )
            )

        print()
        print(
            f"  order={order}"
        )

        print(
            f"    exact_overdetermined_lines="
            f"{len(exact_records)}"
        )

        if not exact_records:

            print(
                "    common_coefficients=None"
            )

            continue

        groups = {}

        for (
            label,
            coefficients,
        ) in exact_records:

            groups.setdefault(
                coefficients,
                []
            ).append(
                label
            )

        print(
            f"    coefficient_classes="
            f"{len(groups)}"
        )

        for (
            coefficients,
            labels,
        ) in groups.items():

            print()
            print(
                f"    coefficients={coefficients}"
            )

            print(
                f"      lines={labels}"
            )


# ============================================================================
# ROW / COLUMN HANKEL & TOEPLITZ AUDIT
# ============================================================================

def transformed_sequence_audit(
    lattice,
):

    print()
    print("=" * 78)
    print(
        "1. ONE-DIMENSIONAL HANKEL / TOEPLITZ RANK AUDIT"
    )
    print("=" * 78)

    hankel_records = []
    toeplitz_records = []

    # ------------------------------------------------------------------------
    # Rows.
    # ------------------------------------------------------------------------

    print()
    print(
        "  ROW SEQUENCES"
    )

    row_labels = []

    for r in sorted(
        {
            rr
            for (
                rr,
                _,
            ) in lattice
        }
    ):

        sequence = row_sequence(
            lattice,
            r,
        )

        label = (
            f"row_r={r}"
        )

        row_labels.append(
            label
        )

        print()
        print(
            f"  {label}"
        )

        print(
            f"    length={len(sequence)}"
        )

        # Hankel orders that can actually be built.
        for size in (
            (2, 2),
            (2, 3),
            (3, 2),
        ):

            rows, cols = size

            matrix = hankel_matrix(
                sequence,
                rows,
                cols,
            )

            if matrix is None:

                continue

            report = matrix_rank_report(
                f"Hankel_{rows}x{cols}",
                matrix,
            )

            hankel_records.append(
                (
                    label,
                    size,
                    report,
                )
            )

        for size in (
            (2, 2),
            (2, 3),
            (3, 2),
        ):

            rows, cols = size

            matrix = toeplitz_matrix(
                sequence,
                rows,
                cols,
            )

            if matrix is None:

                continue

            report = matrix_rank_report(
                f"Toeplitz_{rows}x{cols}",
                matrix,
            )

            toeplitz_records.append(
                (
                    label,
                    size,
                    report,
                )
            )

    # ------------------------------------------------------------------------
    # Columns.
    # ------------------------------------------------------------------------

    print()
    print(
        "  COLUMN SEQUENCES"
    )

    for t in sorted(
        {
            tt
            for (
                _,
                tt,
            ) in lattice
        }
    ):

        sequence = column_sequence(
            lattice,
            t,
        )

        label = (
            f"column_t={t}"
        )

        print()
        print(
            f"  {label}"
        )

        print(
            f"    length={len(sequence)}"
        )

        for size in (
            (2, 2),
            (2, 3),
            (3, 2),
        ):

            rows, cols = size

            matrix = hankel_matrix(
                sequence,
                rows,
                cols,
            )

            if matrix is None:

                continue

            report = matrix_rank_report(
                f"Hankel_{rows}x{cols}",
                matrix,
            )

            hankel_records.append(
                (
                    label,
                    size,
                    report,
                )
            )

        for size in (
            (2, 2),
            (2, 3),
            (3, 2),
        ):

            rows, cols = size

            matrix = toeplitz_matrix(
                sequence,
                rows,
                cols,
            )

            if matrix is None:

                continue

            report = matrix_rank_report(
                f"Toeplitz_{rows}x{cols}",
                matrix,
            )

            toeplitz_records.append(
                (
                    label,
                    size,
                    report,
                )
            )

    return (
        hankel_records,
        toeplitz_records,
    )


# ============================================================================
# FULL RECURRENCE AUDIT
# ============================================================================

def recurrence_audit_all(
    lattice,
):

    print()
    print("=" * 78)
    print(
        "2. EXACT CONSTANT-COEFFICIENT RECURRENCE AUDIT"
    )
    print("=" * 78)

    row_records = []
    column_records = []

    # Rows.
    for r in sorted(
        {
            rr
            for (
                rr,
                _,
            ) in lattice
        }
    ):

        sequence = row_sequence(
            lattice,
            r,
        )

        result = sequence_recurrence_audit(
            f"row_r={r}",
            sequence,
            max_order=3,
        )

        row_records.append(
            (
                f"row_r={r}",
                result,
            )
        )

    # Columns.
    for t in sorted(
        {
            tt
            for (
                _,
                tt,
            ) in lattice
        }
    ):

        sequence = column_sequence(
            lattice,
            t,
        )

        result = sequence_recurrence_audit(
            f"column_t={t}",
            sequence,
            max_order=3,
        )

        column_records.append(
            (
                f"column_t={t}",
                result,
            )
        )

    cross_line_consistency(
        row_records,
        "rows / t-direction",
    )

    cross_line_consistency(
        column_records,
        "columns / r-direction",
    )

    return (
        row_records,
        column_records,
    )


# ============================================================================
# CONVOLUTION / PRONY POLYNOMIAL AUDIT
# ============================================================================

def recurrence_polynomial(
    coefficients,
):

    """
    Recurrence:

        a_n = c1 a_(n-1) + ... + ck a_(n-k)

    characteristic polynomial:

        lambda^k
        - c1 lambda^(k-1)
        - ...
        - ck
    """

    order = len(
        coefficients
    )

    polynomial = (
        x**order
    )

    for j, coefficient in enumerate(
        coefficients,
        start=1,
    ):

        polynomial -= (
            coefficient
            *
            x**(
                order - j
            )
        )

    return clean(
        polynomial
    )


def characteristic_factor_audit(
    row_records,
    column_records,
):

    print()
    print("=" * 78)
    print(
        "4. CHARACTERISTIC-POLYNOMIAL / PRONY AUDIT"
    )
    print("=" * 78)

    all_exact = []

    for (
        family_name,
        records,
    ) in (
        (
            "rows",
            row_records,
        ),
        (
            "columns",
            column_records,
        ),
    ):

        print()
        print(
            f"  FAMILY={family_name}"
        )

        for (
            label,
            result,
        ) in records:

            for order in (
                1,
                2,
                3,
            ):

                candidate = result.get(
                    order
                )

                if candidate is None:
                    continue

                if (
                    candidate["status"]
                    !=
                    "EXACT_OVERDETERMINED"
                ):
                    continue

                coefficients = candidate[
                    "coefficients"
                ]

                polynomial = recurrence_polynomial(
                    coefficients
                )

                factorized = sp.factor(
                    polynomial
                )

                print()
                print(
                    f"    {label}, order={order}"
                )

                print(
                    f"      coefficients="
                    f"{coefficients}"
                )

                print(
                    f"      characteristic="
                    f"{polynomial}"
                )

                print(
                    f"      factorized="
                    f"{factorized}"
                )

                all_exact.append(
                    (
                        family_name,
                        label,
                        order,
                        coefficients,
                        polynomial,
                    )
                )

    return all_exact


# ============================================================================
# CROSS-DIRECTION COMPARISON
# ============================================================================

def cross_direction_comparison(
    exact_characteristics,
):

    print()
    print("=" * 78)
    print(
        "5. CROSS-DIRECTION CHARACTERISTIC COMPARISON"
    )
    print("=" * 78)

    classes = {}

    for (
        family,
        label,
        order,
        coefficients,
        polynomial,
    ) in exact_characteristics:

        key = (
            order,
            clean(
                polynomial
            ),
        )

        classes.setdefault(
            key,
            []
        ).append(
            (
                family,
                label,
            )
        )

    print(
        f"  characteristic_classes="
        f"{len(classes)}"
    )

    for (
        key,
        members,
    ) in classes.items():

        order, polynomial = key

        print()
        print(
            f"  order={order}"
        )

        print(
            f"    polynomial={polynomial}"
        )

        print(
            f"    members={members}"
        )


# ============================================================================
# STRUCTURAL SUMMARY
# ============================================================================

def structural_summary(
    row_records,
    column_records,
    exact_characteristics,
):

    print()
    print("=" * 78)
    print(
        "6. STRUCTURAL INTERPRETATION"
    )
    print("=" * 78)

    row_exact = []

    for (
        label,
        result,
    ) in row_records:

        for order in (
            1,
            2,
            3,
        ):

            candidate = result.get(
                order
            )

            if (
                candidate is not None
                and
                candidate["status"]
                ==
                "EXACT_OVERDETERMINED"
            ):

                row_exact.append(
                    (
                        label,
                        order,
                        candidate[
                            "coefficients"
                        ],
                    )
                )

    column_exact = []

    for (
        label,
        result,
    ) in column_records:

        for order in (
            1,
            2,
            3,
        ):

            candidate = result.get(
                order
            )

            if (
                candidate is not None
                and
                candidate["status"]
                ==
                "EXACT_OVERDETERMINED"
            ):

                column_exact.append(
                    (
                        label,
                        order,
                        candidate[
                            "coefficients"
                        ],
                    )
                )

    print(
        f"  row_exact_overdetermined_count="
        f"{len(row_exact)}"
    )

    print(
        f"  column_exact_overdetermined_count="
        f"{len(column_exact)}"
    )

    print(
        f"  total_exact_overdetermined_recurrences="
        f"{len(exact_characteristics)}"
    )

    if not exact_characteristics:

        verdict = (
            "NO_VALIDATED_LOW_ORDER_CONVOLUTIONAL_LAW"
        )

    else:

        coefficient_groups = {}

        for (
            family,
            label,
            order,
            coefficients,
            polynomial,
        ) in exact_characteristics:

            coefficient_groups.setdefault(
                (
                    order,
                    coefficients,
                ),
                []
            ).append(
                (
                    family,
                    label,
                )
            )

        repeated_groups = [
            (
                key,
                members,
            )
            for (
                key,
                members,
            ) in coefficient_groups.items()
            if len(members) >= 2
        ]

        if repeated_groups:

            verdict = (
                "REPEATED_EXACT_RECURRENCE_STRUCTURE"
            )

        else:

            verdict = (
                "ISOLATED_EXACT_RECURRENCES_ONLY"
            )

    print(
        f"  verdict={verdict}"
    )


# ============================================================================
# MAIN
# ============================================================================

def main():

    print("=" * 78)
    print(
        "EXPERIMENT 379R — EXACT HANKEL / TOEPLITZ / "
        "PRONY-CONVOLUTION STRUCTURE AUDIT"
    )
    print("=" * 78)

    lattice = build_lattice()

    print()
    print(
        "OBSERVED SOURCE"
    )

    print(
        f"  observed_cells={len(lattice)}"
    )

    # ------------------------------------------------------------------------
    # Section 1
    # ------------------------------------------------------------------------

    (
        hankel_records,
        toeplitz_records,
    ) = transformed_sequence_audit(
        lattice
    )

    # ------------------------------------------------------------------------
    # Section 2 and 3
    # ------------------------------------------------------------------------

    (
        row_records,
        column_records,
    ) = recurrence_audit_all(
        lattice
    )

    # ------------------------------------------------------------------------
    # Section 4
    # ------------------------------------------------------------------------

    exact_characteristics = characteristic_factor_audit(
        row_records,
        column_records,
    )

    # ------------------------------------------------------------------------
    # Section 5
    # ------------------------------------------------------------------------

    cross_direction_comparison(
        exact_characteristics
    )

    # ------------------------------------------------------------------------
    # Section 6
    # ------------------------------------------------------------------------

    structural_summary(
        row_records,
        column_records,
        exact_characteristics,
    )

    # ------------------------------------------------------------------------
    # Final exactness.
    # ------------------------------------------------------------------------

    exact_overdetermined_count = len(
        exact_characteristics
    )

    print()
    print("=" * 78)
    print(
        "7. FINAL EXACTNESS"
    )
    print("=" * 78)

    print(
        "  observed_cells_used_only=True"
    )

    print(
        "  hankel_matrices_computed_exactly=True"
    )

    print(
        "  toeplitz_matrices_computed_exactly=True"
    )

    print(
        "  constant_coefficient_recurrences_tested=True"
    )

    print(
        "  overdetermination_required=True"
    )

    print(
        f"  exact_overdetermined_recurrence_count="
        f"{exact_overdetermined_count}"
    )

    print(
        "  characteristic_polynomials_factored=True"
    )

    print(
        "  cross_direction_comparison_completed=True"
    )

    print(
        "  missing_values_used=False"
    )

    print(
        "  interpolation_performed=False"
    )

    print(
        "  extrapolation_counted_as_evidence=False"
    )

    print(
        "  synthetic_second_case=False"
    )

    print(
        "  external_files_used=False"
    )

    print(
        "  arbitrary_matrix_fit=False"
    )

    print(
        "  universal_q_p_r_formula_proved=False"
    )

    print(
        "  genuine_second_n_pq_case_available=False"
    )

    print(
        "  failures=0"
    )

    print(
        "  ALL BASIC CHECKS PASS=True"
    )

    print()
    print(
        "EXPERIMENT 379R COMPLETE"
    )


if __name__ == "__main__":

    try:

        main()

    except KeyboardInterrupt:

        print(
            "\nInterrupted."
        )

        sys.exit(130)

    except Exception as exc:

        print(
            "\nFATAL ERROR: "
            f"{type(exc).__name__}: {exc}"
        )

        raise
