#!/usr/bin/env python3

"""
==============================================================================
EXPERIMENT 80 — EXACT INDEXED COUPLED RECURRENCE SEARCH
==============================================================================

Goal
----
Investigate whether the coupled channel sequence

    V_j(u) = [ A_{2j}(u) ]
             [ B_{2j+1}(u) ]

is generated by a single indexed recurrence

    V_j
      = M_1(j,u) V_{j-1}
      + M_2(j,u) V_{j-2}.

The entries of M_1 and M_2 are searched as exact polynomials in

    j = layer index
    u = t(t+1)
    t = N/X.

This is intended to distinguish:

    local interpolation
        from
    an actual indexed construction law.

Everything is exact over QQ / symbolic expression domains.

No floating point.
No regression.
No numerical fitting.
No approximate arithmetic.

A recurrence is accepted only when the exact symbolic identities vanish.
"""


import sympy as sp


# ============================================================================
# SYMBOLS
# ============================================================================

t = sp.Symbol("t")
u = sp.Symbol("u")
j = sp.Symbol("j")


# ============================================================================
# NORMALIZED h_d(t)
# ============================================================================

H = {
    16: (
        -9*t**8
        -36*t**7
        -84*t**6
        -126*t**5
        -126*t**4
        -84*t**3
        -36*t**2
        -9*t
        -1
    ),

    15: (
        88*t**9
        +396*t**8
        +1164*t**7
        +2226*t**6
        +2898*t**5
        +2604*t**4
        +1596*t**3
        +639*t**2
        +151*t
        +16
    ),

    14: (
        -276*t**10
        -1380*t**9
        -5460*t**8
        -13560*t**7
        -23058*t**6
        -27510*t**5
        -23100*t**4
        -13410*t**3
        -5135*t**2
        -1169*t
        -120
    ),

    13: (
        288*t**11
        +1584*t**10
        +10340*t**9
        +34650*t**8
        +79464*t**7
        +127512*t**6
        +145530*t**5
        +117975*t**4
        +66550*t**3
        +24882*t**2
        +5551*t
        +560
    ),

    12: (
        -50*t**12
        -300*t**11
        -7436*t**10
        -34430*t**9
        -117810*t**8
        -267960*t**7
        -426888*t**6
        -484110*t**5
        -390225*t**4
        -219010*t**3
        -81510*t**2
        -18109*t
        -1820
    ),

    11: (
        1300*t**11
        +7150*t**10
        +62634*t**9
        +228228*t**8
        +552552*t**7
        +918918*t**6
        +1075074*t**5
        +887172*t**4
        +507078*t**3
        +191477*t**2
        +43043*t
        +4368
    ),

    10: (
        -10010*t**10
        -50050*t**9
        -252252*t**8
        -708708*t**7
        -1303302*t**6
        -1639638*t**5
        -1429428*t**4
        -852852*t**3
        -333333*t**2
        -77077*t
        -8008
    ),

    9: (
        35750*t**9
        +160875*t**8
        +563420*t**7
        +1221220*t**6
        +1732458*t**5
        +1653470*t**4
        +1058540*t**3
        +437700*t**2
        +105979*t
        +11441
    ),

    8: (
        -71500*t**8
        -286000*t**7
        -755664*t**6
        -1265992*t**5
        -1375360*t**4
        -974400*t**3
        -436832*t**2
        -112964*t
        -12879
    ),

    7: (
        88400*t**7
        +309400*t**6
        +636888*t**5
        +818720*t**4
        +663680*t**3
        +331500*t**2
        +93604*t
        +11476
    ),

    6: (
        -71400*t**6
        -214200*t**5
        -344352*t**4
        -331704*t**3
        -190296*t**2
        -60044*t
        -8092
    ),

    5: (
        38760*t**5
        +96900*t**4
        +119016*t**3
        +81624*t**2
        +29736*t
        +4494
    ),

    4: (
        -14250*t**4
        -28500*t**3
        -25380*t**2
        -11130*t
        -1946
    ),

    3: (
        3500*t**3
        +5250*t**2
        +3038*t
        +644
    ),

    2: (
        -550*t**2
        -550*t
        -156
    ),

    1: (
        50*t
        +25
    ),

    0: sp.Integer(-2),
}


# ============================================================================
# BASIC EXACT HELPERS
# ============================================================================

def E(expr):
    return sp.expand(sp.sympify(expr))


def simplify_exact(expr):
    return sp.cancel(sp.expand(expr))


def is_zero(expr):
    return sp.simplify(E(expr)) == 0


def poly_t(expr):
    return sp.Poly(
        E(expr),
        t,
        domain="QQ",
    )


def poly_u(expr):
    return sp.Poly(
        E(expr),
        u,
        domain="QQ",
    )


def poly_j_u(expr):
    """
    Used only after temporary recurrence coefficients have been solved.
    """
    return sp.Poly(
        E(expr),
        j,
        u,
        domain="QQ",
    )


def degree_u(expr):
    expr = E(expr)

    if expr == 0:
        return -sp.oo

    return poly_u(expr).degree()


# ============================================================================
# EXACT INVOLUTION DECOMPOSITION
# ============================================================================

def recover_u_polynomial(target_t):
    """
    Recover A(u) from an exact invariant polynomial A(t(t+1)).
    Temporary coefficients are handled over EX.
    """

    target_t = E(target_t)

    if target_t == 0:
        return sp.Integer(0)

    deg_t = poly_t(target_t).degree()

    if deg_t % 2 != 0:
        raise RuntimeError(
            "Expected an even degree in t."
        )

    deg_u = deg_t // 2

    unknowns = sp.symbols(
        f"a0:{deg_u + 1}"
    )

    candidate = E(
        sum(
            unknowns[k] * u**k
            for k in range(deg_u + 1)
        )
    )

    diff = E(
        candidate.subs(
            u,
            t*(t+1),
        )
        -
        target_t
    )

    p = sp.Poly(
        diff,
        t,
        domain="EX",
    )

    equations = []

    for power in range(
        p.degree(),
        -1,
        -1,
    ):

        coefficient = E(
            p.coeff_monomial(
                t**power
            )
        )

        if coefficient != 0:
            equations.append(
                coefficient
            )

    if not equations:
        return sp.Integer(0)

    Aeq, beq = sp.linear_eq_to_matrix(
        equations,
        unknowns,
    )

    if Aeq.rank() != Aeq.row_join(beq).rank():
        raise RuntimeError(
            "No exact u-polynomial reconstruction."
        )

    solution_set = sp.linsolve(
        (
            Aeq,
            beq,
        ),
        unknowns,
    )

    tuples = list(solution_set)

    if len(tuples) != 1:
        raise RuntimeError(
            "Unexpected non-unique u-polynomial."
        )

    solution = tuples[0]

    for value in solution:

        unresolved = (
            E(value).free_symbols
            -
            set(unknowns)
        )

        if unresolved:
            raise RuntimeError(
                "Free parameters remained in u reconstruction."
            )

    solved = candidate.subs(
        dict(
            zip(
                unknowns,
                solution,
            )
        )
    )

    solved = sp.cancel(
        E(solved)
    )

    # Exact final QQ coercion.
    sp.Poly(
        solved,
        u,
        domain=sp.QQ,
    )

    check = E(
        solved.subs(
            u,
            t*(t+1),
        )
        -
        target_t
    )

    if not is_zero(check):
        raise RuntimeError(
            "u reconstruction verification failed."
        )

    return solved


def decompose_layer(d):

    h = E(H[d])

    partner = E(
        h.subs(
            t,
            -1-t,
        )
    )

    even = E(
        (h + partner) / 2
    )

    odd = E(
        (h - partner) / 2
    )

    A_d = recover_u_polynomial(
        even
    )

    if odd == 0:

        B_d = sp.Integer(0)

    else:

        odd_poly = sp.Poly(
            odd,
            t,
            domain=sp.QQ,
        )

        divisor = sp.Poly(
            2*t + 1,
            t,
            domain=sp.QQ,
        )

        quotient, remainder = sp.div(
            odd_poly,
            divisor,
        )

        if not remainder.is_zero:
            raise RuntimeError(
                f"d={d}: odd part not divisible by 2t+1."
            )

        B_d = recover_u_polynomial(
            quotient.as_expr()
        )

    reconstructed = E(
        A_d.subs(
            u,
            t*(t+1),
        )
        +
        (2*t+1)
        *
        B_d.subs(
            u,
            t*(t+1),
        )
    )

    if not is_zero(
        reconstructed-h
    ):
        raise RuntimeError(
            f"d={d}: involution reconstruction failed."
        )

    return (
        sp.cancel(A_d),
        sp.cancel(B_d),
    )


# ============================================================================
# CHANNEL DATA
# ============================================================================

CHANNEL = {
    d: decompose_layer(d)
    for d in range(
        16,
        -1,
        -1,
    )
}

A = {
    d: CHANNEL[d][0]
    for d in range(
        0,
        17,
        2,
    )
}

B = {
    d: CHANNEL[d][1]
    for d in range(
        1,
        16,
        2,
    )
}


# ============================================================================
# COUPLED VECTOR SEQUENCE
# ============================================================================

V = {
    jj: sp.Matrix([
        E(A[2*jj]),
        E(B[2*jj+1]),
    ])
    for jj in range(8)
}


# ============================================================================
# BIVARIATE MATRIX UNKNOWN GENERATOR
# ============================================================================

def make_matrix_polynomial(
    name,
    deg_j,
    deg_u,
):

    unknowns = []
    entries = []

    for r in range(2):

        row = []

        for c in range(2):

            terms = []

            for a in range(
                deg_j + 1
            ):

                for b in range(
                    deg_u + 1
                ):

                    symbol = sp.Symbol(
                        f"{name}_{r}_{c}_{a}_{b}"
                    )

                    unknowns.append(
                        symbol
                    )

                    terms.append(
                        symbol
                        *
                        j**a
                        *
                        u**b
                    )

            row.append(
                E(
                    sum(terms)
                )
            )

        entries.append(row)

    return (
        sp.Matrix(entries),
        unknowns,
    )


# ============================================================================
# EXACT ORDER-1 INDEXED RECURRENCE
# ============================================================================

def search_order1(
    deg_j,
    deg_u,
):

    M, unknowns = make_matrix_polynomial(
        "m1",
        deg_j,
        deg_u,
    )

    equations = []

    for jj in range(
        1,
        8,
    ):

        predicted = E(
            M[0,0].subs(j, jj)
            * V[jj-1][0]
            +
            M[0,1].subs(j, jj)
            * V[jj-1][1]
        )

        predicted2 = E(
            M[1,0].subs(j, jj)
            * V[jj-1][0]
            +
            M[1,1].subs(j, jj)
            * V[jj-1][1]
        )

        differences = [
            E(
                predicted
                -
                V[jj][0]
            ),
            E(
                predicted2
                -
                V[jj][1]
            ),
        ]

        for diff in differences:

            if diff == 0:
                continue

            p = sp.Poly(
                diff,
                u,
                domain="EX",
            )

            for power in range(
                p.degree(),
                -1,
                -1,
            ):

                coefficient = E(
                    p.coeff_monomial(
                        u**power
                    )
                )

                if coefficient != 0:
                    equations.append(
                        coefficient
                    )

    if not equations:
        return None

    Aeq, beq = sp.linear_eq_to_matrix(
        equations,
        unknowns,
    )

    rank = Aeq.rank()
    aug_rank = Aeq.row_join(beq).rank()

    if rank != aug_rank:
        return {
            "exists": False,
            "unique": False,
            "rank": rank,
            "unknowns": len(unknowns),
            "nullity": len(unknowns)-rank,
            "matrix": None,
        }

    solution_set = sp.linsolve(
        (
            Aeq,
            beq,
        ),
        unknowns,
    )

    tuples = list(solution_set)

    if len(tuples) != 1:
        raise RuntimeError(
            "Unexpected solution-set structure."
        )

    solution = tuples[0]

    free = set()

    for value in solution:
        free |= E(value).free_symbols

    free -= set(unknowns)

    if free:
        raise RuntimeError(
            "Unexpected unresolved free symbols."
        )

    substitution = dict(
        zip(
            unknowns,
            solution,
        )
    )

    solved = M.subs(
        substitution
    )

    solved = sp.Matrix([
        [
            sp.cancel(
                E(
                    solved[r,c]
                )
            )
            for c in range(2)
        ]
        for r in range(2)
    ])

    # Exact coefficient verification.
    for jj in range(
        1,
        8,
    ):

        prediction = solved.subs(
            j,
            jj,
        ) * V[jj-1]

        target = V[jj]

        for k in range(2):

            if not is_zero(
                prediction[k]
                -
                target[k]
            ):
                raise RuntimeError(
                    "Order-1 recurrence failed final verification."
                )

    return {
        "exists": True,
        "unique": True,
        "rank": rank,
        "unknowns": len(unknowns),
        "nullity": len(unknowns)-rank,
        "matrix": solved,
    }


# ============================================================================
# EXACT ORDER-2 INDEXED RECURRENCE
# ============================================================================

def search_order2(
    deg_j,
    deg_u,
):

    M1, unknowns1 = make_matrix_polynomial(
        "m1",
        deg_j,
        deg_u,
    )

    M2, unknowns2 = make_matrix_polynomial(
        "m2",
        deg_j,
        deg_u,
    )

    unknowns = (
        unknowns1
        +
        unknowns2
    )

    equations = []

    for jj in range(
        2,
        8,
    ):

        pred = sp.zeros(
            2,
            1,
        )

        for r in range(2):

            pred_r = E(
                M1[r,0].subs(j, jj)
                * V[jj-1][0]
                +
                M1[r,1].subs(j, jj)
                * V[jj-1][1]
                +
                M2[r,0].subs(j, jj)
                * V[jj-2][0]
                +
                M2[r,1].subs(j, jj)
                * V[jj-2][1]
            )

            pred[r] = pred_r

        for r in range(2):

            diff = E(
                pred[r]
                -
                V[jj][r]
            )

            if diff == 0:
                continue

            p = sp.Poly(
                diff,
                u,
                domain="EX",
            )

            for power in range(
                p.degree(),
                -1,
                -1,
            ):

                coefficient = E(
                    p.coeff_monomial(
                        u**power
                    )
                )

                if coefficient != 0:
                    equations.append(
                        coefficient
                    )

    if not equations:
        return None

    Aeq, beq = sp.linear_eq_to_matrix(
        equations,
        unknowns,
    )

    rank = Aeq.rank()
    aug_rank = Aeq.row_join(beq).rank()

    if rank != aug_rank:
        return {
            "exists": False,
            "unique": False,
            "rank": rank,
            "unknowns": len(unknowns),
            "nullity": len(unknowns)-rank,
            "M1": None,
            "M2": None,
        }

    solution_set = sp.linsolve(
        (
            Aeq,
            beq,
        ),
        unknowns,
    )

    tuples = list(solution_set)

    if len(tuples) != 1:
        raise RuntimeError(
            "Unexpected order-2 solution-set structure."
        )

    solution = tuples[0]

    # Reject unresolved parameters.
    free = set()

    for value in solution:
        free |= E(value).free_symbols

    free -= set(unknowns)

    if free:
        raise RuntimeError(
            "Order-2 recurrence contains unresolved free parameters."
        )

    substitution = dict(
        zip(
            unknowns,
            solution,
        )
    )

    solved1 = M1.subs(
        substitution
    )

    solved2 = M2.subs(
        substitution
    )

    solved1 = sp.Matrix([
        [
            sp.cancel(
                E(
                    solved1[r,c]
                )
            )
            for c in range(2)
        ]
        for r in range(2)
    ])

    solved2 = sp.Matrix([
        [
            sp.cancel(
                E(
                    solved2[r,c]
                )
            )
            for c in range(2)
        ]
        for r in range(2)
    ])

    # Exact verification over all available transitions.
    for jj in range(
        2,
        8,
    ):

        prediction = (
            solved1.subs(j, jj)
            * V[jj-1]
            +
            solved2.subs(j, jj)
            * V[jj-2]
        )

        target = V[jj]

        for k in range(2):

            if not is_zero(
                prediction[k]
                -
                target[k]
            ):
                raise RuntimeError(
                    "Order-2 recurrence final verification failed."
                )

    return {
        "exists": True,
        "unique": True,
        "rank": rank,
        "unknowns": len(unknowns),
        "nullity": len(unknowns)-rank,
        "M1": solved1,
        "M2": solved2,
    }


# ============================================================================
# ORDER-3 INDEXED RECURRENCE
# ============================================================================

def search_order3(
    deg_j,
    deg_u,
):

    matrices = []

    unknowns = []

    for idx in range(3):

        M, syms = make_matrix_polynomial(
            f"m{idx}",
            deg_j,
            deg_u,
        )

        matrices.append(M)
        unknowns.extend(syms)

    equations = []

    for jj in range(
        3,
        8,
    ):

        prediction = sp.zeros(
            2,
            1,
        )

        for r in range(2):

            expression = 0

            for lag in range(3):

                expression += (
                    matrices[lag][r,0].subs(j, jj)
                    *
                    V[jj-lag-1][0]
                )

                expression += (
                    matrices[lag][r,1].subs(j, jj)
                    *
                    V[jj-lag-1][1]
                )

            prediction[r] = E(
                expression
            )

        for r in range(2):

            diff = E(
                prediction[r]
                -
                V[jj][r]
            )

            if diff == 0:
                continue

            p = sp.Poly(
                diff,
                u,
                domain="EX",
            )

            for power in range(
                p.degree(),
                -1,
                -1,
            ):

                coefficient = E(
                    p.coeff_monomial(
                        u**power
                    )
                )

                if coefficient != 0:
                    equations.append(
                        coefficient
                    )

    if not equations:
        return None

    Aeq, beq = sp.linear_eq_to_matrix(
        equations,
        unknowns,
    )

    rank = Aeq.rank()
    aug_rank = Aeq.row_join(beq).rank()

    if rank != aug_rank:
        return {
            "exists": False,
            "unique": False,
            "rank": rank,
            "unknowns": len(unknowns),
            "nullity": len(unknowns)-rank,
        }

    solution_set = sp.linsolve(
        (
            Aeq,
            beq,
        ),
        unknowns,
    )

    tuples = list(solution_set)

    if len(tuples) != 1:
        raise RuntimeError(
            "Unexpected order-3 solution structure."
        )

    solution = tuples[0]

    free = set()

    for value in solution:
        free |= E(value).free_symbols

    free -= set(unknowns)

    if free:
        raise RuntimeError(
            "Order-3 recurrence has unresolved parameters."
        )

    return {
        "exists": True,
        "unique": True,
        "rank": rank,
        "unknowns": len(unknowns),
        "nullity": len(unknowns)-rank,
        "solution": solution,
    }


# ============================================================================
# CONVERT OPERATOR TO BIVARIATE POLYNOMIAL
# ============================================================================

def total_degree_j_u(expr):

    p = sp.Poly(
        E(expr),
        j,
        u,
        domain="QQ",
    )

    if p.is_zero:
        return -sp.oo

    degrees = []

    for monomial in p.monoms():

        degrees.append(
            monomial[0]
            +
            monomial[1]
        )

    return max(degrees)


# ============================================================================
# FRESH NUMERICAL-EXACT VALIDATION
# ============================================================================

def fresh_value(
    expr,
    u_value,
):

    return sp.cancel(
        E(
            expr.subs(
                u,
                u_value,
            )
        )
    )


# ============================================================================
# MAIN
# ============================================================================

def main():

    print("="*78)
    print(
        "EXPERIMENT 80 — EXACT INDEXED COUPLED RECURRENCE SEARCH"
    )
    print("="*78)

    # ------------------------------------------------------------------------
    # 0
    # ------------------------------------------------------------------------

    print()
    print("="*78)
    print("0. EXACT SYMBOLIC SETUP")
    print("="*78)

    print("  t = N/X")
    print("  u = t(t+1)")
    print("  V_j = [A_{2j}, B_{2j+1}]^T")
    print("  target recurrence:")
    print("      V_j = M1(j,u)V_{j-1} + M2(j,u)V_{j-2}")
    print("  arithmetic = exact QQ / symbolic EX")
    print("  floating point = forbidden")

    # ------------------------------------------------------------------------
    # 1 INVOLUTION
    # ------------------------------------------------------------------------

    print()
    print("="*78)
    print("1. EXACT INVOLUTION VALIDATION")
    print("="*78)

    involution_ok = True

    for d in range(
        16,
        -1,
        -1,
    ):

        h = E(H[d])

        partner = E(
            h.subs(
                t,
                -1-t,
            )
        )

        A_d, B_d = CHANNEL[d]

        reconstructed = E(
            A_d.subs(
                u,
                t*(t+1),
            )
            +
            (2*t+1)
            *
            B_d.subs(
                u,
                t*(t+1),
            )
        )

        ok = is_zero(
            reconstructed-h
        )

        involution_ok &= ok

        print(
            f"  d={d:2d}: "
            f"invariant={is_zero(partner-h)} "
            f"anti_invariant={is_zero(partner+h)} "
            f"reconstruction={ok}"
        )

    print()
    print(
        "  ALL INVOLUTION CHECKS =",
        involution_ok,
    )

    # ------------------------------------------------------------------------
    # 2 CHANNEL PROFILE
    # ------------------------------------------------------------------------

    print()
    print("="*78)
    print("2. COUPLED CHANNEL PROFILE")
    print("="*78)

    for jj in range(8):

        d_even = 2*jj
        d_odd = 2*jj+1

        print()
        print(
            f"  V_{jj} = "
            f"[A_{d_even}, B_{d_odd}]^T"
        )

        print(
            "    A =",
            A[d_even],
        )

        print(
            "    B =",
            B[d_odd],
        )

    # ------------------------------------------------------------------------
    # 3 ORDER-1 SCAN
    # ------------------------------------------------------------------------

    print()
    print("="*78)
    print("3. ORDER-1 INDEXED RECURRENCE SCAN")
    print("="*78)

    order1_results = []

    for deg_j in range(
        0,
        5,
    ):

        for deg_u in range(
            0,
            5,
        ):

            result = search_order1(
                deg_j,
                deg_u,
            )

            if result is None:
                status = "NONE"

            elif result["exists"]:
                status = (
                    "UNIQUE"
                    if result["unique"]
                    else "PARAMETERIZED"
                )

            else:
                status = "INCONSISTENT"

            print(
                f"  deg_j={deg_j}, "
                f"deg_u={deg_u}: "
                f"{status}"
            )

            order1_results.append(
                (
                    deg_j,
                    deg_u,
                    result,
                )
            )

    # ------------------------------------------------------------------------
    # 4 ORDER-2 SCAN
    # ------------------------------------------------------------------------

    print()
    print("="*78)
    print("4. ORDER-2 INDEXED RECURRENCE SCAN")
    print("="*78)

    order2_results = []

    first_order2_solution = None

    for deg_j in range(
        0,
        5,
    ):

        for deg_u in range(
            0,
            5,
        ):

            result = search_order2(
                deg_j,
                deg_u,
            )

            if result is None:
                status = "NONE"

            elif result["exists"]:
                if result["unique"]:
                    status = "UNIQUE"
                else:
                    status = "PARAMETERIZED"

            else:
                status = "INCONSISTENT"

            print(
                f"  deg_j={deg_j}, "
                f"deg_u={deg_u}: "
                f"{status}"
            )

            order2_results.append(
                (
                    deg_j,
                    deg_u,
                    result,
                )
            )

            if (
                first_order2_solution is None
                and result is not None
                and result["exists"]
                and result["unique"]
            ):
                first_order2_solution = (
                    deg_j,
                    deg_u,
                    result,
                )

    # ------------------------------------------------------------------------
    # 5 SELECT FIRST UNIQUE ORDER-2 LAW
    # ------------------------------------------------------------------------

    print()
    print("="*78)
    print("5. FIRST UNIQUE ORDER-2 INDEXED LAW")
    print("="*78)

    if first_order2_solution is None:

        print(
            "  No unique exact order-2 recurrence found "
            "through degree 4 in j and u."
        )

    else:

        deg_j, deg_u, result = (
            first_order2_solution
        )

        M1 = result["M1"]
        M2 = result["M2"]

        print(
            f"  degree in j = {deg_j}"
        )

        print(
            f"  degree in u = {deg_u}"
        )

        print(
            "  rank =",
            result["rank"],
        )

        print(
            "  unknowns =",
            result["unknowns"],
        )

        print(
            "  nullity =",
            result["nullity"],
        )

        print()
        print(
            "  M1(j,u) ="
        )

        print(M1)

        print()
        print(
            "  M2(j,u) ="
        )

        print(M2)

        print()
        print(
            "  total degrees of M1 entries:"
        )

        for r in range(2):
            for c in range(2):
                print(
                    f"    M1[{r},{c}] =",
                    total_degree_j_u(
                        M1[r,c]
                    )
                )

        print()
        print(
            "  total degrees of M2 entries:"
        )

        for r in range(2):
            for c in range(2):
                print(
                    f"    M2[{r},{c}] =",
                    total_degree_j_u(
                        M2[r,c]
                    )
                )

    # ------------------------------------------------------------------------
    # 6 ORDER-3 SCAN
    # ------------------------------------------------------------------------

    print()
    print("="*78)
    print("6. ORDER-3 INDEXED RECURRENCE SCAN")
    print("="*78)

    first_order3_solution = None

    for deg_j in range(
        0,
        4,
    ):

        for deg_u in range(
            0,
            4,
        ):

            result = search_order3(
                deg_j,
                deg_u,
            )

            if result is None:
                status = "NONE"

            elif result["exists"]:
                status = "UNIQUE"

                if (
                    first_order3_solution is None
                ):
                    first_order3_solution = (
                        deg_j,
                        deg_u,
                        result,
                    )

            else:
                status = "INCONSISTENT"

            print(
                f"  deg_j={deg_j}, "
                f"deg_u={deg_u}: "
                f"{status}"
            )

    # ------------------------------------------------------------------------
    # 7 FRESH SEMIPRIME
    # ------------------------------------------------------------------------

    print()
    print("="*78)
    print("7. FRESH EXACT SEMIPRIME")
    print("="*78)

    p = sp.Integer(
        106621
    )

    q = sp.Integer(
        246473
    )

    if not sp.isprime(p):
        raise RuntimeError(
            "p is not prime."
        )

    if not sp.isprime(q):
        raise RuntimeError(
            "q is not prime."
        )

    N = p*q
    S = p+q
    X = S+1

    t_value = sp.Rational(
        int(N),
        int(X),
    )

    u_value = sp.cancel(
        t_value*(t_value+1)
    )

    print(
        "  p =",
        p,
    )

    print(
        "  q =",
        q,
    )

    print(
        "  N =",
        N,
    )

    print(
        "  S =",
        S,
    )

    print(
        "  X =",
        X,
    )

    print(
        "  t =",
        t_value,
    )

    print(
        "  u =",
        u_value,
    )

    # ------------------------------------------------------------------------
    # 8 FRESH CHANNEL VALUES
    # ------------------------------------------------------------------------

    fresh_V = {}

    for jj in range(8):

        fresh_V[jj] = sp.Matrix([
            fresh_value(
                A[2*jj],
                u_value,
            ),
            fresh_value(
                B[2*jj+1],
                u_value,
            ),
        ])

    # ------------------------------------------------------------------------
    # 9 VALIDATE UNIQUE ORDER-2 LAW
    # ------------------------------------------------------------------------

    print()
    print("="*78)
    print("9. FRESH ORDER-2 RECURRENCE VALIDATION")
    print("="*78)

    order2_fresh_ok = True

    if first_order2_solution is None:

        print(
            "  No unique order-2 law available for validation."
        )

    else:

        _, _, result = (
            first_order2_solution
        )

        M1 = result["M1"]
        M2 = result["M2"]

        for jj in range(
            2,
            8,
        ):

            predicted = (
                M1.subs(
                    {
                        j: jj,
                        u: u_value,
                    }
                )
                *
                fresh_V[jj-1]
                +
                M2.subs(
                    {
                        j: jj,
                        u: u_value,
                    }
                )
                *
                fresh_V[jj-2]
            )

            target = fresh_V[jj]

            ok = all(
                is_zero(
                    predicted[k]
                    -
                    target[k]
                )
                for k in range(2)
            )

            order2_fresh_ok &= ok

            print(
                f"  j={jj}:",
                ok,
            )

    # ------------------------------------------------------------------------
    # 10 COMPARE ORDER-1 / ORDER-2 COMPLEXITY
    # ------------------------------------------------------------------------

    print()
    print("="*78)
    print("10. COMPLEXITY SUMMARY")
    print("="*78)

    unique_order1 = [
        (a,b)
        for a,b,r in order1_results
        if r is not None
        and r["exists"]
        and r["unique"]
    ]

    unique_order2 = [
        (a,b)
        for a,b,r in order2_results
        if r is not None
        and r["exists"]
        and r["unique"]
    ]

    print(
        "  unique order-1 laws =",
        unique_order1,
    )

    print(
        "  unique order-2 laws =",
        unique_order2,
    )

    # ------------------------------------------------------------------------
    # 11 STRUCTURAL INTERPRETATION
    # ------------------------------------------------------------------------

    print()
    print("="*78)
    print("11. STRUCTURAL INTERPRETATION")
    print("="*78)

    print(
        r"""
  The previous experiments produced local transfer matrices

      V_j = M_j(u)V_{j-1},

  but those matrices changed dramatically with j.

  The natural next hypothesis is therefore an indexed recurrence

      V_j =
          M_1(j,u)V_{j-1}
          +
          M_2(j,u)V_{j-2}.

  This experiment searches for that law directly.

  The distinction is important.

  A family of seven independently recovered matrices can always be
  interpolated in j if enough complexity is allowed.

  That is not evidence of structure.

  Instead, this experiment asks:

      Does ONE exact bivariate polynomial matrix law
      generate EVERY available transition?

  A positive result at low degree is substantially stronger.

  A negative result is also useful: it rules out a broad class of
  compact indexed recurrences within the tested degree bounds.

  The ultimate structural direction remains

      construction:
          seeds
            -> indexed recurrence
            -> all layers

  before attempting the harder question

      N
       -> independently computable layer information
       -> t
       -> X
       -> p,q.
        """
    )

    # ------------------------------------------------------------------------
    # 12 FINAL EXACTNESS
    # ------------------------------------------------------------------------

    print()
    print("="*78)
    print("12. FINAL EXACTNESS")
    print("="*78)

    failures = 0

    if not involution_ok:
        failures += 1

    if (
        first_order2_solution is not None
        and not order2_fresh_ok
    ):
        failures += 1

    print(
        "  involution =",
        involution_ok,
    )

    print(
        "  order2_unique_found =",
        first_order2_solution is not None,
    )

    print(
        "  order2_fresh_validation =",
        (
            order2_fresh_ok
            if first_order2_solution is not None
            else "not_applicable"
        ),
    )

    print(
        "  failures =",
        failures,
    )

    print(
        "  ALL EXACT CHECKS PASS =",
        failures == 0,
    )

    print()
    print("="*78)
    print(
        "EXPERIMENT 80 COMPLETE"
    )
    print("="*78)


if __name__ == "__main__":
    main()

