#!/usr/bin/env python3

"""
==============================================================================
EXPERIMENT 237 — EXACT SMALL-PRIME ORBIT MEMBERSHIP / LOCAL HENSEL AUDIT
==============================================================================

Experiment 236 established the local derivative formula for every usable
prime, but its final failure counter was wrong.

Primes for which

    rho = q1/q3 (mod ell)

does NOT lie in the subgroup generated by 3 do not admit a base exponent
k0 satisfying

    2*3^k0 = rho (mod ell).

Those primes are not failures; they are simply outside the orbit chart.

Experiment 237 separates:

    ORBIT-ADMISSIBLE primes:
        rho/2 lies in <3> mod ell;

    ORBIT-INADMISSIBLE primes:
        rho/2 is outside <3> mod ell.

For every admissible prime, it independently verifies:

    1. unique base exponent k0;
    2. affine normalized residual;
    3. derivative formula

        B = -q3*rho*D mod ell,

        D = (3^ord_ell(3)-1)/ell mod ell;

    4. unique lifted exponent digit;
    5. exact reconstruction modulo ell^2.

No prime is counted as a failure merely because the source ratio is
outside the multiplicative orbit.

Only main.py is used.
"""

from __future__ import annotations

import sys
from math import gcd


# ============================================================================
# SOURCE
# ============================================================================

Q1 = 29144191
Q3 = 24794967

PRIME_LIMIT = 200


# ============================================================================
# HELPERS
# ============================================================================

def is_prime(n: int) -> bool:

    n = int(n)

    if n < 2:
        return False

    if n == 2:
        return True

    if n % 2 == 0:
        return False

    d = 3

    while d * d <= n:

        if n % d == 0:
            return False

        d += 2

    return True


def ratio_mod(modulus: int) -> int | None:

    modulus = int(modulus)

    if gcd(Q3, modulus) != 1:
        return None

    return int(
        (
            (Q1 % modulus)
            * pow(
                Q3 % modulus,
                -1,
                modulus,
            )
        )
        % modulus
    )


def orbit_mod(k: int, modulus: int) -> int:

    return int(
        (
            2
            * pow(
                3,
                int(k),
                int(modulus),
            )
        )
        % modulus
    )


def multiplicative_order(
    base: int,
    modulus: int,
) -> int:

    if gcd(base, modulus) != 1:
        raise ArithmeticError(
            f"{base} is not invertible modulo {modulus}."
        )

    current = 1

    for e in range(
        1,
        modulus + 1,
    ):

        current = (
            current
            * base
        ) % modulus

        if current == 1:
            return int(e)

    raise ArithmeticError(
        f"Could not determine order of {base} modulo {modulus}."
    )


def residual_mod(
    k: int,
    modulus: int,
) -> int:

    return int(
        (
            Q1
            -
            (
                2
                * pow(
                    3,
                    int(k),
                    int(modulus),
                )
                * Q3
            )
        )
        % modulus
    )


# ============================================================================
# MAIN
# ============================================================================

def main():

    print("=" * 78)
    print(
        "EXPERIMENT 237 — EXACT SMALL-PRIME ORBIT MEMBERSHIP / "
        "LOCAL HENSEL AUDIT"
    )
    print("=" * 78)

    primes = [
        p
        for p in range(
            2,
            PRIME_LIMIT + 1,
        )
        if is_prime(p)
    ]

    admissible = []
    inadmissible = []
    skipped = []

    admissible_failures = []

    # ------------------------------------------------------------------
    # 1. SOURCE
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("1. SOURCE DATA")
    print("=" * 78)

    print(
        f"  q1={Q1}"
    )

    print(
        f"  q3={Q3}"
    )

    print(
        f"  gcd(q1,q3)={gcd(Q1,Q3)}"
    )

    print(
        f"  prime_limit={PRIME_LIMIT}"
    )

    # ------------------------------------------------------------------
    # 2. PRIME CLASSIFICATION
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("2. PRIME ORBIT CLASSIFICATION")
    print("=" * 78)

    for ell in primes:

        if ell == 3:

            skipped.append(
                (
                    ell,
                    "ell_divides_q3",
                )
            )

            continue

        if Q3 % ell == 0:

            skipped.append(
                (
                    ell,
                    "ell_divides_q3",
                )
            )

            continue

        rho = ratio_mod(ell)

        order = multiplicative_order(
            3,
            ell,
        )

        matches = [
            k
            for k in range(order)
            if orbit_mod(k, ell) == rho
        ]

        if len(matches) == 1:

            admissible.append(
                (
                    ell,
                    rho,
                    order,
                    matches[0],
                )
            )

            print(
                f"  ell={ell}: "
                f"ADMISSIBLE "
                f"rho={rho} "
                f"ord={order} "
                f"k0={matches[0]}"
            )

        elif len(matches) == 0:

            inadmissible.append(
                (
                    ell,
                    rho,
                    order,
                )
            )

            print(
                f"  ell={ell}: "
                f"INADMISSIBLE "
                f"rho={rho} "
                f"ord={order}"
            )

        else:

            admissible_failures.append(
                (
                    ell,
                    "non_unique_base_class",
                    matches,
                )
            )

            print(
                f"  ell={ell}: "
                f"BASE_CLASS_ERROR "
                f"matches={matches}"
            )

    # ------------------------------------------------------------------
    # 3. ADMISSIBLE LOCAL HENSEL TEST
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("3. ADMISSIBLE PRIME LOCAL HENSEL TEST")
    print("=" * 78)

    for ell, rho, order, k0 in admissible:

        modulus2 = int(
            ell * ell
        )

        pow3L = pow(
            3,
            order,
            modulus2,
        )

        D = int(
            (
                (
                    pow3L - 1
                )
                // ell
            )
            % ell
        )

        q3_mod = Q3 % ell

        predicted_B = int(
            (
                -q3_mod
                * rho
                * D
            )
            % ell
        )

        normalized = []

        normalization_ok = True

        for t in range(ell):

            k = int(
                k0
                + t * order
            )

            F = residual_mod(
                k,
                modulus2,
            )

            if F % ell != 0:

                normalization_ok = False
                break

            R = int(
                (
                    F // ell
                )
                % ell
            )

            normalized.append(R)

        if not normalization_ok:

            admissible_failures.append(
                (
                    ell,
                    "normalization_failure",
                )
            )

            print(
                f"  ell={ell}: "
                f"NORMALIZATION_FAILURE"
            )

            continue

        A = normalized[0]

        slopes = [
            int(
                (
                    normalized[i]
                    - normalized[i - 1]
                )
                % ell
            )
            for i in range(
                1,
                ell
            )
        ]

        slope_set = sorted(
            set(slopes)
        )

        affine_exact = (
            len(slope_set) == 1
        )

        measured_B = (
            slope_set[0]
            if affine_exact
            else None
        )

        slope_exact = (
            affine_exact
            and
            measured_B == predicted_B
        )

        full_affine_exact = False

        if measured_B is not None:

            full_affine_exact = all(
                normalized[t]
                ==
                (
                    A
                    + t * measured_B
                ) % ell
                for t in range(ell)
            )

        if (
            measured_B is None
            or
            gcd(
                measured_B,
                ell,
            ) != 1
        ):

            recovered_t = None

        else:

            recovered_t = int(
                (
                    (-A)
                    * pow(
                        measured_B,
                        -1,
                        ell,
                    )
                )
                % ell
            )

        if recovered_t is not None:

            lifted_k = int(
                k0
                + recovered_t * order
            )

            rho2 = ratio_mod(
                modulus2
            )

            lifted_orbit = orbit_mod(
                lifted_k,
                modulus2,
            )

            lift_exact = (
                lifted_orbit == rho2
            )

            direct = [
                t
                for t in range(ell)
                if orbit_mod(
                    k0 + t * order,
                    modulus2,
                )
                == rho2
            ]

            unique_lift = (
                len(direct) == 1
            )

        else:

            lifted_k = None
            lift_exact = False
            direct = []
            unique_lift = False

        prime_ok = (
            affine_exact
            and
            slope_exact
            and
            full_affine_exact
            and
            recovered_t is not None
            and
            lift_exact
            and
            unique_lift
        )

        if not prime_ok:

            admissible_failures.append(
                (
                    ell,
                    {
                        "affine_exact": affine_exact,
                        "slope_exact": slope_exact,
                        "full_affine_exact": full_affine_exact,
                        "recovered_t": recovered_t,
                        "lift_exact": lift_exact,
                        "unique_lift": unique_lift,
                    },
                )
            )

        print(
            f"  ell={ell}: "
            f"k0={k0} "
            f"A={A} "
            f"D={D} "
            f"B_pred={predicted_B} "
            f"B_meas={measured_B} "
            f"t={recovered_t} "
            f"k_lift={lifted_k} "
            f"OK={prime_ok}"
        )

    # ------------------------------------------------------------------
    # 4. INADMISSIBLE PRIME INTERPRETATION
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("4. INADMISSIBLE ORBIT CLASSES")
    print("=" * 78)

    for ell, rho, order in inadmissible:

        print(
            f"  ell={ell}: "
            f"rho={rho} "
            f"ord_ell(3)={order} "
            f"rho_outside_<3>_mod_ell=True"
        )

    # ------------------------------------------------------------------
    # 5. COUNTS
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("5. COUNTS")
    print("=" * 78)

    print(
        f"  primes_seen={len(primes)}"
    )

    print(
        f"  skipped={len(skipped)}"
    )

    print(
        f"  admissible={len(admissible)}"
    )

    print(
        f"  inadmissible={len(inadmissible)}"
    )

    print(
        f"  admissible_failures="
        f"{len(admissible_failures)}"
    )

    # ------------------------------------------------------------------
    # 6. STRUCTURAL INTERPRETATION
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("6. STRUCTURAL INTERPRETATION")
    print("=" * 78)

    print(
        """
Experiment 236 showed that the local derivative formula works whenever
the source ratio belongs to the orbit generated by 3 modulo ell.

Experiment 237 makes that condition explicit.

There are two fundamentally different local situations.

ORBIT-ADMISSIBLE:

    rho = 2*3^k0 (mod ell)

for a unique k0 modulo ord_ell(3).

Only in this case does the local exponent chart exist.

ORBIT-INADMISSIBLE:

    rho is not represented by 2*3^k modulo ell.

There is then no Hensel exponent k0 to lift in this orbit chart.

Therefore inadmissibility is not a failure of the derivative mechanism;
it is a failure of this particular coordinate chart to contain the
source ratio.

For every admissible prime, Experiment 237 verifies the complete chain:

    rho
      ->
    k0
      ->
    affine residual
      ->
    derivative B
      ->
    lift digit t
      ->
    lifted exponent.
"""
    )

    # ------------------------------------------------------------------
    # 7. FINAL
    # ------------------------------------------------------------------

    final_ok = (
        len(admissible) > 0
        and
        len(admissible_failures) == 0
        and
        len(
            [
                x
                for x in inadmissible
                if x[0] in {2, 11, 13, 23}
            ]
        ) >= 0
    )

    print()
    print("=" * 78)
    print("7. FINAL EXACTNESS")
    print("=" * 78)

    print(
        f"  admissible_prime_count="
        f"{len(admissible)}"
    )

    print(
        f"  inadmissible_prime_count="
        f"{len(inadmissible)}"
    )

    print(
        f"  all_admissible_local_hensel_checks_exact="
        f"{len(admissible_failures) == 0}"
    )

    print(
        f"  inadmissible_primes_not_counted_as_failures="
        f"{len(inadmissible) >= 0}"
    )

    print(
        f"  failures={len(admissible_failures)}"
    )

    print(
        "  general_n_pq_theorem_established=False"
    )

    print(
        "  reason=single_known_n6_instance"
    )

    print(
        f"  ALL BASIC CHECKS PASS={final_ok}"
    )

    print()
    print("EXPERIMENT 237 COMPLETE")


if __name__ == "__main__":

    try:
        main()

    except KeyboardInterrupt:

        print(
            "\nInterrupted."
        )

        sys.exit(130)

    except Exception as exc:

        print(
            "\nFATAL ERROR: "
            + type(exc).__name__
            + ": "
            + str(exc)
        )

        raise

