#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <iostream>
#include <numeric>
#include <random>
#include <vector>

using u64 = std::uint64_t;

struct Pair {
    int k1;
    int k2;
    u64 a;
    u64 M;
};

struct CaseData {
    u64 N;
    u64 p;
    u64 q;
    u64 s;
};

struct StageStats {
    u64 cases_reached = 0;
    u64 cases_success = 0;
    u64 factor_tests = 0;
    u64 max_factor_tests = 0;
};

std::vector<bool> build_sieve(int limit) {
    std::vector<bool> prime(
        static_cast<std::size_t>(limit) + 1,
        true
    );

    prime[0] = false;

    if (limit >= 1) {
        prime[1] = false;
    }

    for (int i = 2; 1LL * i * i <= limit; ++i) {
        if (!prime[i]) {
            continue;
        }

        for (int j = i * i; j <= limit; j += i) {
            prime[j] = false;
        }
    }

    return prime;
}

std::vector<int> generate_primes(
    int low,
    int high,
    const std::vector<bool>& prime) {

    std::vector<int> result;

    for (int x = low; x <= high; ++x) {
        if (prime[x]) {
            result.push_back(x);
        }
    }

    return result;
}

std::vector<Pair> build_determinant_one_pairs(
    int k_limit,
    int m_limit) {

    std::vector<Pair> pairs;

    for (int m1 = 1; m1 <= m_limit; ++m1) {
        for (int m2 = 1; m2 <= m_limit; ++m2) {

            for (int k1 = 2; k1 <= k_limit; ++k1) {

                const long long numerator =
                    1LL * m2 * k1 - 1;

                if (numerator <= 0) {
                    continue;
                }

                if (numerator % m1 != 0) {
                    continue;
                }

                const int k2 =
                    static_cast<int>(numerator / m1);

                if (k2 < k1 || k2 > k_limit) {
                    continue;
                }

                if (k2 < 2) {
                    continue;
                }

                if (std::gcd(k1, k2) != 1) {
                    continue;
                }

                const u64 a =
                    static_cast<u64>(k1) +
                    static_cast<u64>(k2);

                const u64 M =
                    static_cast<u64>(k1) *
                    static_cast<u64>(k2);

                pairs.push_back({
                    k1,
                    k2,
                    a,
                    M
                });
            }
        }
    }

    std::sort(
        pairs.begin(),
        pairs.end(),
        [](const Pair& lhs, const Pair& rhs) {
            if (lhs.M != rhs.M) {
                return lhs.M < rhs.M;
            }

            if (lhs.a != rhs.a) {
                return lhs.a < rhs.a;
            }

            if (lhs.k1 != rhs.k1) {
                return lhs.k1 < rhs.k1;
            }

            return lhs.k2 < rhs.k2;
        }
    );

    /*
        Remove duplicate (k1,k2) representations.
    */
    pairs.erase(
        std::unique(
            pairs.begin(),
            pairs.end(),
            [](const Pair& lhs, const Pair& rhs) {
                return
                    lhs.k1 == rhs.k1 &&
                    lhs.k2 == rhs.k2;
            }
        ),
        pairs.end()
    );

    return pairs;
}

CaseData generate_semiprime_case(
    const std::vector<int>& primes,
    std::mt19937_64& rng) {

    std::uniform_int_distribution<std::size_t> dist(
        0,
        primes.size() - 1
    );

    while (true) {
        u64 p =
            static_cast<u64>(
                primes[dist(rng)]
            );

        u64 q =
            static_cast<u64>(
                primes[dist(rng)]
            );

        if (p == q) {
            continue;
        }

        if (p > q) {
            std::swap(p, q);
        }

        const u64 N = p * q;

        u64 s =
            static_cast<u64>(
                std::sqrt(
                    static_cast<long double>(N)
                )
            );

        while ((s + 1) <= N / (s + 1)) {
            ++s;
        }

        while (s > N / s) {
            --s;
        }

        return {N, p, q, s};
    }
}

u64 ordinary_factor_tests(
    u64 N,
    u64 s,
    u64& factor) {

    u64 tests = 0;

    for (u64 candidate = s; candidate >= 2; --candidate) {
        ++tests;

        if (N % candidate == 0) {
            factor = candidate;
            return tests;
        }
    }

    factor = 0;
    return tests;
}

/*
    Add all prime candidates generated by determinant-one
    congruence classes with

        previous_M < M <= new_M.

    seen[x] guarantees that the same prime is never tested
    twice across escalation stages.

    Candidates are inserted first and sorted descending
    so that the search remains numerically ordered.
*/
std::vector<u64> generate_new_prime_candidates(
    const std::vector<Pair>& pairs,
    u64 s,
    u64 previous_M,
    u64 new_M,
    const std::vector<bool>& prime,
    std::vector<bool>& seen) {

    std::vector<u64> values;

    for (const Pair& pair : pairs) {

        if (pair.M <= previous_M) {
            continue;
        }

        if (pair.M > new_M) {
            break;
        }

        if (pair.a > s) {
            continue;
        }

        u64 value = pair.a;

        while (value <= s) {

            if (value >= 2 &&
                value < prime.size() &&
                prime[
                    static_cast<std::size_t>(value)
                ] &&
                !seen[
                    static_cast<std::size_t>(value)
                ]) {

                seen[
                    static_cast<std::size_t>(value)
                ] = true;

                values.push_back(value);
            }

            if (value > s - pair.M) {
                break;
            }

            value += pair.M;
        }
    }

    std::sort(
        values.begin(),
        values.end(),
        std::greater<u64>()
    );

    return values;
}

double average(
    u64 total,
    int count) {

    if (count == 0) {
        return 0.0;
    }

    return
        static_cast<double>(total) /
        static_cast<double>(count);
}

int main() {
    constexpr int CASE_COUNT = 500;

    constexpr int PRIME_LOW = 10000;
    constexpr int PRIME_HIGH = 100000;
    constexpr int PRIME_LIMIT = 100000;

    constexpr int K_LIMIT = 1000;
    constexpr int M_FAMILY_LIMIT = 7;

    /*
        Adaptive escalation:

            10 -> 20 -> 50 -> 250 -> 1000
    */
    const std::vector<u64> STAGES = {
        10,
        20,
        50,
        250,
        1000
    };

    std::cout
        << "START EXPERIMENT 485\n";

    const auto sieve =
        build_sieve(PRIME_LIMIT);

    const auto primes =
        generate_primes(
            PRIME_LOW,
            PRIME_HIGH,
            sieve
        );

    const auto pairs =
        build_determinant_one_pairs(
            K_LIMIT,
            M_FAMILY_LIMIT
        );

    std::cout
        << "PAIR_COUNT="
        << pairs.size()
        << "\n";

    std::cout
        << "PRIME_POOL_SIZE="
        << primes.size()
        << "\n";

    std::mt19937_64 rng(
        4851234567ULL
    );

    std::vector<StageStats> stage_stats(
        STAGES.size()
    );

    u64 ordinary_total_tests = 0;

    u64 adaptive_total_tests = 0;

    u64 adaptive_success = 0;
    u64 adaptive_matching = 0;

    u64 adaptive_max_tests = 0;

    u64 fallback_count = 0;

    std::vector<u64> first_stage_found(
        STAGES.size(),
        0
    );

    std::vector<u64> first_stage_tests(
        STAGES.size(),
        0
    );

    std::vector<u64> first_new_candidates(
        STAGES.size(),
        0
    );

    std::vector<u64> first_cumulative_candidates(
        STAGES.size(),
        0
    );

    u64 first_N = 0;
    u64 first_p = 0;
    u64 first_q = 0;
    u64 first_s = 0;
    u64 first_ordinary_tests = 0;

    const auto start =
        std::chrono::steady_clock::now();

    for (int case_id = 0;
         case_id < CASE_COUNT;
         ++case_id) {

        const CaseData data =
            generate_semiprime_case(
                primes,
                rng
            );

        u64 ordinary_factor = 0;

        const u64 ordinary_tests =
            ordinary_factor_tests(
                data.N,
                data.s,
                ordinary_factor
            );

        ordinary_total_tests +=
            ordinary_tests;

        /*
            seen is over the entire prime range, so a prime
            generated by an earlier stage is never tested again.
        */
        std::vector<bool> seen(
            static_cast<std::size_t>(
                PRIME_LIMIT
            ) + 1,
            false
        );

        u64 total_case_tests = 0;
        u64 cumulative_candidates = 0;
        u64 found_factor = 0;
        u64 previous_M = 0;

        int found_stage = -1;

        for (std::size_t stage = 0;
             stage < STAGES.size();
             ++stage) {

            const u64 current_M =
                STAGES[stage];

            StageStats& ss =
                stage_stats[stage];

            ++ss.cases_reached;

            const auto new_candidates =
                generate_new_prime_candidates(
                    pairs,
                    data.s,
                    previous_M,
                    current_M,
                    sieve,
                    seen
                );

            const u64 new_candidate_count =
                static_cast<u64>(
                    new_candidates.size()
                );

            cumulative_candidates +=
                new_candidate_count;

            /*
                Test only the new candidates.
            */
            u64 stage_tests = 0;
            u64 stage_factor = 0;

            for (u64 candidate : new_candidates) {

                ++stage_tests;
                ++total_case_tests;

                if (data.N % candidate == 0) {
                    stage_factor = candidate;
                    found_factor = candidate;
                    break;
                }
            }

            ss.factor_tests +=
                stage_tests;

            ss.max_factor_tests =
                std::max(
                    ss.max_factor_tests,
                    stage_tests
                );

            if (stage_factor != 0) {
                ++ss.cases_success;

                found_stage =
                    static_cast<int>(stage);

                if (stage_factor == data.p) {
                    ++adaptive_matching;
                }

                break;
            }

            previous_M = current_M;

            /*
                Save first-case details.
            */
            if (case_id == 0) {
                first_new_candidates[stage] =
                    new_candidate_count;

                first_cumulative_candidates[stage] =
                    cumulative_candidates;

                first_stage_tests[stage] =
                    stage_tests;
            }
        }

        /*
            A candidate may not be found in the tested
            determinant-one family.
        */
        if (found_factor == 0) {
            ++fallback_count;
        } else {
            ++adaptive_success;
        }

        adaptive_total_tests +=
            total_case_tests;

        adaptive_max_tests =
            std::max(
                adaptive_max_tests,
                total_case_tests
            );

        if (case_id == 0) {
            first_N = data.N;
            first_p = data.p;
            first_q = data.q;
            first_s = data.s;
            first_ordinary_tests =
                ordinary_tests;

            /*
                Mark the actual stage at which the first
                case was found.
            */
            if (found_stage >= 0) {
                first_stage_found[
                    static_cast<std::size_t>(
                        found_stage
                    )
                ] = found_factor;
            }
        }

        if ((case_id + 1) % 100 == 0) {
            std::cout
                << "PROGRESS="
                << (case_id + 1)
                << "/"
                << CASE_COUNT
                << "\n";
        }
    }

    const auto end =
        std::chrono::steady_clock::now();

    const double elapsed_ms =
        std::chrono::duration<double, std::milli>(
            end - start
        ).count();

    std::cout
        << "FIRST_N="
        << first_N
        << "\n";

    std::cout
        << "FIRST_P="
        << first_p
        << "\n";

    std::cout
        << "FIRST_Q="
        << first_q
        << "\n";

    std::cout
        << "FIRST_S="
        << first_s
        << "\n";

    std::cout
        << "FIRST_ORDINARY_GCD_TESTS="
        << first_ordinary_tests
        << "\n";

    for (std::size_t i = 0;
         i < STAGES.size();
         ++i) {

        std::cout
            << "FIRST_STAGE_M="
            << STAGES[i]
            << " NEW_CANDIDATES="
            << first_new_candidates[i]
            << " CUMULATIVE_CANDIDATES="
            << first_cumulative_candidates[i]
            << " STAGE_FACTOR_TESTS="
            << first_stage_tests[i]
            << " FOUND="
            << first_stage_found[i]
            << "\n";
    }

    std::cout
        << "CASE_COUNT="
        << CASE_COUNT
        << "\n";

    std::cout
        << "ORDINARY_TOTAL_GCD_TESTS="
        << ordinary_total_tests
        << "\n";

    std::cout
        << "ORDINARY_AVG_GCD_TESTS="
        << average(
               ordinary_total_tests,
               CASE_COUNT
           )
        << "\n";

    std::cout
        << "ADAPTIVE_SUCCESS="
        << adaptive_success
        << "\n";

    std::cout
        << "ADAPTIVE_MATCHING="
        << adaptive_matching
        << "\n";

    std::cout
        << "ADAPTIVE_FALLBACK_COUNT="
        << fallback_count
        << "\n";

    std::cout
        << "ADAPTIVE_TOTAL_FACTOR_TESTS="
        << adaptive_total_tests
        << "\n";

    std::cout
        << "ADAPTIVE_AVG_FACTOR_TESTS="
        << average(
               adaptive_total_tests,
               CASE_COUNT
           )
        << "\n";

    std::cout
        << "ADAPTIVE_MAX_FACTOR_TESTS="
        << adaptive_max_tests
        << "\n";

    if (adaptive_success > 0) {
        std::cout
            << "ADAPTIVE_SUCCESS_PERCENT="
            << 100.0 *
               static_cast<double>(
                   adaptive_success
               ) /
               static_cast<double>(
                   CASE_COUNT
               )
            << "\n";
    } else {
        std::cout
            << "ADAPTIVE_SUCCESS_PERCENT=0\n";
    }

    for (std::size_t i = 0;
         i < STAGES.size();
         ++i) {

        const StageStats& ss =
            stage_stats[i];

        std::cout
            << "STAGE_M="
            << STAGES[i]
            << " CASES_REACHED="
            << ss.cases_reached
            << " CASES_SUCCESS="
            << ss.cases_success
            << " AVG_STAGE_TESTS="
            << average(
                   ss.factor_tests,
                   static_cast<int>(
                       ss.cases_reached
                   )
               )
            << " MAX_STAGE_TESTS="
            << ss.max_factor_tests
            << "\n";
    }

    if (adaptive_total_tests > 0) {
        const double ratio =
            static_cast<double>(
                adaptive_total_tests
            ) /
            static_cast<double>(
                ordinary_total_tests
            );

        std::cout
            << "ADAPTIVE_OVER_ORDINARY="
            << ratio
            << "\n";

        std::cout
            << "ADAPTIVE_TEST_REDUCTION_PERCENT="
            << 100.0 *
               (1.0 - ratio)
            << "\n";
    } else {
        std::cout
            << "ADAPTIVE_OVER_ORDINARY=0\n";

        std::cout
            << "ADAPTIVE_TEST_REDUCTION_PERCENT=100\n";
    }

    std::cout
        << "ELAPSED_TIME_MS="
        << elapsed_ms
        << "\n";

    std::cout
        << "FINISHED EXPERIMENT 485\n";

    return 0;
}
