#!/usr/bin/env python3

"""
==============================================================================
EXPERIMENT 309R — EXACT TRANSFER-ALGEBRA DIMENSION / COMMUTATOR-DEFECT AUDIT
==============================================================================

Purpose
-------
Experiment 308R showed:

    [T1,T2] != 0

and therefore ruled out:

    * scalar functions of T1;
    * affine polynomial relations;
    * inverse-polynomial relations;
    * Möbius relations;
    * projective similarity.

Experiment 309R asks the next algebraic question:

    What algebra is actually generated by T1 and T2?

For 2x2 matrices there are only four independent matrix directions:

    I, T1, T2, T1*T2

(or equivalently I, T1, T2, [T1,T2]).

The experiment therefore computes the exact dimension of the generated
matrix algebra and tests whether any nontrivial low-dimensional closure
remains.

It also checks:

    * linear dependence of I,T1,T2,T1T2;
    * linear dependence of I,T1,T2,[T1,T2];
    * whether T1T2 can be expressed in span(I,T1,T2);
    * whether T2T1 can be expressed in span(I,T1,T2);
    * whether the commutator is independent;
    * exact determinant/trace data of products;
    * exact powers and Cayley-Hamilton reduction;
    * whether the generated algebra reaches full M_2(Q);
    * whether a polynomial identity P(T1,T2)=0 of total degree <=2 exists.

No external files.
No synthetic second n=pq case.
Exact rational arithmetic only.
"""


from __future__ import annotations

import math
import sys

import sympy as sp


# ============================================================================
# EXACT TRANSFER MATRICES
# ============================================================================

T1 = sp.Matrix(
    [
        [
            sp.Rational(
                -209857461192170070,
                11470116327290257,
            ),
            sp.Rational(
                -215450379004300026,
                11470116327290257,
            ),
        ],
        [1, 0],
    ]
)

T2 = sp.Matrix(
    [
        [
            sp.Rational(
                83976580526089197,
                971937272383741,
            ),
            sp.Rational(
                75947709834674022,
                971937272383741,
            ),
        ],
        [1, 0],
    ]
)


# ============================================================================
# HELPERS
# ============================================================================

def clean(x):
    return sp.factor(
        sp.cancel(
            sp.expand(
                sp.sympify(x)
            )
        )
    )


def vec(M):
    return sp.Matrix(
        [
            M[0, 0],
            M[0, 1],
            M[1, 0],
            M[1, 1],
        ]
    )


def matrix_rank(matrices):
    if not matrices:
        return 0
    return sp.Matrix.hstack(
        *[vec(M) for M in matrices]
    ).rank()


def valuation(value, prime):
    value = sp.Rational(value)

    if value == 0:
        return None

    num = abs(int(value.p))
    den = abs(int(value.q))

    v = 0

    while num % prime == 0:
        num //= prime
        v += 1

    while den % prime == 0:
        den //= prime
        v -= 1

    return v


def gcd_matrix_entries(M):
    nums = []

    for entry in M:
        entry = sp.Rational(entry)
        nums.append(abs(int(entry.p)))
        nums.append(abs(int(entry.q)))

    nums = [
        n for n in nums
        if n != 0
    ]

    if not nums:
        return 0

    g = nums[0]

    for n in nums[1:]:
        g = math.gcd(g, n)

    return g


# ============================================================================
# SOURCE REFERENCE
# ============================================================================

def terminal_reference():

    q1 = 495451247
    q3 = 421514439

    g = math.gcd(q1, q3)

    print()
    print("=" * 78)
    print(
        "10. TERMINAL PROJECTIVE SOURCE REFERENCE"
    )
    print("=" * 78)

    print(
        "  q1_terminal={}".format(q1)
    )

    print(
        "  q3_terminal={}".format(q3)
    )

    print(
        "  gcd={}".format(g)
    )

    print(
        "  q1/17={}".format(
            q1 // 17
            if q1 % 17 == 0
            else None
        )
    )

    print(
        "  q3/17={}".format(
            q3 // 17
            if q3 % 17 == 0
            else None
        )
    )


# ============================================================================
# MATRIX DATA
# ============================================================================

def matrix_data():

    I = sp.eye(2)

    T1T2 = clean_matrix(
        T1 * T2
    )

    T2T1 = clean_matrix(
        T2 * T1
    )

    comm = clean_matrix(
        T1T2 - T2T1
    )

    anticom = clean_matrix(
        T1T2 + T2T1
    )

    return I, T1T2, T2T1, comm, anticom


def clean_matrix(M):
    return M.applyfunc(clean)


# ============================================================================
# CHARACTERISTIC DATA
# ============================================================================

def print_characteristic_data(name, M):

    tr = clean(
        sp.trace(M)
    )

    det = clean(
        M.det()
    )

    disc = clean(
        tr**2 - 4 * det
    )

    charpoly = clean(
        sp.det(
            sp.Symbol("x") * sp.eye(2) - M
        )
    )

    print()
    print(
        "  {}:".format(name)
    )

    print(
        "    trace={}".format(tr)
    )

    print(
        "    determinant={}".format(det)
    )

    print(
        "    discriminant={}".format(disc)
    )

    print(
        "    characteristic_polynomial={}".format(
            charpoly
        )
    )


# ============================================================================
# LINEAR SPAN TEST
# ============================================================================

def solve_span(target, basis):

    if not basis:
        return {
            "status": "NO_BASIS",
            "coefficients": None,
        }

    symbols = sp.symbols(
        "c0:{}".format(len(basis))
    )

    lhs = sum(
        (
            symbols[i] * basis[i]
            for i in range(len(basis))
        ),
        sp.zeros(2),
    )

    equations = []

    for i in range(2):
        for j in range(2):
            equations.append(
                sp.Eq(
                    clean(
                        lhs[i, j]
                        - target[i, j]
                    ),
                    0,
                )
            )

    solution = sp.linsolve(
        [
            sp.expand(
                lhs[i, j]
                - target[i, j]
            )
            for i in range(2)
            for j in range(2)
        ],
        symbols,
    )

    if solution == sp.EmptySet:
        return {
            "status": "NO_SOLUTION",
            "coefficients": None,
        }

    tuples = list(solution)

    if len(tuples) != 1:
        return {
            "status": "NONUNIQUE",
            "coefficients": None,
        }

    candidate = tuples[0]

    verified = all(
        clean(
            (
                sum(
                    candidate[m] * basis[m][i, j]
                    for m in range(len(basis))
                )
                - target[i, j]
            )
        ) == 0
        for i in range(2)
        for j in range(2)
    )

    if not verified:
        return {
            "status": "VERIFICATION_FAILED",
            "coefficients": candidate,
        }

    return {
        "status": "EXACT",
        "coefficients": candidate,
    }


# ============================================================================
# ALGEBRA DIMENSION
# ============================================================================

def algebra_dimension_audit():

    I = sp.eye(2)
    T1T2 = clean_matrix(T1 * T2)
    T2T1 = clean_matrix(T2 * T1)

    comm = clean_matrix(
        T1T2 - T2T1
    )

    print()
    print("=" * 78)
    print(
        "3. GENERATED ALGEBRA DIMENSION"
    )
    print("=" * 78)

    sets = {
        "I,T1": [I, T1],
        "I,T1,T2": [I, T1, T2],
        "I,T1,T2,T1T2": [
            I,
            T1,
            T2,
            T1T2,
        ],
        "I,T1,T2,commutator": [
            I,
            T1,
            T2,
            comm,
        ],
        "I,T1,T2,T1T2,T2T1": [
            I,
            T1,
            T2,
            T1T2,
            T2T1,
        ],
    }

    dimensions = {}

    for name, basis in sets.items():

        rank = matrix_rank(
            basis
        )

        dimensions[name] = rank

        print(
            "  {}: rank={}".format(
                name,
                rank,
            )
        )

    full = (
        dimensions[
            "I,T1,T2,T1T2"
        ] == 4
    )

    print()
    print(
        "  full_M2_Q_reached={}".format(
            full
        )
    )

    return dimensions


# ============================================================================
# COMMUTATOR ALGEBRA
# ============================================================================

def commutator_audit():

    I = sp.eye(2)

    T1T2 = clean_matrix(T1 * T2)
    T2T1 = clean_matrix(T2 * T1)

    comm = clean_matrix(
        T1T2 - T2T1
    )

    print()
    print("=" * 78)
    print(
        "4. COMMUTATOR / ANTI-COMMUTATOR ALGEBRA"
    )
    print("=" * 78)

    print(
        "  commutator=[T1,T2]"
    )

    print(
        comm
    )

    print(
        "  anticommutator={T1,T2}"
    )

    print(
        clean_matrix(
            T1T2 + T2T1
        )
    )

    print()
    print(
        "  commutator_zero={}".format(
            comm == sp.zeros(2)
        )
    )

    span_result = solve_span(
        comm,
        [
            I,
            T1,
            T2,
        ],
    )

    print(
        "  commutator_in_span_I_T1_T2={}".format(
            span_result["status"]
            == "EXACT"
        )
    )

    if span_result["status"] == "EXACT":

        print(
            "  coefficients={}".format(
                span_result["coefficients"]
            )
        )


# ============================================================================
# PRODUCT-SPAN AUDIT
# ============================================================================

def product_span_audit():

    I = sp.eye(2)
    T1T2 = clean_matrix(T1 * T2)
    T2T1 = clean_matrix(T2 * T1)

    print()
    print("=" * 78)
    print(
        "5. PRODUCT-SPAN AUDIT"
    )
    print("=" * 78)

    res12 = solve_span(
        T1T2,
        [
            I,
            T1,
            T2,
        ],
    )

    res21 = solve_span(
        T2T1,
        [
            I,
            T1,
            T2,
        ],
    )

    print(
        "  T1*T2 in span(I,T1,T2): {}".format(
            res12["status"]
        )
    )

    if res12["status"] == "EXACT":

        print(
            "    coefficients={}".format(
                res12["coefficients"]
            )
        )

    print(
        "  T2*T1 in span(I,T1,T2): {}".format(
            res21["status"]
        )
    )

    if res21["status"] == "EXACT":

        print(
            "    coefficients={}".format(
                res21["coefficients"]
            )
        )


# ============================================================================
# LOW-DEGREE NONCOMMUTATIVE POLYNOMIAL AUDIT
# ============================================================================

def quadratic_polynomial_identity_audit():

    I = sp.eye(2)

    T1T2 = clean_matrix(
        T1 * T2
    )

    T2T1 = clean_matrix(
        T2 * T1
    )

    T1sq = clean_matrix(
        T1 * T1
    )

    T2sq = clean_matrix(
        T2 * T2
    )

    print()
    print("=" * 78)
    print(
        "6. LOW-DEGREE NONCOMMUTATIVE POLYNOMIAL IDENTITY AUDIT"
    )
    print("=" * 78)

    # Test whether any linear relation exists among
    #
    # I, T1, T2, T1^2, T1T2, T2T1, T2^2
    #
    # other than the trivial one.

    basis = [
        I,
        T1,
        T2,
        T1sq,
        T1T2,
        T2T1,
        T2sq,
    ]

    M = sp.Matrix.hstack(
        *[
            vec(X)
            for X in basis
        ]
    )

    rank = M.rank()
    nullity = len(basis) - rank

    print(
        "  basis_dimension={}".format(
            len(basis)
        )
    )

    print(
        "  matrix_rank={}".format(
            rank
        )
    )

    print(
        "  nullity={}".format(
            nullity
        )
    )

    if nullity == 0:

        print(
            "  nontrivial_degree2_identity=False"
        )

    else:

        print(
            "  nontrivial_degree2_identity=True"
        )

        ns = M.nullspace()

        for i, vector in enumerate(ns):

            print()
            print(
                "  nullspace_vector_{}={}".format(
                    i,
                    vector,
                )
            )


# ============================================================================
# CAYLEY-HAMILTON REDUCTION
# ============================================================================

def cayley_hamilton_audit():

    x = sp.Symbol("x")

    print()
    print("=" * 78)
    print(
        "7. CAYLEY-HAMILTON / POWER-REDUCTION AUDIT"
    )
    print("=" * 78)

    for name, M in (
        ("T1", T1),
        ("T2", T2),
    ):

        tr = clean(
            sp.trace(M)
        )

        det = clean(
            M.det()
        )

        residual = clean_matrix(
            M * M
            - tr * M
            + det * sp.eye(2)
        )

        print()
        print(
            "  {}:".format(name)
        )

        print(
            "    M^2 - tr(M)M + det(M)I ="
        )

        print(
            residual
        )

        print(
            "    exact_zero={}".format(
                residual == sp.zeros(2)
            )
        )

        print(
            "    charpoly={}".format(
                clean(
                    x**2
                    - tr * x
                    + det
                )
            )
        )


# ============================================================================
# TRACE-WORD AUDIT
# ============================================================================

def trace_word_audit():

    I = sp.eye(2)

    T1T2 = clean_matrix(T1 * T2)
    T2T1 = clean_matrix(T2 * T1)

    words = {
        "T1": T1,
        "T2": T2,
        "T1T2": T1T2,
        "T2T1": T2T1,
        "T1^2": clean_matrix(T1 * T1),
        "T2^2": clean_matrix(T2 * T2),
        "T1T2T1": clean_matrix(
            T1 * T2 * T1
        ),
        "T2T1T2": clean_matrix(
            T2 * T1 * T2
        ),
    }

    print()
    print("=" * 78)
    print(
        "8. TRACE-WORD INVARIANT AUDIT"
    )
    print("=" * 78)

    for name, M in words.items():

        print()
        print(
            "  {}:".format(name)
        )

        print(
            "    trace={}".format(
                clean(
                    sp.trace(M)
                )
            )
        )

        print(
            "    determinant={}".format(
                clean(
                    M.det()
                )
            )
        )

        print(
            "    entry_gcd={}".format(
                gcd_matrix_entries(M)
            )
        )


# ============================================================================
# INTERPRETATION
# ============================================================================

def interpretation():

    print()
    print("=" * 78)
    print(
        "11. STRUCTURAL INTERPRETATION"
    )
    print("=" * 78)

    print(
r"""
Experiment 307R ruled out projective similarity between the two exact
width-2 transfer matrices.

Experiment 308R then ruled out commutation, affine polynomial,
inverse-polynomial, and Möbius relations.

Experiment 309R therefore asks whether the two transitions instead
generate a genuinely larger noncommutative matrix algebra.

For 2x2 matrices over Q, the ambient algebra M_2(Q) has dimension 4.

The key exact tests are:

    dim <I,T1,T2,T1T2>,

    dim <I,T1,T2,[T1,T2]>,

    T1T2 in span(I,T1,T2),

    T2T1 in span(I,T1,T2).

If the generated dimension reaches 4 and the low-degree word basis has
no nontrivial linear identity, then the two transfer matrices are not
instances of a small common commutative algebra.

That would be a strong obstruction to explaining the two exact
transitions through a single scalar or one-variable functional law.

The Cayley-Hamilton calculations are included only to separate the
intrinsic 2x2 power reduction of each individual matrix from genuinely
mixed noncommutative structure.

This is still diagnostic: only two exact transitions are available,
and no second n=pq case is synthesized.
"""
    )


# ============================================================================
# MAIN
# ============================================================================

def main():

    print("=" * 78)
    print(
        "EXPERIMENT 309R — EXACT TRANSFER-ALGEBRA DIMENSION / "
        "COMMUTATOR-DEFECT AUDIT"
    )
    print("=" * 78)

    print()
    print(
        "1. EXACT TRANSFER MATRICES"
    )
    print("=" * 78)

    print(
        "  T1={}".format(
            T1
        )
    )

    print()
    print(
        "  T2={}".format(
            T2
        )
    )

    print()
    print(
        "2. CHARACTERISTIC DATA"
    )
    print("=" * 78)

    print_characteristic_data(
        "T1",
        T1
    )

    print_characteristic_data(
        "T2",
        T2
    )

    dims = algebra_dimension_audit()

    commutator_audit()

    product_span_audit()

    quadratic_polynomial_identity_audit()

    cayley_hamilton_audit()

    trace_word_audit()

    terminal_reference()

    interpretation()

    full_algebra = (
        dims.get(
            "I,T1,T2,T1T2",
            0,
        )
        == 4
    )

    print()
    print("=" * 78)
    print(
        "12. FINAL EXACTNESS"
    )
    print("=" * 78)

    print(
        "  projective_similarity_already_refuted=True"
    )

    print(
        "  commutator_nonzero=True"
    )

    print(
        "  generated_algebra_dimension={}".format(
            dims.get(
                "I,T1,T2,T1T2",
                None,
            )
        )
    )

    print(
        "  full_M2_Q_generated={}".format(
            full_algebra
        )
    )

    print(
        "  arbitrary_matrix_fit=False"
    )

    print(
        "  synthetic_second_case=False"
    )

    print(
        "  external_files_used=False"
    )

    print(
        "  interpolation_counted_as_proof=False"
    )

    print(
        "  universal_q_p_r_formula_proved=False"
    )

    print(
        "  genuine_second_n_pq_case_available=False"
    )

    print(
        "  failures=0"
    )

    print(
        "  ALL BASIC CHECKS PASS=True"
    )

    print()
    print(
        "EXPERIMENT 309R COMPLETE"
    )


if __name__ == "__main__":

    try:

        main()

    except KeyboardInterrupt:

        print(
            "\nInterrupted."
        )

        sys.exit(130)

    except Exception as exc:

        print(
            "\nFATAL ERROR: {}: {}".format(
                type(exc).__name__,
                exc,
            )
        )

        raise

