from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Dict, List, Tuple, Optional


# =============================================================================
# EXPERIMENT 420
# AUGMENTED (x,k) LLL / NEW-RELATION AUDIT
# =============================================================================
#
# Experiment 419 established:
#
#   all reduced vectors belonged to <f>
#
# where
#
#   f(x,k) = x^2 + 2*d0*x + 4*k-r.
#
# Therefore the previous lattice was structurally restricted to the ideal
# generated by f.
#
# Experiment 420 breaks that restriction.
#
# The lattice now contains:
#
#   1. the old ideal-generated rows x^i*k^j*f
#   2. independent monomial rows that are NOT guaranteed to vanish
#
# The purpose is to ask:
#
#   Can LLL discover a polynomial P(x,k) satisfying
#
#       P(x_true,k_true) = 0
#
#   while P is NOT divisible by f?
#
# Such a relation is classified as:
#
#   NEW_ROOT_VANISHING
#
# This is only a computational diagnostic.
#
# No resultants.
# No symbolic multivariate factorization.
# No modular Coppersmith theorem.
# No floating point in mathematical identities.
#
# ---------------------------------------------------------------------------
#
# IMPORTANT CONTROL
# ---------------------------------------------------------------------------
#
# The free rows are deliberately chosen without using x_true or k_true.
#
# They are:
#
#   1
#   x
#   k
#   x*k
#
# The hidden root is therefore not directly encoded into the augmented
# lattice.
#
# ---------------------------------------------------------------------------
#
# Classification
# ---------------------------------------------------------------------------
#
# INHERITED_MULTIPLE
#     P is exactly divisible by f.
#
# NEW_ROOT_VANISHING
#     P is not divisible by f and P(x_true,k_true)=0.
#
# NONVANISHING
#     P(x_true,k_true)!=0.
#
# NONINTEGRAL
#     The scaled LLL vector cannot be reconstructed as an integral
#     polynomial in x,k.
# =============================================================================


Monomial = Tuple[int, int]
Poly = Dict[Monomial, int]


# -----------------------------------------------------------------------------
# Polynomial arithmetic
# -----------------------------------------------------------------------------

def poly_clean(a: Poly) -> Poly:
    return {
        m: c
        for m, c in a.items()
        if c != 0
    }


def poly_add(a: Poly, b: Poly) -> Poly:
    out = dict(a)

    for m, c in b.items():
        out[m] = out.get(m, 0) + c

    return poly_clean(out)


def poly_scale(a: Poly, c: int) -> Poly:
    if c == 0:
        return {}

    return {
        m: v * c
        for m, v in a.items()
        if v * c != 0
    }


def poly_mul(a: Poly, b: Poly) -> Poly:
    out: Poly = {}

    for (i1, j1), c1 in a.items():
        for (i2, j2), c2 in b.items():

            m = (
                i1 + i2,
                j1 + j2,
            )

            out[m] = (
                out.get(m, 0)
                + c1 * c2
            )

    return poly_clean(out)


def poly_mul_monomial(
    a: Poly,
    dx: int,
    dk: int,
) -> Poly:
    return {
        (
            i + dx,
            j + dk,
        ): c
        for (i, j), c in a.items()
    }


def poly_eval(
    a: Poly,
    x: int,
    k: int,
) -> int:

    total = 0

    for (i, j), c in a.items():
        total += (
            c
            * (x ** i)
            * (k ** j)
        )

    return total


# -----------------------------------------------------------------------------
# Exact division by f
# -----------------------------------------------------------------------------

def poly_as_x_coefficients(
    a: Poly,
) -> Dict[int, Dict[int, int]]:

    out: Dict[int, Dict[int, int]] = {}

    for (i, j), c in a.items():

        out.setdefault(i, {})

        out[i][j] = (
            out[i].get(j, 0)
            + c
        )

    return {
        i: {
            j: c
            for j, c in coeffs.items()
            if c != 0
        }
        for i, coeffs in out.items()
        if any(c != 0 for c in coeffs.values())
    }


def kpoly_add(
    a: Dict[int, int],
    b: Dict[int, int],
) -> Dict[int, int]:

    out = dict(a)

    for j, c in b.items():
        out[j] = (
            out.get(j, 0)
            + c
        )

    return {
        j: c
        for j, c in out.items()
        if c != 0
    }


def kpoly_scale(
    a: Dict[int, int],
    c: int,
) -> Dict[int, int]:

    if c == 0:
        return {}

    return {
        j: v * c
        for j, v in a.items()
        if v * c != 0
    }


def x_coefficients_to_poly(
    a: Dict[int, Dict[int, int]],
) -> Poly:

    out: Poly = {}

    for i, coeffs in a.items():

        for j, c in coeffs.items():

            if c != 0:
                out[(i, j)] = c

    return out


def exact_divide_by_f(
    p: Poly,
    d0: int,
    r: int,
) -> Tuple[Poly, Poly]:
    """
    Exact polynomial division in x by

        f = x^2 + 2*d0*x + 4*k-r.

    Returns

        quotient, remainder
    """

    coeffs = poly_as_x_coefficients(p)

    if not coeffs:
        return {}, {}

    work = {
        degree: dict(value)
        for degree, value in coeffs.items()
    }

    quotient: Dict[int, Dict[int, int]] = {}

    max_degree = max(work)

    for degree in range(
        max_degree,
        1,
        -1,
    ):

        lead = work.get(
            degree,
            {},
        )

        if not lead:
            continue

        # Since f is monic in x,
        # the leading coefficient of the quotient is exactly lead.
        quotient[degree - 2] = kpoly_add(
            quotient.get(
                degree - 2,
                {},
            ),
            lead,
        )

        # subtract lead*x^2
        work[degree] = kpoly_add(
            work.get(degree, {}),
            kpoly_scale(
                lead,
                -1,
            ),
        )

        # subtract lead*(2*d0*x)
        work[degree - 1] = kpoly_add(
            work.get(
                degree - 1,
                {},
            ),
            kpoly_scale(
                lead,
                -2 * d0,
            ),
        )

        # subtract lead*(4*k-r)
        constant = {}

        for j, c in lead.items():

            constant[j + 1] = (
                constant.get(
                    j + 1,
                    0,
                )
                + 4 * c
            )

            constant[j] = (
                constant.get(
                    j,
                    0,
                )
                - r * c
            )

        work[degree - 2] = kpoly_add(
            work.get(
                degree - 2,
                {},
            ),
            kpoly_scale(
                constant,
                -1,
            ),
        )

        # clean
        for deg in list(work):
            if not work[deg]:
                del work[deg]

    remainder = {
        degree: coeffs
        for degree, coeffs in work.items()
        if degree <= 1 and coeffs
    }

    return (
        x_coefficients_to_poly(
            quotient
        ),
        x_coefficients_to_poly(
            remainder
        ),
    )


def is_multiple_of_f(
    p: Poly,
    d0: int,
    r: int,
) -> Tuple[bool, Poly, Poly]:

    quotient, remainder = exact_divide_by_f(
        p,
        d0,
        r,
    )

    return (
        not remainder,
        quotient,
        remainder,
    )


# -----------------------------------------------------------------------------
# Number-theoretic instance
# -----------------------------------------------------------------------------

@dataclass
class Instance:
    p: int
    q: int
    N: int
    S: int
    d: int
    gap: int
    K: int


def make_instance(
    p: int,
    q: int,
) -> Instance:

    N = p * q
    S = p + q

    d = (
        N
        + 1
        - 2 * S
    )

    gap = q - p

    K = (
        -d * d
        - 3 * N * N
        + 6 * N
        + 1
    ) // 4

    assert (
        -4 * K
        - 3 * N * N
        + 6 * N
        + 1
        == d * d
    )

    assert (
        N * N
        - N
        + K
        ==
        S * (N + 1 - S)
    )

    return Instance(
        p=p,
        q=q,
        N=N,
        S=S,
        d=d,
        gap=gap,
        K=K,
    )


# -----------------------------------------------------------------------------
# Partial K
# -----------------------------------------------------------------------------

@dataclass
class PartialK:
    u: int
    K0: int
    k: int
    C0: int
    d0: int
    r: int
    x_true: int


def partial_k_data(
    inst: Instance,
    u: int,
) -> PartialK:

    modulus = 1 << u

    K0 = (
        inst.K // modulus
    ) * modulus

    k = (
        inst.K
        - K0
    )

    assert 0 <= k < modulus
    assert K0 + k == inst.K

    C0 = (
        -4 * K0
        - 3 * inst.N * inst.N
        + 6 * inst.N
        + 1
    )

    d0 = math.isqrt(C0)

    r = (
        C0
        - d0 * d0
    )

    x_true = (
        inst.d
        - d0
    )

    residual = (
        x_true * x_true
        + 2 * d0 * x_true
        + 4 * k
        - r
    )

    assert residual == 0

    return PartialK(
        u=u,
        K0=K0,
        k=k,
        C0=C0,
        d0=d0,
        r=r,
        x_true=x_true,
    )


# -----------------------------------------------------------------------------
# Exact interval
# -----------------------------------------------------------------------------

@dataclass
class IntervalData:
    d_low: int
    d_high: int
    x_low: int
    x_high: int
    candidate_count: int


def exact_d_interval(
    pk: PartialK,
) -> IntervalData:

    lo_sq = (
        pk.C0
        - 4 * ((1 << pk.u) - 1)
    )

    hi_sq = pk.C0

    if lo_sq <= 0:
        d_low = 0

    else:
        d_low = math.isqrt(
            lo_sq
        )

        while (
            d_low * d_low
            < lo_sq
        ):
            d_low += 1

    d_high = math.isqrt(
        hi_sq
    )

    return IntervalData(
        d_low=d_low,
        d_high=d_high,
        x_low=d_low - pk.d0,
        x_high=d_high - pk.d0,
        candidate_count=max(
            0,
            d_high - d_low + 1,
        ),
    )


# -----------------------------------------------------------------------------
# Base polynomial
# -----------------------------------------------------------------------------

def build_f(
    pk: PartialK,
) -> Poly:

    return {
        (2, 0): 1,
        (1, 0): 2 * pk.d0,
        (0, 1): 4,
        (0, 0): -pk.r,
    }


# -----------------------------------------------------------------------------
# Ideal rows
# -----------------------------------------------------------------------------

def build_ideal_rows(
    f: Poly,
    max_i: int,
    max_j: int,
) -> List[Poly]:

    rows: List[Poly] = []

    for i in range(
        max_i + 1
    ):

        for j in range(
            max_j + 1
        ):

            rows.append(
                poly_mul_monomial(
                    f,
                    i,
                    j,
                )
            )

    return rows


# -----------------------------------------------------------------------------
# Independent free rows
# -----------------------------------------------------------------------------
#
# These rows are NOT multiplied by f.
#
# They do not use the hidden root.
# -----------------------------------------------------------------------------

def build_free_rows() -> List[Poly]:

    return [
        {(0, 0): 1},          # 1
        {(1, 0): 1},          # x
        {(0, 1): 1},          # k
        {(1, 1): 1},          # x*k
    ]


# -----------------------------------------------------------------------------
# Lattice basis
# -----------------------------------------------------------------------------

@dataclass
class Lattice:
    monomials: List[Monomial]
    rows: List[List[int]]
    X: int
    Y: int
    labels: List[str]


def monomial_basis(
    polys: List[Poly],
) -> List[Monomial]:

    mons = set()

    for poly in polys:
        mons.update(
            poly.keys()
        )

    return sorted(mons)


def poly_to_scaled_vector(
    poly: Poly,
    monomials: List[Monomial],
    X: int,
    Y: int,
) -> List[int]:

    return [
        poly.get(
            (i, j),
            0,
        )
        * (X ** i)
        * (Y ** j)
        for i, j in monomials
    ]


def vector_to_poly(
    row: List[int],
    monomials: List[Monomial],
    X: int,
    Y: int,
) -> Tuple[Poly, bool]:

    poly: Poly = {}

    integral = True

    for value, (i, j) in zip(
        row,
        monomials,
    ):

        scale = (
            X ** i
        ) * (
            Y ** j
        )

        if scale == 0:
            integral = False
            continue

        if value % scale != 0:
            integral = False
            continue

        coeff = (
            value // scale
        )

        if coeff:
            poly[(i, j)] = coeff

    return poly, integral


def build_lattice(
    pk: PartialK,
    X: int,
    Y: int,
    max_i: int,
    max_j: int,
) -> Lattice:

    f = build_f(pk)

    ideal_rows = build_ideal_rows(
        f,
        max_i,
        max_j,
    )

    free_rows = build_free_rows()

    polys = (
        ideal_rows
        + free_rows
    )

    labels = [
        "IDEAL"
        for _ in ideal_rows
    ] + [
        "FREE_1",
        "FREE_X",
        "FREE_K",
        "FREE_XK",
    ]

    mons = monomial_basis(
        polys
    )

    rows = [
        poly_to_scaled_vector(
            poly,
            mons,
            X,
            Y,
        )
        for poly in polys
    ]

    return Lattice(
        monomials=mons,
        rows=rows,
        X=X,
        Y=Y,
        labels=labels,
    )


# -----------------------------------------------------------------------------
# LLL
# -----------------------------------------------------------------------------

try:
    from fpylll import IntegerMatrix, LLL

    HAVE_FPYLLL = True

except Exception:
    HAVE_FPYLLL = False


def run_lll(
    rows: List[List[int]],
) -> Optional[List[List[int]]]:

    if not HAVE_FPYLLL:
        return None

    if not rows:
        return []

    nr = len(rows)
    nc = len(rows[0])

    M = IntegerMatrix(
        nr,
        nc,
    )

    for i in range(nr):
        for j in range(nc):
            M[i, j] = rows[i][j]

    LLL.reduction(M)

    return [
        [
            int(M[i, j])
            for j in range(nc)
        ]
        for i in range(nr)
    ]


# -----------------------------------------------------------------------------
# Exact candidate enumeration
# -----------------------------------------------------------------------------

def enumerate_candidates(
    pk: PartialK,
    interval: IntervalData,
    limit: int,
) -> Tuple[List[int], bool]:

    if (
        interval.candidate_count
        > limit
    ):
        return [], False

    candidates = []

    for d in range(
        interval.d_low,
        interval.d_high + 1,
    ):

        delta = (
            pk.C0
            - d * d
        )

        if delta < 0:
            continue

        if delta % 4 != 0:
            continue

        k = delta // 4

        if not (
            0 <= k < (1 << pk.u)
        ):
            continue

        x = (
            d
            - pk.d0
        )

        residual = (
            x * x
            + 2 * pk.d0 * x
            + 4 * k
            - pk.r
        )

        if residual == 0:
            candidates.append(d)

    return candidates, True


# -----------------------------------------------------------------------------
# Relation audit
# -----------------------------------------------------------------------------

@dataclass
class RelationAudit:
    index: int
    norm: int
    terms: int
    integral: bool
    value: Optional[int]
    inherited: bool
    classification: str


def audit_row(
    index: int,
    row: List[int],
    lattice: Lattice,
    pk: PartialK,
) -> RelationAudit:

    norm = max(
        (
            abs(x)
            for x in row
        ),
        default=0,
    )

    terms = sum(
        x != 0
        for x in row
    )

    poly, integral = vector_to_poly(
        row,
        lattice.monomials,
        lattice.X,
        lattice.Y,
    )

    if not integral:
        return RelationAudit(
            index=index,
            norm=norm,
            terms=terms,
            integral=False,
            value=None,
            inherited=False,
            classification="NONINTEGRAL",
        )

    value = poly_eval(
        poly,
        pk.x_true,
        pk.k,
    )

    inherited, _, remainder = (
        is_multiple_of_f(
            poly,
            pk.d0,
            pk.r,
        )
    )

    if inherited:
        classification = (
            "INHERITED_MULTIPLE"
        )

    elif value == 0:
        classification = (
            "NEW_ROOT_VANISHING"
        )

    else:
        classification = (
            "NONVANISHING"
        )

    return RelationAudit(
        index=index,
        norm=norm,
        terms=terms,
        integral=True,
        value=value,
        inherited=inherited,
        classification=classification,
    )


# -----------------------------------------------------------------------------
# Result
# -----------------------------------------------------------------------------

@dataclass
class Result:
    instance: int
    u: int
    gap: int
    x_true: int
    X: int
    candidates: int
    unique: bool

    inherited: int
    new: int
    nonzero: int
    nonintegral: int

    shortest: int
    longest: int


# -----------------------------------------------------------------------------
# Single test
# -----------------------------------------------------------------------------

def run_test(
    idx: int,
    inst: Instance,
    u: int,
    max_i: int,
    max_j: int,
    enumeration_limit: int,
) -> Result:

    pk = partial_k_data(
        inst,
        u,
    )

    interval = exact_d_interval(
        pk
    )

    candidates, enumerated = (
        enumerate_candidates(
            pk,
            interval,
            enumeration_limit,
        )
    )

    unique = (
        enumerated
        and len(candidates) == 1
        and candidates[0] == inst.d
    )

    X = max(
        abs(interval.x_low),
        abs(interval.x_high),
        1,
    )

    Y = max(
        (1 << u) - 1,
        1,
    )

    lattice = build_lattice(
        pk,
        X,
        Y,
        max_i,
        max_j,
    )

    reduced = run_lll(
        lattice.rows
    )

    if reduced is None:
        raise RuntimeError(
            "fpylll unavailable"
        )

    audits = [
        audit_row(
            i,
            row,
            lattice,
            pk,
        )
        for i, row in enumerate(
            reduced
        )
    ]

    inherited = sum(
        a.classification
        == "INHERITED_MULTIPLE"
        for a in audits
    )

    new = sum(
        a.classification
        == "NEW_ROOT_VANISHING"
        for a in audits
    )

    nonzero = sum(
        a.classification
        == "NONVANISHING"
        for a in audits
    )

    nonintegral = sum(
        a.classification
        == "NONINTEGRAL"
        for a in audits
    )

    norms = [
        a.norm
        for a in audits
    ]

    return Result(
        instance=idx,
        u=u,
        gap=inst.gap,
        x_true=pk.x_true,
        X=X,
        candidates=interval.candidate_count,
        unique=unique,
        inherited=inherited,
        new=new,
        nonzero=nonzero,
        nonintegral=nonintegral,
        shortest=min(norms),
        longest=max(norms),
    )


# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------

def run_experiment() -> None:

    print("=" * 118)
    print("EXPERIMENT 420 START")
    print("=" * 118)
    print()
    print("AUGMENTED (x,k) LLL / NEW-RELATION AUDIT")
    print()
    print("CORE RELATION")
    print("  f(x,k) = x^2 + 2*d0*x + 4*k-r")
    print()
    print("CHANGE FROM EXPERIMENT 419")
    print("  Previous lattice: only multiples of f.")
    print("  Current lattice : multiples of f + free monomial rows.")
    print()
    print("FREE ROWS")
    print("  1")
    print("  x")
    print("  k")
    print("  x*k")
    print()
    print("QUESTION")
    print("  Can LLL discover a root-vanishing relation outside <f>?")
    print()
    print("CLASSIFICATION")
    print("  inherited = exact multiple of f")
    print("  new       = not divisible by f, but vanishes at root")
    print("  nonzero   = does not vanish at root")
    print()

    unknown_bits = [
        20,
        24,
        28,
        32,
        36,
        40,
        44,
        48,
    ]

    max_i = 2
    max_j = 2

    enumeration_limit = 200000

    instances = [
        (50411, 282599),
        (1013, 10009),
        (10009, 1000033),
        (10009, 10037),
        (50023, 50051),
        (100019, 100043),
        (200009, 200017),
        (300017, 900007),
    ]

    print("CONFIGURATION")
    print(
        f"  instances       = {len(instances)}"
    )
    print(
        f"  K bits          = {unknown_bits}"
    )
    print(
        f"  ideal rows      = {(max_i + 1) * (max_j + 1)}"
    )
    print(
        "  free rows       = 4"
    )
    print(
        f"  total rows      = {(max_i + 1) * (max_j + 1) + 4}"
    )
    print(
        f"  enumeration max = {enumeration_limit}"
    )
    print(
        f"  fpylll          = {HAVE_FPYLLL}"
    )

    if not HAVE_FPYLLL:
        print()
        print("ERROR")
        print(
            "  fpylll import failed."
        )
        print(
            "  Install with:"
        )
        print(
            "    pip install fpylll cysignals"
        )
        return

    generated = [
        make_instance(p, q)
        for p, q in instances
    ]

    # -------------------------------------------------------------------------
    # Compact summary
    # -------------------------------------------------------------------------

    print()
    print("=" * 118)
    print("COMPACT AUGMENTED-LATTICE SUMMARY")
    print("=" * 118)

    print(
        " i   u       gap          x        X      cand unique   "
        "inherit new nonzero shortest"
    )

    print("-" * 118)

    results: List[Result] = []

    for idx, inst in enumerate(
        generated,
        start=1,
    ):

        for u in unknown_bits:

            result = run_test(
                idx,
                inst,
                u,
                max_i,
                max_j,
                enumeration_limit,
            )

            results.append(
                result
            )

            print(
                f"{idx:2d} "
                f"{u:3d} "
                f"{inst.gap:10d} "
                f"{result.x_true:10d} "
                f"{result.X:8d} "
                f"{result.candidates:9d} "
                f"{'YES' if result.unique else 'NO ':>6} "
                f"{result.inherited:7d} "
                f"{result.new:3d} "
                f"{result.nonzero:7d} "
                f"{result.shortest}"
            )

    # -------------------------------------------------------------------------
    # Aggregate
    # -------------------------------------------------------------------------

    total = len(results)

    inherited_total = sum(
        r.inherited
        for r in results
    )

    new_total = sum(
        r.new
        for r in results
    )

    nonzero_total = sum(
        r.nonzero
        for r in results
    )

    nonintegral_total = sum(
        r.nonintegral
        for r in results
    )

    unique_total = sum(
        r.unique
        for r in results
    )

    print()
    print("=" * 118)
    print("GLOBAL AUGMENTED-LATTICE CLASSIFICATION")
    print("=" * 118)

    print(
        f"  total tests               = {total}"
    )
    print(
        f"  reduced vectors           = {total * 13}"
    )
    print(
        f"  inherited multiples      = {inherited_total}"
    )
    print(
        f"  new root-vanishing       = {new_total}"
    )
    print(
        f"  nonvanishing             = {nonzero_total}"
    )
    print(
        f"  nonintegral              = {nonintegral_total}"
    )
    print(
        f"  unique interval recovery = {unique_total}/{total}"
    )

    print()
    print("=" * 118)
    print("AGGREGATE BY UNKNOWN K BITS")
    print("=" * 118)

    print(
        " u   tests unique  inherit  new  nonzero  shortest-min"
    )
    print("-" * 118)

    for u in unknown_bits:

        subset = [
            r
            for r in results
            if r.u == u
        ]

        shortest = min(
            r.shortest
            for r in subset
        )

        print(
            f"{u:2d} "
            f"{len(subset):5d} "
            f"{sum(r.unique for r in subset):6d} "
            f"{sum(r.inherited for r in subset):8d} "
            f"{sum(r.new for r in subset):4d} "
            f"{sum(r.nonzero for r in subset):7d} "
            f"{shortest}"
        )

    # -------------------------------------------------------------------------
    # New relations
    # -------------------------------------------------------------------------

    print()
    print("=" * 118)
    print("NEW ROOT-VANISHING RELATIONS")
    print("=" * 118)

    if new_total == 0:
        print(
            "  NONE DETECTED"
        )
    else:
        print(
            f"  DETECTED = {new_total}"
        )
        print()
        print(
            "  These cases require further inspection because"
        )
        print(
            "  the LLL output contains a relation outside <f>."
        )

    # -------------------------------------------------------------------------
    # Final interpretation
    # -------------------------------------------------------------------------

    print()
    print("=" * 118)
    print("INTERPRETATION")
    print("=" * 118)

    print(
        "  Experiment 419 showed that an ideal-only lattice"
    )
    print(
        "  necessarily returned only multiples of f."
    )
    print()
    print(
        "  Experiment 420 removes that restriction by adding"
    )
    print(
        "  free monomial directions."
    )
    print()
    print(
        "  Therefore NEW_ROOT_VANISHING is now the critical statistic."
    )
    print()
    print(
        "  A nonzero NEW_ROOT_VANISHING count would demonstrate"
    )
    print(
        "  that the augmented lattice found an algebraically new"
    )
    print(
        "  relation satisfied by the hidden root."
    )
    print()
    print(
        "  A zero count means the augmented construction still"
    )
    print(
        "  found no new exact root relation."
    )
    print()
    print(
        "  Neither outcome alone establishes a factorization method."
    )

    print()
    print("=" * 118)
    print("EXPERIMENT 420 FINAL STATUS")
    print("=" * 118)

    print(
        "  ALL EXACT INTERNAL CHECKS = TRUE"
    )

    print(
        f"  NEW ROOT-VANISHING COUNT = {new_total}"
    )

    if new_total == 0:
        print(
            "  NO NEW ALGEBRAIC RELATION DETECTED = TRUE"
        )
    else:
        print(
            "  NEW ALGEBRAIC RELATION DETECTED = TRUE"
        )

    print("=" * 118)
    print("EXPERIMENT 420 FINISHED")
    print("=" * 118)


if __name__ == "__main__":
    run_experiment()
