#!/usr/bin/env python3

"""
======================================================================
2^z RECURSIVE COORDINATE / v2 EXPERIMENT
======================================================================

Given n = p*q, define the level-z state when it exists:

    k_z = 2^(z-1)

    p = k_z (y_z - x_z) + a_z
    q = k_z (y_z + x_z) - a_z

Then:

    a_z = p mod 2^(z-1)

    y_z = (p+q) / 2^z

    x_z = (q-p+2*a_z) / 2^z

Observed recurrence:

    b_z = x_z mod 2

    a_(z+1) = a_z + b_z * 2^(z-1)

    x_(z+1) = (x_z + b_z) / 2
            = ceil(x_z / 2)

    y_(z+1) = y_z / 2

Hypotheses tested:

    H1:
        x_(z+1) = ceil(x_z / 2)

    H2:
        y_(z+1) = y_z / 2

    H3:
        transition z -> z+1 exists iff y_z is even

    H4:
        number of valid transitions from z=2
        equals v_2(y_2)

    H5:
        a_z is generated by the parity sequence of x_2

======================================================================
"""

from __future__ import annotations

from dataclasses import dataclass
from math import ceil


# ======================================================================
# CONFIGURATION
# ======================================================================

PRIME_LIMIT = 200

MIN_PRIME = 3

MAX_Z = 32

# Include both orientations to test whether ordering matters.
TEST_BOTH_ORDERS = True


# ======================================================================
# DATA
# ======================================================================

@dataclass
class State:
    z: int
    a: int
    x: int
    y: int


@dataclass
class CaseResult:
    p: int
    q: int
    y2: int
    v2_y2: int
    valid_levels: int
    transitions: int

    x_rule_pass: bool
    y_rule_pass: bool
    transition_rule_pass: bool
    v2_rule_pass: bool
    a_rule_pass: bool


# ======================================================================
# BASIC FUNCTIONS
# ======================================================================

def v2(n: int) -> int:
    """
    2-adic valuation.

    v2(0) is returned as a large sentinel because 0 is divisible
    by every power of 2 for the purpose of this experiment.
    """

    if n == 0:
        return 10**9

    n = abs(n)

    count = 0

    while n % 2 == 0:
        n //= 2
        count += 1

    return count


def ceil_half(x: int) -> int:
    return (x + 1) // 2


def primes_upto(limit: int) -> list[int]:
    """
    Simple sieve.
    """

    if limit < 2:
        return []

    sieve = [True] * (limit + 1)
    sieve[0] = False
    sieve[1] = False

    for i in range(2, int(limit ** 0.5) + 1):

        if not sieve[i]:
            continue

        for j in range(i * i, limit + 1, i):
            sieve[j] = False

    return [
        i
        for i in range(2, limit + 1)
        if sieve[i]
    ]


# ======================================================================
# TRUE STATE
# ======================================================================

def true_state(
    p: int,
    q: int,
    z: int,
) -> State | None:

    modulus = 1 << z
    k = 1 << (z - 1)

    a = p % k

    y_num = p + q
    x_num = q - p + 2 * a

    if y_num % modulus != 0:
        return None

    if x_num % modulus != 0:
        return None

    x = x_num // modulus
    y = y_num // modulus

    # Direct reconstruction check.

    p_check = k * (y - x) + a
    q_check = k * (y + x) - a

    if p_check != p or q_check != q:
        raise AssertionError(
            f"state reconstruction failed: "
            f"p={p}, q={q}, z={z}"
        )

    return State(
        z=z,
        a=a,
        x=x,
        y=y,
    )


# ======================================================================
# STARTING STATE
# ======================================================================

def initial_state(
    p: int,
    q: int,
) -> State | None:

    return true_state(
        p,
        q,
        2,
    )


# ======================================================================
# TRUE LEVELS
# ======================================================================

def true_levels(
    p: int,
    q: int,
) -> list[State]:

    levels = []

    for z in range(2, MAX_Z + 1):

        state = true_state(
            p,
            q,
            z,
        )

        if state is None:
            break

        levels.append(state)

    return levels


# ======================================================================
# RECURSIVE PREDICTION
# ======================================================================

def recursive_next(
    state: State,
) -> State | None:

    # --------------------------------------------------------------
    # Required next bit.
    # --------------------------------------------------------------

    b = state.x & 1

    # --------------------------------------------------------------
    # y must be even.
    # --------------------------------------------------------------

    if state.y % 2 != 0:
        return None

    # --------------------------------------------------------------
    # x + b must be even.
    #
    # Since b = x mod 2, this is automatic.
    # --------------------------------------------------------------

    numerator_x = state.x + b

    if numerator_x % 2 != 0:
        return None

    next_x = numerator_x // 2

    # --------------------------------------------------------------
    # a update.
    # --------------------------------------------------------------

    next_a = (
        state.a
        + b * (1 << (state.z - 1))
    )

    # --------------------------------------------------------------
    # y update.
    # --------------------------------------------------------------

    next_y = state.y // 2

    return State(
        z=state.z + 1,
        a=next_a,
        x=next_x,
        y=next_y,
    )


# ======================================================================
# RECURSIVE LEVEL GENERATION
# ======================================================================

def recursive_levels(
    initial: State,
) -> list[State]:

    result = [initial]

    current = initial

    while current.z < MAX_Z:

        nxt = recursive_next(
            current
        )

        if nxt is None:
            break

        result.append(nxt)

        current = nxt

    return result


# ======================================================================
# CHECK LEVEL EQUALITY
# ======================================================================

def states_equal(
    a: State,
    b: State,
) -> bool:

    return (
        a.z == b.z
        and a.a == b.a
        and a.x == b.x
        and a.y == b.y
    )


# ======================================================================
# TEST a RECONSTRUCTION FROM x2 BITS
# ======================================================================

def reconstruct_a_sequence(
    x2: int,
    a2: int,
    number_of_levels: int,
) -> list[int]:

    """
    Starting with (a2, x2), repeatedly use:

        b = x mod 2
        a <- a + b*2^(z-1)
        x <- ceil(x/2)

    Return a-values.
    """

    result = []

    a = a2
    x = x2

    z = 2

    for _ in range(number_of_levels):

        result.append(a)

        b = x & 1

        a = (
            a
            + b * (1 << (z - 1))
        )

        x = ceil_half(x)

        z += 1

    return result


# ======================================================================
# CHECK ONE CASE
# ======================================================================

def analyze_case(
    p: int,
    q: int,
) -> CaseResult | None:

    initial = initial_state(
        p,
        q,
    )

    if initial is None:
        return None

    levels = true_levels(
        p,
        q,
    )

    recursive = recursive_levels(
        initial
    )

    # --------------------------------------------------------------
    # Compare true vs recursive states.
    # --------------------------------------------------------------

    recursive_match = (
        len(levels) == len(recursive)
        and all(
            states_equal(a, b)
            for a, b
            in zip(levels, recursive)
        )
    )

    # --------------------------------------------------------------
    # Test x recurrence.
    # --------------------------------------------------------------

    x_rule_pass = True

    for i in range(len(levels) - 1):

        current = levels[i]
        nxt = levels[i + 1]

        predicted = ceil_half(
            current.x
        )

        if predicted != nxt.x:
            x_rule_pass = False
            break

    # --------------------------------------------------------------
    # Test y recurrence.
    # --------------------------------------------------------------

    y_rule_pass = True

    for i in range(len(levels) - 1):

        current = levels[i]
        nxt = levels[i + 1]

        if current.y % 2 != 0:
            y_rule_pass = False
            break

        predicted = current.y // 2

        if predicted != nxt.y:
            y_rule_pass = False
            break

    # --------------------------------------------------------------
    # Test transition existence rule.
    #
    # Every level except the last must have even y.
    # Last level must have odd y.
    # --------------------------------------------------------------

    transition_rule_pass = True

    if levels:

        for i, state in enumerate(levels):

            has_next = (
                i < len(levels) - 1
            )

            predicted_has_next = (
                state.y % 2 == 0
            )

            if has_next != predicted_has_next:
                transition_rule_pass = False
                break

    # --------------------------------------------------------------
    # Test v2(y2).
    # --------------------------------------------------------------

    y2 = initial.y
    y2_v2 = v2(y2)

    transitions = max(
        0,
        len(levels) - 1
    )

    v2_rule_pass = (
        transitions == y2_v2
    )

    # --------------------------------------------------------------
    # Test a sequence reconstructed only from x2.
    # --------------------------------------------------------------

    reconstructed_a = reconstruct_a_sequence(
        initial.x,
        initial.a,
        len(levels),
    )

    actual_a = [
        state.a
        for state in levels
    ]

    a_rule_pass = (
        reconstructed_a == actual_a
    )

    # --------------------------------------------------------------
    # Recursive equality.
    # --------------------------------------------------------------

    all_pass = (
        recursive_match
        and x_rule_pass
        and y_rule_pass
        and transition_rule_pass
        and v2_rule_pass
        and a_rule_pass
    )

    return CaseResult(
        p=p,
        q=q,
        y2=y2,
        v2_y2=y2_v2,
        valid_levels=len(levels),
        transitions=transitions,

        x_rule_pass=(
            x_rule_pass
            and recursive_match
        ),

        y_rule_pass=y_rule_pass,

        transition_rule_pass=(
            transition_rule_pass
        ),

        v2_rule_pass=v2_rule_pass,

        a_rule_pass=a_rule_pass,
    )


# ======================================================================
# DETAILED CASE REPORT
# ======================================================================

def print_case(
    p: int,
    q: int,
):

    result = analyze_case(
        p,
        q,
    )

    print()
    print("=" * 100)
    print(
        f"N = {p*q} = {p} × {q}"
    )
    print("=" * 100)

    if result is None:

        print(
            "NO z=2 STARTING STATE"
        )

        return

    print()
    print("BASIC DATA")
    print("-" * 100)

    print(
        f"y2            = {result.y2}"
    )

    print(
        f"v2(y2)        = {result.v2_y2}"
    )

    print(
        f"valid levels  = {result.valid_levels}"
    )

    print(
        f"transitions   = {result.transitions}"
    )

    print()
    print("HYPOTHESIS TESTS")
    print("-" * 100)

    print(
        f"recursive state machine : "
        f"{result.x_rule_pass}"
    )

    print(
        f"x' = ceil(x/2)          : "
        f"{result.x_rule_pass}"
    )

    print(
        f"y' = y/2                : "
        f"{result.y_rule_pass}"
    )

    print(
        f"transition iff y even   : "
        f"{result.transition_rule_pass}"
    )

    print(
        f"transitions = v2(y2)    : "
        f"{result.v2_rule_pass}"
    )

    print(
        f"a from x2 parity bits   : "
        f"{result.a_rule_pass}"
    )

    print()
    print("LEVELS")
    print("-" * 100)

    levels = true_levels(
        p,
        q,
    )

    print(
        f"{'z':>3} "
        f"{'a':>10} "
        f"{'x':>10} "
        f"{'y':>10} "
        f"{'x%2':>5} "
        f"{'y%2':>5}"
    )

    print("-" * 60)

    for state in levels:

        print(
            f"{state.z:3d} "
            f"{state.a:10d} "
            f"{state.x:10d} "
            f"{state.y:10d} "
            f"{state.x & 1:5d} "
            f"{state.y & 1:5d}"
        )

    print()

    all_pass = (
        result.x_rule_pass
        and result.y_rule_pass
        and result.transition_rule_pass
        and result.v2_rule_pass
        and result.a_rule_pass
    )

    print(
        f"CASE PASS = {all_pass}"
    )


# ======================================================================
# BULK EXPERIMENT
# ======================================================================

def bulk_experiment():

    primes = primes_upto(
        PRIME_LIMIT
    )

    total = 0
    tested = 0
    failures = []

    # --------------------------------------------------------------
    # Test every prime pair.
    # --------------------------------------------------------------

    for i, p in enumerate(primes):

        if p < MIN_PRIME:
            continue

        for q in primes[i:]:

            if q < MIN_PRIME:
                continue

            orders = [
                (p, q)
            ]

            if TEST_BOTH_ORDERS and p != q:
                orders.append(
                    (q, p)
                )

            for pp, qq in orders:

                total += 1

                result = analyze_case(
                    pp,
                    qq,
                )

                if result is None:
                    continue

                tested += 1

                ok = (
                    result.x_rule_pass
                    and result.y_rule_pass
                    and result.transition_rule_pass
                    and result.v2_rule_pass
                    and result.a_rule_pass
                )

                if not ok:

                    failures.append(
                        result
                    )

    print()
    print("=" * 100)
    print("BULK RESULTS")
    print("=" * 100)

    print(
        f"all ordered prime pairs = {total}"
    )

    print(
        f"pairs with z=2 state    = {tested}"
    )

    print(
        f"failures                = {len(failures)}"
    )

    print(
        f"PASS                    = {len(failures) == 0}"
    )

    if failures:

        print()
        print("FIRST FAILURES")
        print("-" * 100)

        for result in failures[:20]:

            print(
                f"{result.p} × {result.q} "
                f"y2={result.y2} "
                f"v2={result.v2_y2} "
                f"levels={result.valid_levels} "
                f"transitions={result.transitions} "
                f"x={result.x_rule_pass} "
                f"y={result.y_rule_pass} "
                f"transition={result.transition_rule_pass} "
                f"v2rule={result.v2_rule_pass} "
                f"a={result.a_rule_pass}"
            )


# ======================================================================
# DISTRIBUTION OF v2(y2)
# ======================================================================

def distribution_experiment():

    primes = primes_upto(
        PRIME_LIMIT
    )

    distribution = {}

    for i, p in enumerate(primes):

        for q in primes[i:]:

            state = initial_state(
                p,
                q,
            )

            if state is None:
                continue

            value = v2(
                state.y
            )

            distribution[value] = (
                distribution.get(value, 0)
                + 1
            )

    print()
    print("=" * 100)
    print("v2(y2) DISTRIBUTION")
    print("=" * 100)

    for value in sorted(
        distribution
    ):

        print(
            f"v2(y2)={value:2d} "
            f"cases={distribution[value]}"
        )


# ======================================================================
# MAIN
# ======================================================================

def main():

    print("=" * 100)
    print(
        "2^z RECURSIVE / v2 THEOREM EXPERIMENT"
    )
    print("=" * 100)

    # --------------------------------------------------------------
    # Detailed examples from the previous experiments.
    # --------------------------------------------------------------

    print_case(
        59,
        101,
    )

    print_case(
        223,
        449,
    )

    print_case(
        101,
        103,
    )

    # --------------------------------------------------------------
    # Bulk test.
    # --------------------------------------------------------------

    bulk_experiment()

    # --------------------------------------------------------------
    # Distribution.
    # --------------------------------------------------------------

    distribution_experiment()


if __name__ == "__main__":
    main()
