#!/usr/bin/env python3
"""
EXPERIMENT 520
==============================================================================
HISTORICAL CONIC -> QUADRATIC OPERATOR -> KAPPA TRANSLATION BRIDGE
==============================================================================

Purpose
-------
Attack the remaining upstream interface symbolically.

The downstream KAPPA spectrum is generated by

    Q0(z) = z^2 - S*z + N
    Q1(z) = Q0(z-1).

Experiment 520 asks whether the historical conic

    K = U^2 - V^2

and its translated copy

    K_shift = (U+r)^2 - V^2

naturally contain the missing quadratic coefficient -S.

This is deliberately a SYMBOLIC operator experiment.
No numerical fitting, interpolation, or data analysis is used.
"""

import sympy as sp

# ---------------------------------------------------------------------------
# Symbols
# ---------------------------------------------------------------------------
U, V, r, z, xi = sp.symbols("U V r z xi", nonzero=True)
p, q, N, S = sp.symbols("p q N S")
A, B = sp.symbols("A B")

def cert(label, expr, expected=0):
    diff = sp.factor(sp.expand(expr - expected))
    ok = diff == 0
    print(f"  {label}")
    print(f"    difference = {diff}")
    print(f"    PASS = {ok}")
    return ok


print("=" * 78)
print("EXPERIMENT 520 START")
print("=" * 78)
print("HISTORICAL CONIC -> QUADRATIC OPERATOR -> KAPPA TRANSLATION BRIDGE")
print()

# ===========================================================================
# 1. HISTORICAL NORMALIZATION
# ===========================================================================
print("[1] HISTORICAL NORMALIZATION")
print("-" * 78)

P = (U - V) / r
Q = (U + V) / r

N_expr = sp.expand(P * Q)
S_expr = sp.expand(P + Q)
Delta_expr = sp.expand((P - Q) ** 2)

print("  P =", P)
print("  Q =", Q)
print("  N =", N_expr)
print("  S =", S_expr)
print("  Delta =", Delta_expr)
print()

cert("PQ -> N", N_expr - (U**2 - V**2) / r**2)
cert("P+Q -> S", S_expr - 2*U / r)
cert("P-Q -> -2V/r", P - Q, -2*V/r)
print()

# ===========================================================================
# 2. THE SINGLE QUADRATIC OPERATOR
# ===========================================================================
print("[2] SINGLE QUADRATIC OPERATOR")
print("-" * 78)

Q0 = sp.expand((z - P) * (z - Q))
Q0_target = sp.expand(z**2 - S_expr*z + N_expr)

print("  Q0(z) =", sp.factor(Q0))
cert("Q0 = z^2-Sz+N", Q0, Q0_target)
print()

a = sp.expand(-S_expr)
b = sp.expand(N_expr)

print("  quadratic coefficients:")
print("    a =", a)
print("    b =", b)
cert("constant coefficient b=N", b, N_expr)
cert("linear coefficient a=-S", a, -S_expr)
print()

# ===========================================================================
# 3. UNIVERSAL TRANSLATION OPERATOR
# ===========================================================================
print("[3] UNIVERSAL TRANSLATION OPERATOR")
print("-" * 78)

# Q0(z-1)
Q1_direct = sp.expand(Q0.subs(z, z - 1))
Q1_coeff = sp.expand(
    z**2 + (a - 2)*z + (b - a + 1)
)

print("  T(Q)(z) = Q(z-1)")
cert("coefficient translation law", Q1_direct, Q1_coeff)

Q1_target = sp.expand((z - (P + 1)) * (z - (Q + 1)))
cert("T(Q0) = (z-(P+1))(z-(Q+1))", Q1_direct, Q1_target)
print()

# ===========================================================================
# 4. COMPOSITION RECONSTRUCTS THE FOUR-BASE CHARACTERISTIC
# ===========================================================================
print("[4] COMPOSITION -> FOUR-BASE CHARACTERISTIC")
print("-" * 78)

chi = sp.expand(Q0 * Q1_direct)

chi_target = sp.expand(
    (z - P) * (z - Q) * (z - P - 1) * (z - Q - 1)
)

cert("Q0*T(Q0) = chi_F", chi, chi_target)

poly = sp.Poly(chi, z)
coeffs = poly.all_coeffs()
a1, a2, a3, a4 = map(sp.expand, [-coeffs[1], coeffs[2], -coeffs[3], coeffs[4]])

print("  recurrence coefficients:")
print("    a1 =", sp.factor(a1))
print("    a2 =", sp.factor(a2))
print("    a3 =", sp.factor(a3))
print("    a4 =", sp.factor(a4))
print()

# ===========================================================================
# 5. HISTORICAL CONIC TRANSLATION
# ===========================================================================
print("[5] HISTORICAL CONIC TRANSLATION")
print("-" * 78)

K0 = sp.expand(U**2 - V**2)
K1 = sp.expand((U + r)**2 - V**2)
Kdiff = sp.expand(K1 - K0)

print("  K0      =", K0)
print("  K1      =", K1)
print("  K1-K0   =", Kdiff)

cert("K1-K0 = r*(2U+r)", Kdiff, r*(2*U + r))
cert(
    "(K1-K0)/r^2 = S+1",
    sp.expand(Kdiff / r**2),
    sp.expand(S_expr + 1),
)
print()

# ===========================================================================
# 6. QUADRATIC COEFFICIENT FROM CONIC TRANSLATION
# ===========================================================================
print("[6] QUADRATIC COEFFICIENT FROM CONIC TRANSLATION")
print("-" * 78)

# Since a=-S, derive a directly from K1-K0:
a_from_K = sp.expand(1 - (K1 - K0) / r**2)

print("  proposed:")
print("    a = 1 - (K1-K0)/r^2")
print("  a_from_K =", sp.factor(a_from_K))

cert("a_from_K = -S", a_from_K, -S_expr)
print()

# This is the key interface:
# K0 gives N, K1 supplies the missing linear coefficient.
print("  KEY INTERFACE:")
print("    K0/r^2              -> N")
print("    (K1-K0)/r^2 - 1     -> S")
print("    1-(K1-K0)/r^2       -> -S")
print()

# ===========================================================================
# 7. N-ONLY OBSTRUCTION AUDIT
# ===========================================================================
print("[7] N-ONLY OBSTRUCTION AUDIT")
print("-" * 78)

# Treat p,q as algebraically independent. Any polynomial/rational function
# depending on N=pq alone is symmetric under p<->q and, more importantly,
# is constant on all factorizations of the same N. S=p+q is not determined
# by N on the unrestricted two-variable factor space.
#
# We certify the formal distinction by exhibiting two factor pairs with the
# same product but different sums symbolically using a parameter t:
#   p=2, q=t and p=3, q=2t/3 is not generally integer, so instead use
#   the algebraic transformation q=N/p:
#   S(p)=p+N/p.
#
# Its derivative is not identically zero, so S is not a function of N alone.

pvar = sp.symbols("pvar", nonzero=True)
Nvar = sp.symbols("Nvar", nonzero=True)

S_as_p = sp.expand(pvar + Nvar / pvar)
dS_dp = sp.factor(sp.diff(S_as_p, pvar))

print("  For fixed N:")
print("    S(p) = p + N/p")
print("    dS/dp =", dS_dp)
print()

cert("dS/dp is not identically zero", dS_dp, 0)
print("  Therefore no universal expression S=f(N) exists on the")
print("  unrestricted two-variable factor space.")
print()

# ===========================================================================
# 8. CAN K0 ALONE GENERATE THE QUADRATIC?
# ===========================================================================
print("[8] K0-ONLY OPERATOR TEST")
print("-" * 78)

# Any quadratic whose coefficients are polynomial in K0 and r cannot produce
# the required coefficient -2U/r, because K0 contains U only through U^2.
# We test the stronger symmetry statement U -> -U:
#
# K0 is invariant, while -S is odd in U.
#
# If a candidate coefficient were generated solely from K0,r, it would be
# even in U.

odd_part = sp.expand(((-S_expr) - (-S_expr).subs(U, -U)) / 2)

print("  odd part of required coefficient -S:")
print("   ", sp.factor(odd_part))
cert("required coefficient has nonzero U-odd part", odd_part != 0, True)
print()

# Verify K0 symmetry explicitly.
cert("K0(U)=K0(-U)", K0.subs(U, -U), K0)
print()

# ===========================================================================
# 9. MINIMAL TWO-OBJECT BRIDGE
# ===========================================================================
print("[9] MINIMAL TWO-OBJECT BRIDGE")
print("-" * 78)

# K0 -> N
# K1-K0 -> S+1
# hence the missing coefficient is obtainable from two conic invariants.

N_from_K = sp.expand(K0 / r**2)
S_from_Kpair = sp.expand((K1 - K0) / r**2 - 1)
a_from_Kpair = sp.expand(-S_from_Kpair)

print("  N_from_Kpair =", sp.factor(N_from_K))
print("  S_from_Kpair =", sp.factor(S_from_Kpair))
print("  a_from_Kpair =", sp.factor(a_from_Kpair))

cert("N bridge", N_from_K, N_expr)
cert("S bridge", S_from_Kpair, S_expr)
cert("quadratic coefficient bridge", a_from_Kpair, -S_expr)
print()

# ===========================================================================
# 10. RECURRENCE COEFFICIENTS FROM K0,K1 ONLY
# ===========================================================================
print("[10] RECURRENCE COEFFICIENTS FROM TWO CONIC OBJECTS")
print("-" * 78)

a1_from_pair = sp.expand(2 * (S_from_Kpair + 1))
a2_from_pair = sp.expand(2 * N_from_K + S_from_Kpair**2 + 3*S_from_Kpair + 1)

print("  a1_from_pair =", sp.factor(a1_from_pair))
print("  a2_from_pair =", sp.factor(a2_from_pair))

cert("a1 pair bridge", a1_from_pair, a1)
cert("a2 pair bridge", a2_from_pair, a2)

Delta_from_pair = sp.expand(
    3*a1_from_pair**2 / 4 - 2*a2_from_pair - 1
)

print("  Delta_from_pair =", sp.factor(Delta_from_pair))
cert("Delta pair bridge", Delta_from_pair, Delta_expr)
print()

# ===========================================================================
# 11. UPSTREAM TARGET CLASSIFICATION
# ===========================================================================
print("[11] UPSTREAM TARGET CLASSIFICATION")
print("-" * 78)

print("  CLASS A: one N-only object")
print("    K0 alone -> N")
print("    missing coefficient -S NOT recoverable")
print()
print("  CLASS B: two translated conic objects")
print("    K0, K1 -> N, S")
print("    therefore -> Q0 -> Q1 -> chi_F")
print()
print("  CLASS C: one object plus intrinsic translation")
print("    Q0 with coefficient -S")
print("    T(Q0)=Q0(z-1)")
print("    -> chi_F")
print()
print("  Thus the remaining upstream target is exactly:")
print()
print("      N-only homogeneous construction")
print("          -> K0,K1")
print("        OR")
print("          -> a quadratic Q(z)=z^2+a*z+N")
print("        with a=-S")
print()
print("  Reproducing F0,...,F7 is no longer necessary.")
print()

# ===========================================================================
# 12. FINAL SYMBOLIC AUDIT
# ===========================================================================
print("[12] FINAL SYMBOLIC AUDIT")
print("-" * 78)

checks = {
    "Q0 quadratic": sp.expand(Q0 - Q0_target),
    "translation Q1": sp.expand(Q1_direct - Q1_target),
    "four-base characteristic": sp.expand(chi - chi_target),
    "conic translation": sp.expand(K1 - K0 - r*(2*U + r)),
    "N from K0": sp.expand(N_from_K - N_expr),
    "S from K0,K1": sp.expand(S_from_Kpair - S_expr),
    "quadratic coefficient": sp.expand(a_from_Kpair + S_expr),
    "a1 bridge": sp.expand(a1_from_pair - a1),
    "a2 bridge": sp.expand(a2_from_pair - a2),
    "Delta bridge": sp.expand(Delta_from_pair - Delta_expr),
}

failures = 0
for name, diff in checks.items():
    ok = sp.factor(diff) == 0
    print(f"  {name:<28} PASS={ok}")
    if not ok:
        failures += 1

print()
print("=" * 78)
print("EXPERIMENT 520 FINISHED")
print("=" * 78)
print()
print("CONCLUSION")
print("-" * 78)
print("""
The downstream KAPPA spectrum is generated by a single quadratic

    Q0(z) = z^2 - S*z + N

and the universal translation

    Q1(z) = Q0(z-1).

The historical conic provides an exact two-object representation:

    K0 = U^2-V^2
    K1 = (U+r)^2-V^2

with

    K0/r^2 = N
    (K1-K0)/r^2 - 1 = S.

Therefore

    K0,K1
       -> Q0
       -> Q0(z-1)
       -> chi_F
       -> recurrence
       -> S, Delta.

The important negative result is equally sharp:

    K0 alone
       -> N

cannot supply -S, because K0 is even in U while -S is odd in U.

So the next upstream experiment should search the original
homogeneous-layer construction specifically for TWO translated
quadratic/conic observables analogous to K0 and K1, not for
individual F-values and not for arbitrary feature combinations.

The ideal signature is:

    L0(N-only) = K0/r^2
    L1(N-only) = K1/r^2

or, equivalently,

    L1-L0 = S+1.

That is the narrowest remaining bridge identified by the
2020-2026 coordinate system.
""")

if failures:
    print(f"SYMBOLIC FAILURES = {failures}")
    raise SystemExit(1)
else:
    print("OVERALL EXACT SYMBOLIC AUDIT = True")

