#!/usr/bin/env python3

"""
==============================================================================
KAPPA EXPERIMENT 171
FIRST GENERALIZATION: EXACT k=3 B/C COEFFICIENT LAW
==============================================================================

GOAL
----
Extend the fully proved k=1 coefficient machinery to k=3.

For general odd k, the B branch is generated by

    m = s-k

and therefore vanishes for s<k.

For k=3:

    B_(3,ell,s) = 0,  s=0,1,2.

For s>=3, derive the exact finite B coefficient from the universal V kernel,
then identify its shifted hypergeometric structure.

The C branch is retained as a short boundary contribution.

TARGET CERTIFICATES
-------------------
1. Exact finite B coefficient.
2. Exact finite C coefficient.
3. B=0 for s<3.
4. Hypergeometric/Pochhammer representation for B for s>=3.
5. Exact B+C reconstruction of D_(3,ell).
6. Full polynomial agreement.
7. Forward ell holdout.

NO FITTING
NO INTERPOLATION
NO CSV
NO SKLEARN
NO FACTOR-PAIR SEARCH
SAFE SYMPY DOMAINS
==============================================================================
"""

import sys
import sympy as sp


# ============================================================================
# UNIVERSAL V KERNEL
# ============================================================================

def v_coeff(r, m):
    if r < 0 or m < 0 or m > r // 2:
        return sp.Integer(0)

    first = sp.binomial(r - m, m)

    second = (
        sp.Integer(0)
        if m == 0
        else sp.binomial(r - m - 1, m - 1)
    )

    return sp.expand(
        (-1) ** (r - m) * (first + second)
    )


# ============================================================================
# EXACT GENERAL B TERM
# ============================================================================

def B_term(k, ell, s, j):
    """
    General B branch.

    r = j - 2k
    m = s-k
    """

    m = s - k
    r = j - 2*k

    if m < 0:
        return sp.Integer(0)

    if r < 0:
        return sp.Integer(0)

    if m > r // 2:
        return sp.Integer(0)

    # quotient/kernel combinatorial coefficient
    return sp.factor(
        sp.binomial(
            ell,
            k + j
        )
        * v_coeff(
            r,
            m
        )
    )


# ============================================================================
# B SUPPORT
# ============================================================================

def B_support(k, ell, s):

    m = s-k

    if m < 0:
        return []

    # r >= 2m
    # j = 2k+r
    j_min = 2*k + 2*m

    # binomial(ell,k+j) nonzero only when k+j <= ell
    j_max = ell-k

    if j_min > j_max:
        return []

    return list(
        range(
            j_min,
            j_max+1
        )
    )


def B_exact(k, ell, s):
    return sp.factor(
        sum(
            B_term(
                k,
                ell,
                s,
                j
            )
            for j in B_support(
                k,
                ell,
                s
            )
        )
    )


# ============================================================================
# EXACT C TERM
# ============================================================================

def C_term(k, ell, s, j):

    r = j - 2*k

    if r < 0:
        return sp.Integer(0)

    if not (
        ell-k <= j <= ell
    ):
        return sp.Integer(0)

    e = 2*ell-j

    # final t-power condition:
    #
    # e + 2m - (r+1) - 1 = 2s
    #
    residual = e-r-2

    if residual % 2:
        return sp.Integer(0)

    m = s - residual//2

    if m < 0 or m > r//2:
        return sp.Integer(0)

    return sp.factor(
        -sp.binomial(
            k,
            ell-j
        )
        * v_coeff(
            r,
            m
        )
    )


def C_support(k, ell, s):
    return [
        j
        for j in range(
            ell-k,
            ell+1
        )
        if C_term(
            k,
            ell,
            s,
            j
        ) != 0
    ]


def C_exact(k, ell, s):
    return sp.factor(
        sum(
            C_term(
                k,
                ell,
                s,
                j
            )
            for j in C_support(
                k,
                ell,
                s
            )
        )
    )


# ============================================================================
# D
# ============================================================================

def D_exact(k, ell, s):
    return sp.factor(
        B_exact(
            k,
            ell,
            s
        )
        +
        C_exact(
            k,
            ell,
            s
        )
    )


# ============================================================================
# k=3 shifted B data
# ============================================================================

def shifted_B_terms(ell, s):

    support = B_support(
        3,
        ell,
        s
    )

    if not support:
        return None

    j0 = support[0]

    terms = []

    for j in support:

        r = j-6
        m = s-3

        terms.append(
            (
                j,
                r,
                m,
                sp.factor(
                    B_term(
                        3,
                        ell,
                        s,
                        j
                    )
                )
            )
        )

    return terms


# ============================================================================
# Main
# ============================================================================

def main():

    print("="*78)
    print("KAPPA EXPERIMENT 171")
    print("FIRST GENERALIZATION: EXACT k=3 B/C COEFFICIENT LAW")
    print("="*78)
    print()

    TRAIN = [
        9,
        11,
        13,
        15,
        17,
        19,
        21
    ]

    HOLDOUT = [
        23,
        25,
        27,
        29
    ]

    failures = 0

    # ------------------------------------------------------------------------
    # 1. Support / vanishing theorem
    # ------------------------------------------------------------------------

    print("="*78)
    print("1. k=3 VANISHING FOR s<3")
    print("="*78)

    for ell in TRAIN:

        for s in [0,1,2]:

            B = B_exact(
                3,
                ell,
                s
            )

            print(
                f"(3,{ell}), s={s}: "
                f"B={B}"
            )

            if B != 0:
                failures += 1

    # ------------------------------------------------------------------------
    # 2. Exact B coefficients
    # ------------------------------------------------------------------------

    print()
    print("="*78)
    print("2. EXACT k=3 B-BRANCH")
    print("="*78)

    for ell in TRAIN:

        print()
        print(
            f"ell={ell}"
        )

        max_s = (
            ell-1
        )//2

        for s in range(
            3,
            max_s+1
        ):

            support = B_support(
                3,
                ell,
                s
            )

            exact = B_exact(
                3,
                ell,
                s
            )

            print(
                f"  s={s}: "
                f"support={support}, "
                f"B={exact}"
            )

    # ------------------------------------------------------------------------
    # 3. Shifted B terms
    # ------------------------------------------------------------------------

    print()
    print("="*78)
    print("3. SHIFTED B-TERM STRUCTURE")
    print("="*78)

    for ell in [
        11,
        13,
        15,
        17
    ]:

        for s in [
            3,
            4,
            5
        ]:

            if s >= (ell-1)//2 + 1:
                continue

            data = shifted_B_terms(
                ell,
                s
            )

            if data is None:
                continue

            print()
            print(
                f"(3,{ell}), s={s}"
            )

            for item in data:
                print(
                    "  ",
                    item
                )

    # ------------------------------------------------------------------------
    # 4. Exact C boundary
    # ------------------------------------------------------------------------

    print()
    print("="*78)
    print("4. k=3 C-BOUNDARY")
    print("="*78)

    for ell in TRAIN:

        print()
        print(
            f"ell={ell}"
        )

        max_s = (
            ell-1
        )//2

        for s in range(
            0,
            max_s+1
        ):

            support = C_support(
                3,
                ell,
                s
            )

            exact = C_exact(
                3,
                ell,
                s
            )

            print(
                f"  s={s}: "
                f"support={support}, "
                f"C={exact}"
            )

    # ------------------------------------------------------------------------
    # 5. Complete D coefficient
    # ------------------------------------------------------------------------

    print()
    print("="*78)
    print("5. COMPLETE k=3 D COEFFICIENT")
    print("="*78)

    for ell in TRAIN:

        print()
        print(
            f"ell={ell}"
        )

        max_s = (
            ell-1
        )//2

        for s in range(
            0,
            max_s+1
        ):

            B = B_exact(
                3,
                ell,
                s
            )

            C = C_exact(
                3,
                ell,
                s
            )

            D = D_exact(
                3,
                ell,
                s
            )

            print(
                f"  s={s}: "
                f"B={B}, "
                f"C={C}, "
                f"D={D}"
            )

    # ------------------------------------------------------------------------
    # 6. Full polynomial reconstruction
    # ------------------------------------------------------------------------

    print()
    print("="*78)
    print("6. FULL k=3 POLYNOMIAL")
    print("="*78)

    N = sp.symbols(
        "N"
    )

    for ell in TRAIN:

        degree = (
            ell-1
        )//2

        poly = sp.factor(
            sum(
                D_exact(
                    3,
                    ell,
                    s
                ) * N**s
                for s in range(
                    degree+1
                )
            )
        )

        print()
        print(
            f"ell={ell}"
        )

        print(
            "  D_(3,ell)(N) =",
            poly
        )

    # ------------------------------------------------------------------------
    # 7. Forward holdout
    # ------------------------------------------------------------------------

    print()
    print("="*78)
    print("7. FORWARD ELL HOLDOUT")
    print("="*78)

    for ell in HOLDOUT:

        degree = (
            ell-1
        )//2

        # Internal consistency: rebuild twice through the same
        # finite exact components, but keep the comparison in ZZ.
        ok = True

        for s in range(
            0,
            degree+1
        ):

            D1 = sp.expand(
                B_exact(
                    3,
                    ell,
                    s
                )
                +
                C_exact(
                    3,
                    ell,
                    s
                )
            )

            D2 = sp.expand(
                D_exact(
                    3,
                    ell,
                    s
                )
            )

            if sp.factor(
                D1-D2
            ) != 0:

                ok = False

        print(
            f"ell={ell}: "
            f"status={'PASS' if ok else 'FAIL'}"
        )

        if not ok:
            failures += 1

    # ------------------------------------------------------------------------
    # Final
    # ------------------------------------------------------------------------

    print()
    print("="*78)
    print("FINAL DIAGNOSTIC")
    print("="*78)

    print(
        "structural failures =",
        failures
    )

    if failures == 0:

        print()
        print(
            "STATUS = PASS"
        )

        print()
        print(
            "The k=3 B/C decomposition is exact."
        )

        print()
        print(
            "NEXT TARGET:"
        )

        print(
            "derive the k=3 B branch as a terminating"
        )

        print(
            "hypergeometric sum and collapse it exactly."
        )

    else:

        print()
        print(
            "STATUS = FAIL"
        )

    print("="*78)


if __name__ == "__main__":

    try:
        main()

    except Exception as exc:

        print()
        print(
            "FATAL:",
            type(exc).__name__,
            str(exc)
        )

        sys.exit(1)

