#!/usr/bin/env python3

"""
==============================================================================
KAPPA EXPERIMENT 99R
PATCHED H-TOWER MASTER RECURRENCE SEARCH

PAPER-DERIVED H_k COEFFICIENTS
CORRECT D^2 ACTION: n^2
SEMIPRIME SPECIALIZATION
T = S^2 - 3N = 4 H8/H6

QUESTION:
    Is the entire Eisenstein tower H6,H8,H10,... generated by
    the pair (N,T)?

SEARCHES:
    H10/H6, H12/H6, H14/H6, ...
    H10/H8, H12/H10, ...
    low-degree polynomial representations P(N,T)
    N-only collapse tests

STRICT TRAIN / TEST VALIDATION
NO FACTOR-PAIR CHECK
NO CSV
NO SKLEARN
==============================================================================
"""

from __future__ import annotations

import math
import random
import time
from dataclasses import dataclass
from typing import Dict, List, Sequence, Tuple, Optional

import sympy as sp


# =============================================================================
# PARAMETERS
# =============================================================================

PRIME_MIN = 2_000_000
PRIME_MAX = 4_200_000

NUM_TARGETS = 40
TRAIN_TARGETS = 30

MAX_H_WEIGHT = 20

MAX_N_DEGREE = 3
MAX_T_DEGREE = 4

RANDOM_SEED = 991234


# =============================================================================
# SYMBOLS
# =============================================================================

P, Q = sp.symbols("P Q")
N, S = sp.symbols("N S")
T = sp.symbols("T")


# =============================================================================
# TARGET
# =============================================================================

@dataclass(frozen=True)
class Target:
    p: int
    q: int
    n: int
    s: int


# =============================================================================
# PRIME SIEVE
# =============================================================================

def sieve_primes(lo: int, hi: int) -> List[int]:
    if hi < 2:
        return []

    flags = bytearray(b"\x01") * (hi + 1)
    flags[0] = 0
    flags[1] = 0

    for x in range(2, math.isqrt(hi) + 1):
        if flags[x]:
            start = x * x
            count = ((hi - start) // x) + 1
            flags[start:hi + 1:x] = b"\x00" * count

    return [i for i in range(lo, hi + 1) if flags[i]]


# =============================================================================
# TARGET GENERATION
# =============================================================================

def generate_targets(
    primes: Sequence[int],
    count: int,
) -> List[Target]:

    rng = random.Random(RANDOM_SEED)

    seen = set()
    out: List[Target] = []

    while len(out) < count:
        p = primes[rng.randrange(len(primes))]
        q = primes[rng.randrange(len(primes))]

        if p == q:
            continue

        if p > q:
            p, q = q, p

        key = (p, q)

        if key in seen:
            continue

        seen.add(key)

        out.append(
            Target(
                p=p,
                q=q,
                n=p * q,
                s=p + q,
            )
        )

    return out


# =============================================================================
# DIVISOR-SUM SPECIALIZATION FOR pq
# =============================================================================

def sigma_pq(
    p: sp.Expr,
    q: sp.Expr,
    j: int,
) -> sp.Expr:
    """
    sigma_j(pq) = (1+p^j)(1+q^j)
    """
    return sp.expand(
        (1 + p**j) * (1 + q**j)
    )


# =============================================================================
# CORRECT PAPER H_k FORMULA
# =============================================================================

def H_pq(k: int) -> sp.Expr:
    """
    Paper definition:

        H6 = 1/6 ((D^2-D+1)G2 - G4)

    For k >= 8:

        H_k = 1/24(
              -D^2 G_{k-6}
              +(D^2+1)G_{k-4}
              -G_{k-2}
        )

    Since D^2(q^n) = n^2 q^n,

        24 H_k(n)
          = -n^2 sigma_{k-7}(n)
            +(n^2+1) sigma_{k-5}(n)
            - sigma_{k-3}(n).

    This is the critical correction to Experiment 99.
    """

    n = P * Q

    if k == 6:
        return sp.expand(
            (
                (n**2 - n + 1) * sigma_pq(P, Q, 1)
                - sigma_pq(P, Q, 3)
            ) / 6
        )

    if k < 8 or k % 2:
        raise ValueError(
            "H_pq only implemented for even k >= 6."
        )

    return sp.expand(
        (
            -n**2 * sigma_pq(P, Q, k - 7)
            + (n**2 + 1) * sigma_pq(P, Q, k - 5)
            - sigma_pq(P, Q, k - 3)
        ) / 24
    )


# =============================================================================
# SYMMETRIC REDUCTION
# =============================================================================

def symmetric_to_NS(expr: sp.Expr) -> sp.Expr:
    """
    Convert a symmetric polynomial in p,q to a polynomial in
    S=p+q and N=pq.
    """

    reduced, remainder, mapping = sp.symmetrize(
        sp.expand(expr),
        [P, Q],
        formal=True,
    )

    if remainder != 0:
        raise ArithmeticError(
            f"Nonzero symmetric reduction remainder: {remainder}"
        )

    # symmetrize(..., formal=True) returns elementary symmetric symbols.
    s1 = mapping[0][0]
    s2 = mapping[1][0]

    return sp.expand(
        reduced.subs(
            {
                s1: S,
                s2: N,
            }
        )
    )


# =============================================================================
# BUILD TOWER
# =============================================================================

def build_tower() -> Dict[int, sp.Expr]:

    print("\n1. BUILDING SEMIPRIME H-TOWER")
    print("-" * 78)

    tower: Dict[int, sp.Expr] = {}

    for k in range(6, MAX_H_WEIGHT + 1, 2):

        raw = H_pq(k)

        ns = sp.factor(
            symmetric_to_NS(raw)
        )

        tower[k] = ns

        poly = sp.Poly(
            ns,
            N,
            S,
            domain="EX",
        )

        print(
            f"H{k}: "
            f"degree_N={poly.degree(N)} "
            f"degree_S={poly.degree(S)} "
            f"total_degree={poly.total_degree()}"
        )

    return tower


# =============================================================================
# NUMERIC EVALUATION
# =============================================================================

def eval_NS(
    expr: sp.Expr,
    n: int,
    s: int,
) -> int:

    value = expr.subs(
        {
            N: n,
            S: s,
        }
    )

    if value.is_Rational:
        if value.q != 1:
            raise ArithmeticError(
                f"Non-integral H coefficient: {value}"
            )
        return int(value)

    return int(value)


# =============================================================================
# BASIC H6/H8 RESOLVENT VALIDATION
# =============================================================================

def validate_basic_resolvent(
    tower: Dict[int, sp.Expr],
    targets: Sequence[Target],
) -> None:

    print("\n2. H6/H8 RESOLVENT VALIDATION")
    print("-" * 78)

    H6 = tower[6]
    H8 = tower[8]

    failures = 0
    h6_zero = 0

    for i, t in enumerate(targets, 1):

        h6 = eval_NS(H6, t.n, t.s)
        h8 = eval_NS(H8, t.n, t.s)

        if h6 == 0:
            h6_zero += 1
            failures += 1
            continue

        recovered_t = sp.Rational(
            4 * h8,
            h6,
        )

        expected_t = sp.Integer(
            t.s * t.s - 3 * t.n
        )

        if recovered_t != expected_t:
            failures += 1
            print(
                f"target {i}: FAIL "
                f"recovered={recovered_t} "
                f"expected={expected_t}"
            )

    print(
        f"resolvent failures = {failures}/{len(targets)}"
    )
    print(
        f"H6 zero targets    = {h6_zero}"
    )

    if failures:
        raise ArithmeticError(
            "Correct H8/H6 resolvent validation failed."
        )

    print("status = PASS")


# =============================================================================
# REDUCTION MODULO T RELATION
# =============================================================================

def reduce_mod_T(
    expr: sp.Expr,
) -> sp.Expr:
    """
    Reduce with

        S^2 = T + 3N

    so every polynomial becomes A(N,T)*S + B(N,T).
    """

    poly = sp.Poly(
        sp.expand(expr),
        S,
        domain="EX",
    )

    relation = sp.Poly(
        S**2 - 3*N - T,
        S,
        domain="EX",
    )

    remainder = sp.rem(
        poly,
        relation,
    )

    return sp.factor(
        remainder.as_expr()
    )


def split_linear_S(
    expr: sp.Expr,
) -> Tuple[sp.Expr, sp.Expr]:

    reduced = reduce_mod_T(expr)

    poly = sp.Poly(
        reduced,
        S,
        domain="EX",
    )

    if poly.degree() <= 0:
        return (
            sp.Integer(0),
            sp.factor(poly.as_expr()),
        )

    if poly.degree() != 1:
        raise ArithmeticError(
            "Expression did not reduce to degree <= 1 in S."
        )

    coeffs = poly.all_coeffs()

    return (
        sp.factor(coeffs[0]),
        sp.factor(coeffs[1]),
    )


# =============================================================================
# INTERPOLATION BASIS
# =============================================================================

def monomial_basis(
    max_n: int,
    max_t: int,
) -> List[sp.Expr]:

    return [
        N**i * T**j
        for i in range(max_n + 1)
        for j in range(max_t + 1)
    ]


def fit_polynomial(
    samples: Sequence[
        Tuple[int, int, sp.Rational]
    ],
    max_n: int,
    max_t: int,
) -> Optional[sp.Expr]:

    basis = monomial_basis(
        max_n,
        max_t,
    )

    if len(samples) < len(basis):
        return None

    A_rows = []
    b_vals = []

    for n0, t0, value in samples:

        A_rows.append(
            [
                sp.Integer(n0)**i
                * sp.Integer(t0)**j
                for i in range(max_n + 1)
                for j in range(max_t + 1)
            ]
        )

        b_vals.append(value)

    A = sp.Matrix(A_rows)
    b = sp.Matrix(b_vals)

    try:
        solution = sp.linsolve(
            (A, b)
        )
    except Exception:
        return None

    if solution == sp.EmptySet:
        return None

    tuples = list(solution)

    if not tuples:
        return None

    vec = tuples[0]

    # Reject underdetermined fits.
    if any(x.free_symbols for x in vec):
        return None

    expr = sp.expand(
        sum(
            c * m
            for c, m in zip(vec, basis)
        )
    )

    return sp.factor(expr)


# =============================================================================
# TEST CANDIDATE
# =============================================================================

def validate_formula(
    formula: sp.Expr,
    actual_num: sp.Expr,
    actual_den: sp.Expr,
    targets: Sequence[Target],
) -> int:

    failures = 0

    for t in targets:

        den = eval_NS(
            actual_den,
            t.n,
            t.s,
        )

        num = eval_NS(
            actual_num,
            t.n,
            t.s,
        )

        if den == 0:
            failures += 1
            continue

        actual = sp.Rational(
            num,
            den,
        )

        tv = sp.Integer(
            t.s * t.s - 3 * t.n
        )

        predicted = sp.cancel(
            formula.subs(
                {
                    N: t.n,
                    T: tv,
                }
            )
        )

        if sp.simplify(
            predicted - actual
        ) != 0:
            failures += 1

    return failures


# =============================================================================
# DIRECT TOWER RATIOS
# =============================================================================

def tower_ratio_analysis(
    tower: Dict[int, sp.Expr],
) -> None:

    print(
        "\n3. TOWER RATIO STRUCTURE"
    )
    print("-" * 78)

    for k in range(
        8,
        MAX_H_WEIGHT + 1,
        2,
    ):

        numerator = tower[k]
        denominator = tower[6]

        ratio = sp.factor(
            sp.cancel(
                numerator / denominator
            )
        )

        reduced_num = reduce_mod_T(
            numerator
        )

        reduced_den = reduce_mod_T(
            denominator
        )

        a_num, b_num = split_linear_S(
            numerator
        )

        a_den, b_den = split_linear_S(
            denominator
        )

        print(
            f"\nH{k}/H6"
        )
        print(
            f"  ratio = {ratio}"
        )
        print(
            f"  H{k} reduced = "
            f"({a_num})*S + ({b_num})"
        )
        print(
            f"  H6 reduced = "
            f"({a_den})*S + ({b_den})"
        )


# =============================================================================
# H_k / H_6 POLYNOMIAL SEARCH
# =============================================================================

def search_Hk_over_H6(
    tower: Dict[int, sp.Expr],
    targets: Sequence[Target],
) -> None:

    print(
        "\n4. H_k / H6 POLYNOMIAL SEARCH IN (N,T)"
    )
    print("-" * 78)

    train = targets[:TRAIN_TARGETS]
    test = targets[TRAIN_TARGETS:]

    H6 = tower[6]

    for k in range(
        8,
        MAX_H_WEIGHT + 1,
        2,
    ):

        Hk = tower[k]

        samples = []

        invalid = False

        for t in train:

            h6 = eval_NS(
                H6,
                t.n,
                t.s,
            )

            if h6 == 0:
                invalid = True
                break

            hk = eval_NS(
                Hk,
                t.n,
                t.s,
            )

            tv = t.s * t.s - 3 * t.n

            samples.append(
                (
                    t.n,
                    tv,
                    sp.Rational(
                        hk,
                        h6,
                    ),
                )
            )

        if invalid:
            print(
                f"H{k}/H6: invalid zero denominator"
            )
            continue

        found = None

        for dn in range(
            MAX_N_DEGREE + 1
        ):
            for dt in range(
                MAX_T_DEGREE + 1
            ):

                formula = fit_polynomial(
                    samples,
                    dn,
                    dt,
                )

                if formula is None:
                    continue

                failures = 0

                for t in test:

                    h6 = eval_NS(
                        H6,
                        t.n,
                        t.s,
                    )
                    hk = eval_NS(
                        Hk,
                        t.n,
                        t.s,
                    )

                    if h6 == 0:
                        failures += 1
                        continue

                    tv = sp.Integer(
                        t.s * t.s - 3 * t.n
                    )

                    actual = sp.Rational(
                        hk,
                        h6,
                    )

                    predicted = sp.cancel(
                        formula.subs(
                            {
                                N: t.n,
                                T: tv,
                            }
                        )
                    )

                    if sp.simplify(
                        predicted - actual
                    ) != 0:
                        failures += 1

                if failures == 0:
                    found = (
                        dn,
                        dt,
                        formula,
                    )
                    break

            if found is not None:
                break

        if found is None:
            print(
                f"H{k}/H6: "
                "NO low-degree polynomial "
                "validated on holdout"
            )
        else:
            dn, dt, formula = found
            print(
                f"H{k}/H6:"
            )
            print(
                f"  degree_N = {dn}"
            )
            print(
                f"  degree_T = {dt}"
            )
            print(
                f"  formula = {formula}"
            )
            print(
                f"  holdout = PASS"
            )


# =============================================================================
# CONSECUTIVE RATIO SEARCH
# =============================================================================

def search_consecutive_ratios(
    tower: Dict[int, sp.Expr],
    targets: Sequence[Target],
) -> None:

    print(
        "\n5. CONSECUTIVE H_{k+2}/H_k SEARCH"
    )
    print("-" * 78)

    train = targets[:TRAIN_TARGETS]
    test = targets[TRAIN_TARGETS:]

    for k in range(
        8,
        MAX_H_WEIGHT,
        2,
    ):

        Hk = tower[k]
        Hnext = tower[k + 2]

        samples = []

        valid = True

        for t in train:

            old = eval_NS(
                Hk,
                t.n,
                t.s,
            )

            if old == 0:
                valid = False
                break

            new = eval_NS(
                Hnext,
                t.n,
                t.s,
            )

            tv = t.s * t.s - 3 * t.n

            samples.append(
                (
                    t.n,
                    tv,
                    sp.Rational(
                        new,
                        old,
                    ),
                )
            )

        if not valid:
            print(
                f"H{k+2}/H{k}: zero denominator"
            )
            continue

        found = None

        for dn in range(
            MAX_N_DEGREE + 1
        ):
            for dt in range(
                MAX_T_DEGREE + 1
            ):

                formula = fit_polynomial(
                    samples,
                    dn,
                    dt,
                )

                if formula is None:
                    continue

                failures = 0

                for t in test:

                    old = eval_NS(
                        Hk,
                        t.n,
                        t.s,
                    )
                    new = eval_NS(
                        Hnext,
                        t.n,
                        t.s,
                    )

                    if old == 0:
                        failures += 1
                        continue

                    tv = sp.Integer(
                        t.s * t.s - 3 * t.n
                    )

                    actual = sp.Rational(
                        new,
                        old,
                    )

                    predicted = sp.cancel(
                        formula.subs(
                            {
                                N: t.n,
                                T: tv,
                            }
                        )
                    )

                    if sp.simplify(
                        predicted - actual
                    ) != 0:
                        failures += 1

                if failures == 0:
                    found = (
                        dn,
                        dt,
                        formula,
                    )
                    break

            if found is not None:
                break

        if found is None:
            print(
                f"H{k+2}/H{k}: "
                "NO low-degree polynomial "
                "validated on holdout"
            )
        else:
            dn, dt, formula = found
            print(
                f"H{k+2}/H{k}:"
            )
            print(
                f"  degree_N = {dn}"
            )
            print(
                f"  degree_T = {dt}"
            )
            print(
                f"  formula = {formula}"
            )
            print(
                "  holdout = PASS"
            )


# =============================================================================
# SYMBOLIC T-ONLY TEST
# =============================================================================

def symbolic_T_collapse_test(
    tower: Dict[int, sp.Expr],
) -> None:

    print(
        "\n6. SYMBOLIC T-ONLY COLLAPSE TEST"
    )
    print("-" * 78)

    for k in range(
        8,
        MAX_H_WEIGHT + 1,
        2,
    ):

        reduced = reduce_mod_T(
            tower[k]
        )

        a, b = split_linear_S(
            tower[k]
        )

        print(
            f"H{k}:"
        )
        print(
            f"  S coefficient = {a}"
        )

        if sp.expand(a) == 0:
            print(
                "  STATUS = T-ONLY"
            )
        else:
            print(
                "  STATUS = still contains S"
            )


# =============================================================================
# MAIN
# =============================================================================

def main() -> None:

    start = time.perf_counter()

    print("=" * 78)
    print("KAPPA EXPERIMENT 99R")
    print("PATCHED H-TOWER MASTER RECURRENCE SEARCH")
    print("CORRECT n^2 EISENSTEIN DERIVATIVE FACTOR")
    print("T = S^2 - 3N = 4H8/H6")
    print("STRICT TARGET HOLDOUT")
    print("NO FACTOR-PAIR CHECK")
    print("NO CSV")
    print("NO SKLEARN")
    print("=" * 78)

    # -------------------------------------------------------------------------
    # PRIME POPULATION
    # -------------------------------------------------------------------------

    t0 = time.perf_counter()

    primes = sieve_primes(
        PRIME_MIN,
        PRIME_MAX,
    )

    print(
        "\n1. PRIME POPULATION"
    )
    print("-" * 78)
    print(
        f"prime population = {len(primes)}"
    )
    print(
        f"generation time = "
        f"{time.perf_counter() - t0:.6f}s"
    )

    # -------------------------------------------------------------------------
    # TARGETS
    # -------------------------------------------------------------------------

    targets = generate_targets(
        primes,
        NUM_TARGETS,
    )

    for i, t in enumerate(
        targets[:20],
        1,
    ):
        print(
            f"target {i:3d}: "
            f"p={t.p} "
            f"q={t.q} "
            f"n={t.n} "
            f"s={t.s}"
        )

    print(
        f"\ntraining targets = {TRAIN_TARGETS}"
    )
    print(
        f"test targets     = "
        f"{NUM_TARGETS - TRAIN_TARGETS}"
    )

    # -------------------------------------------------------------------------
    # BUILD
    # -------------------------------------------------------------------------

    tower = build_tower()

    # -------------------------------------------------------------------------
    # CRITICAL VALIDATION
    # -------------------------------------------------------------------------

    validate_basic_resolvent(
        tower,
        targets,
    )

    # -------------------------------------------------------------------------
    # STRUCTURE
    # -------------------------------------------------------------------------

    tower_ratio_analysis(
        tower
    )

    # -------------------------------------------------------------------------
    # POLYNOMIAL SEARCH
    # -------------------------------------------------------------------------

    search_Hk_over_H6(
        tower,
        targets,
    )

    # -------------------------------------------------------------------------
    # CONSECUTIVE RECURRENCE
    # -------------------------------------------------------------------------

    search_consecutive_ratios(
        tower,
        targets,
    )

    # -------------------------------------------------------------------------
    # SYMBOLIC COLLAPSE
    # -------------------------------------------------------------------------

    symbolic_T_collapse_test(
        tower
    )

    # -------------------------------------------------------------------------
    # FINAL
    # -------------------------------------------------------------------------

    print(
        "\n7. FINAL DIAGNOSTIC"
    )
    print("=" * 78)

    print(
        """
The critical correction is that D^2 acting on q^n contributes n^2.

Therefore for k >= 8:

    24 H_k(n)
      = -n^2 sigma_{k-7}(n)
        +(n^2+1) sigma_{k-5}(n)
        -sigma_{k-3}(n).

For n=pq this gives the exact semiprime H_k coefficient.

The first mandatory check is

    H8/H6 = (S^2 - 3N)/4.

If this passes, the experiment asks the next structural question:

    Is H_{k+2}/H_k a low-degree polynomial in
    N and T = S^2 - 3N?

A successful low-degree recurrence across held-out targets would
strongly compress the entire Eisenstein tower.

This remains an oracle structural experiment:
H_k is still evaluated from p,q.
It does not yet produce an N-only factorization algorithm.
"""
    )

    print(
        f"\ntotal runtime = "
        f"{time.perf_counter() - start:.6f}s"
    )

    print("=" * 78)
    print("EXPERIMENT 99R COMPLETE")
    print("=" * 78)


if __name__ == "__main__":
    main()