#!/usr/bin/env python3
"""
==============================================================================
EXPERIMENT 151 — EXACT 2-ADIC DEFECT / BOUNDARY-COORDINATE AUDIT
==============================================================================

Experiment 150 established that the first 2-adic defect

    E mod 2

has rank 3 and is distributed across the retained transition rows

    p=1 -> 3 : 5 rows
    p=3 -> 5 : 4 rows
    p=5 -> 7 : 3 rows.

The substantive findings were:

    rank(p=1 -> 3) = 2
    rank(p=3 -> 5) = 2
    rank(p=5 -> 7) = 1

and cumulatively

    rank(first) = 2
    rank(first+second) = 3
    rank(first+second+third) = 3.

Several rows are exactly identical modulo 2 across different
transitions.

Experiment 151 tests the most natural remaining coordinate:

    d = D(p) - r.

For each retained row we record

    (p, r, d)

and compare its defect row E(p,r) against every other row having:

    the same d,
    the same r,
    the same distance from the terminal boundary.

The experiment tests:

    1. exact equality of defect rows for equal d;
    2. equality for equal r;
    3. equality for equal (d mod 2);
    4. the rank of all rows grouped by d;
    5. whether the three defect directions can be generated by
       a small family indexed only by d;
    6. whether p contributes an independent direction after d is fixed.

This is a provenance test, not a recurrence fit.

No coefficients are interpolated.

No SymPy.
No floating point.
No extrapolation.
No connection to the original (p,q)-kernel is asserted.
"""

from __future__ import annotations

from fractions import Fraction
import sys


# ============================================================================
# DATA
# ============================================================================

Q = {
    1: [
        -126258696,
        -11600759760,
        2668721436,
        1764373740,
        -1338089411,
        495451247,
    ],
    3: [
        9955176,
        -1263551016,
        -152369292,
        -128667196,
        421514439,
    ],
    5: [
        -62398,
        4771718,
        16027881,
    ],
    7: [
        1,
    ],
}

D = {
    1: 5,
    3: 4,
    5: 2,
    7: 0,
}

TRANSITIONS = [
    (1, 3),
    (3, 5),
    (5, 7),
]

DELTA_11 = 9512681472


# ============================================================================
# HELPERS
# ============================================================================

def q_value(p, r):
    if r < 0 or r >= len(Q[p]):
        return 0
    return Q[p][r]


def basis(p, d):
    return [
        1,
        d,
        d*d,
        p,
        p*d,
        p*p,
    ]


def bareiss_det(A):

    if not A:
        return 1

    M = [[int(x) for x in row] for row in A]
    n = len(M)

    if n == 1:
        return M[0][0]

    prev = 1
    sign = 1

    for k in range(n - 1):

        pivot = None

        for r in range(k, n):
            if M[r][k] != 0:
                pivot = r
                break

        if pivot is None:
            return 0

        if pivot != k:
            M[k], M[pivot] = M[pivot], M[k]
            sign *= -1

        pk = M[k][k]

        for i in range(k + 1, n):

            for j in range(k + 1, n):

                v = (
                    M[i][j] * pk
                    - M[i][k] * M[k][j]
                )

                if k > 0:
                    if v % prev != 0:
                        raise ArithmeticError(
                            "Bareiss division failure."
                        )
                    v //= prev

                M[i][j] = v

        for i in range(k + 1, n):
            M[i][k] = 0

        prev = pk

    return sign * M[-1][-1]


def build_system():

    M = []
    meta = []

    for p, pnext in TRANSITIONS:

        for r in range(D[p] + 1):

            d = D[p] - r

            q0 = q_value(p, r)
            q1 = q_value(p, r + 1)

            b = basis(p, d)

            row = [0] * 14

            for j in range(6):
                row[j] = b[j] * q0

            for j in range(6):
                row[6+j] = b[j] * q1

            if d == 0:
                row[12] = 1
                row[13] = p

            M.append(row)

            meta.append(
                {
                    "p": p,
                    "pnext": pnext,
                    "r": r,
                    "d": d,
                }
            )

    return M, meta


def build_core(M):

    b0 = M[5]
    b1 = M[10]

    H = [
        [b0[12], b0[13]],
        [b1[12], b1[13]],
    ]

    detH = (
        H[0][0]*H[1][1]
        - H[0][1]*H[1][0]
    )

    if detH == 0:
        raise ArithmeticError(
            "Boundary block singular."
        )

    Hinv = [
        [
            Fraction(H[1][1], detH),
            Fraction(-H[0][1], detH),
        ],
        [
            Fraction(-H[1][0], detH),
            Fraction(H[0][0], detH),
        ],
    ]

    hc = [
        [Fraction(0) for _ in range(12)]
        for _ in range(2)
    ]

    for i in range(2):
        for j in range(12):
            hc[i][j] = -(
                Hinv[i][0]*b0[j]
                + Hinv[i][1]*b1[j]
            )

    core = []
    core_meta = []

    for idx in range(14):

        if idx in (5, 10):
            continue

        row = M[idx]

        out = []

        for j in range(12):

            v = (
                Fraction(row[j])
                + Fraction(row[12])*hc[0][j]
                + Fraction(row[13])*hc[1][j]
            )

            if v.denominator != 1:
                raise ArithmeticError(
                    "Non-integral F-core entry."
                )

            out.append(v.numerator)

        core.append(out)

    return core


def maximal_minor(A, i, j):

    rows = [
        r for r in range(len(A))
        if r != i
    ]

    cols = [
        c for c in range(len(A[0]))
        if c != j
    ]

    return [
        [A[r][c] for c in cols]
        for r in rows
    ]


def normalized_cofactors(A):

    n = len(A)
    R = []

    for i in range(n):

        row = []

        for j in range(n):

            det = bareiss_det(
                maximal_minor(A, i, j)
            )

            if det % DELTA_11 != 0:
                raise ArithmeticError(
                    "Delta_11 divisibility failure."
                )

            row.append(
                det // DELTA_11
            )

        R.append(row)

    return R


# ============================================================================
# MOD-2 LINEAR ALGEBRA
# ============================================================================

def rref2(A):

    M = [
        [int(x) & 1 for x in row]
        for row in A
    ]

    rows = len(M)
    cols = len(M[0])

    pivots = []
    rp = 0

    for c in range(cols):

        pivot = None

        for r in range(rp, rows):
            if M[r][c]:
                pivot = r
                break

        if pivot is None:
            continue

        M[rp], M[pivot] = M[pivot], M[rp]

        for r in range(rows):

            if r == rp:
                continue

            if M[r][c]:
                for j in range(c, cols):
                    M[r][j] ^= M[rp][j]

        pivots.append(c)
        rp += 1

        if rp == rows:
            break

    return M, pivots


def rank2(A):
    _, pivots = rref2(A)
    return len(pivots)


# ============================================================================
# MOD-8 RANK-1 DEFECT
# ============================================================================

def make_defect(R):

    n = len(R)

    pivot = None
    inv = None

    for i in range(n):

        for j in range(n):

            x = R[i][j] % 8

            if x == 0:
                continue

            try:
                inv = pow(x, -1, 8)
            except ValueError:
                continue

            pivot = (i, j)
            break

        if pivot is not None:
            break

    if pivot is None:
        raise ArithmeticError(
            "No unit pivot modulo 8."
        )

    i0, j0 = pivot

    u = [
        R[i][j0] % 8
        for i in range(n)
    ]

    v = [
        R[i0][j] * inv % 8
        for j in range(n)
    ]

    E = []

    for i in range(n):

        row = []

        for j in range(n):

            diff = (
                R[i][j]
                - u[i]*v[j]
            )

            if diff % 8 != 0:
                raise ArithmeticError(
                    "Invalid mod-8 factorization."
                )

            row.append(
                (diff // 8) & 1
            )

        E.append(row)

    return E


# ============================================================================
# GROUPING
# ============================================================================

def group_indices(meta, key_function):

    groups = {}

    for i, info in enumerate(meta):

        key = key_function(info)

        groups.setdefault(
            key,
            [],
        ).append(i)

    return groups


def row_tuple(row):
    return tuple(row)


# ============================================================================
# MAIN
# ============================================================================

def main():

    print("=" * 78)
    print(
        "EXPERIMENT 151 — EXACT 2-ADIC DEFECT / "
        "BOUNDARY-COORDINATE AUDIT"
    )
    print("=" * 78)

    M, full_meta = build_system()
    core = build_core(M)
    R = normalized_cofactors(core)

    # Reconstruct retained core metadata.
    meta = [
        info
        for idx, info in enumerate(full_meta)
        if idx not in (5, 10)
    ]

    E = make_defect(R)

    # ------------------------------------------------------------------
    # 1. VALIDATION
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("1. EXACT DATA VALIDATION")
    print("=" * 78)

    print(
        f"  retained_rows={len(meta)}"
    )

    print(
        f"  defect_rows={len(E)}"
    )

    print(
        f"  defect_columns={len(E[0])}"
    )

    print(
        f"  defect_rank={rank2(E)}"
    )

    # ------------------------------------------------------------------
    # 2. COMPLETE p,r,d TABLE
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("2. EXACT (p,r,d) DEFECT TABLE")
    print("=" * 78)

    for i, info in enumerate(meta):

        print(
            f"  row={i}: "
            f"p={info['p']} "
            f"r={info['r']} "
            f"d={info['d']} "
            f"type={row_tuple(E[i])}"
        )

    # ------------------------------------------------------------------
    # 3. SAME-d GROUPS
    # ------------------------------------------------------------------

    by_d = group_indices(
        meta,
        lambda x: x["d"],
    )

    print()
    print("=" * 78)
    print("3. GROUPING BY BOUNDARY DISTANCE d")
    print("=" * 78)

    same_d_rank_data = {}

    for d in sorted(by_d):

        rows = by_d[d]

        block = [
            E[i]
            for i in rows
        ]

        rnk = rank2(block)

        same_d_rank_data[d] = rnk

        print()
        print(
            f"  d={d}: rows={rows} rank={rnk}"
        )

        for i in rows:
            print(
                f"    row={i} "
                f"p={meta[i]['p']} "
                f"r={meta[i]['r']} "
                f"type={row_tuple(E[i])}"
            )

    # ------------------------------------------------------------------
    # 4. GROUPING BY r
    # ------------------------------------------------------------------

    by_r = group_indices(
        meta,
        lambda x: x["r"],
    )

    print()
    print("=" * 78)
    print("4. GROUPING BY ORIGINAL FALLING INDEX r")
    print("=" * 78)

    for r in sorted(by_r):

        rows = by_r[r]

        block = [
            E[i]
            for i in rows
        ]

        print()
        print(
            f"  r={r}: rows={rows} rank={rank2(block)}"
        )

        for i in rows:
            print(
                f"    p={meta[i]['p']} "
                f"d={meta[i]['d']} "
                f"type={row_tuple(E[i])}"
            )

    # ------------------------------------------------------------------
    # 5. d PARITY
    # ------------------------------------------------------------------

    by_dparity = group_indices(
        meta,
        lambda x: x["d"] % 2,
    )

    print()
    print("=" * 78)
    print("5. GROUPING BY d PARITY")
    print("=" * 78)

    for parity in sorted(by_dparity):

        rows = by_dparity[parity]

        block = [
            E[i]
            for i in rows
        ]

        print(
            f"  d mod 2={parity}: "
            f"rows={rows} "
            f"rank={rank2(block)}"
        )

    # ------------------------------------------------------------------
    # 6. EQUALITY TEST FOR SAME d
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("6. SAME-d ROW EQUALITY AUDIT")
    print("=" * 78)

    same_d_exact = True

    for d in sorted(by_d):

        rows = by_d[d]

        if len(rows) <= 1:
            continue

        first = row_tuple(E[rows[0]])

        equal = all(
            row_tuple(E[i]) == first
            for i in rows[1:]
        )

        print(
            f"  d={d}: equal={equal}"
        )

        same_d_exact = (
            same_d_exact
            and equal
        )

    # ------------------------------------------------------------------
    # 7. p-DEPENDENCE AFTER FIXING d
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("7. p-DEPENDENCE AT FIXED d")
    print("=" * 78)

    for d in sorted(by_d):

        rows = by_d[d]

        if len(rows) <= 1:
            continue

        types = [
            row_tuple(E[i])
            for i in rows
        ]

        distinct = len(set(types))

        print(
            f"  d={d}: "
            f"distinct_row_types={distinct}"
        )

        for i in rows:

            print(
                f"    p={meta[i]['p']} "
                f"r={meta[i]['r']} "
                f"type={row_tuple(E[i])}"
            )

    # ------------------------------------------------------------------
    # 8. DEFECT DIRECTION COUNT BY d
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("8. DISTINCT DEFECT DIRECTIONS BY d")
    print("=" * 78)

    all_types = {}

    for i, info in enumerate(meta):

        key = row_tuple(E[i])

        all_types.setdefault(
            key,
            [],
        ).append(
            (
                info["p"],
                info["r"],
                info["d"],
            )
        )

    for index, (key, locations) in enumerate(
        sorted(
            all_types.items(),
            key=lambda x: x[1][0],
        )
    ):

        print()
        print(
            f"  direction_{index}:"
        )

        print(
            f"    locations={locations}"
        )

        print(
            f"    vector={list(key)}"
        )

    # ------------------------------------------------------------------
    # 9. STRUCTURAL INTERPRETATION
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("9. STRUCTURAL INTERPRETATION")
    print("=" * 78)

    print(
        """
The purpose of this experiment is to test whether the first 2-adic
obstruction is naturally indexed by the boundary-distance coordinate

    d = D(p) - r.

There are three possible outcomes:

    A. same d gives the same defect row;
       then d alone may explain the repeated directions;

    B. same d splits into several defect rows;
       then p or r carries independent information;

    C. d-group ranks remain large;
       then the defect is not naturally boundary-distance indexed.

The test deliberately uses exact row equality and exact F_2 ranks.

No interpolation is involved.

In particular, a repeated row vector across different p values is
reported as an observed equality, not promoted to a general formula.

The central question is therefore whether the rank-3 obstruction can
already be organized by the finite boundary coordinate d.
"""
    )

    # ------------------------------------------------------------------
    # 10. FINAL
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("10. FINAL EXACTNESS")
    print("=" * 78)

    final_ok = (
        len(meta) == 12
        and len(E) == 12
        and len(E[0]) == 12
        and rank2(E) == 3
        and len(all_types) <= 3
    )

    print(
        f"  data_exact={len(meta) == 12 and len(E) == 12}"
    )

    print(
        f"  defect_rank_exact={rank2(E) == 3}"
    )

    print(
        f"  distinct_direction_count={len(all_types)}"
    )

    print(
        f"  same_d_equality={same_d_exact}"
    )

    print(
        f"  boundary_coordinate_audit_completed=True"
    )

    print(
        f"  failures={0 if final_ok else 1}"
    )

    print(
        f"  ALL BASIC CHECKS PASS={final_ok}"
    )

    print()
    print("EXPERIMENT 151 COMPLETE")


if __name__ == "__main__":

    try:
        main()

    except KeyboardInterrupt:

        print("\nInterrupted.")
        sys.exit(130)

    except Exception as exc:

        print(
            "\nFATAL ERROR: "
            + type(exc).__name__
            + ": "
            + str(exc)
        )

        raise

