#!/usr/bin/env python3

from fractions import Fraction
from math import factorial, gcd
from functools import reduce


# ============================================================================
# EXPERIMENT 117
# EXACT RESIDUAL-KERNEL INDEX RECURRENCE AUDIT
# ============================================================================
#
# Established:
#
#   C_p(k) = (K-k)_s Q_p(k)
#
#   Q_p(k) = sum_r q[p,r] k_(r)
#
# Experiment 115 established the second falling-basis representation.
# Experiment 116 found no rank collapse under several natural
# normalizations.
#
# Experiment 117 asks a more structural question:
#
#     Can consecutive parity rows q[p,r] be generated by
#     a finite-order recurrence in p with coefficients that are
#     low-degree polynomials in r?
#
# We test:
#
#   q[p+2,r]
#       = sum_{a=0}^{A} f_a(r) q[p,r+a]
#
# and
#
#   q[p+4,r]
#       = sum_{a=0}^{A} f_a(r) q[p,r+a]
#
# with f_a(r) polynomials of bounded degree.
#
# The search is exact over QQ.
#
# We also test the simpler multiplicative form
#
#     q[p+2,r] = f(r) q[p,r]
#
# and affine-shift forms.
#
# Crucially, every candidate is accepted only when the exact identity
# holds at every available overlapping coefficient.
#
# No floating point.
# No SymPy.
# No extrapolation.
#
# ============================================================================


# ----------------------------------------------------------------------------
# DATA FROM EXPERIMENT 115
# ----------------------------------------------------------------------------

A_even = {
    0: [
        Fraction(-12879), Fraction(-15362), Fraction(8307),
        Fraction(-748), Fraction(-62305, 144),
        Fraction(34070797, 201600), Fraction(-102402481, 3628800)
    ],
    2: [
        Fraction(2797337, 11520), Fraction(7319861, 19200),
        Fraction(-266207819, 1612800), Fraction(-141551327, 14515200),
        Fraction(2461903867, 116121600),
        Fraction(-783039371, 116121600)
    ],
    4: [
        Fraction(-2083937, 921600), Fraction(-3930151, 921600),
        Fraction(218532413, 77414400), Fraction(238646881, 232243200),
        Fraction(-145404619, 92897280)
    ],
    6: [
        Fraction(85591, 22118400), Fraction(249013, 22118400),
        Fraction(-24042833, 619315200)
    ],
    8: [
        Fraction(-4913, 353894400)
    ],
}

A_odd = {
    1: [
        Fraction(12143, 3360), Fraction(76427, 192),
        Fraction(1954873, 17920), Fraction(-61469491, 483840),
        Fraction(42852113, 1935360), Fraction(4384549, 645120)
    ],
    3: [
        Fraction(-989, 345600), Fraction(-36064769, 2764800),
        Fraction(-24988097, 2580480), Fraction(87300373, 19353600),
        Fraction(116226679, 77414400)
    ],
    5: [
        Fraction(-517, 2764800), Fraction(1189391, 5529600),
        Fraction(22183547, 103219200), Fraction(-69294643, 185794560)
    ],
    7: [
        Fraction(373, 928972800), Fraction(-616981, 371589120)
    ],
}

B_even = {
    0: [
        Fraction(12980463, 1024), Fraction(12041869, 1024),
        Fraction(-594517923, 71680), Fraction(112271581, 71680),
        Fraction(123350021, 860160), Fraction(-1803389011, 12902400)
    ],
    2: [
        Fraction(-19344659, 76800), Fraction(-38450509, 115200),
        Fraction(490918171, 3225600), Fraction(-31781287, 1209600),
        Fraction(254480207, 12902400)
    ],
    4: [
        Fraction(25883, 12288), Fraction(682871, 184320),
        Fraction(-1505893, 2580480), Fraction(-25483559, 7741440)
    ],
    6: [
        Fraction(-2267, 614400), Fraction(-100657, 5529600)
    ],
}

B_odd = {
    1: [
        Fraction(-584531, 35840), Fraction(-32224291, 21504),
        Fraction(74131151, 215040), Fraction(29406229, 129024),
        Fraction(-1338089411, 7741440),
        Fraction(495451247, 7741440)
    ],
    3: [
        Fraction(-59257, 230400), Fraction(7521137, 230400),
        Fraction(12697441, 3225600), Fraction(4595257, 1382400),
        Fraction(-140504813, 12902400)
    ],
    5: [
        Fraction(4457, 2764800), Fraction(-340837, 2764800),
        Fraction(-5342627, 12902400)
    ],
    7: [
        Fraction(-421, 38707200)
    ],
}


CHANNELS = {
    "A-even": A_even,
    "A-odd": A_odd,
    "B-even": B_even,
    "B-odd": B_odd,
}


# ----------------------------------------------------------------------------
# EXACT LINEAR ALGEBRA
# ----------------------------------------------------------------------------

def matrix_rank(M):
    if not M:
        return 0

    A = [[Fraction(x) for x in row] for row in M]
    n = len(A)
    m = max(len(row) for row in A)

    for row in A:
        row.extend([Fraction(0)] * (m - len(row)))

    rank = 0

    for col in range(m):

        pivot = None

        for i in range(rank, n):
            if A[i][col] != 0:
                pivot = i
                break

        if pivot is None:
            continue

        A[rank], A[pivot] = A[pivot], A[rank]

        pv = A[rank][col]

        for j in range(col, m):
            A[rank][j] /= pv

        for i in range(n):
            if i == rank:
                continue

            f = A[i][col]

            if f == 0:
                continue

            for j in range(col, m):
                A[i][j] -= f * A[rank][j]

        rank += 1

        if rank == n:
            break

    return rank


def nullspace_one(M):
    """
    Return one exact nullspace vector, or None.

    The routine is deliberately explicit so there is no dependence
    on symbolic polynomial domains.
    """
    if not M:
        return None

    A = [[Fraction(x) for x in row] for row in M]

    rows = len(A)
    cols = max(len(row) for row in A)

    for row in A:
        row.extend([Fraction(0)] * (cols - len(row)))

    pivot_cols = []
    pivot_row = 0

    for col in range(cols):

        pivot = None

        for r in range(pivot_row, rows):
            if A[r][col] != 0:
                pivot = r
                break

        if pivot is None:
            continue

        A[pivot_row], A[pivot] = A[pivot], A[pivot_row]

        pv = A[pivot_row][col]

        A[pivot_row] = [
            x / pv for x in A[pivot_row]
        ]

        for r in range(rows):
            if r == pivot_row:
                continue

            f = A[r][col]

            if f == 0:
                continue

            A[r] = [
                A[r][j] - f * A[pivot_row][j]
                for j in range(cols)
            ]

        pivot_cols.append(col)
        pivot_row += 1

        if pivot_row == rows:
            break

    free_cols = [
        c for c in range(cols)
        if c not in pivot_cols
    ]

    if not free_cols:
        return None

    free = free_cols[0]

    v = [Fraction(0)] * cols
    v[free] = Fraction(1)

    for i in range(len(pivot_cols) - 1, -1, -1):
        pc = pivot_cols[i]

        value = Fraction(0)

        for c in free_cols:
            value += A[i][c] * v[c]

        for c in pivot_cols:
            if c == pc:
                continue

            value += A[i][c] * v[c]

        v[pc] = -value

    return v


# ----------------------------------------------------------------------------
# POLYNOMIAL BASIS IN r
# ----------------------------------------------------------------------------

def polynomial_basis_values(r, degree):
    """
    Monomial basis:
        1, r, r^2, ..., r^degree
    """
    return [
        Fraction(r ** d)
        for d in range(degree + 1)
    ]


def build_operator_matrix(
    prev_row,
    next_row,
    order,
    degree,
):
    """
    Search

        next_row[r]
          = sum_a f_a(r) prev_row[r+a]

    where each f_a(r) has degree <= degree.

    Unknowns are coefficients of all f_a.
    """
    equations = []

    max_r = len(next_row)

    for r in range(max_r):

        row = [Fraction(0)] * (
            order * (degree + 1)
        )

        for a in range(order):

            source_index = r + a

            if source_index >= len(prev_row):
                continue

            source = prev_row[source_index]

            basis = polynomial_basis_values(
                r,
                degree,
            )

            base = a * (degree + 1)

            for d, value in enumerate(basis):
                row[base + d] = (
                    source * value
                )

        # constant target term
        equations.append(
            [*row, -next_row[r]]
        )

    return equations


def solve_operator(
    prev_row,
    next_row,
    order,
    degree,
):
    """
    Solve the exact operator system.

    Unknown vector represents f_a(r).

    We fix no arbitrary normalization; the target value
    is appended as the final constant.
    """
    M = build_operator_matrix(
        prev_row,
        next_row,
        order,
        degree,
    )

    unknowns = order * (degree + 1)

    A = [
        row[:unknowns]
        for row in M
    ]

    b = [
        -row[-1]
        for row in M
    ]

    augmented = [
        A[i] + [b[i]]
        for i in range(len(A))
    ]

    rank_A = matrix_rank(A)
    rank_aug = matrix_rank(augmented)

    if rank_A != rank_aug:
        return {
            "consistent": False,
            "rank": rank_A,
            "unknowns": unknowns,
            "nullity": 0,
            "solution": None,
        }

    # Build one solution by elimination.
    E = [
        row[:] for row in augmented
    ]

    nrows = len(E)
    ncols = unknowns

    pivot_cols = []
    pr = 0

    for col in range(ncols):

        pivot = None

        for r in range(pr, nrows):
            if E[r][col] != 0:
                pivot = r
                break

        if pivot is None:
            continue

        E[pr], E[pivot] = E[pivot], E[pr]

        pv = E[pr][col]

        E[pr] = [
            x / pv for x in E[pr]
        ]

        for r in range(nrows):
            if r == pr:
                continue

            f = E[r][col]

            if f == 0:
                continue

            E[r] = [
                E[r][j] - f * E[pr][j]
                for j in range(ncols + 1)
            ]

        pivot_cols.append(col)
        pr += 1

    free_cols = [
        c for c in range(ncols)
        if c not in pivot_cols
    ]

    solution = [Fraction(0)] * ncols

    # Canonical solution: all free variables zero.
    for i, col in enumerate(pivot_cols):
        solution[col] = E[i][-1]

    return {
        "consistent": True,
        "rank": rank_A,
        "unknowns": unknowns,
        "nullity": unknowns - rank_A,
        "solution": solution,
    }


# ----------------------------------------------------------------------------
# OPERATOR EVALUATION
# ----------------------------------------------------------------------------

def eval_operator(
    prev_row,
    solution,
    order,
    degree,
    r,
):
    result = Fraction(0)

    for a in range(order):

        idx = r + a

        if idx >= len(prev_row):
            continue

        source = prev_row[idx]

        base = a * (degree + 1)

        f = Fraction(0)

        for d in range(degree + 1):
            f += (
                solution[base + d]
                * (r ** d)
            )

        result += f * source

    return result


def verify_operator(
    prev_row,
    next_row,
    solution,
    order,
    degree,
):
    checks = []

    for r in range(len(next_row)):
        predicted = eval_operator(
            prev_row,
            solution,
            order,
            degree,
            r,
        )

        checks.append(
            predicted == next_row[r]
        )

    return all(checks)


# ----------------------------------------------------------------------------
# MULTIPLICATIVE SPECIAL CASE
# ----------------------------------------------------------------------------

def multiplicative_search(prev_row, next_row, degree):
    """
    Search

        next[r] = f(r) prev[r]

    where f has degree <= degree.
    """
    points = []

    for r in range(
        min(len(prev_row), len(next_row))
    ):
        if prev_row[r] == 0:
            if next_row[r] != 0:
                return None
            continue

        points.append(
            (
                r,
                next_row[r] / prev_row[r],
            )
        )

    if not points:
        return None

    if len(points) <= degree:
        return None

    # Solve Vandermonde system.
    M = []
    for r, value in points:
        M.append(
            [Fraction(r ** d) for d in range(degree + 1)]
            + [-value]
        )

    rank_A = matrix_rank(
        [row[:-1] for row in M]
    )
    rank_aug = matrix_rank(M)

    if rank_A != rank_aug:
        return None

    # Use first degree+1 independent points and verify globally.
    selected = points[:degree + 1]

    A = [
        [Fraction(r ** d) for d in range(degree + 1)]
        for r, _ in selected
    ]

    b = [value for _, value in selected]

    aug = [
        A[i] + [b[i]]
        for i in range(len(A))
    ]

    # Gaussian elimination
    n = degree + 1

    for col in range(n):
        pivot = None

        for row in range(col, n):
            if aug[row][col] != 0:
                pivot = row
                break

        if pivot is None:
            return None

        aug[col], aug[pivot] = aug[pivot], aug[col]

        pv = aug[col][col]

        aug[col] = [
            x / pv for x in aug[col]
        ]

        for row in range(n):
            if row == col:
                continue

            f = aug[row][col]

            if f:
                aug[row] = [
                    aug[row][j] - f * aug[col][j]
                    for j in range(n + 1)
                ]

    coeffs = [
        aug[i][-1]
        for i in range(n)
    ]

    for r, value in points:

        predicted = sum(
            coeffs[d] * (r ** d)
            for d in range(degree + 1)
        )

        if predicted != value:
            return None

    return coeffs


# ----------------------------------------------------------------------------
# SHIFT SEARCH
# ----------------------------------------------------------------------------

def shift_proportional(prev_row, next_row):
    """
    Tests direct proportionality after shifts.
    """
    results = []

    for shift in range(-3, 4):

        if shift >= 0:
            shifted = (
                [Fraction(0)] * shift
                + prev_row
            )
        else:
            s = -shift

            if s >= len(prev_row):
                shifted = [Fraction(0)]
            else:
                shifted = prev_row[s:]

        width = max(
            len(shifted),
            len(next_row),
        )

        a = shifted + [Fraction(0)] * (
            width - len(shifted)
        )
        b = next_row + [Fraction(0)] * (
            width - len(next_row)
        )

        scalar = None
        ok = True

        for x, y in zip(b, a):

            if x == 0 and y == 0:
                continue

            if y == 0 or x == 0:
                ok = False
                break

            q = x / y

            if scalar is None:
                scalar = q
            elif q != scalar:
                ok = False
                break

        if ok and scalar is not None:
            results.append(
                (shift, scalar)
            )

    return results


# ----------------------------------------------------------------------------
# MAIN
# ----------------------------------------------------------------------------

def main():

    print("=" * 78)
    print("EXPERIMENT 117 — EXACT RESIDUAL-KERNEL")
    print("INDEX-RECURRENCE AUDIT")
    print("=" * 78)
    print()

    failures = 0

    # ------------------------------------------------------------------------
    # 1. BASIC PROFILE
    # ------------------------------------------------------------------------

    print("=" * 78)
    print("1. ROW DEGREE PROFILE")
    print("=" * 78)

    for name, rows in CHANNELS.items():

        print(name)

        for p, row in rows.items():
            print(
                f"  p={p}: degree={len(row)-1}"
            )

        print()

    # ------------------------------------------------------------------------
    # 2. SPECIAL MULTIPLICATIVE SEARCH
    # ------------------------------------------------------------------------

    print("=" * 78)
    print("2. EXACT MULTIPLICATIVE p->p+2 SEARCH")
    print("=" * 78)

    for name, rows in CHANNELS.items():

        print()
        print(name)

        ps = sorted(rows)

        for p1, p2 in zip(ps, ps[1:]):

            prev = rows[p1]
            nxt = rows[p2]

            # Test degree 0,1,2,3.
            found = None

            for deg in range(4):

                coeffs = multiplicative_search(
                    prev,
                    nxt,
                    deg,
                )

                if coeffs is not None:
                    found = (deg, coeffs)
                    break

            print(
                f"  {p1}->{p2}: "
                f"multiplicative={found}"
            )

    print()

    # ------------------------------------------------------------------------
    # 3. DIRECT SHIFT SEARCH
    # ------------------------------------------------------------------------

    print("=" * 78)
    print("3. EXACT SHIFT / PROPORTIONALITY SEARCH")
    print("=" * 78)

    for name, rows in CHANNELS.items():

        print()
        print(name)

        ps = sorted(rows)

        for p1, p2 in zip(ps, ps[1:]):

            results = shift_proportional(
                rows[p1],
                rows[p2],
            )

            print(
                f"  {p1}->{p2}: {results}"
            )

    print()

    # ------------------------------------------------------------------------
    # 4. FIRST-ORDER r-DEPENDENT OPERATOR
    #
    #     q[p+2,r] =
    #        f0(r) q[p,r]
    #        + f1(r) q[p,r+1]
    #
    # f0,f1 polynomial degree <= d.
    # ------------------------------------------------------------------------

    print("=" * 78)
    print("4. EXACT TWO-TERM r-KERNEL OPERATOR")
    print("=" * 78)

    for name, rows in CHANNELS.items():

        print()
        print(name)

        ps = sorted(rows)

        for p1, p2 in zip(ps, ps[1:]):

            prev = rows[p1]
            nxt = rows[p2]

            results = []

            for degree in range(4):

                sol = solve_operator(
                    prev,
                    nxt,
                    order=2,
                    degree=degree,
                )

                if (
                    sol["consistent"]
                    and sol["nullity"] == 0
                ):

                    exact = verify_operator(
                        prev,
                        nxt,
                        sol["solution"],
                        order=2,
                        degree=degree,
                    )

                    if exact:
                        results.append(
                            (
                                degree,
                                sol["rank"],
                                sol["unknowns"],
                            )
                        )

            print(
                f"  {p1}->{p2}: "
                f"unique_exact_candidates={results}"
            )

    print()

    # ------------------------------------------------------------------------
    # 5. THREE-TERM r-KERNEL OPERATOR
    #
    #     q[p+2,r] =
    #         f0(r) q[p,r]
    #       + f1(r) q[p,r+1]
    #       + f2(r) q[p,r+2]
    #
    # We only accept unique solutions.
    # ------------------------------------------------------------------------

    print("=" * 78)
    print("5. EXACT THREE-TERM r-KERNEL OPERATOR")
    print("=" * 78)

    for name, rows in CHANNELS.items():

        print()
        print(name)

        ps = sorted(rows)

        for p1, p2 in zip(ps, ps[1:]):

            prev = rows[p1]
            nxt = rows[p2]

            results = []

            for degree in range(3):

                sol = solve_operator(
                    prev,
                    nxt,
                    order=3,
                    degree=degree,
                )

                if (
                    sol["consistent"]
                    and sol["nullity"] == 0
                ):

                    exact = verify_operator(
                        prev,
                        nxt,
                        sol["solution"],
                        order=3,
                        degree=degree,
                    )

                    if exact:
                        results.append(
                            (
                                degree,
                                sol["rank"],
                                sol["unknowns"],
                            )
                        )

            print(
                f"  {p1}->{p2}: "
                f"unique_exact_candidates={results}"
            )

    print()

    # ------------------------------------------------------------------------
    # 6. PRINT FIRST EXACT LOW-COMPLEXITY OPERATOR IF FOUND
    # ------------------------------------------------------------------------

    print("=" * 78)
    print("6. LOWEST-COMPLEXITY UNIQUE OPERATORS")
    print("=" * 78)

    found_any = False

    for name, rows in CHANNELS.items():

        ps = sorted(rows)

        for p1, p2 in zip(ps, ps[1:]):

            prev = rows[p1]
            nxt = rows[p2]

            found = None

            for order in (1, 2, 3):

                for degree in range(4):

                    sol = solve_operator(
                        prev,
                        nxt,
                        order=order,
                        degree=degree,
                    )

                    if (
                        sol["consistent"]
                        and sol["nullity"] == 0
                        and verify_operator(
                            prev,
                            nxt,
                            sol["solution"],
                            order,
                            degree,
                        )
                    ):
                        found = (
                            order,
                            degree,
                            sol["solution"],
                        )
                        break

                if found is not None:
                    break

            if found is not None:

                found_any = True

                order, degree, solution = found

                print()
                print(
                    f"{name} transition "
                    f"{p1}->{p2}"
                )
                print(
                    f"  order={order} "
                    f"degree={degree}"
                )

                block = degree + 1

                for a in range(order):

                    coeffs = solution[
                        a * block:
                        (a + 1) * block
                    ]

                    print(
                        f"  f_{a}(r) coefficients="
                        f"{coeffs}"
                    )

    if not found_any:
        print("  NONE")

    print()

    # ------------------------------------------------------------------------
    # 7. UNIVERSAL OPERATOR SEARCH
    #
    # Search for a single operator valid for every transition within
    # a channel, with coefficients depending only on r.
    #
    # This is much stronger than fitting each transition independently.
    # ------------------------------------------------------------------------

    print("=" * 78)
    print("7. UNIVERSAL r-KERNEL OPERATOR SEARCH")
    print("=" * 78)

    universal_results = {}

    for name, rows in CHANNELS.items():

        print()
        print(name)

        ps = sorted(rows)

        for order in (1, 2, 3):

            for degree in range(3):

                matrices = []

                for p1, p2 in zip(ps, ps[1:]):

                    local = build_operator_matrix(
                        rows[p1],
                        rows[p2],
                        order,
                        degree,
                    )

                    matrices.extend(local)

                unknowns = order * (degree + 1)

                A = [
                    row[:unknowns]
                    for row in matrices
                ]

                aug = [
                    row
                    for row in matrices
                ]

                rank_A = matrix_rank(A)
                rank_aug = matrix_rank(aug)

                consistent = (
                    rank_A == rank_aug
                )

                nullity = (
                    unknowns - rank_A
                )

                result = (
                    consistent,
                    nullity,
                    rank_A,
                    unknowns,
                )

                universal_results[
                    (name, order, degree)
                ] = result

                print(
                    f"  order={order} "
                    f"degree={degree}: "
                    f"consistent={consistent} "
                    f"rank={rank_A} "
                    f"unknowns={unknowns} "
                    f"nullity={nullity}"
                )

    print()

    # ------------------------------------------------------------------------
    # 8. UNIVERSAL OPERATOR WITH AFFINE p-DEPENDENCE
    #
    # Allow each coefficient polynomial to depend on p linearly:
    #
    #     f_a(p,r) = A_a(r) + p B_a(r)
    #
    # This is a controlled next level, not unrestricted interpolation.
    # ------------------------------------------------------------------------

    print("=" * 78)
    print("8. UNIVERSAL p/r OPERATOR SEARCH")
    print("=" * 78)

    for name, rows in CHANNELS.items():

        print()
        print(name)

        ps = sorted(rows)

        for order in (1, 2):

            for degree_r in range(2):

                unknowns = (
                    order
                    * 2
                    * (degree_r + 1)
                )

                equations = []

                for p1, p2 in zip(ps, ps[1:]):

                    prev = rows[p1]
                    nxt = rows[p2]

                    for r in range(len(nxt)):

                        row = [
                            Fraction(0)
                        ] * unknowns

                        for a in range(order):

                            idx = r + a

                            if idx >= len(prev):
                                continue

                            source = prev[idx]

                            base = (
                                a
                                * 2
                                * (degree_r + 1)
                            )

                            for d in range(
                                degree_r + 1
                            ):

                                mon = (
                                    source
                                    * (r ** d)
                                )

                                row[
                                    base + d
                                ] += mon

                                row[
                                    base
                                    + degree_r
                                    + 1
                                    + d
                                ] += (
                                    p1 * mon
                                )

                        equations.append(
                            row + [-nxt[r]]
                        )

                rank_A = matrix_rank(
                    [
                        row[:-1]
                        for row in equations
                    ]
                )

                rank_aug = matrix_rank(
                    equations
                )

                consistent = (
                    rank_A == rank_aug
                )

                nullity = (
                    unknowns - rank_A
                )

                print(
                    f"  order={order} "
                    f"degree_r={degree_r}: "
                    f"consistent={consistent} "
                    f"rank={rank_A} "
                    f"unknowns={unknowns} "
                    f"nullity={nullity}"
                )

    print()

    # ------------------------------------------------------------------------
    # 9. RECONSTRUCTION SANITY
    # ------------------------------------------------------------------------

    print("=" * 78)
    print("9. EXACT DATA RECONSTRUCTION SANITY")
    print("=" * 78)

    reconstruction_ok = True

    for name, rows in CHANNELS.items():

        print(name)

        for p, row in rows.items():

            D = len(row) - 1

            # Evaluate falling basis.
            values = []

            for k in range(D + 1):

                total = Fraction(0)

                for r, coeff in enumerate(row):

                    if r <= k:

                        total += (
                            coeff
                            * Fraction(
                                factorial(k),
                                factorial(k-r),
                            )
                        )

                values.append(total)

            # Recover.
            recovered = [Fraction(0)] * (
                D + 1
            )

            for n in range(D + 1):

                residual = values[n]

                for r in range(n):

                    residual -= (
                        recovered[r]
                        * Fraction(
                            factorial(n),
                            factorial(n-r),
                        )
                    )

                recovered[n] = (
                    residual
                    / factorial(n)
                )

            exact = (
                recovered == row
            )

            if not exact:
                reconstruction_ok = False

            print(
                f"  p={p}: exact={exact}"
            )

        print()

    # ------------------------------------------------------------------------
    # 10. INTERPRETATION
    # ------------------------------------------------------------------------

    print("=" * 78)
    print("10. STRUCTURAL INTERPRETATION")
    print("=" * 78)
    print()
    print("Experiment 116 ruled out obvious rank collapse after several")
    print("natural coefficient normalizations.")
    print()
    print("The degree-3 A/B nullspaces in Experiment 116 were not treated")
    print("as discoveries because the systems were underdetermined.")
    print()
    print("Experiment 117 therefore asks a different question:")
    print()
    print("    Does the residual row q[p,r] propagate in p by a fixed")
    print("    finite-band operator in the falling index r?")
    print()
    print("A positive result would give an actual construction mechanism:")
    print()
    print("    q[p+2,r] = sum_a f_a(r) q[p,r+a].")
    print()
    print("The universal operator test is substantially stronger than")
    print("fitting each transition independently.")
    print()
    print("The p/r operator test then checks whether a small indexed")
    print("correction is enough when a purely r-dependent operator fails.")
    print()
    print("Only unique exact solutions are highlighted as structural.")
    print("Underdetermined systems are reported but not promoted.")
    print()
    print("Everything is exact over QQ.")
    print("No floating point.")
    print("No SymPy.")
    print("No extrapolation.")
    print()

    print("=" * 78)
    print("11. FINAL EXACTNESS")
    print("=" * 78)

    print(
        f"  reconstruction = {reconstruction_ok}"
    )
    print(
        f"  recurrence_audit_completed = True"
    )
    print(
        f"  failures = {0 if reconstruction_ok else 1}"
    )
    print(
        f"  ALL BASIC CHECKS PASS = {reconstruction_ok}"
    )

    print()
    print("EXPERIMENT 117 COMPLETE")


if __name__ == "__main__":
    main()

