import sympy as sp
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple


# =============================================================================
# EXPERIMENT 73
# EXACT A/B CHANNEL RECURRENCE DISCOVERY
#
# Goal:
#
#   We know that
#
#       L_d(N,X) = X^d h_d(N/X)
#
#   and
#
#       h_d(t) = A_d(u) + (2t+1) B_d(u),
#       u = t(t+1).
#
# The present experiment asks:
#
#   Are the A_d and B_d sequences generated by short exact recurrences
#   with low-degree polynomial coefficients in u?
#
# No floating point.
# No regression.
# No numerical fitting.
# No interpolation.
# All identities are checked exactly.
# =============================================================================


# =============================================================================
# SYMBOLS
# =============================================================================

t = sp.Symbol("t")
u = sp.Symbol("u")


# =============================================================================
# NORMALIZED LAYER POLYNOMIALS
# =============================================================================

H_RAW = {
    16: -(3*t**2 + 3*t + 1) * (
        3*t**6 + 9*t**5 + 18*t**4 + 21*t**3 +
        15*t**2 + 6*t + 1
    ),

    15: (2*t + 1) * (
        44*t**8 + 176*t**7 + 494*t**6 + 866*t**5 +
        1016*t**4 + 794*t**3 + 401*t**2 + 119*t + 16
    ),

    14: -(
        276*t**10 + 1380*t**9 + 5460*t**8 + 13560*t**7 +
        23058*t**6 + 27510*t**5 + 23100*t**4 +
        13410*t**3 + 5135*t**2 + 1169*t + 120
    ),

    13: (2*t + 1) * (
        144*t**10 + 720*t**9 + 4810*t**8 + 14920*t**7 +
        32272*t**6 + 47620*t**5 + 48955*t**4 +
        34510*t**3 + 16020*t**2 + 4431*t + 560
    ),

    12: -(
        50*t**12 + 300*t**11 + 7436*t**10 + 34430*t**9 +
        117810*t**8 + 267960*t**7 + 426888*t**6 +
        484110*t**5 + 390225*t**4 + 219010*t**3 +
        81510*t**2 + 18109*t + 1820
    ),

    11: 13 * (2*t + 1) * (
        50*t**10 + 250*t**9 + 2284*t**8 + 7636*t**7 +
        17434*t**6 + 26626*t**5 + 28036*t**4 +
        20104*t**3 + 9451*t**2 + 2639*t + 336
    ),

    10: -1001 * (
        10*t**10 + 50*t**9 + 252*t**8 + 708*t**7 +
        1302*t**6 + 1638*t**5 + 1428*t**4 +
        852*t**3 + 333*t**2 + 77*t + 8
    ),

    9: (2*t + 1) * (
        17875*t**8 + 71500*t**7 + 245960*t**6 +
        487630*t**5 + 622414*t**4 + 515528*t**3 +
        271506*t**2 + 83097*t + 11441
    ),

    8: -(
        71500*t**8 + 286000*t**7 + 755664*t**6 +
        1265992*t**5 + 1375360*t**4 + 974400*t**3 +
        436832*t**2 + 112964*t + 12879
    ),

    7: 4 * (2*t + 1) * (
        11050*t**6 + 33150*t**5 + 63036*t**4 +
        70822*t**3 + 47549*t**2 + 17663*t + 2869
    ),

    6: -4 * (
        17850*t**6 + 53550*t**5 + 86088*t**4 +
        82926*t**3 + 47574*t**2 + 15036*t + 2023
    ),

    5: 6 * (2*t + 1) * (
        3230*t**4 + 6460*t**3 + 6688*t**2 +
        3458*t + 749
    ),

    4: -2 * (
        7125*t**4 + 14250*t**3 + 12690*t**2 +
        5565*t + 973
    ),

    3: 14 * (2*t + 1) * (
        125*t**2 + 125*t + 46
    ),

    2: -2 * (
        275*t**2 + 275*t + 78
    ),

    1: 25 * (2*t + 1),

    0: -2,
}


# Convert ALL entries, including constants such as -2, into SymPy Expr.
H: Dict[int, sp.Expr] = {
    d: sp.sympify(expr)
    for d, expr in H_RAW.items()
}


# =============================================================================
# BASIC EXACT HELPERS
# =============================================================================

def exact_zero(expr: sp.Expr) -> bool:
    return sp.expand(sp.sympify(expr)) == 0


def poly_t(expr: sp.Expr) -> sp.Poly:
    return sp.Poly(
        sp.expand(sp.sympify(expr)),
        t,
        domain=sp.QQ,
    )


def poly_u(expr: sp.Expr) -> sp.Poly:
    return sp.Poly(
        sp.expand(sp.sympify(expr)),
        u,
        domain=sp.QQ,
    )


def degree_u(expr: sp.Expr):
    p = poly_u(expr)

    if p.is_zero:
        return -sp.oo

    return p.degree()


def primitive_integer_signature(
    expr: sp.Expr,
    variable: sp.Symbol,
) -> Tuple[int, List[int]]:

    p = sp.Poly(
        sp.expand(sp.sympify(expr)),
        variable,
        domain=sp.QQ,
    )

    if p.is_zero:
        return 0, [0]

    coeffs = p.all_coeffs()

    den_lcm = 1

    for c in coeffs:
        den_lcm = int(
            sp.ilcm(
                den_lcm,
                int(sp.denom(c)),
            )
        )

    integers = [
        int(c * den_lcm)
        for c in coeffs
    ]

    g = 0

    for z in integers:
        g = sp.igcd(g, abs(z))

    if g == 0:
        return 0, [0]

    integers = [
        z // g
        for z in integers
    ]

    if integers[0] < 0:
        integers = [
            -z
            for z in integers
        ]

    return int(g), integers


# =============================================================================
# EXACT INVOLUTION DECOMPOSITION
# =============================================================================

def decompose_involution(
    h_expr: sp.Expr,
) -> Tuple[sp.Expr, sp.Expr]:

    h = sp.expand(
        sp.sympify(h_expr)
    )

    partner = sp.expand(
        h.subs(
            t,
            -1 - t,
        )
    )

    even_part = sp.expand(
        (h + partner) / 2
    )

    odd_part = sp.expand(
        (h - partner) / 2
    )

    y = sp.Symbol("y")

    # -------------------------------------------------------------------------
    # A channel
    # -------------------------------------------------------------------------

    even_y = sp.expand(
        even_part.subs(
            t,
            (y - 1) / 2,
        )
    )

    even_poly = sp.Poly(
        even_y,
        y,
        domain=sp.QQ,
    )

    A_expr = sp.Integer(0)

    for (power,), coeff in even_poly.terms():

        if power % 2 != 0:
            raise RuntimeError(
                f"Odd y-power {power} appeared in invariant channel."
            )

        A_expr += (
            coeff *
            (4*u + 1)**(power // 2)
        )

    A_expr = sp.expand(A_expr)

    # -------------------------------------------------------------------------
    # B channel
    # -------------------------------------------------------------------------

    divisor = 2*t + 1

    quotient, remainder = sp.div(
        sp.Poly(
            odd_part,
            t,
            domain=sp.QQ,
        ),
        sp.Poly(
            divisor,
            t,
            domain=sp.QQ,
        ),
        domain=sp.QQ,
    )

    if not remainder.is_zero:
        raise RuntimeError(
            "Anti-invariant part is not divisible by 2t+1."
        )

    B_t = sp.expand(
        quotient.as_expr()
    )

    B_y = sp.expand(
        B_t.subs(
            t,
            (y - 1) / 2,
        )
    )

    B_poly = sp.Poly(
        B_y,
        y,
        domain=sp.QQ,
    )

    B_expr = sp.Integer(0)

    for (power,), coeff in B_poly.terms():

        if power % 2 != 0:
            raise RuntimeError(
                f"Odd y-power {power} appeared in B channel."
            )

        B_expr += (
            coeff *
            (4*u + 1)**(power // 2)
        )

    B_expr = sp.expand(B_expr)

    # -------------------------------------------------------------------------
    # Full exact reconstruction
    # -------------------------------------------------------------------------

    reconstruction = sp.expand(
        A_expr.subs(
            u,
            t*(t + 1),
        )
        +
        (2*t + 1) *
        B_expr.subs(
            u,
            t*(t + 1),
        )
    )

    if reconstruction != h:
        raise RuntimeError(
            "Involution reconstruction failed."
        )

    return A_expr, B_expr


# =============================================================================
# BUILD A/B CHANNELS
# =============================================================================

A: Dict[int, sp.Expr] = {}
B: Dict[int, sp.Expr] = {}

for d in range(17):

    A[d], B[d] = decompose_involution(
        H[d]
    )


# =============================================================================
# RECURRENCE ENGINE
# =============================================================================

@dataclass
class RecurrenceResult:
    order: int
    coefficient_degree: int
    valid: bool
    coefficients: Optional[List[sp.Expr]]
    tested_positions: List[int]
    rank: int
    unknown_count: int
    message: str


def create_recurrence_unknowns(
    order: int,
    coefficient_degree: int,
):
    """
    Construct symbolic polynomials

        c_0(u),...,c_order(u)

    where every coefficient is an independent symbol.
    """

    symbols: List[sp.Symbol] = []
    coefficient_polynomials: List[sp.Expr] = []

    for j in range(order + 1):

        c = sp.Integer(0)

        for k in range(coefficient_degree + 1):

            symbol = sp.Symbol(
                f"c_{j}_{k}"
            )

            symbols.append(
                symbol
            )

            c += (
                symbol *
                u**k
            )

        coefficient_polynomials.append(
            sp.expand(c)
        )

    return (
        symbols,
        coefficient_polynomials,
    )


def extract_linear_u_system(
    recurrence_expr: sp.Expr,
    unknowns: List[sp.Symbol],
) -> List[List[sp.Expr]]:
    """
    Convert

        recurrence_expr(u, c_ij) = 0

    into a matrix of exact linear equations in the c_ij.

    IMPORTANT:
    We do NOT call Poly(..., domain=QQ) while the unknown c_ij
    are still present.
    """

    expr = sp.expand(
        sp.sympify(recurrence_expr)
    )

    # Determine u-degree without trying to force coefficients
    # into QQ.
    polynomial = sp.Poly(
        expr,
        u,
        domain=sp.EX,
    )

    rows: List[List[sp.Expr]] = []

    for (u_power,), coeff_expr in polynomial.terms():

        coefficient = sp.expand(
            coeff_expr
        )

        row = []

        for symbol in unknowns:

            value = sp.expand(
                coefficient.coeff(
                    symbol
                )
            )

            # Reject accidental nonlinear dependence.
            remainder = sp.expand(
                coefficient -
                sum(
                    other *
                    sp.expand(
                        coefficient.coeff(
                            other
                        )
                    )
                    for other in unknowns
                )
            )

            # We do not need the remainder here to be zero globally
            # because the coefficient itself is expected to be linear
            # in the unknown symbols. Check explicitly below.
            if any(
                monomial.as_powers_dict().get(symbol, 0) > 1
                for monomial in sp.Add.make_args(
                    sp.expand(coefficient)
                )
                for symbol in unknowns
            ):
                raise RuntimeError(
                    "Nonlinear symbolic dependence detected "
                    "in recurrence coefficient system."
                )

            row.append(
                value
            )

        rows.append(
            row
        )

    return rows


def recurrence_candidate_valid(
    sequence: List[sp.Expr],
    candidate: List[sp.Expr],
    order: int,
) -> bool:

    for r in range(
        order,
        len(sequence),
    ):

        check = sp.Integer(0)

        for j in range(order + 1):

            check += (
                candidate[j] *
                sequence[r - j]
            )

        if not exact_zero(check):
            return False

    return True


def normalize_recurrence(
    coefficients: List[sp.Expr],
) -> List[sp.Expr]:

    nonzero = [
        c
        for c in coefficients
        if not exact_zero(c)
    ]

    if not nonzero:
        return coefficients

    den_lcm = 1

    for c in coefficients:

        p = poly_u(c)

        for q in p.all_coeffs():

            den_lcm = int(
                sp.ilcm(
                    den_lcm,
                    int(sp.denom(q)),
                )
            )

    scaled = [
        sp.expand(
            c * den_lcm
        )
        for c in coefficients
    ]

    integer_coefficients = []

    for c in scaled:

        p = poly_u(c)

        for q in p.all_coeffs():
            integer_coefficients.append(
                int(q)
            )

    g = 0

    for z in integer_coefficients:
        g = sp.igcd(
            g,
            abs(z),
        )

    if g:
        scaled = [
            sp.expand(
                c / g
            )
            for c in scaled
        ]

    # Make first nonzero leading coefficient positive.
    for c in scaled:

        if not exact_zero(c):

            lead = poly_u(c).LC()

            if lead < 0:
                scaled = [
                    sp.expand(-x)
                    for x in scaled
                ]

            break

    return scaled


def search_exact_recurrence(
    sequence: List[sp.Expr],
    order: int,
    coefficient_degree: int,
) -> RecurrenceResult:

    positions = list(
        range(
            order,
            len(sequence),
        )
    )

    if not positions:

        return RecurrenceResult(
            order=order,
            coefficient_degree=coefficient_degree,
            valid=False,
            coefficients=None,
            tested_positions=[],
            rank=0,
            unknown_count=(order + 1) *
            (coefficient_degree + 1),
            message="not enough sequence terms",
        )

    (
        unknowns,
        coefficient_polynomials,
    ) = create_recurrence_unknowns(
        order,
        coefficient_degree,
    )

    all_rows: List[List[sp.Expr]] = []

    for r in positions:

        recurrence = sp.Integer(0)

        for j in range(
            order + 1
        ):

            recurrence += (
                coefficient_polynomials[j] *
                sequence[r - j]
            )

        recurrence = sp.expand(
            recurrence
        )

        rows = extract_linear_u_system(
            recurrence,
            unknowns,
        )

        all_rows.extend(
            rows
        )

    if not all_rows:

        return RecurrenceResult(
            order,
            coefficient_degree,
            False,
            None,
            positions,
            0,
            len(unknowns),
            "no equations",
        )

    M = sp.Matrix(
        all_rows
    )

    rank = M.rank()
    nullspace = M.nullspace()

    if not nullspace:

        return RecurrenceResult(
            order,
            coefficient_degree,
            False,
            None,
            positions,
            rank,
            len(unknowns),
            "no exact recurrence",
        )

    for vector in nullspace:

        candidate: List[sp.Expr] = []

        index = 0

        for j in range(
            order + 1
        ):

            c = sp.Integer(0)

            for k in range(
                coefficient_degree + 1
            ):

                c += (
                    vector[index] *
                    u**k
                )

                index += 1

            candidate.append(
                sp.expand(c)
            )

        candidate = normalize_recurrence(
            candidate
        )

        if recurrence_candidate_valid(
            sequence,
            candidate,
            order,
        ):

            return RecurrenceResult(
                order,
                coefficient_degree,
                True,
                candidate,
                positions,
                rank,
                len(unknowns),
                "exact recurrence found",
            )

    return RecurrenceResult(
        order,
        coefficient_degree,
        False,
        None,
        positions,
        rank,
        len(unknowns),
        "nullspace existed but no candidate validated",
    )


# =============================================================================
# RECURRENCE SWEEP
# =============================================================================

def recurrence_sweep(
    name: str,
    sequence: List[sp.Expr],
):

    print()
    print("-" * 78)
    print(
        f"{name} EXACT RECURRENCE SEARCH"
    )
    print("-" * 78)

    found_any = False

    # Search from simplest to more complicated.
    for order in (1, 2, 3):

        for coefficient_degree in (
            0,
            1,
            2,
            3,
        ):

            result = search_exact_recurrence(
                sequence,
                order,
                coefficient_degree,
            )

            status = (
                "FOUND"
                if result.valid
                else "NONE"
            )

            print(
                f"  order={order}, "
                f"degree={coefficient_degree}: "
                f"{status} "
                f"(rank={result.rank}, "
                f"unknowns={result.unknown_count})"
            )

            if result.valid:

                found_any = True

                print(
                    "    recurrence:"
                )

                for j, coeff in enumerate(
                    result.coefficients
                ):

                    print(
                        f"      c_{j}(u) = "
                        f"{sp.factor(coeff)}"
                    )

                print(
                    "    verified positions = "
                    f"{result.tested_positions}"
                )

                # Continue searching.
                # We want the complete structural picture.
    
    if not found_any:

        print(
            "  No exact recurrence found "
            "within the scanned complexity."
        )


# =============================================================================
# QUOTIENT / REMAINDER AUDIT
# =============================================================================

def quotient_remainder_audit(
    name: str,
    degrees: List[int],
    channel: Dict[int, sp.Expr],
):

    print()
    print("-" * 78)
    print(
        f"{name} QUOTIENT / REMAINDER AUDIT"
    )
    print("-" * 78)

    for d_hi, d_lo in zip(
        degrees[:-1],
        degrees[1:],
    ):

        hi = poly_u(
            channel[d_hi]
        )

        lo = poly_u(
            channel[d_lo]
        )

        if lo.is_zero:

            print(
                f"  {name}_{d_hi}/{name}_{d_lo}: "
                f"denominator is zero"
            )

            continue

        q, r = sp.div(
            hi,
            lo,
            domain=sp.QQ,
        )

        q_degree = (
            -sp.oo
            if q.is_zero
            else q.degree()
        )

        r_degree = (
            -sp.oo
            if r.is_zero
            else r.degree()
        )

        print(
            f"  {name}_{d_hi}/{name}_{d_lo}: "
            f"quotient_degree={q_degree} "
            f"remainder_degree={r_degree}"
        )

        print(
            f"    quotient={sp.factor(q.as_expr())}"
        )

        print(
            f"    remainder={sp.factor(r.as_expr())}"
        )


# =============================================================================
# FINITE DIFFERENCE AUDIT
# =============================================================================

def finite_difference(
    sequence: List[sp.Expr],
) -> List[sp.Expr]:

    return [
        sp.expand(
            sequence[i + 1] -
            sequence[i]
        )
        for i in range(
            len(sequence) - 1
        )
    ]


def finite_difference_orders(
    name: str,
    sequence: List[sp.Expr],
):

    print()
    print("-" * 78)
    print(
        f"{name} FINITE-DIFFERENCE AUDIT"
    )
    print("-" * 78)

    current = list(
        sequence
    )

    for order in range(1, 5):

        current = finite_difference(
            current
        )

        degrees = [
            degree_u(x)
            for x in current
        ]

        print(
            f"  order={order}: "
            f"degrees={degrees}"
        )


# =============================================================================
# CHANNEL PROFILE
# =============================================================================

def channel_profile(
    name: str,
    channel: Dict[int, sp.Expr],
    degrees: List[int],
):

    print()
    print("-" * 78)
    print(
        f"{name} CHANNEL PROFILE"
    )
    print("-" * 78)

    for d in degrees:

        expr = channel[d]

        poly = poly_u(
            expr
        )

        degree = (
            -sp.oo
            if poly.is_zero
            else poly.degree()
        )

        content, primitive = (
            primitive_integer_signature(
                expr,
                u,
            )
        )

        print(
            f"  {name}_{d}: "
            f"degree={degree} "
            f"terms={len(poly.terms())} "
            f"content={content}"
        )

        print(
            f"    primitive={primitive}"
        )


# =============================================================================
# CROSS-CHANNEL GCD AUDIT
# =============================================================================

def cross_channel_gcd_audit():

    print()
    print("-" * 78)
    print(
        "CROSS-CHANNEL GCD AUDIT"
    )
    print("-" * 78)

    for d in range(16):

        a = poly_u(
            A[d]
        )

        b = poly_u(
            B[d + 1]
        )

        if a.is_zero or b.is_zero:

            print(
                f"  A_{d}, B_{d+1}: "
                f"one channel is zero"
            )

            continue

        g = sp.gcd(
            a,
            b,
        )

        degree = (
            -sp.oo
            if g.is_zero
            else g.degree()
        )

        print(
            f"  A_{d}, B_{d+1}: "
            f"gcd_degree={degree} "
            f"gcd={sp.factor(g.as_expr())}"
        )


# =============================================================================
# FRESH EXACT VALIDATION
# =============================================================================

def fresh_exact_check():

    print()
    print("=" * 78)
    print(
        "FRESH EXACT SEMIPRIME VALIDATION"
    )
    print("=" * 78)

    p = sp.Integer(106621)
    q = sp.Integer(246473)

    N = p*q
    S = p + q
    X = S + 1

    t_value = sp.cancel(
        N / X
    )

    u_value = sp.cancel(
        t_value *
        (t_value + 1)
    )

    print(
        f"  p = {p}"
    )
    print(
        f"  q = {q}"
    )
    print(
        f"  N = {N}"
    )
    print(
        f"  S = {S}"
    )
    print(
        f"  X = {X}"
    )
    print(
        f"  t = {t_value}"
    )
    print(
        f"  u = {u_value}"
    )

    all_ok = True

    for d in range(
        16,
        -1,
        -1,
    ):

        h_true = sp.expand(
            H[d].subs(
                t,
                t_value,
            )
        )

        a_value = sp.expand(
            A[d].subs(
                u,
                u_value,
            )
        )

        b_value = sp.expand(
            B[d].subs(
                u,
                u_value,
            )
        )

        h_reconstructed = sp.expand(
            a_value +
            (2*t_value + 1) *
            b_value
        )

        ok = (
            h_true ==
            h_reconstructed
        )

        if not ok:
            all_ok = False

        print(
            f"  d={d:2d}: "
            f"reconstruction={ok}"
        )

    print()
    print(
        f"  ALL FRESH CHECKS PASS = "
        f"{all_ok}"
    )

    return all_ok


# =============================================================================
# MAIN
# =============================================================================

def main():

    print("=" * 78)
    print(
        "EXPERIMENT 73 — EXACT A/B CHANNEL "
        "RECURRENCE DISCOVERY"
    )
    print("=" * 78)

    print()
    print("0. EXACT SYMBOLIC SETUP")
    print("  t = N/X")
    print("  u = t(t+1)")
    print("  involution = t -> -1-t")
    print("  arithmetic = exact QQ")
    print("  floating point = forbidden")

    # -------------------------------------------------------------------------
    # 1. INVOLUTION CHECK
    # -------------------------------------------------------------------------

    print()
    print("=" * 78)
    print("1. INVOLUTION CHECK")
    print("=" * 78)

    decomposition_ok = True

    for d in range(
        16,
        -1,
        -1,
    ):

        h = H[d]

        partner = sp.expand(
            h.subs(
                t,
                -1 - t,
            )
        )

        inv = exact_zero(
            partner - h
        )

        anti = exact_zero(
            partner + h
        )

        reconstruction = sp.expand(
            A[d].subs(
                u,
                t*(t + 1),
            )
            +
            (2*t + 1) *
            B[d].subs(
                u,
                t*(t + 1),
            )
        )

        ok = (
            reconstruction ==
            h
        )

        if not ok:
            decomposition_ok = False

        print(
            f"  d={d:2d}: "
            f"invariant={inv} "
            f"anti_invariant={anti} "
            f"reconstruction={ok}"
        )

    print(
        f"\n  ALL INVOLUTION CHECKS = "
        f"{decomposition_ok}"
    )

    # -------------------------------------------------------------------------
    # 2. CHANNEL PROFILES
    # -------------------------------------------------------------------------

    even_degrees = [
        16, 14, 12, 10,
        8, 6, 4, 2, 0
    ]

    odd_degrees = [
        15, 13, 11, 9,
        7, 5, 3, 1
    ]

    channel_profile(
        "A",
        A,
        even_degrees,
    )

    channel_profile(
        "B",
        B,
        odd_degrees,
    )

    # -------------------------------------------------------------------------
    # 3. QUOTIENT / REMAINDER
    # -------------------------------------------------------------------------

    quotient_remainder_audit(
        "A",
        even_degrees,
        A,
    )

    quotient_remainder_audit(
        "B",
        odd_degrees,
        B,
    )

    # -------------------------------------------------------------------------
    # 4. RECURRENCE SEARCH
    # -------------------------------------------------------------------------

    print()
    print("=" * 78)
    print(
        "2. EXACT POLYNOMIAL-COEFFICIENT "
        "RECURRENCE SEARCH"
    )
    print("=" * 78)

    A_sequence = [
        A[d]
        for d in even_degrees
    ]

    B_sequence = [
        B[d]
        for d in odd_degrees
    ]

    recurrence_sweep(
        "A",
        A_sequence,
    )

    recurrence_sweep(
        "B",
        B_sequence,
    )

    # -------------------------------------------------------------------------
    # 5. FINITE DIFFERENCES
    # -------------------------------------------------------------------------

    finite_difference_orders(
        "A",
        A_sequence,
    )

    finite_difference_orders(
        "B",
        B_sequence,
    )

    # -------------------------------------------------------------------------
    # 6. CROSS-CHANNEL STRUCTURE
    # -------------------------------------------------------------------------

    cross_channel_gcd_audit()

    # -------------------------------------------------------------------------
    # 7. FRESH VALIDATION
    # -------------------------------------------------------------------------

    fresh_ok = fresh_exact_check()

    # -------------------------------------------------------------------------
    # 8. FINAL DIAGNOSTIC
    # -------------------------------------------------------------------------

    print()
    print("=" * 78)
    print(
        "3. FINAL DIAGNOSTIC"
    )
    print("=" * 78)

    print(
        """
The exact involution decomposition is

    h_d(t)
      = A_d(u)
      + (2t+1) B_d(u),

    u=t(t+1).

The present experiment is aimed at the construction law of the
layer sequence itself.

The important object is now the pair of exact sequences

    A_16, A_14, A_12, ..., A_0

and

    B_15, B_13, B_11, ..., B_1.

We search for recurrences of the form

    c_0(u) H_r
      + c_1(u) H_{r-1}
      + ...
      + c_m(u) H_{r-m}
      = 0,

where every c_j(u) has small exact rational/integer degree.

A recurrence that survives every available transition is strong
evidence that the kernel is generated recursively.

A recurrence appearing only because the sequence is short is not
accepted as a universal law.

The key distinction remains:

    reconstruction:
        observed layer values -> t -> X -> N -> p,q

versus

    construction:
        kernel definition -> recurrence -> all layers.

The second is the structural target.

Fresh semiprime reconstruction is included only as an exact
consistency check.
"""
    )

    print()
    print("=" * 78)
    print("FINAL EXACTNESS")
    print("=" * 78)

    print(
        f"  involution_decomposition = "
        f"{decomposition_ok}"
    )

    print(
        f"  fresh_validation = "
        f"{fresh_ok}"
    )

    print(
        f"  all_basic_checks = "
        f"{decomposition_ok and fresh_ok}"
    )

    print("=" * 78)
    print(
        "EXPERIMENT 73 COMPLETE"
    )
    print("=" * 78)


if __name__ == "__main__":
    main()