#!/usr/bin/env python3
"""
==============================================================================
EXPERIMENT 206 — EXACT 7-ADIC EXPONENT-DIGIT /
                SOURCE-DEFECT CORRESPONDENCE AUDIT
==============================================================================

Experiment 205 established:

    delta_e = A_e mod 7,

with observed defect digits

    delta = [0,5,4,1,2]

for e=8,...,12.

It also established that delta_e is not explained by a simple affine
recurrence in the observed finite window.

The exponent lift is governed by

    k_(e+1) = k_e + t_e * ord_{7^e}(3),

where

    t_e = -delta_e mod 7

because the residual slope is exactly 1.

Experiment 206 asks whether the defect digits are therefore exactly
the base-7 digits of the 7-adic discrete logarithm exponent.

Define

    rho = q1/q3,

and formally

    rho / 2 = 3^k

in the 7-adic unit group generated by 3.

The exponent sequence is represented in the inverse-limit system

    k_(e+1) = k_e + t_e * 6*7^(e-1).

The experiment extracts:

    * the lift digit t_e;
    * the corresponding defect digit -t_e;
    * the normalized exponent increment;
    * consistency modulo the previous orbit order;
    * the reconstruction of the orbit residue from the accumulated
      exponent digits.

No p-adic logarithm is evaluated numerically.
Everything is done with exact modular arithmetic.
"""

from __future__ import annotations

import sys


# ============================================================================
# DATA
# ============================================================================

Q1 = 29144191
Q3 = 24794967

P = 7
BASE = 2
MULT = 3

# Verified levels from Experiment 205.
LEVELS = [
    (8, 3401371),
    (9, 3401371),
    (10, 72578983),
    (11, 798943909),
    (12, 10968052873),
]


# ============================================================================
# HELPERS
# ============================================================================

def valuation_7(x: int):
    if x == 0:
        return None

    x = abs(x)
    e = 0

    while x % P == 0:
        x //= P
        e += 1

    return e


def inverse_mod(a: int, m: int) -> int:
    if m <= 1:
        return 0

    a %= m

    if a == 0:
        raise ArithmeticError(
            f"Cannot invert 0 modulo {m}."
        )

    old_r, r = a, m
    old_s, s = 1, 0

    while r:
        q = old_r // r

        old_r, r = (
            r,
            old_r - q * r,
        )

        old_s, s = (
            s,
            old_s - q * s,
        )

    if old_r != 1:
        raise ArithmeticError(
            f"{a} is not invertible modulo {m}."
        )

    return old_s % m


def ratio_mod(modulus: int) -> int:
    return (
        Q1
        * inverse_mod(Q3, modulus)
    ) % modulus


def orbit_mod(k: int, modulus: int) -> int:
    return (
        BASE
        * pow(MULT, k, modulus)
    ) % modulus


def order_3_mod_7e(e: int) -> int:
    return (
        6
        * (P ** (e - 1))
    )


# ============================================================================
# MAIN
# ============================================================================

def main():

    print("=" * 78)
    print(
        "EXPERIMENT 206 — EXACT 7-ADIC EXPONENT-DIGIT / "
        "SOURCE-DEFECT CORRESPONDENCE AUDIT"
    )
    print("=" * 78)

    # ------------------------------------------------------------------
    # 1. SOURCE
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("1. SOURCE DATA")
    print("=" * 78)

    print(
        f"  q1={Q1}"
    )

    print(
        f"  q3={Q3}"
    )

    print(
        f"  q3_mod7={Q3 % P}"
    )

    print(
        f"  v7(q1)={valuation_7(Q1)}"
    )

    print(
        f"  v7(q3)={valuation_7(Q3)}"
    )

    # ------------------------------------------------------------------
    # 2. EXPONENT SEQUENCE
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("2. VERIFIED EXPONENT SEQUENCE")
    print("=" * 78)

    for e, k in LEVELS:

        modulus = P ** e
        residue = orbit_mod(
            k,
            modulus,
        )
        rho = ratio_mod(
            modulus,
        )

        print(
            f"  e={e}: "
            f"k={k} "
            f"modulus={modulus} "
            f"2*3^k={residue} "
            f"rho={rho} "
            f"exact={residue == rho}"
        )

    # ------------------------------------------------------------------
    # 3. LIFT DIGITS
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("3. EXPONENT LIFT DIGITS")
    print("=" * 78)

    exponent_digits = []
    defect_digits = []

    for i in range(
        len(LEVELS) - 1
    ):

        e, k = LEVELS[i]
        _, next_k = LEVELS[i + 1]

        order = order_3_mod_7e(
            e
        )

        delta_k = (
            next_k - k
        )

        if delta_k % order != 0:
            raise ArithmeticError(
                f"Exponent difference at e={e} "
                f"is not divisible by order {order}."
            )

        t = (
            delta_k // order
        ) % P

        exponent_digits.append(
            t
        )

        defect_digits.append(
            (-t) % P
        )

        print(
            f"  e={e}: "
            f"order={order} "
            f"delta_k={delta_k} "
            f"t={t} "
            f"-t mod7={(-t) % P}"
        )

    # ------------------------------------------------------------------
    # 4. SOURCE DEFECT DIGITS
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("4. DIRECT SOURCE-DEFECT DIGITS")
    print("=" * 78)

    direct_defects = []

    for e, k in LEVELS:

        modulus_e = P ** e
        modulus_next = P ** (
            e + 1
        )

        rho_next = ratio_mod(
            modulus_next,
        )

        orbit_next = orbit_mod(
            k,
            modulus_next,
        )

        diff = (
            orbit_next
            - rho_next
        ) % modulus_next

        if diff % modulus_e != 0:
            raise ArithmeticError(
                f"Defect not divisible by 7^{e}."
            )

        defect = (
            diff // modulus_e
        ) % P

        direct_defects.append(
            defect
        )

        print(
            f"  e={e}: "
            f"delta={defect}"
        )

    # Only the transition levels have lift digits.
    aligned_direct_defects = direct_defects[:-1]

    # ------------------------------------------------------------------
    # 5. DIGIT-BY-DIGIT MATCH
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("5. EXPONENT-DIGIT / DEFECT-DIGIT MATCH")
    print("=" * 78)

    match_flags = []

    for i in range(
        len(exponent_digits)
    ):

        t = exponent_digits[i]
        delta = aligned_direct_defects[i]

        exact = (
            delta
            == (-t) % P
        )

        match_flags.append(
            exact
        )

        print(
            f"  e={LEVELS[i][0]}: "
            f"t={t} "
            f"delta={delta} "
            f"-t mod7={(-t) % P} "
            f"exact={exact}"
        )

    # ------------------------------------------------------------------
    # 6. ACCUMULATED EXPONENT DIGIT RECONSTRUCTION
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("6. ACCUMULATED EXPONENT RECONSTRUCTION")
    print("=" * 78)

    reconstructed_k = LEVELS[0][1]

    reconstruction_rows = []

    for i, t in enumerate(
        exponent_digits
    ):

        e = LEVELS[i][0]

        order = order_3_mod_7e(
            e
        )

        reconstructed_k += (
            t * order
        )

        actual_k = LEVELS[i + 1][1]

        exact = (
            reconstructed_k
            == actual_k
        )

        reconstruction_rows.append(
            exact
        )

        print(
            f"  e={e}: "
            f"added={t}*{order} "
            f"reconstructed={reconstructed_k} "
            f"actual={actual_k} "
            f"exact={exact}"
        )

    # ------------------------------------------------------------------
    # 7. ORBIT-RESIDUE RECONSTRUCTION
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("7. ORBIT RESIDUE RECONSTRUCTION")
    print("=" * 78)

    orbit_checks = []

    for e, k in LEVELS:

        modulus = P ** e

        reconstructed = orbit_mod(
            k,
            modulus,
        )

        rho = ratio_mod(
            modulus,
        )

        exact = (
            reconstructed
            == rho
        )

        orbit_checks.append(
            exact
        )

        print(
            f"  e={e}: "
            f"orbit={reconstructed} "
            f"rho={rho} "
            f"exact={exact}"
        )

    # ------------------------------------------------------------------
    # 8. BASE-7 DIGIT DESCRIPTION
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("8. BASE-7 DIGIT DESCRIPTION")
    print("=" * 78)

    print(
        f"  exponent_digits={exponent_digits}"
    )

    print(
        f"  defect_digits={defect_digits}"
    )

    print(
        f"  direct_defects={aligned_direct_defects}"
    )

    print(
        f"  digit_identity="
        f"{exponent_digits == [(-x) % P for x in aligned_direct_defects]}"
    )

    # ------------------------------------------------------------------
    # 9. STRUCTURAL INTERPRETATION
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("9. STRUCTURAL INTERPRETATION")
    print("=" * 78)

    print(
        """
The defect digit is not an unrelated sequence.

At each Hensel level,

    t_e = -delta_e mod 7.

The exponent increment is

    k_(e+1)-k_e
        = t_e * ord_{7^e}(3).

Therefore the source-ratio defect digit determines the next exponent
digit exactly.

This is the finite inverse-limit analogue of a discrete logarithm:

    source ratio rho
        ->
    defect digit delta_e
        ->
    exponent digit t_e
        ->
    lifted exponent k_e.

The result does not require evaluating a p-adic logarithm. It is an
exact digit-by-digit statement in the finite quotients
(Z/7^e Z)^*.
"""
    )

    # ------------------------------------------------------------------
    # 10. FINAL
    # ------------------------------------------------------------------

    all_match = all(
        match_flags
    )

    all_reconstruction = all(
        reconstruction_rows
    )

    all_orbit = all(
        orbit_checks
    )

    final_ok = (
        valuation_7(Q1) == 0
        and valuation_7(Q3) == 0
        and all_match
        and all_reconstruction
        and all_orbit
    )

    print()
    print("=" * 78)
    print("10. FINAL EXACTNESS")
    print("=" * 78)

    print(
        f"  exponent_defect_digit_match="
        f"{all_match}"
    )

    print(
        f"  exponent_reconstruction_exact="
        f"{all_reconstruction}"
    )

    print(
        f"  orbit_reconstruction_exact="
        f"{all_orbit}"
    )

    print(
        f"  exponent_digits="
        f"{exponent_digits}"
    )

    print(
        f"  defect_digits="
        f"{aligned_direct_defects}"
    )

    print(
        f"  failures={0 if final_ok else 1}"
    )

    print(
        f"  ALL BASIC CHECKS PASS={final_ok}"
    )

    print()
    print("EXPERIMENT 206 COMPLETE")


if __name__ == "__main__":

    try:
        main()

    except KeyboardInterrupt:
        print("\nInterrupted.")
        sys.exit(130)

    except Exception as exc:
        print(
            "\nFATAL ERROR: "
            + type(exc).__name__
            + ": "
            + str(exc)
        )
        raise

