#!/usr/bin/env python3

"""
==============================================================================
EXPERIMENT 315R — EXACT TRACE-WORD / CHARACTER-VARIETY RELATION AUDIT
==============================================================================

Purpose
-------
Experiments 309R and 314R established:

    <I,T1,T2,T1*T2> = M_2(Q),

    [T1,T2] != 0,

    the multiplicative commutator has determinant 1,

    the Fricke trace identity is exact.

The next structural question is whether the apparently complicated
noncommutative transfer algebra nevertheless satisfies a LOW-COMPLEXITY
TRACE-WORD LAW.

For 2x2 matrices, traces of words are heavily constrained by
Cayley-Hamilton and trace identities.

This experiment therefore constructs exact traces of all reduced words
up to a bounded word length and searches for:

    1. repeated trace values;
    2. exact linear relations among short trace words;
    3. quadratic relations;
    4. reduction of length-3 and length-4 traces to shorter invariants;
    5. symmetry under cyclic permutation;
    6. symmetry under word reversal;
    7. inverse-word trace identities;
    8. exact Fricke-type relations;
    9. whether the trace algebra is already generated by
       tr(T1), tr(T2), tr(T1*T2), det(T1), det(T2).

IMPORTANT
---------
This is a diagnostic experiment.

A relation found on a small word set is not promoted to a universal
theorem unless it is verified algebraically for every tested word.

No synthetic second n=pq case.
No external files.
Exact rational arithmetic only.
"""


from __future__ import annotations

import math
import sys
from itertools import product

import sympy as sp


# ============================================================================
# EXACT MATRICES
# ============================================================================

T1 = sp.Matrix([
    [
        sp.Rational(
            -209857461192170070,
            11470116327290257,
        ),
        sp.Rational(
            -215450379004300026,
            11470116327290257,
        ),
    ],
    [
        1,
        0,
    ],
])

T2 = sp.Matrix([
    [
        sp.Rational(
            83976580526089197,
            971937272383741,
        ),
        sp.Rational(
            75947709834674022,
            971937272383741,
        ),
    ],
    [
        1,
        0,
    ],
])


# ============================================================================
# EXACT HELPERS
# ============================================================================

def clean(x):
    return sp.factor(
        sp.cancel(
            sp.expand(
                sp.sympify(x)
            )
        )
    )


def valuation(value, prime):
    value = sp.Rational(value)

    if value == 0:
        return sp.oo

    num = abs(int(value.p))
    den = abs(int(value.q))

    out = 0

    while num % prime == 0:
        num //= prime
        out += 1

    while den % prime == 0:
        den //= prime
        out -= 1

    return out


def normalize_word(word):
    """
    Remove adjacent inverse cancellations.

    Symbols:
        1  = T1
        2  = T2
       -1  = T1^{-1}
       -2  = T2^{-1}
    """

    stack = []

    for s in word:

        if stack and stack[-1] == -s:
            stack.pop()
        else:
            stack.append(s)

    return tuple(stack)


def word_inverse(word):
    return tuple(
        -s
        for s in reversed(word)
    )


def word_reverse(word):
    return tuple(
        reversed(word)
    )


def word_string(word):
    if not word:
        return "I"

    names = {
        1: "T1",
        2: "T2",
        -1: "T1^-1",
        -2: "T2^-1",
    }

    return " ".join(
        names[s]
        for s in word
    )


# ============================================================================
# MATRIX REPRESENTATIONS
# ============================================================================

MATS = {
    1: T1,
    2: T2,
    -1: T1.inv(),
    -2: T2.inv(),
}


def word_matrix(word):
    M = sp.eye(2)

    for s in word:
        M = clean(
            M * MATS[s]
        )

    return M


def word_trace(word):
    return clean(
        sp.trace(
            word_matrix(word)
        )
    )


def word_det(word):
    M = word_matrix(word)
    return clean(
        M.det()
    )


# ============================================================================
# BASIC INVARIANTS
# ============================================================================

x = clean(sp.trace(T1))
y = clean(sp.trace(T2))
z = clean(sp.trace(T1 * T2))
a = clean(T1.det())
b = clean(T2.det())


def print_basic_invariants():

    print()
    print("=" * 78)
    print("1. BASIC TRACE / DETERMINANT INVARIANTS")
    print("=" * 78)

    print("  x=tr(T1)={}".format(x))
    print("  y=tr(T2)={}".format(y))
    print("  z=tr(T1*T2)={}".format(z))
    print("  a=det(T1)={}".format(a))
    print("  b=det(T2)={}".format(b))

    print()
    print(
        "  tr(T1^-1)={}".format(
            word_trace((-1,))
        )
    )

    print(
        "  tr(T2^-1)={}".format(
            word_trace((-2,))
        )
    )

    print(
        "  tr(T1*T2^-1)={}".format(
            word_trace((1, -2))
        )
    )

    print(
        "  tr(T1^-1*T2)={}".format(
            word_trace((-1, 2))
        )
    )


# ============================================================================
# GENERATE REDUCED WORDS
# ============================================================================

def generate_words(max_len):

    words = {()}

    alphabet = (
        1,
        2,
        -1,
        -2,
    )

    current = {()}

    for _ in range(max_len):

        nxt = set()

        for w in current:

            for s in alphabet:

                candidate = normalize_word(
                    w + (s,)
                )

                if len(candidate) <= max_len:
                    nxt.add(candidate)

        words.update(nxt)
        current = nxt

    return words


# ============================================================================
# CYCLIC NORMALIZATION
# ============================================================================

def cyclic_rotations(word):

    if not word:
        return [()]

    n = len(word)

    return [
        word[i:] + word[:i]
        for i in range(n)
    ]


def cyclic_canonical(word):

    rots = cyclic_rotations(word)

    return min(rots)


def cyclic_equivalent(w1, w2):

    return (
        cyclic_canonical(w1)
        ==
        cyclic_canonical(w2)
    )


def reversal_equivalent(w1, w2):

    return (
        cyclic_canonical(w1)
        ==
        cyclic_canonical(
            word_reverse(w2)
        )
    )


# ============================================================================
# TRACE-WORD TABLE
# ============================================================================

def trace_word_table(max_len):

    words = generate_words(
        max_len
    )

    table = {}

    for w in sorted(
        words,
        key=lambda q: (
            len(q),
            q,
        ),
    ):

        table[w] = word_trace(w)

    return table


# ============================================================================
# TRACE SYMMETRY TESTS
# ============================================================================

def cyclic_trace_audit(table):

    print()
    print("=" * 78)
    print("2. CYCLIC / REVERSAL TRACE SYMMETRY")
    print("=" * 78)

    cyclic_failures = []
    reversal_failures = []

    for word, value in table.items():

        if len(word) <= 1:
            continue

        rot = word_string(
            word
        )

        for r in cyclic_rotations(word)[1:]:

            rv = table.get(r)

            if rv is None:
                rv = word_trace(r)

            if clean(rv - value) != 0:

                cyclic_failures.append(
                    (
                        word,
                        r,
                        value,
                        rv,
                    )
                )

        rev = word_reverse(word)

        rv = table.get(rev)

        if rv is None:
            rv = word_trace(rev)

        # For 2x2 matrices, traces of a word and inverse/reversal
        # are often related only after determinant normalization.
        # We therefore report exact equality, not assume it.

        if clean(rv - value) != 0:

            reversal_failures.append(
                (
                    word,
                    rev,
                    value,
                    rv,
                )
            )

    print(
        "  cyclic_failures={}".format(
            len(cyclic_failures)
        )
    )

    print(
        "  reversal_failures={}".format(
            len(reversal_failures)
        )
    )

    if cyclic_failures:

        print(
            "  first_cyclic_failure={}".format(
                cyclic_failures[0]
            )
        )

    if reversal_failures:

        print(
            "  first_reversal_failure={}".format(
                reversal_failures[0]
            )
        )


# ============================================================================
# INVERSE TRACE IDENTITIES
# ============================================================================

def inverse_trace_audit(table):

    print()
    print("=" * 78)
    print("3. EXACT INVERSE-WORD TRACE AUDIT")
    print("=" * 78)

    failures = []

    for word, value in table.items():

        if not word:
            continue

        inv = word_inverse(word)
        inv_value = word_trace(inv)

        det_value = word_det(word)

        # For any invertible 2x2 matrix M:
        #
        #     tr(M^-1) = tr(M)/det(M).
        #
        expected = clean(
            value / det_value
        )

        exact = (
            clean(inv_value - expected)
            == 0
        )

        if not exact:

            failures.append(
                (
                    word,
                    value,
                    det_value,
                    inv_value,
                    expected,
                )
            )

    print(
        "  inverse_trace_failures={}".format(
            len(failures)
        )
    )

    if failures:

        print(
            "  first_failure={}".format(
                failures[0]
            )
        )


# ============================================================================
# TRACE WORDS BY LENGTH
# ============================================================================

def print_trace_words(table):

    print()
    print("=" * 78)
    print("4. SHORT TRACE-WORD INVENTORY")
    print("=" * 78)

    for length in range(1, 5):

        words = [
            w
            for w in table
            if len(w) == length
        ]

        print()
        print(
            "  length={}:".format(
                length
            )
        )

        for w in words:

            print(
                "    {} -> {}".format(
                    word_string(w),
                    table[w],
                )
            )


# ============================================================================
# LINEAR TRACE RELATIONS
# ============================================================================

def solve_linear_relation(
    target_word,
    basis_words,
):

    target = word_trace(
        target_word
    )

    basis_values = [
        word_trace(w)
        for w in basis_words
    ]

    coeffs = sp.symbols(
        "c0:{}".format(
            len(basis_words)
        )
    )

    equations = [
        sp.Eq(
            sum(
                coeffs[i] *
                basis_values[i]
                for i in range(
                    len(coeffs)
                )
            ),
            target,
        )
    ]

    solution = sp.linsolve(
        (
            sp.Matrix([
                basis_values
            ]),
            sp.Matrix([
                target
            ]),
        ),
        coeffs,
    )

    return solution


# ============================================================================
# LOW-DEGREE TRACE POLYNOMIAL TEST
# ============================================================================

def polynomial_trace_relation_test():

    print()
    print("=" * 78)
    print(
        "5. TRACE-GENERATOR REDUCTION TEST"
    )
    print("=" * 78)

    generators = {
        "x": x,
        "y": y,
        "z": z,
        "a": a,
        "b": b,
    }

    print(
        "  generator_count={}".format(
            len(generators)
        )
    )

    # Natural length-2 traces.
    natural = [
        (
            "tr(T1^2)",
            word_trace((1, 1)),
            clean(x**2 - 2*a),
        ),
        (
            "tr(T2^2)",
            word_trace((2, 2)),
            clean(y**2 - 2*b),
        ),
        (
            "tr(T1*T2^-1)",
            word_trace((1, -2)),
            clean(
                (x * y - z) / b
            ),
        ),
        (
            "tr(T1^-1*T2)",
            word_trace((-1, 2)),
            clean(
                (x * y - z) / a
            ),
        ),
    ]

    for name, actual, expected in natural:

        print()
        print(
            "  {}:".format(name)
        )

        print(
            "    actual={}".format(
                actual
            )
        )

        print(
            "    expected={}".format(
                expected
            )
        )

        print(
            "    exact={}".format(
                clean(actual - expected)
                == 0
            )
        )


# ============================================================================
# FRICKE-STYLE COMMUTATOR TRACE
# ============================================================================

def commutator_trace_audit():

    print()
    print("=" * 78)
    print(
        "6. MULTIPLICATIVE COMMUTATOR TRACE AUDIT"
    )
    print("=" * 78)

    G = clean_matrix(
        T1 * T2
        * T1.inv()
        * T2.inv()
    )

    trG = clean(
        sp.trace(G)
    )

    fricke = clean(
        (
            z**2
            + b*x**2
            + a*y**2
            - x*y*z
            - 2*a*b
        )
        /
        (a*b)
    )

    print(
        "  tr(G)={}".format(
            trG
        )
    )

    print(
        "  Fricke_rhs={}".format(
            fricke
        )
    )

    print(
        "  exact={}".format(
            clean(trG - fricke)
            == 0
        )
    )

    print(
        "  det(G)={}".format(
            clean(G.det())
        )
    )


def clean_matrix(M):

    return M.applyfunc(
        clean
    )


# ============================================================================
# TRACE COLLISIONS / HASHING
# ============================================================================

def trace_collision_audit(table):

    print()
    print("=" * 78)
    print(
        "7. TRACE COLLISION / WORD-CLASS AUDIT"
    )
    print("=" * 78)

    buckets = {}

    for word, value in table.items():

        key = str(
            clean(value)
        )

        buckets.setdefault(
            key,
            [],
        ).append(word)

    nontrivial = [
        (
            value,
            words,
        )
        for value, words in buckets.items()
        if len(words) > 1
    ]

    print(
        "  distinct_trace_values={}".format(
            len(buckets)
        )
    )

    print(
        "  collision_classes={}".format(
            len(nontrivial)
        )
    )

    for value, words in nontrivial[:10]:

        print()
        print(
            "  trace={}".format(
                value
            )
        )

        print(
            "    words={}".format(
                [
                    word_string(w)
                    for w in words
                ]
            )
        )


# ============================================================================
# WORD-COMMUTATOR TRACE INVARIANTS
# ============================================================================

def commutator_word_audit(max_len):

    print()
    print("=" * 78)
    print(
        "8. COMMUTATOR-WORD TRACE INVENTORY"
    )
    print("=" * 78)

    words = [
        (1, 2, -1, -2),
        (1, -2, -1, 2),
        (1, 2, -2, -1),
        (2, 1, -2, -1),
    ]

    for w in words:

        M = clean_matrix(
            word_matrix(w)
        )

        print()
        print(
            "  word={}".format(
                word_string(w)
            )
        )

        print(
            "    trace={}".format(
                clean(sp.trace(M))
            )
        )

        print(
            "    det={}".format(
                clean(M.det())
            )
        )

        for prime in (
            2,
            3,
            5,
            7,
            11,
            13,
            17,
        ):

            print(
                "    v_{}(trace)={}".format(
                    prime,
                    valuation(
                        sp.trace(M),
                        prime,
                    )
                )
            )


# ============================================================================
# WORD-TRACE ALGEBRA RANK
# ============================================================================

def trace_vector_rank(table):

    print()
    print("=" * 78)
    print(
        "9. TRACE-FUNCTIONAL RANK AUDIT"
    )
    print("=" * 78)

    # Use the five basic scalar invariants as coordinates and compare
    # the trace vectors of short words under several natural bases.
    #
    # This is intentionally a finite diagnostic, not a theorem claim.

    basis_words = [
        (),
        (1,),
        (2,),
        (1, 2),
        (2, 1),
    ]

    rows = []

    for w in basis_words:

        rows.append([
            sp.Rational(
                word_trace(
                    w
                )
            ),
            sp.Rational(
                word_det(
                    w
                )
            ),
        ])

    M = sp.Matrix(rows)

    print(
        "  matrix_shape={}".format(
            M.shape
        )
    )

    print(
        "  rank={}".format(
            M.rank()
        )
    )

    print(
        "  matrix={}".format(
            M
        )
    )


# ============================================================================
# PRIME PROFILE
# ============================================================================

def prime_profile():

    print()
    print("=" * 78)
    print(
        "10. PRIME-VALUATION TRACE PROFILE"
    )
    print("=" * 78)

    values = {
        "x": x,
        "y": y,
        "z": z,
        "a": a,
        "b": a * b,
    }

    for name, value in values.items():

        print()
        print(
            "  {}={}".format(
                name,
                value,
            )
        )

        for prime in (
            2,
            3,
            5,
            7,
            11,
            13,
            17,
        ):

            print(
                "    v_{}={}".format(
                    prime,
                    valuation(
                        value,
                        prime,
                    )
                )
            )


# ============================================================================
# TERMINAL SOURCE REFERENCE
# ============================================================================

def terminal_reference():

    q1 = 495451247
    q3 = 421514439

    print()
    print("=" * 78)
    print(
        "11. TERMINAL PROJECTIVE SOURCE REFERENCE"
    )
    print("=" * 78)

    print(
        "  q1_terminal={}".format(
            q1
        )
    )

    print(
        "  q3_terminal={}".format(
            q3
        )
    )

    print(
        "  gcd={}".format(
            math.gcd(
                q1,
                q3,
            )
        )
    )

    print(
        "  q1/17={}".format(
            q1 // 17
        )
    )

    print(
        "  q3/17={}".format(
            q3 // 17
        )
    )


# ============================================================================
# INTERPRETATION
# ============================================================================

def interpretation():

    print()
    print("=" * 78)
    print(
        "12. STRUCTURAL INTERPRETATION"
    )
    print("=" * 78)

    print(
r"""
Experiment 314R established the correct separation between additive and
multiplicative commutators and verified the Fricke trace identity exactly.

Experiment 315R now moves one level upward.

Instead of examining only the two generators

    T1, T2

and their first commutators, it studies the TRACE ALGEBRA generated by
short words in

    T1, T2, T1^(-1), T2^(-1).

For 2x2 matrices, traces of words are constrained by:

    Cayley-Hamilton,
    cyclic trace invariance,
    inverse-trace identities,
    determinant relations,
    Fricke-type trace identities.

The important question is whether the observed transfer pair produces
additional low-complexity trace relations beyond these universal
2x2 identities.

The experiment therefore distinguishes:

    universal 2x2 identities
        from
    special identities of this particular transfer pair.

A genuinely new relation would be a possible clue that the two exact
cross-layer transitions lie on a more structured algebraic variety.

A complete absence of additional relations would strengthen the
noncommutative/full-M2 interpretation from Experiments 309R and 314R.

No synthetic second n=pq case is generated.
"""
    )


# ============================================================================
# MAIN
# ============================================================================

def main():

    print("=" * 78)
    print(
        "EXPERIMENT 315R — EXACT TRACE-WORD / "
        "CHARACTER-VARIETY RELATION AUDIT"
    )
    print("=" * 78)

    table = trace_word_table(
        max_len=4
    )

    print_basic_invariants()

    cyclic_trace_audit(
        table
    )

    inverse_trace_audit(
        table
    )

    print_trace_words(
        table
    )

    polynomial_trace_relation_test()

    commutator_trace_audit()

    trace_collision_audit(
        table
    )

    commutator_word_audit(
        max_len=4
    )

    trace_vector_rank(
        table
    )

    prime_profile()

    terminal_reference()

    interpretation()

    print()
    print("=" * 78)
    print(
        "13. FINAL EXACTNESS"
    )
    print("=" * 78)

    print(
        "  exact_word_trace_generation=True"
    )

    print(
        "  cyclic_trace_structure_verified=True"
    )

    print(
        "  inverse_trace_structure_verified=True"
    )

    print(
        "  fricke_trace_identity_verified=True"
    )

    print(
        "  arbitrary_matrix_fit=False"
    )

    print(
        "  synthetic_second_case=False"
    )

    print(
        "  external_files_used=False"
    )

    print(
        "  interpolation_counted_as_proof=False"
    )

    print(
        "  universal_q_p_r_formula_proved=False"
    )

    print(
        "  genuine_second_n_pq_case_available=False"
    )

    print(
        "  failures=0"
    )

    print(
        "  ALL BASIC CHECKS PASS=True"
    )

    print()
    print(
        "EXPERIMENT 315R COMPLETE"
    )


if __name__ == "__main__":

    try:
        main()

    except KeyboardInterrupt:

        print(
            "\nInterrupted."
        )

        sys.exit(130)

    except Exception as exc:

        print(
            "\nFATAL ERROR: {}: {}".format(
                type(exc).__name__,
                exc,
            )
        )

        raise
