#!/usr/bin/env python3

"""
====================================================================================================
FOREIGN-MODULUS FINGERPRINT / EXACT C-CLASS DISCRIMINATION EXPERIMENT
====================================================================================================

PURPOSE
-------

Previous experiments established:

    M = 3*5*7*11*13*17*19*23

and

    C = p*q mod M.

All members of an exact C-class satisfy

    a*b == p*q (mod M).

Therefore no combination of

    3,5,7,11,13,17,19,23

can distinguish members inside the same exact C-class.

This experiment introduces NEW primes which do NOT divide M.

FOREIGN MODULI:

    [29,31,37,41,43,47,53,59,61,67]

The experiment asks:

    1. How many C-class members remain indistinguishable using
       each single foreign modulus?

    2. How many are distinguished by pairs of foreign moduli?

    3. How many are distinguished by triples?

    4. What is the minimum number of foreign moduli required to
       uniquely fingerprint every member of every observed C-class?

    5. What is the first foreign modulus that distinguishes each
       shifted collision pair from its original anchor?

    6. How does PRODUCT fingerprinting compare with FACTOR-PAIR
       fingerprinting?

PRODUCT FINGERPRINT:

    F_r(a,b) = (a*b) mod r

FACTOR FINGERPRINT:

    G_r(a,b) = (a mod r, b mod r)

The product fingerprint is the direct continuation of the original
idea:

    n mod r.

The factor-pair fingerprint contains additional information and is
reported separately.

IMPORTANT
---------

This experiment does NOT claim that a new modulus solves factoring.

It measures how much discriminatory information a collection of
non-divisor moduli supplies inside the finite C-classes generated by
the original M-congruence.


====================================================================================================
"""

import math
import random
from itertools import combinations
from collections import Counter


# ================================================================================================
# CONFIGURATION
# ================================================================================================

M = 111_546_435

FACTOR_MIN = 10_000
FACTOR_MAX = 100_000

TRIALS = 300

T_MIN = -25
T_MAX = 25

SEED = 1_511_464_998

ORIGINAL_MODULI = [
    3, 5, 7, 11, 13, 17, 19, 23
]

FOREIGN_MODULI = [
    29, 31, 37, 41, 43,
    47, 53, 59, 61, 67
]

MAX_PRINT_CLASSES = 25


# ================================================================================================
# PRIME GENERATION
# ================================================================================================

def sieve(limit):
    prime = bytearray(b"\x01") * (limit + 1)

    prime[0] = 0
    prime[1] = 0

    for p in range(2, int(limit ** 0.5) + 1):
        if prime[p]:
            start = p * p
            count = ((limit - start) // p) + 1
            prime[start:limit + 1:p] = b"\x00" * count

    return [
        x for x in range(limit + 1)
        if prime[x]
    ]


ALL_PRIMES = sieve(FACTOR_MAX)

FACTOR_PRIMES = [
    p for p in ALL_PRIMES
    if FACTOR_MIN <= p <= FACTOR_MAX
]

PRIME_SET = set(FACTOR_PRIMES)


# ================================================================================================
# RANDOM ANCHORS
# ================================================================================================

def random_prime_pair(rng):
    while True:

        a = rng.choice(FACTOR_PRIMES)
        b = rng.choice(FACTOR_PRIMES)

        if a != b:
            return tuple(sorted((a, b)))


def generate_unique_anchors(count, rng):

    seen = set()
    anchors = []

    while len(anchors) < count:

        p, q = random_prime_pair(rng)
        n = p * q

        if n in seen:
            continue

        seen.add(n)
        anchors.append((p, q))

    return anchors


# ================================================================================================
# EXACT C-CLASS
# ================================================================================================

def exact_c_class(p, q):

    """
    Find all prime pairs (a,b) in the factor range satisfying

        a*b == p*q (mod M).

    No giant product table is created.

    For each a:

        b = C * a^(-1) mod M
    """

    C = (p * q) % M

    result = set()

    for a in FACTOR_PRIMES:

        inv_a = pow(a, -1, M)

        b = (C * inv_a) % M

        if (
            FACTOR_MIN <= b <= FACTOR_MAX
            and b in PRIME_SET
            and a != b
        ):

            result.add(
                tuple(sorted((a, b)))
            )

    return sorted(result)


# ================================================================================================
# FINGERPRINTS
# ================================================================================================

def product_fingerprint(pair, moduli):

    a, b = pair
    product = a * b

    return tuple(
        product % r
        for r in moduli
    )


def factor_fingerprint(pair, moduli):

    a, b = pair

    return tuple(
        (a % r, b % r)
        for r in moduli
    )


# ================================================================================================
# FIND FIRST DISCRIMINATING MODULUS
# ================================================================================================

def first_discriminating_modulus(
    anchor,
    candidate,
    moduli
):

    anchor_product = anchor[0] * anchor[1]
    candidate_product = candidate[0] * candidate[1]

    for r in moduli:

        if (
            anchor_product % r
            != candidate_product % r
        ):
            return r

    return None


# ================================================================================================
# CLASS ANALYSIS
# ================================================================================================

def analyze_class(anchor, members):

    result = {
        "anchor": anchor,
        "members": members,
        "class_size": len(members),
        "product_unique": {},
        "factor_unique": {},
        "first_discriminating": {},
        "min_product_k": None,
        "min_factor_k": None,
    }

    # -------------------------------------------------------------------------
    # Every foreign subset
    # -------------------------------------------------------------------------

    for k in range(1, len(FOREIGN_MODULI) + 1):

        for subset in combinations(
            FOREIGN_MODULI,
            k
        ):

            product_signatures = {
                member:
                product_fingerprint(member, subset)
                for member in members
            }

            factor_signatures = {
                member:
                factor_fingerprint(member, subset)
                for member in members
            }

            unique_product = (
                len(set(product_signatures.values()))
                == len(members)
            )

            unique_factor = (
                len(set(factor_signatures.values()))
                == len(members)
            )

            if unique_product:

                if result["min_product_k"] is None:
                    result["min_product_k"] = k

            if unique_factor:

                if result["min_factor_k"] is None:
                    result["min_factor_k"] = k

            # We only need to know whether at least one subset of this
            # cardinality succeeds. Once found, no need to inspect the
            # remaining subsets for this k.
            if (
                result["min_product_k"] == k
                and result["min_factor_k"] == k
            ):
                break

        if (
            result["min_product_k"] is not None
            and result["min_factor_k"] is not None
            and result["min_product_k"] <= k
            and result["min_factor_k"] <= k
        ):
            pass

    # -------------------------------------------------------------------------
    # First discriminating modulus for each non-anchor member
    # -------------------------------------------------------------------------

    for member in members:

        if member == anchor:
            continue

        result["first_discriminating"][member] = (
            first_discriminating_modulus(
                anchor,
                member,
                FOREIGN_MODULI
            )
        )

    return result


# ================================================================================================
# GLOBAL SINGLE-MODULUS COLLISION TABLE
# ================================================================================================

def global_modulus_statistics(anchors):

    print("=" * 100)
    print("GLOBAL FOREIGN-MODULUS FINGERPRINT STATISTICS")
    print("=" * 100)

    products = [
        p * q
        for p, q in anchors
    ]

    print(
        f"{'r':>6} "
        f"{'unique products':>18} "
        f"{'max collision':>16} "
        f"{'collision pairs':>18}"
    )

    print("-" * 100)

    for r in FOREIGN_MODULI:

        counts = Counter(
            x % r
            for x in products
        )

        unique = len(counts)

        maximum = max(
            counts.values()
        )

        collision_pairs = sum(
            c * (c - 1) // 2
            for c in counts.values()
        )

        print(
            f"{r:6d} "
            f"{unique:18d} "
            f"{maximum:16d} "
            f"{collision_pairs:18d}"
        )

    print()


# ================================================================================================
# CLASS SIZE SUMMARY
# ================================================================================================

def class_summary(results):

    print("=" * 100)
    print("EXACT C-CLASS SUMMARY")
    print("=" * 100)

    sizes = [
        x["class_size"]
        for x in results
    ]

    print(
        f"classes              = {len(results)}"
    )

    print(
        f"minimum class size   = {min(sizes)}"
    )

    print(
        f"maximum class size   = {max(sizes)}"
    )

    print(
        f"mean class size      = "
        f"{sum(sizes) / len(sizes):.6f}"
    )

    counter = Counter(sizes)

    print()
    print("class-size distribution:")

    for size in sorted(counter):

        print(
            f"    size={size} "
            f"classes={counter[size]}"
        )

    print()


# ================================================================================================
# MINIMUM FOREIGN-MODULUS COUNT
# ================================================================================================

def minimum_k_summary(results):

    print("=" * 100)
    print("MINIMUM NUMBER OF FOREIGN MODULI FOR UNIQUE FINGERPRINT")
    print("=" * 100)

    for k in range(1, len(FOREIGN_MODULI) + 1):

        product_count = sum(
            r["min_product_k"] == k
            for r in results
        )

        factor_count = sum(
            r["min_factor_k"] == k
            for r in results
        )

        print(
            f"k={k:2d} "
            f"product-fingerprint classes={product_count:3d} "
            f"factor-fingerprint classes={factor_count:3d}"
        )

    never_product = sum(
        r["min_product_k"] is None
        for r in results
    )

    never_factor = sum(
        r["min_factor_k"] is None
        for r in results
    )

    print()
    print(
        f"never uniquely resolved by product fingerprint = "
        f"{never_product}"
    )

    print(
        f"never uniquely resolved by factor fingerprint   = "
        f"{never_factor}"
    )

    print()


# ================================================================================================
# BEST MODULUS COMBINATIONS
# ================================================================================================

def best_combinations(results):

    print("=" * 100)
    print("BEST FOREIGN-MODULUS COMBINATIONS")
    print("=" * 100)

    for k in range(1, 5):

        best = None

        for subset in combinations(
            FOREIGN_MODULI,
            k
        ):

            resolved = 0

            for result in results:

                signatures = {
                    product_fingerprint(
                        member,
                        subset
                    )
                    for member in result["members"]
                }

                if len(signatures) == result["class_size"]:
                    resolved += 1

            candidate = (
                resolved,
                subset
            )

            if (
                best is None
                or candidate[0] > best[0]
            ):
                best = candidate

        resolved, subset = best

        print(
            f"k={k} "
            f"best={subset} "
            f"resolved={resolved}/{len(results)}"
        )

    print()


# ================================================================================================
# FIRST-DISCRIMINATING-MODULUS DISTRIBUTION
# ================================================================================================

def first_modulus_distribution(results):

    print("=" * 100)
    print("FIRST FOREIGN MODULUS THAT DISTINGUISHES C-CLASS MEMBERS")
    print("=" * 100)

    counter = Counter()

    for result in results:

        for modulus in result[
            "first_discriminating"
        ].values():

            counter[modulus] += 1

    total = sum(counter.values())

    for r in FOREIGN_MODULI:

        count = counter[r]

        fraction = (
            count / total
            if total
            else 0.0
        )

        print(
            f"r={r:2d} "
            f"count={count:4d} "
            f"fraction={fraction:.6f}"
        )

    print()


# ================================================================================================
# SHIFTED COLLISION TEST
# ================================================================================================

def shifted_collision_test(results):

    print("=" * 100)
    print("SHIFTED COLLISION FOREIGN-MODULUS TEST")
    print("=" * 100)

    total_events = 0

    first_modulus_counter = Counter()

    identity_failures = 0

    examples = []

    for result in results:

        anchor = result["anchor"]

        anchor_product = anchor[0] * anchor[1]

        # Any other member of the C-class is a potential shifted
        # collision candidate. We reconstruct t exactly.
        for member in result["members"]:

            if member == anchor:
                continue

            candidate_product = member[0] * member[1]

            difference = (
                candidate_product - anchor_product
            )

            if difference % (2 * M) != 0:

                continue

            t = difference // (2 * M)

            if not (T_MIN <= t <= T_MAX):

                continue

            total_events += 1

            r = first_discriminating_modulus(
                anchor,
                member,
                FOREIGN_MODULI
            )

            if r is not None:
                first_modulus_counter[r] += 1

            if (
                candidate_product
                != anchor_product + 2 * M * t
            ):
                identity_failures += 1

            if len(examples) < 20:

                examples.append(
                    (
                        anchor,
                        member,
                        t,
                        r
                    )
                )

    print(
        f"shifted events inside T range = "
        f"{total_events}"
    )

    print(
        f"identity failures              = "
        f"{identity_failures}"
    )

    print()

    for r in FOREIGN_MODULI:

        print(
            f"r={r:2d} "
            f"first-discriminating-events="
            f"{first_modulus_counter[r]}"
        )

    print()

    print("-" * 100)
    print("EXAMPLES")
    print("-" * 100)

    for anchor, member, t, r in examples:

        print(
            f"anchor={anchor[0]:,}*{anchor[1]:,} "
            f"candidate={member[0]:,}*{member[1]:,} "
            f"t={t:+d} "
            f"first_r={r}"
        )

    print()


# ================================================================================================
# FOREIGN FINGERPRINT COLLISIONS INSIDE C-CLASSES
# ================================================================================================

def internal_collision_summary(results):

    print("=" * 100)
    print("FOREIGN FINGERPRINT COLLISIONS INSIDE EXACT C-CLASSES")
    print("=" * 100)

    print(
        f"{'k':>4} "
        f"{'subsets':>10} "
        f"{'classes fully resolved':>24} "
        f"{'class-resolution %':>22}"
    )

    print("-" * 100)

    for k in range(
        1,
        len(FOREIGN_MODULI) + 1
    ):

        total_subsets = 0
        total_resolved = 0

        for subset in combinations(
            FOREIGN_MODULI,
            k
        ):

            total_subsets += 1

            for result in results:

                signatures = {
                    product_fingerprint(
                        member,
                        subset
                    )
                    for member in result["members"]
                }

                if len(signatures) == result["class_size"]:
                    total_resolved += 1

        possible = (
            total_subsets * len(results)
        )

        percentage = (
            total_resolved / possible
            if possible
            else 0.0
        )

        print(
            f"{k:4d} "
            f"{total_subsets:10d} "
            f"{total_resolved:24d} "
            f"{percentage:21.6f}%"
        )

    print()


# ================================================================================================
# MOST INTERESTING CLASSES
# ================================================================================================

def print_interesting_classes(results):

    print("=" * 100)
    print("C-CLASSES WITH THE MOST INTERESTING FOREIGN-MODULUS BEHAVIOR")
    print("=" * 100)

    rows = []

    for result in results:

        if result["class_size"] <= 1:
            continue

        # Find the best single foreign modulus.
        best_single = None

        for r in FOREIGN_MODULI:

            signatures = {
                product_fingerprint(
                    member,
                    (r,)
                )
                for member in result["members"]
            }

            unique = len(signatures)

            score = unique

            if (
                best_single is None
                or score > best_single[0]
            ):
                best_single = (
                    score,
                    r
                )

        rows.append(
            (
                result["class_size"],
                best_single[0],
                best_single[1],
                result
            )
        )

    rows.sort(
        key=lambda x: (
            -x[0],
            -x[1]
        )
    )

    shown = 0

    for class_size, unique, r, result in rows:

        if shown >= MAX_PRINT_CLASSES:
            break

        anchor = result["anchor"]

        print()
        print(
            f"C={result['anchor'][0] * result['anchor'][1] % M:,} "
            f"class_size={class_size} "
            f"anchor=({anchor[0]:,},{anchor[1]:,})"
        )

        print(
            f"best single modulus = {r}"
            f" -> {unique}/{class_size} unique"
        )

        for member in result["members"]:

            fp = product_fingerprint(
                member,
                FOREIGN_MODULI
            )

            first = result[
                "first_discriminating"
            ].get(member)

            marker = (
                "*"
                if member == anchor
                else " "
            )

            print(
                f" {marker} "
                f"({member[0]:,},{member[1]:,}) "
                f"first_r={first} "
                f"fp={fp}"
            )

        shown += 1

    print()


# ================================================================================================
# SANITY
# ================================================================================================

def sanity_check(results):

    c_failures = 0
    membership_failures = 0

    for result in results:

        anchor = result["anchor"]

        C = (
            anchor[0] * anchor[1]
        ) % M

        for member in result["members"]:

            if (
                member[0] * member[1] % M
                != C
            ):
                c_failures += 1

        if anchor not in result["members"]:

            membership_failures += 1

    print("=" * 100)
    print("SANITY CHECK")
    print("=" * 100)

    print(
        f"C identity failures      = {c_failures}"
    )

    print(
        f"anchor membership failures = "
        f"{membership_failures}"
    )

    print()


# ================================================================================================
# MAIN
# ================================================================================================

def main():

    print("=" * 100)
    print("FOREIGN-MODULUS FINGERPRINT / EXACT C-CLASS DISCRIMINATION")
    print("=" * 100)

    print(
        f"M                    = {M:,}"
    )

    print(
        f"factor range         = "
        f"{FACTOR_MIN:,} - {FACTOR_MAX:,}"
    )

    print(
        f"T range              = "
        f"[{T_MIN}, {T_MAX}]"
    )

    print(
        f"actual anchors       = {TRIALS}"
    )

    print(
        f"original moduli      = {ORIGINAL_MODULI}"
    )

    print(
        f"foreign moduli       = {FOREIGN_MODULI}"
    )

    print(
        f"factor primes        = "
        f"{len(FACTOR_PRIMES):,}"
    )

    print(
        f"seed                 = {SEED:,}"
    )

    print()

    rng = random.Random(SEED)

    # --------------------------------------------------------------------------------------------
    # Generate actual anchors
    # --------------------------------------------------------------------------------------------

    print("=" * 100)
    print("GENERATING ACTUAL ANCHORS")
    print("=" * 100)

    anchors = generate_unique_anchors(
        TRIALS,
        rng
    )

    print(
        f"anchors = {len(anchors)}"
    )

    print()

    # --------------------------------------------------------------------------------------------
    # Exact classes
    # --------------------------------------------------------------------------------------------

    print("=" * 100)
    print("BUILDING EXACT C-CLASSES")
    print("=" * 100)

    results = []

    for i, anchor in enumerate(
        anchors,
        start=1
    ):

        members = exact_c_class(
            *anchor
        )

        result = analyze_class(
            tuple(sorted(anchor)),
            members
        )

        results.append(result)

        if (
            i % 25 == 0
            or i == len(anchors)
        ):

            print(
                f"class {i:3d}/{len(anchors)}"
            )

    print()

    # --------------------------------------------------------------------------------------------
    # Sanity
    # --------------------------------------------------------------------------------------------

    sanity_check(results)

    # --------------------------------------------------------------------------------------------
    # Summaries
    # --------------------------------------------------------------------------------------------

    class_summary(results)

    global_modulus_statistics(
        anchors
    )

    minimum_k_summary(
        results
    )

    best_combinations(
        results
    )

    internal_collision_summary(
        results
    )

    first_modulus_distribution(
        results
    )

    shifted_collision_test(
        results
    )

    print_interesting_classes(
        results
    )

    # --------------------------------------------------------------------------------------------
    # Final interpretation
    # --------------------------------------------------------------------------------------------

    print("=" * 100)
    print("INTERPRETATION")
    print("=" * 100)

    print(
        """
The previous experiments established that the moduli

    3,5,7,11,13,17,19,23

are all divisors of M.

Consequently, if two prime pairs satisfy

    a*b == p*q (mod M),

then they necessarily have exactly the same residue under every
combination of those eight moduli.

This experiment changes only one thing:

    NEW primes which do NOT divide M.

For example:

    29,31,37,41,...

Now two members of the same C-class can have different fingerprints.

The direct product fingerprint is

    (a*b mod r1,
     a*b mod r2,
     ...)

and is exactly the multi-modulus version of the original

    n mod r

idea.

A class is "resolved" when all of its members have distinct
fingerprints.

Because the observed C-classes contain at most a few members, this
experiment can directly determine how many foreign moduli are needed
to identify every member within a class.

There are three possible outcomes.

1. ONE foreign modulus frequently resolves the class.

   Then even a single modulus outside M carries substantial
   discriminatory information.

2. TWO OR THREE foreign moduli are usually enough.

   Then the fingerprint idea works as a compact identifier of the
   finite C-class.

3. Some classes remain unresolved even with all foreign moduli.

   Then those classes possess genuine product-residue collisions
   extending across the larger modulus set.

The important distinction is:

    divisors of M
        test the same congruence information

whereas:

    primes not dividing M
        test independent residue information.

For the shifted relation

    a*b = p*q + 2*M*t,

a foreign modulus r gives

    a*b - p*q = 2*M*t (mod r).

Because r does not divide M, the right-hand side generally does NOT
vanish modulo r.

Therefore foreign moduli can actually see the shift.

That is exactly the direction required to return to the original
fingerprint hypothesis.

This experiment still does not establish a factoring algorithm.

It establishes something more basic first:

    whether a small collection of independent modular fingerprints
    can uniquely identify the relevant prime-pair state inside the
    exact M-congruence class.

"""
    )

    print("=" * 100)
    print("EXPERIMENT COMPLETE")
    print("=" * 100)


if __name__ == "__main__":
    main()
