#!/usr/bin/env python3

"""
========================================================================================================================
EXPERIMENT 460R2
========================================================================================================================

CORRECTED SYMBOLIC IDEAL / EXTENDED J-FIBRE DEPENDENCY AUDIT

PURPOSE

  Experiment 460 demonstrated the symbolic fibre ideal, but its
  failure counts mixed genuine zero identities with deliberately
  nonzero control expressions.

  Experiment 460R2 separates:

    1. TRUE IDEAL RELATIONS
       Polynomial relations that vanish identically on the fibre.

    2. NONZERO CONTROL EXPRESSIONS
       Polynomials intentionally expected NOT to belong to the ideal.

    3. EXTENDED j-RELATIONS
       Relations involving the explicit fibre parameter j.

  This gives a clean symbolic distinction between:

      "generated by the existing algebra"

  and

      "not an identity of the fibre."

CORE THREE-VARIABLE FIBRE IDEAL

    g1 = x + d0 - d

    g2 = 4K - r + 2*d*x - x^2

Equivalent eliminated form:

    g2' = 4K + d^2 - r - d0^2

EXPLICIT PARAMETERIZATION

    d0(j) = d0_ref + 2j
    x(j)  = x0 - 2j
    K(j)  = K_ref + d0_ref*j + j^2

EXTENDED IDEAL

Using j explicitly:

    h1 = d0 - d0_ref - 2j
    h2 = x - x0 + 2j
    h3 = K - K_ref - d0_ref*j - j^2

This ideal describes the same fibre together with its
chosen integer parameterization.

RULES

  exact symbolic arithmetic
  exact rational coefficients
  no factorization
  no giant enumeration
  no CRT Cartesian product
  hidden true values are diagnostics only
========================================================================================================================
"""

from __future__ import annotations

from dataclasses import dataclass
import sympy as sp


# ======================================================================================================================
# DATA
# ======================================================================================================================

@dataclass(frozen=True)
class Instance:
    idx: int
    N: int
    S: int
    d: int
    d0_true: int
    x_true: int
    K_true: int
    r: int


INSTANCES = [
    Instance(
        1, 14246098189, 333010, 14245432170,
        14245432180, -10,
        -3449849766661475506269,
        -13799399066930810668576,
    ),
    Instance(
        2, 10139117, 11022, 10117074,
        10117091, -17,
        -2968347695488785,
        -11873391125935945,
    ),
    Instance(
        3, 10009330297, 1010042, 10007310214,
        10007310238, -24,
        -4306289434216722346403,
        -17225157737347240276460,
    ),
    Instance(
        4, 100460333, 20046, 100420242,
        100420273, -31,
        -615138736337991015,
        -2460554951578020025,
    ),
    Instance(
        5, 2503701173, 100074, 2503501026,
        2503501064, -38,
        -557809093589551261113,
        -2231236374548471123872,
    ),
    Instance(
        6, 10006200817, 200062, 10005800694,
        10005800739, -45,
        -12714738365215418549091,
        -50858953461762196260849,
    ),
    Instance(
        7, 40005200153, 400026, 40004400102,
        40004400154, -52,
        -305667239831581101061223,
        -1222668959330484861858204,
    ),
    Instance(
        8, 270017400119, 1200024, 270015000072,
        270015000131, -59,
        -18737381797403407039327539,
        -74949527189645489927322133,
    ),
]


# ======================================================================================================================
# SYMBOLS
# ======================================================================================================================

x, d0, K, j = sp.symbols("x d0 K j")


# ======================================================================================================================
# REFERENCE DERIVATION
# ======================================================================================================================

def derive_reference(inst: Instance) -> tuple[int, int, int]:

    target = (inst.d * inst.d - inst.r) % 4

    valid_parities = [
        p for p in (0, 1)
        if (p * p) % 4 == target
    ]

    if len(valid_parities) != 1:
        raise AssertionError(
            f"unexpected d0 parity family: instance={inst.idx}, "
            f"valid={valid_parities}"
        )

    parity = valid_parities[0]

    candidates = []

    for x0 in (0, 1):
        d0_ref = inst.d - x0

        if d0_ref % 2 == parity:
            candidates.append((x0, d0_ref))

    if len(candidates) != 1:
        raise AssertionError(
            f"reference ambiguity: instance={inst.idx}, "
            f"candidates={candidates}"
        )

    x0, d0_ref = candidates[0]

    numerator = (
        inst.r
        + d0_ref * d0_ref
        - inst.d * inst.d
    )

    if numerator % 4 != 0:
        raise AssertionError(
            f"reference K not integral: instance={inst.idx}"
        )

    K_ref = numerator // 4

    return x0, d0_ref, K_ref


# ======================================================================================================================
# IDEALS
# ======================================================================================================================

def three_variable_generators(inst: Instance):
    d = sp.Integer(inst.d)
    r = sp.Integer(inst.r)

    g1 = x + d0 - d

    g2 = (
        4 * K
        - r
        + 2 * d * x
        - x**2
    )

    return g1, g2


def extended_generators(inst: Instance):

    x0, d0_ref, K_ref = derive_reference(inst)

    h1 = (
        d0
        - sp.Integer(d0_ref)
        - 2 * j
    )

    h2 = (
        x
        - sp.Integer(x0)
        + 2 * j
    )

    h3 = (
        K
        - sp.Integer(K_ref)
        - sp.Integer(d0_ref) * j
        - j**2
    )

    return h1, h2, h3


def three_variable_basis(inst: Instance):

    g1, g2 = three_variable_generators(inst)

    return sp.groebner(
        [g1, g2],
        K,
        d0,
        x,
        order="lex",
        domain=sp.QQ,
    )


def extended_basis(inst: Instance):

    h1, h2, h3 = extended_generators(inst)

    return sp.groebner(
        [h1, h2, h3],
        K,
        d0,
        x,
        j,
        order="lex",
        domain=sp.QQ,
    )


# ======================================================================================================================
# TRUE IDEAL RELATIONS
# ======================================================================================================================

def true_relations(inst: Instance):

    d = sp.Integer(inst.d)
    r = sp.Integer(inst.r)
    N = sp.Integer(inst.N)
    S = sp.Integer(inst.S)

    return [
        (
            "N-2S+1-d",
            N - 2 * S + 1 - d,
        ),

        (
            "x+d0-d",
            x + d0 - d,
        ),

        (
            "4K-r+2dx-x^2",
            4 * K
            - r
            + 2 * d * x
            - x**2,
        ),

        (
            "4K+d^2-r-d0^2",
            4 * K
            + d**2
            - r
            - d0**2,
        ),

        (
            "(x+d0)^2-d^2",
            (x + d0)**2 - d**2,
        ),

        (
            "4K+d^2-r-(x+d0)^2 + 4K-r correction",
            (
                4 * K
                + d**2
                - r
                - (x + d0)**2
                - (4 * K - r)
            ),
        ),

        (
            "x^2-2dx+d^2-d0^2",
            x**2
            - 2 * d * x
            + d**2
            - d0**2,
        ),

        (
            "4K+d^2-r-(r+d0^2-r)",
            (
                4 * K
                + d**2
                - r
                - d0**2
            ),
        ),
    ]


# ======================================================================================================================
# CONTROL EXPRESSIONS
#
# These were failures in Experiment 460, and SHOULD remain nonzero.
# Their non-membership is a result, not an experiment failure.
# ======================================================================================================================

def control_relations(inst: Instance):

    d = sp.Integer(inst.d)
    r = sp.Integer(inst.r)

    return [
        (
            "CONTROL: 4K+d^2-r-(x+d0)^2",
            4 * K
            + d**2
            - r
            - (x + d0)**2,
        ),

        (
            "CONTROL: 4K-r+x^2-2dx",
            4 * K
            - r
            + x**2
            - 2 * d * x,
        ),
    ]


# ======================================================================================================================
# EXTENDED j-RELATIONS
# ======================================================================================================================

def extended_relations(inst: Instance):

    x0, d0_ref, K_ref = derive_reference(inst)

    return [
        (
            "d0-d0_ref-2j",
            d0
            - sp.Integer(d0_ref)
            - 2 * j,
        ),

        (
            "x-x0+2j",
            x
            - sp.Integer(x0)
            + 2 * j,
        ),

        (
            "K-K_ref-d0_ref*j-j^2",
            K
            - sp.Integer(K_ref)
            - sp.Integer(d0_ref) * j
            - j**2,
        ),

        (
            "d0+x-d",
            d0 + x - sp.Integer(inst.d),
        ),

        (
            "4K-r+2dx-x^2",
            (
                4 * K
                - sp.Integer(inst.r)
                + 2 * sp.Integer(inst.d) * x
                - x**2
            ),
        ),

        (
            "x0+d0_ref-d",
            sp.Integer(x0 + d0_ref - inst.d),
        ),
    ]


# ======================================================================================================================
# FIBRE SUBSTITUTION
# ======================================================================================================================

def fibre_substitute(inst: Instance, expr: sp.Expr):

    x0, d0_ref, K_ref = derive_reference(inst)

    substitutions = {
        d0: sp.Integer(d0_ref) + 2 * j,
        x: sp.Integer(x0) - 2 * j,
        K: (
            sp.Integer(K_ref)
            + sp.Integer(d0_ref) * j
            + j**2
        ),
    }

    return sp.expand(expr.subs(substitutions))


# ======================================================================================================================
# MAIN
# ======================================================================================================================

def main():

    print("=" * 120)
    print("EXPERIMENT 460R2")
    print("=" * 120)
    print()
    print("CORRECTED SYMBOLIC IDEAL / EXTENDED J-FIBRE DEPENDENCY AUDIT")
    print()

    true_relation_failures = 0
    control_unexpected_membership = 0
    extended_failures = 0

    true_relation_count = 0
    control_count = 0
    extended_count = 0

    for inst in INSTANCES:

        print("-" * 120)

        x0, d0_ref, K_ref = derive_reference(inst)

        print(
            f"INSTANCE {inst.idx}: "
            f"N={inst.N} "
            f"S={inst.S} "
            f"d={inst.d} "
            f"r={inst.r}"
        )
        print()

        print("KNOWN-DATA REFERENCE")
        print(f"  x0     = {x0}")
        print(f"  d0_ref = {d0_ref}")
        print(f"  K_ref  = {K_ref}")
        print()

        print("POST-HOC DIAGNOSTIC")
        print(f"  true d0 = {inst.d0_true}")
        print(f"  true x  = {inst.x_true}")
        print(f"  true K  = {inst.K_true}")

        true_j = (
            (inst.d0_true - d0_ref) // 2
            if (inst.d0_true - d0_ref) % 2 == 0
            else None
        )

        print(f"  true j  = {true_j}")
        print()

        # --------------------------------------------------------------------------------------------------------------
        # THREE-VARIABLE IDEAL
        # --------------------------------------------------------------------------------------------------------------

        basis3 = three_variable_basis(inst)

        print("THREE-VARIABLE IDEAL")

        for generator in three_variable_generators(inst):
            print(f"  {generator}")

        print()

        print("THREE-VARIABLE GROEBNER BASIS")

        for poly in basis3.polys:
            print(f"  {poly.as_expr()}")

        print()

        # --------------------------------------------------------------------------------------------------------------
        # TRUE RELATIONS
        # --------------------------------------------------------------------------------------------------------------

        print("TRUE IDEAL RELATION AUDIT")

        print(
            "  relation"
            + " " * 40
            + "remainder"
            + " " * 28
            + "member"
            + "   fibre-zero"
        )

        print("  " + "-" * 110)

        for name, expr in true_relations(inst):

            true_relation_count += 1

            remainder = sp.expand(
                basis3.reduce(expr)[1]
            )

            member = remainder == 0

            fibre_value = fibre_substitute(inst, expr)

            fibre_zero = sp.expand(fibre_value) == 0

            if not member or not fibre_zero:
                true_relation_failures += 1

            print(
                f"  {name:<45}"
                f"{str(remainder):<35}"
                f"{str(member):>8}"
                f"   {fibre_zero}"
            )

        print()

        # --------------------------------------------------------------------------------------------------------------
        # NONZERO CONTROLS
        # --------------------------------------------------------------------------------------------------------------

        print("NONZERO CONTROL AUDIT")

        print(
            "  expression"
            + " " * 34
            + "remainder"
            + " " * 28
            + "member"
            + "   fibre-zero"
        )

        print("  " + "-" * 110)

        for name, expr in control_relations(inst):

            control_count += 1

            remainder = sp.expand(
                basis3.reduce(expr)[1]
            )

            member = remainder == 0

            fibre_value = fibre_substitute(inst, expr)

            fibre_zero = sp.expand(fibre_value) == 0

            # These are controls. Non-membership/nonzero is EXPECTED.
            if member or fibre_zero:
                control_unexpected_membership += 1

            print(
                f"  {name:<45}"
                f"{str(remainder):<35}"
                f"{str(member):>8}"
                f"   {fibre_zero}"
            )

        print()

        # --------------------------------------------------------------------------------------------------------------
        # EXTENDED j IDEAL
        # --------------------------------------------------------------------------------------------------------------

        basis4 = extended_basis(inst)

        print("EXTENDED j-FIBRE IDEAL")

        for generator in extended_generators(inst):
            print(f"  {generator}")

        print()

        print("EXTENDED j-RELATION AUDIT")

        print(
            "  relation"
            + " " * 38
            + "remainder"
            + " " * 28
            + "member"
        )

        print("  " + "-" * 100)

        for name, expr in extended_relations(inst):

            extended_count += 1

            remainder = sp.expand(
                basis4.reduce(expr)[1]
            )

            member = remainder == 0

            if not member:
                extended_failures += 1

            print(
                f"  {name:<45}"
                f"{str(remainder):<35}"
                f"{str(member):>8}"
            )

        print()

        # --------------------------------------------------------------------------------------------------------------
        # ELIMINATION CHECK
        # --------------------------------------------------------------------------------------------------------------

        d = sp.Integer(inst.d)
        r = sp.Integer(inst.r)

        eliminated = sp.expand(
            (
                4 * K
                + d**2
                - r
                - d0**2
            )
        )

        remainder = sp.expand(
            basis3.reduce(eliminated)[1]
        )

        print("ELIMINATION CHECK")

        print(
            "  4K+d^2-r-d0^2"
        )
        print(
            f"    Groebner remainder = {remainder}"
        )
        print(
            f"    generated by fibre ideal = {remainder == 0}"
        )

        # --------------------------------------------------------------------------------------------------------------
        # PARAMETERIZATION
        # --------------------------------------------------------------------------------------------------------------

        parameter_d0 = (
            sp.Integer(d0_ref)
            + 2 * j
        )

        parameter_x = (
            sp.Integer(x0)
            - 2 * j
        )

        parameter_K = (
            sp.Integer(K_ref)
            + sp.Integer(d0_ref) * j
            + j**2
        )

        print()
        print("EXPLICIT PARAMETERIZATION")

        print(f"  d0(j) = {parameter_d0}")
        print(f"  x(j)  = {parameter_x}")
        print(f"  K(j)  = {parameter_K}")

        check_g1 = sp.expand(
            parameter_x
            + parameter_d0
            - d
        )

        check_g2 = sp.expand(
            4 * parameter_K
            - r
            + 2 * d * parameter_x
            - parameter_x**2
        )

        print(
            f"  g1(j) = {check_g1}"
        )

        print(
            f"  g2(j) = {check_g2}"
        )

        if check_g1 != 0 or check_g2 != 0:
            extended_failures += 1

        # --------------------------------------------------------------------------------------------------------------
        # TRUE BRANCH
        # --------------------------------------------------------------------------------------------------------------

        print()
        print("TRUE BRANCH POST-HOC")

        if true_j is None:

            print(
                "  parity-compatible true branch = False"
            )

        else:

            d0_check = sp.expand(
                parameter_d0.subs(j, true_j)
            )

            x_check = sp.expand(
                parameter_x.subs(j, true_j)
            )

            K_check = sp.expand(
                parameter_K.subs(j, true_j)
            )

            print(f"  true j                  = {true_j}")
            print(
                "  exact d0 reconstruction = "
                f"{d0_check == inst.d0_true}"
            )
            print(
                "  exact x reconstruction  = "
                f"{x_check == inst.x_true}"
            )
            print(
                "  exact K reconstruction  = "
                f"{K_check == inst.K_true}"
            )

        print()

    # ==================================================================================================================
    # GLOBAL SUMMARY
    # ==================================================================================================================

    print("=" * 120)
    print("GLOBAL EXPERIMENT 460R2 SUMMARY")
    print("=" * 120)
    print()

    print(
        f"  instances                       = {len(INSTANCES)}"
    )
    print(
        f"  true ideal relations             = {true_relation_count}"
    )
    print(
        f"  true relation failures           = {true_relation_failures}"
    )
    print(
        f"  nonzero controls                 = {control_count}"
    )
    print(
        f"  unexpected control memberships   = "
        f"{control_unexpected_membership}"
    )
    print(
        f"  extended relation tests          = {extended_count}"
    )
    print(
        f"  extended relation failures       = "
        f"{extended_failures}"
    )
    print()

    clean = (
        true_relation_failures == 0
        and control_unexpected_membership == 0
        and extended_failures == 0
    )

    print("EXPECTED INTERPRETATION")
    print()
    print(
        "  TRUE RELATIONS:"
    )
    print(
        "    Every genuine fibre identity should have"
    )
    print(
        "    Groebner remainder 0."
    )
    print()
    print(
        "  CONTROL EXPRESSIONS:"
    )
    print(
        "    A nonzero remainder is expected and is not"
    )
    print(
        "    counted as an experiment failure."
    )
    print()
    print(
        "  EXTENDED j-RELATIONS:"
    )
    print(
        "    The explicit parameterization should itself"
    )
    print(
        "    reduce to zero in the extended ideal."
    )
    print()

    print("CENTRAL RESULT")
    print()
    print(
        "  The three-variable fibre ideal is"
    )
    print()
    print(
        "      < x+d0-d,"
    )
    print(
        "        4K-r+2dx-x^2 >."
    )
    print()
    print(
        "  Eliminating x gives"
    )
    print()
    print(
        "      4K+d^2-r-d0^2 = 0."
    )
    print()
    print(
        "  This is therefore not an additional independent"
    )
    print(
        "  equation; it is generated by the existing ideal."
    )
    print()

    print("INFORMATION-SEPARATION TEST")
    print()
    print(
        "  A relation that varies with j is not automatically"
    )
    print(
        "  an independent observable."
    )
    print()
    print(
        "  A relation that is not in the ideal and is also"
    )
    print(
        "  zero on the actual data would be interesting."
    )
    print()
    print(
        "  The current controls are deliberately NOT zero,"
    )
    print(
        "  so their non-membership is expected."
    )
    print()

    print("=" * 120)
    print("EXPERIMENT 460R2 FINAL STATUS")
    print("=" * 120)

    print(
        f"  TRUE IDEAL RELATIONS CLEAN   = "
        f"{true_relation_failures == 0}"
    )
    print(
        f"  CONTROLS BEHAVE AS EXPECTED  = "
        f"{control_unexpected_membership == 0}"
    )
    print(
        f"  EXTENDED j IDEAL CLEAN       = "
        f"{extended_failures == 0}"
    )
    print(
        f"  OVERALL SYMBOLIC AUDIT       = {clean}"
    )
    print(
        "  GIANT K ENUMERATION          = False"
    )
    print(
        "  GIANT d0 ENUMERATION         = False"
    )
    print(
        "  CRT CARTESIAN PRODUCT        = False"
    )
    print(
        "  INTEGER-EXACT                = True"
    )
    print(
        "  SYMBOLIC GROEBNER BASIS      = True"
    )
    print()
    print(
        "  CONCLUSION:"
    )
    print(
        "    Genuine zero identities are separated from"
    )
    print(
        "    nonzero controls, and the explicit j-parameter"
    )
    print(
        "    is audited as an extended symbolic ideal."
    )
    print("=" * 120)
    print("EXPERIMENT 460R2 FINISHED")
    print("=" * 120)


if __name__ == "__main__":
    main()
