#!/usr/bin/env python3

"""
==============================================================================
EXPERIMENT 238 — EXACT ORBIT-MEMBERSHIP CRITERION / DISCRETE-LOG CHART AUDIT
==============================================================================

Experiment 237 separated primes into:

    admissible:
        rho = 2*3^k (mod ell)

    inadmissible:
        no such k exists.

Experiment 238 replaces the exponent search by the subgroup criterion.

For ell not dividing 6*q3, define

    rho = q1/q3 (mod ell),

    x = rho/2 (mod ell),

    d = ord_ell(3).

Since <3> is the unique cyclic subgroup generated by 3 of order d,

    x in <3>

iff

    x^d = 1 (mod ell).

Thus the orbit chart exists exactly when

    (rho/2)^d = 1 (mod ell).

The experiment verifies, for every prime ell <= PRIME_LIMIT:

    * search-based admissibility;
    * subgroup-power admissibility;
    * exact agreement;
    * uniqueness of k0 modulo d for admissible primes;
    * exact reconstruction 2*3^k0 = rho mod ell.

It also records the first discrete-log coordinate

    k0 = log_3(rho/2) mod d

for every admissible prime.

Only main.py is used.
"""

from __future__ import annotations

import sys
from math import gcd


# ============================================================================
# SOURCE
# ============================================================================

Q1 = 29144191
Q3 = 24794967

PRIME_LIMIT = 200


# ============================================================================
# HELPERS
# ============================================================================

def is_prime(
    n: int,
) -> bool:

    n = int(n)

    if n < 2:
        return False

    if n == 2:
        return True

    if n % 2 == 0:
        return False

    d = 3

    while d * d <= n:

        if n % d == 0:
            return False

        d += 2

    return True


def multiplicative_order(
    base: int,
    modulus: int,
) -> int:

    if gcd(
        base,
        modulus,
    ) != 1:
        raise ArithmeticError(
            f"{base} is not invertible modulo {modulus}."
        )

    current = 1

    for e in range(
        1,
        modulus + 1,
    ):

        current = (
            current * base
        ) % modulus

        if current == 1:
            return int(e)

    raise ArithmeticError(
        f"Could not determine order of {base} modulo {modulus}."
    )


def ratio_mod(
    modulus: int,
) -> int | None:

    modulus = int(modulus)

    if gcd(
        Q3,
        modulus,
    ) != 1:
        return None

    return int(
        (
            (Q1 % modulus)
            * pow(
                Q3 % modulus,
                -1,
                modulus,
            )
        )
        % modulus
    )


def orbit_mod(
    k: int,
    modulus: int,
) -> int:

    return int(
        (
            2
            * pow(
                3,
                int(k),
                int(modulus),
            )
        )
        % modulus
    )


# ============================================================================
# MAIN
# ============================================================================

def main():

    print("=" * 78)
    print(
        "EXPERIMENT 238 — EXACT ORBIT-MEMBERSHIP CRITERION / "
        "DISCRETE-LOG CHART AUDIT"
    )
    print("=" * 78)

    primes = [
        p
        for p in range(
            2,
            PRIME_LIMIT + 1,
        )
        if is_prime(p)
    ]

    skipped = []
    admissible = []
    inadmissible = []
    failures = []

    print()
    print("=" * 78)
    print("1. SOURCE DATA")
    print("=" * 78)

    print(
        f"  q1={Q1}"
    )

    print(
        f"  q3={Q3}"
    )

    print(
        f"  gcd(q1,q3)={gcd(Q1,Q3)}"
    )

    print(
        f"  prime_limit={PRIME_LIMIT}"
    )

    # ------------------------------------------------------------------
    # 2. PRIME-BY-PRIME CRITERION
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("2. SEARCH VS SUBGROUP-MEMBERSHIP CRITERION")
    print("=" * 78)

    for ell in primes:

        # We need 2, 3, q3 to be units.
        if ell in (
            2,
            3,
        ):

            skipped.append(
                (
                    ell,
                    "ell_divides_6",
                )
            )

            continue

        if Q3 % ell == 0:

            skipped.append(
                (
                    ell,
                    "ell_divides_q3",
                )
            )

            continue

        rho = ratio_mod(
            ell
        )

        if rho is None:

            skipped.append(
                (
                    ell,
                    "ratio_undefined",
                )
            )

            continue

        inv2 = pow(
            2,
            -1,
            ell,
        )

        x = int(
            rho
            * inv2
            % ell
        )

        d = multiplicative_order(
            3,
            ell,
        )

        # Search criterion.
        search_matches = [
            k
            for k in range(d)
            if orbit_mod(
                k,
                ell,
            ) == rho
        ]

        search_admissible = (
            len(search_matches) == 1
        )

        # Algebraic subgroup criterion.
        power_test_value = pow(
            x,
            d,
            ell,
        )

        subgroup_admissible = (
            power_test_value == 1
        )

        criterion_agrees = (
            search_admissible
            == subgroup_admissible
        )

        if not criterion_agrees:

            failures.append(
                (
                    ell,
                    "criterion_mismatch",
                    search_matches,
                    power_test_value,
                )
            )

        if subgroup_admissible:

            k0 = search_matches[0]

            reconstruction = (
                orbit_mod(
                    k0,
                    ell,
                )
                == rho
            )

            unique_coordinate = (
                len(search_matches) == 1
            )

            admissible.append(
                (
                    ell,
                    rho,
                    x,
                    d,
                    power_test_value,
                    k0,
                )
            )

            print(
                f"  ell={ell}: "
                f"ADMISSIBLE "
                f"rho={rho} "
                f"x=rho/2={x} "
                f"ord={d} "
                f"x^d mod ell={power_test_value} "
                f"k0={k0} "
                f"unique={unique_coordinate} "
                f"reconstructs={reconstruction}"
            )

            if not reconstruction:
                failures.append(
                    (
                        ell,
                        "reconstruction_failure",
                    )
                )

            if not unique_coordinate:
                failures.append(
                    (
                        ell,
                        "nonunique_discrete_log",
                    )
                )

        else:

            inadmissible.append(
                (
                    ell,
                    rho,
                    x,
                    d,
                    power_test_value,
                )
            )

            print(
                f"  ell={ell}: "
                f"INADMISSIBLE "
                f"rho={rho} "
                f"x=rho/2={x} "
                f"ord={d} "
                f"x^d mod ell={power_test_value}"
            )

    # ------------------------------------------------------------------
    # 3. ADMISSIBLE / INADMISSIBLE COUNTS
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("3. COUNTS")
    print("=" * 78)

    print(
        f"  primes_seen={len(primes)}"
    )

    print(
        f"  skipped={len(skipped)}"
    )

    print(
        f"  admissible={len(admissible)}"
    )

    print(
        f"  inadmissible={len(inadmissible)}"
    )

    print(
        f"  failures={len(failures)}"
    )

    # ------------------------------------------------------------------
    # 4. DISCRETE-LOG COORDINATE TABLE
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("4. PRINCIPAL DISCRETE-LOG COORDINATES")
    print("=" * 78)

    for (
        ell,
        rho,
        x,
        d,
        power_test,
        k0,
    ) in admissible:

        print(
            f"  ell={ell}: "
            f"x={x} "
            f"k0={k0} "
            f"modulus={d} "
            f"x=3^k0="
            f"{pow(3,k0,ell)}"
        )

    # ------------------------------------------------------------------
    # 5. INADMISSIBILITY WITNESS
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("5. INADMISSIBILITY WITNESSES")
    print("=" * 78)

    for (
        ell,
        rho,
        x,
        d,
        power_test,
    ) in inadmissible:

        print(
            f"  ell={ell}: "
            f"x={x} "
            f"ord={d} "
            f"x^d mod ell={power_test} "
            f"outside_subgroup=True"
        )

    # ------------------------------------------------------------------
    # 6. CONNECTION TO LOCAL HENSEL CHART
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("6. CHART EXISTENCE CONSEQUENCE")
    print("=" * 78)

    chart_failures = []

    for (
        ell,
        rho,
        x,
        d,
        power_test,
        k0,
    ) in admissible:

        modulus2 = int(
            ell * ell
        )

        rho2 = ratio_mod(
            modulus2
        )

        # The first Hensel chart step has exactly ell possible lifts:
        # k0 + t*d.
        lift_matches = [
            (
                t,
                k0 + t * d,
            )
            for t in range(
                ell
            )
            if orbit_mod(
                k0 + t * d,
                modulus2,
            )
            == rho2
        ]

        unique_lift = (
            len(lift_matches) == 1
        )

        print(
            f"  ell={ell}: "
            f"k0={k0} "
            f"lift_matches={lift_matches} "
            f"unique_lift={unique_lift}"
        )

        if not unique_lift:

            chart_failures.append(
                (
                    ell,
                    lift_matches,
                )
            )

    # ------------------------------------------------------------------
    # 7. STRUCTURAL INTERPRETATION
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("7. STRUCTURAL INTERPRETATION")
    print("=" * 78)

    print(
        """
Experiment 237 treated orbit admissibility as an empirical search:

    2*3^k = rho (mod ell).

Experiment 238 gives an algebraic criterion.

Write

    x = rho/2 mod ell,

and

    d = ord_ell(3).

Then

    rho = 2*3^k mod ell

is equivalent to

    x = 3^k mod ell.

Since <3> has exactly d elements,

    x in <3>

iff

    x^d = 1 mod ell.

Thus the local exponent chart exists precisely when

    (rho/2)^d = 1 mod ell.

Once the chart exists, the exponent k0 is unique modulo d because
3 has order d.

The experiment then checks that the resulting chart can actually be
lifted one prime-power level.

This separates two statements:

    chart existence:
        subgroup membership;

    chart lifting:
        affine Hensel recovery.

Together they give a clean local theorem template.
"""
    )

    # ------------------------------------------------------------------
    # 8. FINAL
    # ------------------------------------------------------------------

    final_ok = (
        len(failures) == 0
        and
        len(chart_failures) == 0
        and
        len(admissible) > 0
    )

    print()
    print("=" * 78)
    print("8. FINAL EXACTNESS")
    print("=" * 78)

    print(
        f"  subgroup_criterion_matches_search="
        f"{len(failures) == 0}"
    )

    print(
        f"  all_admissible_discrete_logs_unique="
        f"{len(failures) == 0}"
    )

    print(
        f"  all_admissible_first_lifts_unique="
        f"{len(chart_failures) == 0}"
    )

    print(
        f"  admissible_count="
        f"{len(admissible)}"
    )

    print(
        f"  inadmissible_count="
        f"{len(inadmissible)}"
    )

    print(
        f"  failures={len(failures) + len(chart_failures)}"
    )

    print(
        "  general_n_pq_theorem_established=False"
    )

    print(
        "  reason=single_known_n6_instance"
    )

    print(
        f"  ALL BASIC CHECKS PASS={final_ok}"
    )

    print()
    print("EXPERIMENT 238 COMPLETE")


if __name__ == "__main__":

    try:
        main()

    except KeyboardInterrupt:

        print(
            "\nInterrupted."
        )

        sys.exit(130)

    except Exception as exc:

        print(
            "\nFATAL ERROR: "
            + type(exc).__name__
            + ": "
            + str(exc)
        )

        raise

