#!/usr/bin/env python3
"""
==============================================================================
EXPERIMENT 159 — EXACT NORMALIZED-ADJUGATE ROW / p-ADIC LEFT-KERNEL AUDIT
==============================================================================

Experiment 158 ruled out simple low-degree column laws for the six
primitive minimal-cofactor entries.

The next experiment uses the defining algebraic identity of the
cofactor matrix.

Let A be the exact 12x12 F-core and C=adj(A). Then

    C A = det(A) I.

Let

    R = C / Delta_11

with

    d12 = det(A) / Delta_11.

Therefore exactly

    R A = d12 I.

For the distinguished row i=5,

    R_5 A = d12 e_5^T.

Known arithmetic:

    v2(Delta_11) = 24
    v2(det(A))  = 33
    v2(d12)     = 9.

Hence the entire normalized cofactor row should behave as a
2-adic left-kernel vector modulo 2^9, except for the distinguished
identity coordinate.

This experiment checks that statement directly.

It then determines:

    1. exact R*A;
    2. exact distinguished-row residual;
    3. maximum e for which R_5 A = 0 mod 2^e;
    4. maximum e for which the non-distinguished coordinates vanish;
    5. the valuation profile of every component of R_5 A;
    6. whether the same phenomenon occurs for other rows of R;
    7. the mod-2 left-kernel subspace generated by the surviving
       cofactor rows;
    8. whether the six-entry minimal cofactor support is simply the
       mod-2 support of a lifted left-kernel vector.

This is an exact adjugate identity audit, not a fitted recurrence.

No SymPy.
No floating point.
No extrapolation.
No connection to the original (p,q)-kernel is asserted.
"""

from __future__ import annotations

from fractions import Fraction
import sys


# ============================================================================
# EXACT INPUT DATA
# ============================================================================

Q = {
    1: [
        -126258696,
        -11600759760,
        2668721436,
        1764373740,
        -1338089411,
        495451247,
    ],
    3: [
        9955176,
        -1263551016,
        -152369292,
        -128667196,
        421514439,
    ],
    5: [
        -62398,
        4771718,
        16027881,
    ],
    7: [
        1,
    ],
}

D = {
    1: 5,
    3: 4,
    5: 2,
    7: 0,
}

TRANSITIONS = [
    (1, 3),
    (3, 5),
    (5, 7),
]

DELTA_11 = 9512681472

N = 12
DISTINGUISHED_ROW = 5


# ============================================================================
# BASIC HELPERS
# ============================================================================

def q_value(p: int, r: int) -> int:
    if r < 0 or r >= len(Q[p]):
        return 0
    return Q[p][r]


def basis(p: int, d: int):
    return [
        1,
        d,
        d * d,
        p,
        p * d,
        p * p,
    ]


def valuation(n: int, p: int):
    n = abs(int(n))

    if n == 0:
        return float("inf")

    v = 0

    while n % p == 0:
        n //= p
        v += 1

    return v


# ============================================================================
# EXACT BAREISS
# ============================================================================

def bareiss_det(A):

    if not A:
        return 1

    M = [[int(x) for x in row] for row in A]
    n = len(M)

    if n == 1:
        return M[0][0]

    previous = 1
    sign = 1

    for k in range(n - 1):

        pivot_row = None

        for r in range(k, n):
            if M[r][k] != 0:
                pivot_row = r
                break

        if pivot_row is None:
            return 0

        if pivot_row != k:
            M[k], M[pivot_row] = M[pivot_row], M[k]
            sign *= -1

        pivot = M[k][k]

        for i in range(k + 1, n):

            for j in range(k + 1, n):

                value = (
                    M[i][j] * pivot
                    - M[i][k] * M[k][j]
                )

                if k > 0:

                    if value % previous != 0:
                        raise ArithmeticError(
                            "Bareiss exact division failed."
                        )

                    value //= previous

                M[i][j] = value

        for i in range(k + 1, n):
            M[i][k] = 0

        previous = pivot

    return sign * M[-1][-1]


# ============================================================================
# FULL SYSTEM
# ============================================================================

def build_system():

    M = []

    for p, pnext in TRANSITIONS:

        for r in range(D[p] + 1):

            d = D[p] - r

            q0 = q_value(p, r)
            q1 = q_value(p, r + 1)

            b = basis(p, d)

            row = [0] * 14

            for j in range(6):
                row[j] = b[j] * q0

            for j in range(6):
                row[6 + j] = b[j] * q1

            if d == 0:
                row[12] = 1
                row[13] = p

            M.append(row)

    return M


# ============================================================================
# F-CORE
# ============================================================================

def build_core(M):

    b0 = M[5]
    b1 = M[10]

    H = [
        [b0[12], b0[13]],
        [b1[12], b1[13]],
    ]

    det_h = (
        H[0][0] * H[1][1]
        - H[0][1] * H[1][0]
    )

    if det_h == 0:
        raise ArithmeticError("Boundary block singular.")

    H_inv = [
        [
            Fraction(H[1][1], det_h),
            Fraction(-H[0][1], det_h),
        ],
        [
            Fraction(-H[1][0], det_h),
            Fraction(H[0][0], det_h),
        ],
    ]

    h_coeff = [
        [Fraction(0) for _ in range(12)]
        for _ in range(2)
    ]

    for i in range(2):

        for j in range(12):

            h_coeff[i][j] = -(
                H_inv[i][0] * b0[j]
                + H_inv[i][1] * b1[j]
            )

    core = []

    for idx in range(14):

        if idx in (5, 10):
            continue

        row = M[idx]

        out = []

        for j in range(12):

            value = (
                Fraction(row[j])
                + Fraction(row[12]) * h_coeff[0][j]
                + Fraction(row[13]) * h_coeff[1][j]
            )

            if value.denominator != 1:
                raise ArithmeticError(
                    "Non-integral F-core entry."
                )

            out.append(value.numerator)

        core.append(out)

    return core


# ============================================================================
# COFACTOR MATRIX
# ============================================================================

def maximal_minor(A, omit_row, omit_col):

    rows = [
        i
        for i in range(len(A))
        if i != omit_row
    ]

    cols = [
        j
        for j in range(len(A[0]))
        if j != omit_col
    ]

    return [
        [A[i][j] for j in cols]
        for i in rows
    ]


def cofactor_matrix(A):

    n = len(A)
    C = []

    for i in range(n):

        row = []

        for j in range(n):

            value = bareiss_det(
                maximal_minor(A, i, j)
            )

            if (i + j) & 1:
                value = -value

            row.append(value)

        C.append(row)

    return C


def normalized_matrix(C):

    R = []

    for row in C:

        out = []

        for value in row:

            if value % DELTA_11 != 0:
                raise ArithmeticError(
                    "Delta_11 does not divide cofactor."
                )

            out.append(
                value // DELTA_11
            )

        R.append(out)

    return R


# ============================================================================
# EXACT MATRIX PRODUCT
# ============================================================================

def matmul(A, B):

    rows = len(A)
    mid = len(B)
    cols = len(B[0])

    out = [
        [0 for _ in range(cols)]
        for _ in range(rows)
    ]

    for i in range(rows):

        for k in range(mid):

            aik = A[i][k]

            if aik == 0:
                continue

            for j in range(cols):
                out[i][j] += aik * B[k][j]

    return out


# ============================================================================
# MOD-2 RREF / RANK
# ============================================================================

def rref_mod2(A):

    M = [
        [int(x) & 1 for x in row]
        for row in A
    ]

    rows = len(M)
    cols = len(M[0])

    pivots = []
    pivot_row = 0

    for col in range(cols):

        pivot = None

        for r in range(pivot_row, rows):

            if M[r][col]:
                pivot = r
                break

        if pivot is None:
            continue

        M[pivot_row], M[pivot] = (
            M[pivot],
            M[pivot_row],
        )

        for r in range(rows):

            if r == pivot_row:
                continue

            if M[r][col]:

                for j in range(col, cols):
                    M[r][j] ^= M[pivot_row][j]

        pivots.append(col)
        pivot_row += 1

        if pivot_row == rows:
            break

    return M, pivots


def rank_mod2(A):
    _, pivots = rref_mod2(A)
    return len(pivots)


def row_space_basis_mod2(A):

    R, _ = rref_mod2(A)

    return [
        row
        for row in R
        if any(row)
    ]


# ============================================================================
# VECTOR REDUCTION
# ============================================================================

def row_mod2(row):

    return [
        int(x) & 1
        for x in row
    ]


def dot2(a, b):

    s = 0

    for x, y in zip(a, b):
        s ^= (
            (int(x) & 1)
            & (int(y) & 1)
        )

    return s


# ============================================================================
# MAIN
# ============================================================================

def main():

    print("=" * 78)
    print(
        "EXPERIMENT 159 — EXACT NORMALIZED-ADJUGATE ROW / "
        "p-ADIC LEFT-KERNEL AUDIT"
    )
    print("=" * 78)

    M = build_system()
    A = build_core(M)

    C = cofactor_matrix(A)
    R = normalized_matrix(C)

    det_A = bareiss_det(A)
    d12 = Fraction(
        det_A,
        DELTA_11,
    )

    RA = matmul(
        R,
        A,
    )

    # ------------------------------------------------------------------
    # 1. EXACT ADJUGATE IDENTITY
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("1. EXACT NORMALIZED ADJUGATE IDENTITY")
    print("=" * 78)

    print(
        f"  core_shape={len(A)}x{len(A[0])}"
    )

    print(
        f"  det_digits={len(str(abs(det_A)))}"
    )

    print(
        f"  Delta_11={DELTA_11}"
    )

    print(
        f"  d12={d12}"
    )

    expected = [
        [0 for _ in range(N)]
        for _ in range(N)
    ]

    for i in range(N):
        expected[i][i] = d12

    identity_exact = (
        RA == expected
    )

    print(
        f"  R*A=d12*I exact={identity_exact}"
    )

    # ------------------------------------------------------------------
    # 2. DISTINGUISHED ROW
    # ------------------------------------------------------------------

    r = R[DISTINGUISHED_ROW]
    residual = RA[DISTINGUISHED_ROW]

    print()
    print("=" * 78)
    print("2. DISTINGUISHED NORMALIZED COFACTOR ROW")
    print("=" * 78)

    print(
        f"  row_index={DISTINGUISHED_ROW}"
    )

    print(
        f"  R_row={r}"
    )

    print(
        f"  R_row*A={residual}"
    )

    # ------------------------------------------------------------------
    # 3. COMPONENT VALUATIONS
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("3. EXACT RESIDUAL 2-ADIC PROFILE")
    print("=" * 78)

    residual_v2 = [
        valuation(x, 2)
        for x in residual
    ]

    for j, (x, v) in enumerate(
        zip(residual, residual_v2)
    ):

        print(
            f"  column={j}: "
            f"value={x} "
            f"v2={v}"
        )

    finite_vals = [
        v
        for v in residual_v2
        if v != float("inf")
    ]

    print(
        f"  minimum_finite_v2={min(finite_vals)}"
    )

    print(
        f"  expected_terminal_v2={valuation(d12.numerator,2) - valuation(d12.denominator,2)}"
    )

    # ------------------------------------------------------------------
    # 4. KERNEL PRECISION
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("4. 2-ADIC LEFT-KERNEL PRECISION")
    print("=" * 78)

    non_distinguished = [
        residual[j]
        for j in range(N)
        if j != DISTINGUISHED_ROW
    ]

    min_non_dist_v2 = min(
        valuation(x, 2)
        for x in non_distinguished
    )

    print(
        f"  min_non_distinguished_v2={min_non_dist_v2}"
    )

    print(
        f"  distinguished_coordinate_v2="
        f"{valuation(residual[DISTINGUISHED_ROW],2)}"
    )

    for e in range(1, 12):

        non_dist_zero = all(
            x % (2 ** e) == 0
            for x in non_distinguished
        )

        full_zero = all(
            x % (2 ** e) == 0
            for x in residual
        )

        print(
            f"  modulus=2^{e}: "
            f"non_distinguished_zero={non_dist_zero} "
            f"full_row_annihilation={full_zero}"
        )

    # ------------------------------------------------------------------
    # 5. MOD-2 LEFT KERNEL
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("5. MOD-2 LEFT-KERNEL RELATION")
    print("=" * 78)

    r2 = row_mod2(r)
    A2 = [
        row_mod2(row)
        for row in A
    ]

    row_times_A_mod2 = [
        dot2(
            r2,
            [
                A[i][j]
                for i in range(N)
            ],
        )
        for j in range(N)
    ]

    print(
        f"  R_row_mod2={r2}"
    )

    print(
        f"  R_row*A mod2={row_times_A_mod2}"
    )

    print(
        f"  exact_left_null_mod2="
        f"{all(x == 0 for x in row_times_A_mod2)}"
    )

    # ------------------------------------------------------------------
    # 6. COFACTOR ROWS MOD 2
    # ------------------------------------------------------------------

    R2 = [
        row_mod2(row)
        for row in R
    ]

    active_rows = [
        i
        for i, row in enumerate(R2)
        if any(row)
    ]

    active_basis = row_space_basis_mod2(R2)

    print()
    print("=" * 78)
    print("6. MOD-2 COFACTOR ROW-SPACE")
    print("=" * 78)

    print(
        f"  active_cofactor_rows={active_rows}"
    )

    print(
        f"  cofactor_rowspace_rank={len(active_basis)}"
    )

    for i, row in enumerate(active_basis):
        print(
            f"  basis_{i}={row}"
        )

    # ------------------------------------------------------------------
    # 7. COMPARE WITH CORE LEFT NULLSPACE
    # ------------------------------------------------------------------

    left_null_basis = row_space_basis_mod2(
        [
            [
                A[j][i]
                for j in range(N)
            ]
            for i in range(N)
        ]
    )

    print()
    print("=" * 78)
    print("7. COFACTOR SPACE VS CORE LEFT NULLSPACE")
    print("=" * 78)

    print(
        f"  core_left_nullspace_dimension="
        f"{N - rank_mod2(A2)}"
    )

    print(
        f"  cofactor_rowspace_dimension="
        f"{len(active_basis)}"
    )

    for i, row in enumerate(active_basis):

        test_space = (
            left_null_basis + [row]
        )

        in_span = (
            rank_mod2(left_null_basis)
            == rank_mod2(test_space)
        )

        print(
            f"  cofactor_basis_{i}_in_left_nullspace="
            f"{in_span}"
        )

    # ------------------------------------------------------------------
    # 8. STRUCTURAL INTERPRETATION
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("8. STRUCTURAL INTERPRETATION")
    print("=" * 78)

    print(
        """
The defining cofactor identity gives an exact algebraic relation:

    C A = det(A) I.

After dividing by Delta_11,

    R A = d12 I.

This means the normalized cofactor rows are not arbitrary vectors.

For every row i,

    R_i A = d12 e_i^T.

Therefore every R_i is an exact left-kernel vector modulo any
power of 2 below v2(d12).

Since

    v2(d12)=9,

every normalized cofactor row satisfies

    R_i A = 0 (mod 2^9)

away from its own distinguished coordinate, and in fact the entire
row product vanishes modulo 2^9.

The mod-2 row space of R therefore sits naturally inside the
left nullspace of A mod 2.

This experiment checks that relationship directly rather than
inferring it from rank patterns.

The six-entry support discovered in Experiments 155-158 is therefore
being viewed as one coordinate representation of an exact lifted
left-kernel vector.

No claim is made that this explains the original kernel.
"""
    )

    # ------------------------------------------------------------------
    # 9. FINAL
    # ------------------------------------------------------------------

    final_ok = (
        identity_exact
        and len(A) == N
        and len(R) == N
        and min_non_dist_v2 >= 9
        and valuation(
            residual[DISTINGUISHED_ROW],
            2,
        ) >= 9
        and all(
            x % 2 == 0
            for x in residual
        )
    )

    print()
    print("=" * 78)
    print("9. FINAL EXACTNESS")
    print("=" * 78)

    print(
        f"  normalized_adjugate_identity_exact={identity_exact}"
    )

    print(
        f"  distinguished_row_left_kernel_mod2="
        f"{all(x == 0 for x in row_times_A_mod2)}"
    )

    print(
        f"  min_non_distinguished_v2={min_non_dist_v2}"
    )

    print(
        f"  terminal_v2={valuation(d12.numerator,2) - valuation(d12.denominator,2)}"
    )

    print(
        f"  p_adic_left_kernel_precision_exact="
        f"{min_non_dist_v2 >= 9}"
    )

    print(
        f"  failures={0 if final_ok else 1}"
    )

    print(
        f"  ALL BASIC CHECKS PASS={final_ok}"
    )

    print()
    print("EXPERIMENT 159 COMPLETE")


if __name__ == "__main__":

    try:
        main()

    except KeyboardInterrupt:
        print("\nInterrupted.")
        sys.exit(130)

    except Exception as exc:

        print(
            "\nFATAL ERROR: "
            + type(exc).__name__
            + ": "
            + str(exc)
        )

        raise

