#!/usr/bin/env python3
"""
==============================================================================
EXPERIMENT 218 — EXACT n=pq FAMILY / PROJECTIVE 7-ADIC INVARIANT AUDIT
==============================================================================

Purpose
-------

Move from the single observed source pair

    (q1,q3) = (29144191,24794967)

toward a genuine p,q family analysis.

IMPORTANT:

This script deliberately does NOT invent formulas for q1(p,q) or q3(p,q).
Those formulas must come from the actual n=pq construction.

For now, the experiment accepts exact source pairs labelled by (p,q) and
tests the structural statements that should hold once those source pairs
have been generated by the n=pq system:

    rho = q1/q3,

    k = k1 + 6m,

    unique 7-adic Hensel lift,

    local slope

        B = rho * ((729-1)/7) mod 7
          = 6*rho mod 7,

    logarithmic principal coordinate

        m = log(rho / (2*3^k1)) / log(729),

and invariance under common source scaling.

This is a pure main.py experiment.
It imports no other Python file.

To analyze actual n=pq instances, add exact source pairs to CASES below
using the output of the actual n=pq construction.
"""


from __future__ import annotations

from fractions import Fraction
from math import gcd
import sys


# ============================================================================
# USER-EDITABLE FAMILY DATA
# ============================================================================
#
# Replace/add entries here with exact (p,q,q1,q3) values generated by the
# actual n=pq construction.
#
# The first entry reproduces the current known case after the common factor
# 17 has been removed.
#
# Format:
#
#     (p, q, q1, q3)
#
# Do not put expressions requiring another Python module here.
# ============================================================================

CASES = [
    (2, 3, 29144191, 24794967),
]


# Precision of the 7-adic family audit.
END_E = 10

P7 = 7
PRINCIPAL_BASE = 729


# ============================================================================
# EXACT ARITHMETIC
# ============================================================================

def valuation_p(
    x: int,
    p: int,
) -> int | None:

    x = int(x)
    p = int(p)

    if x == 0:
        return None

    x = abs(x)
    v = 0

    while x % p == 0:
        x //= p
        v += 1

    return v


def inverse_mod(
    a: int,
    m: int,
) -> int:

    a = int(a)
    m = int(m)

    if m <= 1:
        return 0

    a %= m

    if a == 0:
        raise ArithmeticError(
            f"Cannot invert 0 modulo {m}."
        )

    old_r = a
    r = m
    old_s = 1
    s = 0

    while r:
        q = old_r // r

        old_r, r = (
            r,
            old_r - q * r,
        )

        old_s, s = (
            s,
            old_s - q * s,
        )

    if old_r != 1:
        raise ArithmeticError(
            f"{a} is not invertible modulo {m}."
        )

    return int(
        old_s % m
    )


def ratio_mod(
    q1: int,
    q3: int,
    modulus: int,
) -> int:

    return int(
        (
            int(q1)
            * inverse_mod(
                int(q3),
                int(modulus),
            )
        )
        % int(modulus)
    )


def orbit_mod(
    k: int,
    modulus: int,
) -> int:

    return int(
        (
            2
            * pow(
                3,
                int(k),
                int(modulus),
            )
        )
        % int(modulus)
    )


# ============================================================================
# BASE EXPONENT
# ============================================================================

def find_k1(
    q1: int,
    q3: int,
) -> int:

    rho = ratio_mod(
        q1,
        q3,
        7,
    )

    matches = []

    for k in range(6):

        if orbit_mod(
            k,
            7,
        ) == rho:

            matches.append(
                int(k)
            )

    if len(matches) != 1:
        raise ArithmeticError(
            "The source ratio is not giving a unique "
            f"mod-7 exponent class: rho={rho}, matches={matches}."
        )

    return int(
        matches[0]
    )


# ============================================================================
# GENERAL HENSEL LIFT
# ============================================================================

def lift_one_case(
    q1: int,
    q3: int,
    end_e: int,
):

    k1 = find_k1(
        q1,
        q3,
    )

    current_k = int(
        k1
    )

    exponents = [
        current_k
    ]

    digits = []
    slopes = []
    intercepts = []

    for e in range(
        1,
        end_e,
    ):

        modulus_e = int(
            P7 ** e
        )

        modulus_next = int(
            P7 ** (
                e + 1
            )
        )

        target = ratio_mod(
            q1,
            q3,
            modulus_next,
        )

        candidates = []

        residuals = []

        order = int(
            6
            * (
                P7 ** (
                    e - 1
                )
            )
        )

        for t in range(7):

            candidate_k = int(
                current_k
                + t * order
            )

            candidate_orbit = orbit_mod(
                candidate_k,
                modulus_next,
            )

            residual = int(
                (
                    candidate_orbit
                    - target
                )
                % modulus_next
            )

            if residual % modulus_e != 0:
                raise ArithmeticError(
                    f"Candidate does not descend from level {e}: "
                    f"k={candidate_k}."
                )

            digit = int(
                (
                    residual
                    // modulus_e
                )
                % P7
            )

            candidates.append(
                candidate_k
            )

            residuals.append(
                digit
            )

        A = int(
            residuals[0]
        )

        B = int(
            (
                residuals[1]
                - residuals[0]
            )
            % P7
        )

        affine = all(
            residuals[t]
            ==
            (
                A
                + B * t
            ) % P7
            for t in range(7)
        )

        matches = [
            t
            for t in range(7)
            if orbit_mod(
                candidates[t],
                modulus_next,
            ) == target
        ]

        if len(matches) != 1:
            raise ArithmeticError(
                f"Expected one lift at e={e}; "
                f"got {matches}."
            )

        chosen_t = int(
            matches[0]
        )

        next_k = int(
            candidates[
                chosen_t
            ]
        )

        if orbit_mod(
            next_k,
            modulus_next,
        ) != target:

            raise ArithmeticError(
                f"Chosen lift failed at e={e}."
            )

        digits.append(
            chosen_t
        )

        slopes.append(
            B
        )

        intercepts.append(
            A
        )

        exponents.append(
            next_k
        )

        current_k = int(
            next_k
        )

    rho7 = ratio_mod(
        q1,
        q3,
        7,
    )

    predicted_slope = int(
        (
            rho7
            * (
                (PRINCIPAL_BASE - 1)
                // P7
            )
        )
        % P7
    )

    slope_formula_exact = all(
        B == predicted_slope
        for B in slopes
    )

    return {
        "rho7": rho7,
        "k1": k1,
        "exponents": exponents,
        "digits": digits,
        "slopes": slopes,
        "intercepts": intercepts,
        "predicted_slope": predicted_slope,
        "slope_formula_exact": slope_formula_exact,
    }


# ============================================================================
# PRINCIPAL COORDINATE
# ============================================================================

def principal_coordinate(
    k: int,
    k1: int,
) -> int:

    k = int(k)
    k1 = int(k1)

    difference = k - k1

    if difference % 6 != 0:
        raise ArithmeticError(
            f"k={k} is not congruent to k1={k1} modulo 6."
        )

    return int(
        difference // 6
    )


# ============================================================================
# LOGARITHM
# ============================================================================

def fraction_valuation_7(
    x: Fraction,
) -> int | None:

    if x == 0:
        return None

    vn = valuation_p(
        x.numerator,
        7,
    )

    vd = valuation_p(
        x.denominator,
        7,
    )

    vn = 0 if vn is None else vn
    vd = 0 if vd is None else vd

    return vn - vd


def log_one_plus_x(
    x: Fraction,
    precision: int,
) -> Fraction:

    vx = fraction_valuation_7(
        x
    )

    if vx is None or vx <= 0:
        raise ArithmeticError(
            "7-adic log requires v7(x)>0."
        )

    total = Fraction(0)

    n = 1

    while True:

        term = (
            x ** n
        ) / n

        tv = fraction_valuation_7(
            term
        )

        sign = (
            1
            if n % 2 == 1
            else -1
        )

        total += (
            sign * term
        )

        if tv is not None and tv >= precision:

            safe = True

            for j in range(
                n + 1,
                n + 8,
            ):

                future = (
                    j * vx
                    - (
                        valuation_p(
                            j,
                            7,
                        )
                        or 0
                    )
                )

                if future < precision:
                    safe = False
                    break

            if safe:
                break

        n += 1

        if n > 4 * precision + 100:
            raise ArithmeticError(
                "7-adic logarithm truncation exceeded safe limit."
            )

    return total


def fraction_mod(
    x: Fraction,
    modulus: int,
) -> int:

    modulus = int(modulus)

    if x.denominator % 7 == 0:
        raise ArithmeticError(
            "Cannot reduce rational with 7-divisible denominator."
        )

    return int(
        (
            (x.numerator % modulus)
            * inverse_mod(
                x.denominator % modulus,
                modulus,
            )
        )
        % modulus
    )


# ============================================================================
# SINGLE CASE AUDIT
# ============================================================================

def audit_case(
    p: int,
    q: int,
    q1: int,
    q3: int,
):

    result = lift_one_case(
        q1,
        q3,
        END_E,
    )

    k1 = result["k1"]

    final_k = result["exponents"][-1]

    m_sequence = [
        principal_coordinate(
            k,
            k1,
        )
        for k in result["exponents"]
    ]

    rho = Fraction(
        q1,
        q3,
    )

    chart_base = int(
        2
        * pow(
            3,
            k1,
        )
    )

    # Only the 7-adic local chart is needed, so avoid constructing giant
    # exact rational powers beyond this symbolic integer.
    #
    # For the original k1=1 case this becomes rho/6.
    #
    # The logarithmic ratio is evaluated modulo the finite chart using
    # the normalized integer ratio:
    #
    #     rho / (2*3^k1).
    #
    # To avoid huge exact powers, compute the base residue modulo a
    # sufficiently large power and use the ordinary exact integer chart
    # only when the exponent k1 is small (which it always is: 0..5).
    chart_base = int(
        2
        * pow(
            3,
            k1,
        )
    )

    chart_fraction = (
        rho
        / chart_base
    )

    log_argument = (
        chart_fraction
        - 1
    )

    log_base = (
        Fraction(
            PRINCIPAL_BASE,
            1,
        )
        - 1
    )

    log_defined = (
        fraction_valuation_7(
            log_argument
        )
        is not None
        and
        fraction_valuation_7(
            log_argument
        ) > 0
    )

    logarithmic_m = None
    log_match = False

    if log_defined:

        log_source = log_one_plus_x(
            log_argument,
            END_E + 3,
        )

        log_denominator = log_one_plus_x(
            log_base,
            END_E + 3,
        )

        if fraction_valuation_7(
            log_source
        ) is not None:

            logarithmic_m = (
                log_source
                / log_denominator
            )

            modulus = int(
                P7 ** (
                    END_E - 1
                )
            )

            log_m_residue = fraction_mod(
                logarithmic_m,
                modulus,
            )

            hensel_m_residue = (
                m_sequence[-1]
                % modulus
            )

            log_match = (
                log_m_residue
                == hensel_m_residue
            )

    return {
        "p": int(p),
        "q": int(q),
        "q1": int(q1),
        "q3": int(q3),
        "gcd_q": gcd(
            int(q1),
            int(q3),
        ),
        "rho7": result["rho7"],
        "k1": k1,
        "exponents": result["exponents"],
        "m": m_sequence,
        "digits": result["digits"],
        "slopes": result["slopes"],
        "predicted_slope": result["predicted_slope"],
        "slope_exact": result["slope_formula_exact"],
        "log_defined": log_defined,
        "log_match": log_match,
        "final_k": final_k,
        "final_m": m_sequence[-1],
    }


# ============================================================================
# MAIN
# ============================================================================

def main():

    print("=" * 78)
    print(
        "EXPERIMENT 218 — EXACT n=pq FAMILY / "
        "PROJECTIVE 7-ADIC INVARIANT AUDIT"
    )
    print("=" * 78)

    if not CASES:
        raise RuntimeError(
            "CASES is empty. Add exact (p,q,q1,q3) rows."
        )

    # ------------------------------------------------------------------
    # 1. FAMILY INPUT
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("1. FAMILY CASES")
    print("=" * 78)

    for p, q, q1, q3 in CASES:

        print(
            f"  (p,q)=({p},{q}) "
            f"n={p*q} "
            f"q1={q1} "
            f"q3={q3}"
        )

    # ------------------------------------------------------------------
    # 2. CASE AUDITS
    # ------------------------------------------------------------------

    results = []

    print()
    print("=" * 78)
    print("2. EXACT CASE-BY-CASE 7-ADIC AUDIT")
    print("=" * 78)

    for case in CASES:

        result = audit_case(
            *case
        )

        results.append(
            result
        )

        print()
        print(
            f"  (p,q)=({result['p']},{result['q']}) "
            f"n={result['p']*result['q']}"
        )

        print(
            f"    gcd(q1,q3)={result['gcd_q']}"
        )

        print(
            f"    rho_mod7={result['rho7']}"
        )

        print(
            f"    k1={result['k1']}"
        )

        print(
            f"    final_k={result['final_k']}"
        )

        print(
            f"    final_m={result['final_m']}"
        )

        print(
            f"    t_digits={result['digits']}"
        )

        print(
            f"    slopes={result['slopes']}"
        )

        print(
            f"    predicted_slope="
            f"{result['predicted_slope']}"
        )

        print(
            f"    slope_formula_exact="
            f"{result['slope_exact']}"
        )

        print(
            f"    logarithmic_chart_defined="
            f"{result['log_defined']}"
        )

        print(
            f"    logarithmic_match="
            f"{result['log_match']}"
        )

    # ------------------------------------------------------------------
    # 3. FAMILY INVARIANTS
    # ------------------------------------------------------------------

    all_slope_exact = all(
        result["slope_exact"]
        for result in results
    )

    all_log_exact = all(
        result["log_match"]
        for result in results
        if result["log_defined"]
    )

    all_unique = True

    for result in results:

        # Every transition generated by the seven-candidate procedure
        # has exactly one selected digit if the construction succeeded.
        #
        # Successful completion is itself the uniqueness assertion here.
        if len(
            result["digits"]
        ) != END_E - 1:

            all_unique = False

    print()
    print("=" * 78)
    print("3. FAMILY INVARIANT SUMMARY")
    print("=" * 78)

    print(
        f"  number_of_cases={len(results)}"
    )

    print(
        f"  all_slope_formulas_exact="
        f"{all_slope_exact}"
    )

    print(
        f"  all_hensel_lifts_unique="
        f"{all_unique}"
    )

    print(
        f"  all_logarithmic_matches="
        f"{all_log_exact}"
    )

    # ------------------------------------------------------------------
    # 4. WHAT THIS CURRENT DATA CAN/CANNOT PROVE
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("4. FAMILY-THEOREM STATUS")
    print("=" * 78)

    if len(results) == 1:

        print(
            "  family_size=1"
        )

        print(
            "  family_generalization_established=False"
        )

        print(
            "  reason=only one exact (p,q) source case supplied"
        )

    else:

        print(
            "  family_size>1"
        )

        print(
            "  family_generalization_candidate=True"
        )

    # ------------------------------------------------------------------
    # 5. STRUCTURAL INTERPRETATION
    # ------------------------------------------------------------------

    print()
    print("=" * 78)
    print("5. STRUCTURAL INTERPRETATION")
    print("=" * 78)

    print(
        """
This experiment deliberately separates two levels of analysis.

Level 1:

    Given an exact source pair (q1,q3) generated by an n=pq instance,
    the 7-adic projective mechanism can be tested independently.

Level 2:

    A genuine n=pq theorem requires deriving q1(p,q), q3(p,q), H(p,q),
    B(p,q), C(p,q), and the retained matrix from the underlying
    construction.

Therefore this script does not fabricate a symbolic p,q formula.

Once multiple exact source rows from genuinely different n=pq cases are
inserted into CASES, this becomes a controlled family experiment:

    (p,q)
       ->
    (q1,q3)
       ->
    rho
       ->
    k1 + Hensel digits
       ->
    principal 7-adic coordinate.

A future family result is meaningful only if the source pairs themselves
come from the actual n=pq construction.
"""
    )

    # ------------------------------------------------------------------
    # 6. FINAL
    # ------------------------------------------------------------------

    final_ok = (
        len(results) >= 1
        and all_slope_exact
        and all_unique
    )

    print()
    print("=" * 78)
    print("6. FINAL EXACTNESS")
    print("=" * 78)

    print(
        f"  cases_nonempty="
        f"{len(results) >= 1}"
    )

    print(
        f"  all_general_7adic_slope_checks="
        f"{all_slope_exact}"
    )

    print(
        f"  all_hensel_reconstructions_complete="
        f"{all_unique}"
    )

    print(
        f"  family_theorem_not_yet_claimed="
        f"{len(results) < 2}"
    )

    print(
        f"  failures={0 if final_ok else 1}"
    )

    print(
        f"  ALL BASIC CHECKS PASS={final_ok}"
    )

    print()
    print("EXPERIMENT 218 COMPLETE")


if __name__ == "__main__":

    try:
        main()

    except KeyboardInterrupt:
        print(
            "\nInterrupted."
        )
        sys.exit(130)

    except Exception as exc:
        print(
            "\nFATAL ERROR: "
            + type(exc).__name__
            + ": "
            + str(exc)
        )
        raise

