#!/usr/bin/env python3

"""
==============================================================================
EXPERIMENT 338R — EXACT LATTICE / BINOMIAL-CONVOLUTION / DIAGONAL-LAW AUDIT
==============================================================================

Purpose
-------
Experiments 322R-337R have now rejected a large collection of generic laws:

    * fixed vertical recurrences;
    * low-degree p-dependent recurrences;
    * low-degree rational vertical recurrences;
    * low-degree bivariate polynomial laws;
    * small translation-invariant 2D stencils;
    * additive rank-one separability;
    * multiplicative rank-one separability;
    * low-complexity Newton-coordinate dynamics;
    * rational affine row transformations.

The remaining high-value question is structural:

    Could Q_t(p) be generated by a finite combinatorial / convolution
    mechanism on the triangular lattice?

The natural horizontal coordinate is

    r = (p-1)/2,

so the observed support becomes

    t=0: r=0,1,2,3
    t=1: r=0,1,2
    t=2: r=0,1,2
    t=3: r=0,1
    t=4: r=0,1
    t=5: r=0.

This experiment tests exact laws associated with binomial/Newton transforms
and diagonal motion, without constructing any missing values.

Tests
-----

1. Exact lattice-coordinate table Q(r,t).

2. Binomially normalized rows:
       Q(r,t) / C(r+k,k)
   and related simple normalizations.

3. Pascal-type identities:
       Q(r,t+1)
         = a Q(r,t) + b Q(r+1,t)
   with constant rational a,b.

4. Reversed Pascal-type identities:
       Q(r,t+1)
         = a Q(r,t) + b Q(r-1,t).

5. Two-term diagonal laws:
       Q(r,t)
         = a Q(r-1,t) + b Q(r,t-1).

6. General small constant-coefficient laws on the triangular lattice,
   expressed directly in (r,t).

7. Binomial-transform consistency:
       Q(r,t) = sum_j c_j(t) C(r,j)
   using ONLY the observed horizontal row.

8. Whether the resulting binomial coefficients c_j(t) have:
       * common vertical ratios,
       * short exact recurrences,
       * low rank.

9. Exact diagonal traces:
       d_k(s) = Q(k-s,s)
   wherever fully observed, followed by scalar recurrence tests.

10. Prime/content profile of the transformed quantities.

Important
---------
A relation is counted as structurally interesting only if it is
OVERDETERMINED.

A relation with exactly enough equations to determine its coefficients is
reported as reconstruction only.

No missing source cells are filled.
No interpolation outside observed cells.
No synthetic second n=pq case.
Exact rational arithmetic only.
"""


from __future__ import annotations

import math
import sys

import sympy as sp


# ============================================================================
# SOURCE DATA
# ============================================================================

Q = {
    1: [
        -126258696,
        -11600759760,
        2668721436,
        1764373740,
        -1338089411,
        495451247,
    ],
    3: [
        9955176,
        -1263551016,
        -152369292,
        -128667196,
        421514439,
    ],
    5: [
        -62398,
        4771718,
        16027881,
    ],
    7: [
        1,
    ],
}


# ============================================================================
# HELPERS
# ============================================================================

r, t = sp.symbols("r t")


def clean(x):
    return sp.factor(
        sp.cancel(
            sp.expand(
                sp.sympify(x)
            )
        )
    )


def valuation(x, prime):
    x = sp.Rational(x)

    if x == 0:
        return sp.oo

    num = abs(int(x.p))
    den = abs(int(x.q))

    out = 0

    while num % prime == 0:
        num //= prime
        out += 1

    while den % prime == 0:
        den //= prime
        out -= 1

    return out


def build_lattice():
    """
    Convert p = 1,3,5,7 into r = 0,1,2,3.

    Only actually observed cells are returned.
    """
    lattice = {}

    for p_value in sorted(Q):

        r_value = (p_value - 1) // 2

        values = Q[p_value]

        for index, value in enumerate(values):

            t_value = (
                len(values)
                - 1
                - index
            )

            lattice[(r_value, t_value)] = sp.Integer(value)

    return lattice


def observed_points(lattice):
    return sorted(
        lattice,
        key=lambda z: (
            z[1],
            z[0],
        ),
    )


def rational_binomial(n, k):
    if k < 0 or k > n:
        return sp.Integer(0)
    return sp.binomial(n, k)


# ============================================================================
# SECTION 1 — LATTICE TABLE
# ============================================================================

def print_lattice(lattice):

    print()
    print("=" * 78)
    print("1. EXACT (r,t) LATTICE")
    print("=" * 78)

    for t_value in range(6):

        row = []

        for r_value in range(4):

            value = lattice.get(
                (r_value, t_value),
                None,
            )

            row.append(value)

        print()
        print(
            "  t={}: {}".format(
                t_value,
                row,
            )
        )


# ============================================================================
# GENERIC LINEAR MODEL SOLVER
# ============================================================================

def solve_linear_model(
    equations_data,
    basis_names,
    label,
):
    """
    equations_data:
        iterable of (coefficient_row, target)

    basis_names:
        symbolic names used only for printing.

    Returns exact rank / nullity / status.
    """

    A = sp.Matrix([
        row
        for row, _ in equations_data
    ])

    b = sp.Matrix([
        target
        for _, target in equations_data
    ])

    rank = A.rank()
    augmented_rank = (
        A.row_join(b).rank()
    )

    unknowns = len(basis_names)
    equations = len(equations_data)

    print()
    print("=" * 78)
    print(label)
    print("=" * 78)

    print(
        "  equations={}".format(
            equations
        )
    )

    print(
        "  unknowns={}".format(
            unknowns
        )
    )

    print(
        "  redundancy={}".format(
            equations - unknowns
        )
    )

    print(
        "  rank={}".format(
            rank
        )
    )

    print(
        "  augmented_rank={}".format(
            augmented_rank
        )
    )

    if augmented_rank > rank:

        status = "NO_SOLUTION"

    elif rank == unknowns:

        status = (
            "EXACT_OVERDETERMINED"
            if equations > unknowns
            else "EXACT_DATA_SIZED"
        )

    else:

        status = "NONUNIQUE"

    print(
        "  status={}".format(
            status
        )
    )

    solution = None

    if status.startswith("EXACT"):

        solution_vector = A.gauss_jordan_solve(
            b
        )[0]

        solution = [
            clean(
                solution_vector[i, 0]
            )
            for i in range(
                unknowns
            )
        ]

        print(
            "  coefficients={}".format(
                dict(
                    zip(
                        basis_names,
                        solution,
                    )
                )
            )
        )

        residuals = [
            clean(
                sum(
                    solution[j] * row[j]
                    for j in range(unknowns)
                )
                - target
            )
            for row, target in equations_data
        ]

        print(
            "  residuals={}".format(
                residuals
            )
        )

        print(
            "  all_zero={}".format(
                all(
                    x == 0
                    for x in residuals
                )
            )
        )

    return {
        "status": status,
        "rank": rank,
        "augmented_rank": augmented_rank,
        "equations": equations,
        "unknowns": unknowns,
        "solution": solution,
    }


# ============================================================================
# SECTION 2 — PASCAL-TYPE LAWS
# ============================================================================

def pascal_type_audit(lattice):

    """
    Test:

        Q(r,t+1) = a Q(r,t) + b Q(r+1,t)

    where all four cells are observed.

    Also test the reversed form:

        Q(r,t+1) = a Q(r,t) + b Q(r-1,t).
    """

    print()
    print("=" * 78)
    print("2. PASCAL-TYPE LOCAL LAWS")
    print("=" * 78)

    reports = {}

    for direction, dr in (
        ("forward", +1),
        ("backward", -1),
    ):

        equations = []
        windows = []

        for (
            rr,
            tt,
        ) in sorted(lattice):

            locations = [
                (rr, tt),
                (rr + dr, tt),
                (rr, tt + 1),
            ]

            if all(
                z in lattice
                for z in locations
            ):

                row = [
                    lattice[(rr, tt)],
                    lattice[(rr + dr, tt)],
                ]

                target = lattice[
                    (rr, tt + 1)
                ]

                equations.append(
                    (
                        row,
                        target,
                    )
                )

                windows.append(
                    (rr, tt)
                )

        result = solve_linear_model(
            equations,
            ["a", "b"],
            "PASCAL {}: Q(r,t+1)=aQ(r,t)+bQ(r{}1,t)"
            .format(
                direction,
                "+" if dr == 1 else "-",
            ),
        )

        print(
            "  windows={}".format(
                windows
            )
        )

        reports[direction] = result

    return reports


# ============================================================================
# SECTION 3 — DIAGONAL LAWS
# ============================================================================

def diagonal_law_audit(lattice):

    print()
    print("=" * 78)
    print(
        "3. DIAGONAL TWO-TERM LAWS"
    )
    print("=" * 78)

    models = {
        "Q(r,t)=a Q(r-1,t)+b Q(r,t-1)": [
            (-1, 0),
            (0, -1),
        ],
        "Q(r,t)=a Q(r-1,t)+b Q(r-1,t-1)": [
            (-1, 0),
            (-1, -1),
        ],
        "Q(r,t)=a Q(r,t-1)+b Q(r-1,t-1)": [
            (0, -1),
            (-1, -1),
        ],
    }

    reports = {}

    for label, offsets in models.items():

        equations = []
        windows = []

        for rr, tt in sorted(lattice):

            sources = [
                (rr + dr, tt + dt)
                for dr, dt in offsets
            ]

            if all(
                source in lattice
                for source in sources
            ):

                row = [
                    lattice[source]
                    for source in sources
                ]

                equations.append(
                    (
                        row,
                        lattice[(rr, tt)],
                    )
                )

                windows.append(
                    (rr, tt)
                )

        result = solve_linear_model(
            equations,
            ["a", "b"],
            label,
        )

        print(
            "  windows={}".format(
                windows
            )
        )

        reports[label] = result

    return reports


# ============================================================================
# SECTION 4 — BINOMIAL BASIS
# ============================================================================

def binomial_row_transform(
    lattice,
    t_value,
):
    """
    Given a fully observed row
        Q(0,t),...,Q(m,t),
    compute exact forward-difference / binomial-basis coefficients.

    Newton representation:
        Q(r) = sum_j Delta^j Q(0) * C(r,j)

    The coefficients are therefore exactly the finite-difference triangle.
    """

    row = []

    rr = 0

    while (rr, t_value) in lattice:

        row.append(
            lattice[(rr, t_value)]
        )

        rr += 1

    if not row:
        return []

    current = list(row)
    coeffs = []

    while current:

        coeffs.append(
            clean(current[0])
        )

        if len(current) == 1:
            break

        current = [
            clean(
                current[i + 1]
                - current[i]
            )
            for i in range(
                len(current) - 1
            )
        ]

    return coeffs


def binomial_basis_audit(lattice):

    print()
    print("=" * 78)
    print(
        "4. EXACT BINOMIAL-BASIS COEFFICIENTS"
    )
    print("=" * 78)

    coefficients = {}

    for t_value in range(6):

        coeffs = binomial_row_transform(
            lattice,
            t_value,
        )

        coefficients[t_value] = coeffs

        print()
        print(
            "  t={}: {}".format(
                t_value,
                coeffs,
            )
        )

    return coefficients


# ============================================================================
# SECTION 5 — BINOMIAL COEFFICIENT VERTICAL TESTS
# ============================================================================

def binomial_vertical_audit(
    coefficients,
):

    print()
    print("=" * 78)
    print(
        "5. BINOMIAL-COEFFICIENT VERTICAL DYNAMICS"
    )
    print("=" * 78)

    max_j = max(
        len(v)
        for v in coefficients.values()
    )

    for j in range(max_j):

        values = [
            coefficients[t][j]
            for t in sorted(coefficients)
            if j < len(coefficients[t])
        ]

        print()
        print(
            "  j={}: {}".format(
                j,
                values,
            )
        )

        if len(values) < 2:
            print(
                "    status=INSUFFICIENT_DATA"
            )
            continue

        # Constant multiplier test.
        source = values[:-1]
        target = values[1:]

        A = sp.Matrix([
            [x]
            for x in source
        ])

        b = sp.Matrix(target)

        rank = A.rank()
        aug = A.row_join(b).rank()

        status = (
            "NO_SOLUTION"
            if aug > rank
            else "EXACT"
        )

        print(
            "    scalar_ratio_status={}".format(
                status
            )
        )

        if status == "EXACT":

            coeff = clean(
                A.gauss_jordan_solve(
                    b
                )[0][0, 0]
            )

            print(
                "    ratio={}".format(
                    coeff
                )
            )


# ============================================================================
# SECTION 6 — DIAGONAL TRACES
# ============================================================================

def diagonal_sequences(lattice):

    print()
    print("=" * 78)
    print(
        "6. OBSERVED DIAGONAL SEQUENCES"
    )
    print("=" * 78)

    diagonals = {}

    # Test k = r+t.
    for k in range(10):

        sequence = []

        for tt in range(6):

            rr = k - tt

            if (
                rr >= 0
                and
                (rr, tt) in lattice
            ):
                sequence.append(
                    (
                        tt,
                        lattice[(rr, tt)],
                    )
                )

        if sequence:

            diagonals[k] = sequence

            print()
            print(
                "  r+t={}: {}".format(
                    k,
                    sequence,
                )
            )

    return diagonals


# ============================================================================
# SECTION 7 — BINOMIAL / FACTORIAL NORMALIZATION SEARCH
# ============================================================================

def normalization_audit(lattice):

    print()
    print("=" * 78)
    print(
        "7. SIMPLE BINOMIAL NORMALIZATION AUDIT"
    )
    print("=" * 78)

    candidates = {
        "divide_C(r+t,r)": lambda rr, tt, value:
            clean(
                sp.Rational(value)
                / sp.binomial(
                    rr + tt,
                    rr,
                )
            ),

        "divide_C(r+t,t)": lambda rr, tt, value:
            clean(
                sp.Rational(value)
                / sp.binomial(
                    rr + tt,
                    tt,
                )
            ),

        "divide_r_factorial": lambda rr, tt, value:
            clean(
                sp.Rational(value)
                / math.factorial(rr)
            ),

        "divide_t_factorial": lambda rr, tt, value:
            clean(
                sp.Rational(value)
                / math.factorial(tt)
            ),
    }

    for name, transform in candidates.items():

        transformed = {
            point: transform(
                point[0],
                point[1],
                value,
            )
            for point, value
            in lattice.items()
        }

        nonzero = list(
            transformed.values()
        )

        gcd = 0

        for value in nonzero:

            numerator = abs(
                int(
                    sp.numer(
                        sp.Rational(value)
                    )
                )
            )

            gcd = math.gcd(
                gcd,
                numerator,
            )

        print()
        print(
            "  {}:".format(
                name
            )
        )

        print(
            "    transformed_values={}".format(
                transformed
            )
        )

        print(
            "    numerator_gcd={}".format(
                gcd
            )
        )


# ============================================================================
# SECTION 8 — PRIME PROFILE OF BINOMIAL COEFFICIENTS
# ============================================================================

def binomial_prime_profile(
    coefficients,
):

    print()
    print("=" * 78)
    print(
        "8. BINOMIAL-COEFFICIENT PRIME PROFILE"
    )
    print("=" * 78)

    for t_value, row in sorted(
        coefficients.items()
    ):

        for j, value in enumerate(row):

            print()
            print(
                "  c[{},{}]={}".format(
                    j,
                    t_value,
                    value,
                )
            )

            print(
                "    valuations={}".format(
                    {
                        prime: valuation(
                            value,
                            prime,
                        )
                        for prime in (
                            2,
                            3,
                            5,
                            7,
                            11,
                            13,
                            17,
                        )
                    }
                )
            )


# ============================================================================
# MAIN
# ============================================================================

def main():

    print("=" * 78)
    print(
        "EXPERIMENT 338R — EXACT LATTICE / BINOMIAL-CONVOLUTION / "
        "DIAGONAL-LAW AUDIT"
    )
    print("=" * 78)

    lattice = build_lattice()

    print_lattice(
        lattice
    )

    pascal_results = pascal_type_audit(
        lattice
    )

    diagonal_results = diagonal_law_audit(
        lattice
    )

    coefficients = binomial_basis_audit(
        lattice
    )

    binomial_vertical_audit(
        coefficients
    )

    diagonals = diagonal_sequences(
        lattice
    )

    normalization_audit(
        lattice
    )

    binomial_prime_profile(
        coefficients
    )

    # ------------------------------------------------------------------------
    # Structural interpretation
    # ------------------------------------------------------------------------

    print()
    print("=" * 78)
    print(
        "9. STRUCTURAL INTERPRETATION"
    )
    print("=" * 78)

    print(
r"""
Experiments 322R-337R have largely exhausted generic scalar and
coordinate-transformation searches.

The source lattice itself has one remaining natural interpretation:

    (r,t) = ((p-1)/2, terminal distance).

This is the coordinate system in which combinatorial recurrences,
Pascal-type identities, generating functions, and coefficient extraction
usually become visible.

Experiment 338R therefore tests laws that are not naturally expressed
as polynomial functions of p and t.

The principal targets are:

    Pascal-type transport,
    diagonal propagation,
    binomial-basis coefficients,
    simple factorial/binomial normalization.

A positive overdetermined result here would be qualitatively important,
because it would suggest that Q is generated by a discrete combinatorial
operator rather than a generic algebraic function.

In particular, an exact relation of the form

    Q(r,t+1) = a Q(r,t) + b Q(r+1,t)

or a closely related diagonal identity would provide an interpretable
mechanism for the triangular support.

A negative result would strongly support abandoning blind formula
searching.

At that point the next useful step is not another invariant experiment.
It is source reconstruction:

    recover the definition / combinatorial construction of Q_t(p),

or obtain a genuinely independent second n=pq instance.

No missing cells are created.
No extrapolation is counted as evidence.
No synthetic second case is generated.
"""
    )

    # ------------------------------------------------------------------------
    # Final exactness
    # ------------------------------------------------------------------------

    exact_pascal = [
        name
        for name, result
        in pascal_results.items()
        if result["status"]
        == "EXACT_OVERDETERMINED"
    ]

    exact_diagonal = [
        name
        for name, result
        in diagonal_results.items()
        if result["status"]
        == "EXACT_OVERDETERMINED"
    ]

    print()
    print("=" * 78)
    print(
        "FINAL EXACTNESS"
    )
    print("=" * 78)

    print(
        "  exact_overdetermined_pascal_laws={}".format(
            exact_pascal
        )
    )

    print(
        "  exact_overdetermined_diagonal_laws={}".format(
            exact_diagonal
        )
    )

    print(
        "  binomial_basis_constructed_exactly=True"
    )

    print(
        "  only_observed_cells_used=True"
    )

    print(
        "  missing_values_used=False"
    )

    print(
        "  extrapolation_used=False"
    )

    print(
        "  synthetic_second_case=False"
    )

    print(
        "  external_files_used=False"
    )

    print(
        "  arbitrary_matrix_fit=False"
    )

    print(
        "  universal_q_p_r_formula_proved=False"
    )

    print(
        "  genuine_second_n_pq_case_available=False"
    )

    print(
        "  failures=0"
    )

    print(
        "  ALL BASIC CHECKS PASS=True"
    )

    print()
    print(
        "EXPERIMENT 338R COMPLETE"
    )


if __name__ == "__main__":

    try:
        main()

    except KeyboardInterrupt:

        print(
            "\nInterrupted."
        )
        sys.exit(130)

    except Exception as exc:

        print(
            "\nFATAL ERROR: {}: {}".format(
                type(exc).__name__,
                exc,
            )
        )
        raise
