#!/usr/bin/env python3

import sympy as sp

# ==============================================================================
# EXPERIMENT 556
# ==============================================================================
# 2020 ROOT-ORBIT -> HOMOGENEOUS LAYER-STEP OPERATOR
#
# PURPOSE
# -------
# We now know exactly:
#
#     A0 = 2y - 2x + 3
#     B0 = 2y + 2x - 3
#
# and:
#
#     L_m = (A0 + m r)(B0 + m r) / r^2
#         = N + m S + m^2.
#
# We also know:
#
#     F2 = L0 + L1 - 1 - Delta
#
#     F3 = (L1-L0) F2.
#
# This experiment does NOT invent F4/F5/F6.
#
# Instead it asks:
#
#     Is there a natural layer-step multiplier generated entirely
#     by the root-orbit differences?
#
# The known step is:
#
#     G_2 = F3/F2 = L1-L0 = S+1.
#
# The canonical orbit differences are:
#
#     D_m = L_{m+1}-L_m = S+2m+1.
#
# We classify what follows symbolically if the homogeneous hierarchy
# is generated by such orbit-step operators.
#
# No numerical fitting.
# No factor enumeration.
# No p,q insertion.
# ==============================================================================


print("=" * 78)
print("EXPERIMENT 556 START")
print("=" * 78)
print("2020 ROOT-ORBIT -> HOMOGENEOUS LAYER-STEP OPERATOR")
print()


# ==============================================================================
# SYMBOLS
# ==============================================================================

A, B, r = sp.symbols("A B r", nonzero=True)
m, n = sp.symbols("m n", integer=True)
h, z = sp.symbols("h z")


failures = 0


# ==============================================================================
# HELPERS
# ==============================================================================

def simp(expr):
    return sp.factor(
        sp.cancel(
            sp.together(
                sp.expand(
                    sp.simplify(expr)
                )
            )
        )
    )


def cert(name, actual, expected=0):
    global failures

    diff = simp(actual - expected)
    passed = diff == 0

    print(f"  {name}")
    print("    difference =")
    sp.pprint(diff)
    print(f"    PASS = {passed}")
    print()

    if not passed:
        failures += 1

    return passed


def show(name, expr):
    print(f"  {name} =")
    sp.pprint(simp(expr))
    print()


# ==============================================================================
# [1] ROOT COORDINATES
# ==============================================================================

print("[1] ROOT COORDINATES")
print("-" * 78)

P = simp(A / r)
Q = simp(B / r)

N = simp(A * B / r**2)
S = simp((A + B) / r)
Delta = simp((A - B)**2 / r**2)

show("P", P)
show("Q", Q)
show("N", N)
show("S", S)
show("Delta", Delta)

cert("N=PQ", N, P * Q)
cert("S=P+Q", S, P + Q)
cert("Delta=(P-Q)^2", Delta, (P - Q)**2)


# ==============================================================================
# [2] TRANSLATED ROOT ORBIT
# ==============================================================================

print("[2] TRANSLATED ROOT ORBIT")
print("-" * 78)


def L(k):
    return simp(
        (A + k*r) * (B + k*r) / r**2
    )


def D(k):
    return simp(
        L(k + 1) - L(k)
    )


L0 = L(0)
L1 = L(1)
L2 = L(2)
L3 = L(3)
L4 = L(4)

show("L0", L0)
show("L1", L1)
show("L2", L2)

cert("L0=N", L0, N)
cert("L1=N+S+1", L1, N + S + 1)
cert("L2=N+2S+4", L2, N + 2*S + 4)


# ==============================================================================
# [3] ORBIT STEP OPERATOR
# ==============================================================================

print("[3] ORBIT STEP OPERATOR")
print("-" * 78)

D0 = D(0)
D1 = D(1)
D2 = D(2)
D3 = D(3)

show("D0=L1-L0", D0)
show("D1=L2-L1", D1)
show("D2=L3-L2", D2)
show("D3=L4-L3", D3)

cert("D0=S+1", D0, S + 1)
cert("D1=S+3", D1, S + 3)
cert("D2=S+5", D2, S + 5)
cert("D3=S+7", D3, S + 7)


# ==============================================================================
# [4] ORBIT STEP CURVATURE
# ==============================================================================

print("[4] ORBIT STEP CURVATURE")
print("-" * 78)

cert(
    "D1-D0=2",
    D1 - D0,
    2,
)

cert(
    "D2-D1=2",
    D2 - D1,
    2,
)

cert(
    "D3-D2=2",
    D3 - D2,
    2,
)


# ==============================================================================
# [5] KNOWN HOMOGENEOUS LAYERS
# ==============================================================================

print("[5] KNOWN HOMOGENEOUS LAYERS")
print("-" * 78)

F2 = simp(
    6*N - S**2 + S
)

F3 = simp(
    (S + 1) * F2
)

show("F2", F2)
show("F3", F3)

cert(
    "F2=2N+S-Delta",
    F2,
    2*N + S - Delta,
)

cert(
    "F3=(S+1)F2",
    F3,
    (S + 1)*F2,
)


# ==============================================================================
# [6] F2 / F3 AS ROOT-ORBIT STEP
# ==============================================================================

print("[6] F2 / F3 AS ROOT-ORBIT STEP")
print("-" * 78)

ratio_23 = simp(
    F3 / F2
)

cert(
    "F3/F2=D0",
    ratio_23,
    D0,
)

cert(
    "F3/F2=S+1",
    ratio_23,
    S + 1,
)


# ==============================================================================
# [7] NATURAL LAYER-STEP ANSATZ
# ==============================================================================

print("[7] NATURAL LAYER-STEP ANSATZ")
print("-" * 78)

print(
    r"""
  The known layer transition is exactly:

      F2 -> F3

      F3 = D0 * F2

  where:

      D0 = L1-L0.

  The root-orbit supplies the canonical sequence:

      D_m = L_{m+1}-L_m

          = S+2m+1.

  Therefore the natural symbolic layer-step ansatz is:

      G_n = D_{n-2}

  so that:

      G_2 = D0
      G_3 = D1
      G_4 = D2
      ...

  This is a hypothesis about the operator, not a definition
  of the unknown higher homogeneous layers.
"""
)


# ==============================================================================
# [8] STEP OPERATOR IN CLOSED FORM
# ==============================================================================

print("[8] STEP OPERATOR IN CLOSED FORM")
print("-" * 78)

G_n = simp(
    S + 2*n - 3
)

cert(
    "G_n = D_(n-2)",
    G_n,
    D(n - 2),
)


# ==============================================================================
# [9] LAYER-INDEX INVARIANT
# ==============================================================================

print("[9] LAYER-INDEX INVARIANT")
print("-" * 78)

invariant_candidate = simp(
    G_n - 2*n
)

show("G_n-2n", invariant_candidate)

cert(
    "G_n-2n = S-3",
    invariant_candidate,
    S - 3,
)


# ==============================================================================
# [10] STEP OPERATOR UNDER ROOT TRANSLATION
# ==============================================================================

print("[10] STEP OPERATOR UNDER ROOT TRANSLATION")
print("-" * 78)

# Under A -> A+h*r, B -> B+h*r:
#
# S -> S+2h
#
# Therefore:
#
# G_n -> G_n+2h.

S_h = simp(
    (A + h*r + B + h*r) / r
)

G_n_h = simp(
    S_h + 2*n - 3
)

cert(
    "S_h=S+2h",
    S_h,
    S + 2*h,
)

cert(
    "G_n(h)=G_n+2h",
    G_n_h,
    G_n + 2*h,
)


# ==============================================================================
# [11] OPERATOR COMPOSITION
# ==============================================================================

print("[11] OPERATOR COMPOSITION")
print("-" * 78)

print(
    r"""
  If the genuine homogeneous-layer transition is multiplication
  by G_n, then the hypothetical hierarchy would obey:

      F_{n+1} = G_n F_n

  with:

      G_n = S+2n-3.

  This would imply:

      F3 = (S+1)F2,

  exactly matching the established layer.

  Higher layers are NOT asserted here.
"""
)


# ==============================================================================
# [12] SYMBOLIC HYPOTHETICAL PRODUCTS
# ==============================================================================

print("[12] SYMBOLIC HYPOTHETICAL PRODUCTS")
print("-" * 78)

# Start with an abstract F2 seed.
F2_seed = sp.Symbol("F2_seed")

F3_hyp = simp(
    G_n.subs(n, 2) * F2_seed
)

F4_hyp = simp(
    G_n.subs(n, 3) * F3_hyp
)

F5_hyp = simp(
    G_n.subs(n, 4) * F4_hyp
)

F6_hyp = simp(
    G_n.subs(n, 5) * F5_hyp
)

show("F3_hyp", F3_hyp)
show("F4_hyp", F4_hyp)
show("F5_hyp", F5_hyp)
show("F6_hyp", F6_hyp)


# ==============================================================================
# [13] DIVISION-FREE RECURRENCE OF THE HYPOTHETICAL OPERATOR
# ==============================================================================

print("[13] DIVISION-FREE RECURRENCE")
print("-" * 78)

E2 = simp(
    F4_hyp * F2_seed
    - F3_hyp**2
    - 2*F3_hyp*F2_seed
)

E3 = simp(
    F5_hyp * F3_hyp
    - F4_hyp**2
    - 2*F4_hyp*F3_hyp
)

E4 = simp(
    F6_hyp * F4_hyp
    - F5_hyp**2
    - 2*F5_hyp*F4_hyp
)

cert(
    "hypothetical E2=0",
    E2,
    0,
)

cert(
    "hypothetical E3=0",
    E3,
    0,
)

cert(
    "hypothetical E4=0",
    E4,
    0,
)


# ==============================================================================
# [14] ROOT-ORBIT VS HOMOGENEOUS STEP
# ==============================================================================

print("[14] ROOT-ORBIT VS HOMOGENEOUS STEP")
print("-" * 78)

print(
    r"""
  Exact root-orbit identities:

      D0 = L1-L0 = S+1
      D1 = L2-L1 = S+3
      D2 = L3-L2 = S+5
      D3 = L4-L3 = S+7.

  Known homogeneous identity:

      F3/F2 = S+1 = D0.

  Therefore the FIRST layer transition is exactly the
  FIRST translated-product difference.

  The unresolved question is whether the actual original
  construction continues with:

      F4/F3 = D1
      F5/F4 = D2
      F6/F5 = D3.

  This experiment does not assume those identities are true.
"""
)


# ==============================================================================
# [15] DIFFERENCE-OF-DIFFERENCES TEST
# ==============================================================================

print("[15] DIVISION-FREE COMPARISON TEMPLATE")
print("-" * 78)

F4_actual = sp.Symbol("F4_actual")
F5_actual = sp.Symbol("F5_actual")
F6_actual = sp.Symbol("F6_actual")

test4 = simp(
    F4_actual * F2
    - F3**2
    - 2*F3*F2
)

test5 = simp(
    F5_actual * F3
    - F4_actual**2
    - 2*F4_actual*F3
)

test6 = simp(
    F6_actual * F4_actual
    - F5_actual**2
    - 2*F5_actual*F4_actual
)

print(
    r"""
  Genuine higher layers must eventually be substituted into:

      E2 = F4*F2 - F3^2 - 2F3F2

      E3 = F5*F3 - F4^2 - 2F4F3

      E4 = F6*F4 - F5^2 - 2F5F4.

  The present experiment deliberately leaves these quantities
  symbolic.
"""
)


# ==============================================================================
# [16] F2 STRUCTURE IN ROOT ORBIT
# ==============================================================================

print("[16] F2 ROOT-ORBIT STRUCTURE")
print("-" * 78)

F2_orbit = simp(
    L0 + L1 - 1 - Delta
)

cert(
    "F2=L0+L1-1-Delta",
    F2_orbit,
    F2,
)

print(
    r"""
  This is useful because it shows that F2 already combines:

      L0       = N
      L1       = N+S+1
      Delta    = invariant transverse channel.

  Hence F2 is not arbitrary with respect to the root orbit.
"""
)


# ==============================================================================
# [17] F3 STRUCTURE IN ROOT ORBIT
# ==============================================================================

print("[17] F3 ROOT-ORBIT STRUCTURE")
print("-" * 78)

F3_orbit = simp(
    D0 * F2_orbit
)

cert(
    "F3=D0*F2",
    F3_orbit,
    F3,
)

print(
    r"""
  Therefore the first homogeneous-layer transition is already
  expressed entirely through the root-orbit operator:

      F2
       |
       | multiply by D0=L1-L0
       v
      F3.

  This is the strongest exact layer/operator identification
  currently justified by the available layers.
"""
)


# ==============================================================================
# [18] KAPPA SPECTRAL POLYNOMIAL
# ==============================================================================

print("[18] KAPPA SPECTRAL POLYNOMIAL")
print("-" * 78)

Q_poly = simp(
    z**2 - S*z + N
)

Q_factor = simp(
    (z-A/r) * (z-B/r)
)

cert(
    "Q=(z-A/r)(z-B/r)",
    Q_poly,
    Q_factor,
)

cert(
    "disc(Q)=Delta",
    sp.discriminant(Q_poly, z),
    Delta,
)


# ==============================================================================
# [19] OPERATOR SUMMARY
# ==============================================================================

print("[19] OPERATOR SUMMARY")
print("-" * 78)

print(
    r"""
  ROOT OPERATOR:

      A -> A+h r
      B -> B+h r

  ROOT PRODUCT ORBIT:

      L_m = (A+mr)(B+mr)/r^2
          = N+mS+m^2.

  ROOT STEP:

      D_m = L_{m+1}-L_m
          = S+2m+1.

  KNOWN HOMOGENEOUS LAYERS:

      F2 = L0+L1-1-Delta

      F3 = D0 F2.

  Therefore:

      F3/F2 = D0.

  The natural higher-step hypothesis would be:

      F_{n+1} = D_{n-2} F_n.

  This is equivalent to:

      F_{n+1}/F_n = S+2n-3.

  BUT THIS REMAINS A HYPOTHESIS until genuine F4/F5/F6
  from the original 2020 homogeneous construction are inserted.
"""
)


# ==============================================================================
# [20] FINAL AUDIT
# ==============================================================================

print("=" * 78)
print("EXPERIMENT 556 FINISHED")
print("=" * 78)
print()

print(f"SYMBOLIC FAILURES = {failures}")
print(f"OVERALL EXACT AUDIT = {failures == 0}")

print()
print("=" * 78)
print("NEXT RESEARCH TARGET")
print("=" * 78)

print(
    r"""
The exact result is now:

    F2 = L0 + L1 - 1 - Delta

    F3 = (L1-L0) F2

with:

    L_m = (A0+mr)(B0+mr)/r^2

and:

    L_{m+1}-L_m = S+2m+1.

Thus:

    F3/F2 = L1-L0.

The unresolved question has been reduced to a single concrete
operator-continuation question:

    Does the ORIGINAL homogeneous construction satisfy

        F4 = (L2-L1)F3

        F5 = (L3-L2)F4

        F6 = (L4-L3)F5

?

Equivalently:

    F4/F3 = S+3

    F5/F4 = S+5

    F6/F5 = S+7.

These must be tested against the genuine original formulas.

Do not replace them with the hypothetical expressions generated
inside this experiment.

The important distinction is:

    ROOT ORBIT:
        proven.

    F2/F3 operator correspondence:
        proven.

    Higher homogeneous continuation:
        still unproven.
"""
)
