#!/usr/bin/env python3

# ==============================================================================
# EXPERIMENT 592
# ==============================================================================
# SYMBOLIC FUNCTION CONJUGACY UNDER COORDINATE HALVING
#
# NO FILES
# NO WEB
#
# We now know from Experiment 591 that:
#
#     x_(z+1) = x_z / 2
#     y_(z+1) = y_z / 2
#
# exactly on every observed SAME-N transition.
#
# The previous affine search incorrectly required integer coefficients,
# so it could not discover the true 1/2 transformation.
#
# This experiment directly tests:
#
#     F_(z+1)(x/2,y/2) = F_z(x,y)
#
# for p and q.
#
#
# We also discover:
#
#     residue_z -> residue_(z+1)
#
# and determine whether the child residue is generated by a fixed
# branch-bit rule.
#
#
# The key goal:
#
#     A_z(x,y)
#        |
#        | H(x,y)=(x/2,y/2)
#        v
#     A_(z+1)(x',y')
#
# If:
#
#     A_(z+1)(x/2,y/2) = A_z(x,y)
#
# exactly at every level, then the apparent changing function is
# only a coordinate renormalization.
#
#
# Then we separately test the USER'S original hypothesis:
#
#     parent residue
#         ->
#     one of two child residues
#
# and ask whether the child branch is controlled by the low bit
# discarded by:
#
#     x -> x/2.
#
# ==============================================================================

from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass
from fractions import Fraction
from math import isqrt


# ==============================================================================
# CONFIGURATION
# ==============================================================================

MAX_N = 2_000_000

MIN_Z = 2
MAX_Z = 9

MAX_EXAMPLES = 12


# ==============================================================================
# DATA
# ==============================================================================

@dataclass(frozen=True)
class Point:
    n: int
    p: int
    q: int
    x: Fraction
    y: Fraction
    residue: int


# ==============================================================================
# PRIME SIEVE
# ==============================================================================

def prime_sieve(limit: int):

    sieve = bytearray(
        b"\x01"
    ) * (
        limit + 1
    )

    sieve[0] = 0
    sieve[1] = 0

    root = isqrt(limit)

    for p in range(
        2,
        root + 1,
    ):

        if not sieve[p]:
            continue

        start = p * p

        count = (
            (limit - start) // p
        ) + 1

        sieve[
            start:limit + 1:p
        ] = b"\x00" * count

    return sieve


# ==============================================================================
# SEMIPRIME GENERATION
# ==============================================================================

def generate_semiprimes(
    max_n,
    sieve,
):

    primes = [
        p
        for p in range(
            3,
            max_n + 1,
            2,
        )
        if sieve[p]
    ]

    result = []

    for i, p in enumerate(primes):

        if p * p > max_n:
            break

        max_q = max_n // p

        for q in primes[i:]:

            if q > max_q:
                break

            result.append(
                (
                    p * q,
                    p,
                    q,
                )
            )

    return result


# ==============================================================================
# INVARIANT COORDINATES
# ==============================================================================
#
#     X = (q-p+6)/2
#     Y = (p+q)/2
#
# and:
#
#     p = Y-X+3
#     q = Y+X-3.
#
# At level z:
#
#     k = 2^(z-1)
#
#     x_z = X/k
#     y_z = Y/k
#
# ==============================================================================

def invariant_coordinates(
    p,
    q,
):

    if (
        (q - p + 6) % 2 != 0
        or
        (p + q) % 2 != 0
    ):
        return None

    X = Fraction(
        q - p + 6,
        2,
    )

    Y = Fraction(
        p + q,
        2,
    )

    return X, Y


def normalized_point(
    n,
    p,
    q,
    z,
):

    coords = invariant_coordinates(
        p,
        q,
    )

    if coords is None:
        return None

    X, Y = coords

    k = 1 << (
        z - 1
    )

    x = X / k
    y = Y / k

    if (
        x.denominator != 1
        or
        y.denominator != 1
    ):
        return None

    return Point(
        n=n,
        p=p,
        q=q,
        x=x,
        y=y,
        residue=n % (1 << z),
    )


# ==============================================================================
# LEVELS
# ==============================================================================

def build_levels(
    semiprimes,
):

    levels = {}

    for z in range(
        MIN_Z,
        MAX_Z + 1,
    ):

        level = defaultdict(list)

        for n, p, q in semiprimes:

            point = normalized_point(
                n,
                p,
                q,
                z,
            )

            if point is None:
                continue

            level[
                point.residue
            ].append(
                point
            )

        levels[z] = level

        total = sum(
            len(group)
            for group in level.values()
        )

        print(
            f"    z={z:<2} "
            f"active={total:<7} "
            f"residues={len(level)}"
        )

    return levels


# ==============================================================================
# DIRECT FUNCTION FOR A LEVEL
# ==============================================================================
#
# Given z and normalized coordinates:
#
#     X = 2^(z-1)x
#     Y = 2^(z-1)y
#
# the factor equations are:
#
#     p = Y-X+3
#     q = Y+X-3
#
# Therefore:
#
#     p = -2^(z-1)x + 2^(z-1)y + 3
#     q =  2^(z-1)x + 2^(z-1)y - 3
#
# ==============================================================================

def symbolic_p_rule(
    z,
):

    k = Fraction(
        1 << (
            z - 1
        )
    )

    return (
        -k,
        k,
        Fraction(3),
    )


def symbolic_q_rule(
    z,
):

    k = Fraction(
        1 << (
            z - 1
        )
    )

    return (
        k,
        k,
        Fraction(-3),
    )


def apply_rule(
    rule,
    x,
    y,
):

    a, b, c = rule

    return (
        a * x
        + b * y
        + c
    )


# ==============================================================================
# FUNCTION CONJUGACY
# ==============================================================================

def test_function_conjugacy():

    print()
    print("=" * 90)
    print(
        "SYMBOLIC FUNCTION CONJUGACY"
    )
    print("=" * 90)

    for z in range(
        MIN_Z,
        MAX_Z,
    ):

        p_parent = symbolic_p_rule(
            z
        )

        q_parent = symbolic_q_rule(
            z
        )

        p_child = symbolic_p_rule(
            z + 1
        )

        q_child = symbolic_q_rule(
            z + 1
        )

        # --------------------------------------------------------------
        # Parent:
        #
        #     p_z(x,y)
        #
        # Child:
        #
        #     p_(z+1)(x/2,y/2)
        # --------------------------------------------------------------

        samples = [
            (
                Fraction(-10),
                Fraction(-4),
            ),
            (
                Fraction(-3),
                Fraction(2),
            ),
            (
                Fraction(0),
                Fraction(0),
            ),
            (
                Fraction(1),
                Fraction(5),
            ),
            (
                Fraction(7),
                Fraction(11),
            ),
        ]

        p_ok = True
        q_ok = True

        for x, y in samples:

            parent_value = apply_rule(
                p_parent,
                x,
                y,
            )

            child_value = apply_rule(
                p_child,
                x / 2,
                y / 2,
            )

            if parent_value != child_value:

                p_ok = False

            parent_value = apply_rule(
                q_parent,
                x,
                y,
            )

            child_value = apply_rule(
                q_child,
                x / 2,
                y / 2,
            )

            if parent_value != child_value:

                q_ok = False

        print()
        print(
            f"z={z} -> z={z+1}"
        )

        print(
            f"    p_(z+1)(x/2,y/2) = p_z(x,y): "
            f"{p_ok}"
        )

        print(
            f"    q_(z+1)(x/2,y/2) = q_z(x,y): "
            f"{q_ok}"
        )

        print(
            "    parent p:"
        )

        print(
            f"        "
            f"p = "
            f"({p_parent[0]})x + "
            f"({p_parent[1]})y + "
            f"({p_parent[2]})"
        )

        print(
            "    child p:"
        )

        print(
            f"        "
            f"p = "
            f"({p_child[0]})x' + "
            f"({p_child[1]})y' + "
            f"({p_child[2]})"
        )

        print(
            "    with:"
        )

        print(
            "        x'=x/2"
        )

        print(
            "        y'=y/2"
        )


# ==============================================================================
# EMPIRICAL CONJUGACY
# ==============================================================================
#
# SAME n:
#
#     parent point = (x,y)
#     child point  = (x',y')
#
# We directly test:
#
#     p_child(x/2,y/2) == p_parent(x,y)
#
# rather than trying to fit a new affine transformation.
#
# ==============================================================================

def empirical_conjugacy(
    levels,
):

    print()
    print("=" * 90)
    print(
        "EMPIRICAL SAME-N CONJUGACY"
    )
    print("=" * 90)

    for z in range(
        MIN_Z,
        MAX_Z,
    ):

        parent_by_n = {}

        for group in levels[z].values():

            for point in group:

                parent_by_n[
                    point.n
                ] = point

        child_by_n = {}

        for group in levels[z + 1].values():

            for point in group:

                child_by_n[
                    point.n
                ] = point

        common = (
            set(parent_by_n)
            &
            set(child_by_n)
        )

        p_fail = 0
        q_fail = 0
        x_fail = 0
        y_fail = 0

        for n in common:

            parent = parent_by_n[n]
            child = child_by_n[n]

            if (
                child.x
                != parent.x / 2
            ):

                x_fail += 1

            if (
                child.y
                != parent.y / 2
            ):

                y_fail += 1

            # Evaluate the LEVEL-(z+1) formula
            # at the child's normalized coordinates.
            p_rule = symbolic_p_rule(
                z + 1
            )

            q_rule = symbolic_q_rule(
                z + 1
            )

            predicted_p = apply_rule(
                p_rule,
                child.x,
                child.y,
            )

            predicted_q = apply_rule(
                q_rule,
                child.x,
                child.y,
            )

            if predicted_p != parent.p:

                p_fail += 1

            if predicted_q != parent.q:

                q_fail += 1

        print()
        print(
            f"z={z}->{z+1} "
            f"common={len(common)}"
        )

        print(
            f"    x halving failures = {x_fail}"
        )

        print(
            f"    y halving failures = {y_fail}"
        )

        print(
            f"    p conjugacy failures = {p_fail}"
        )

        print(
            f"    q conjugacy failures = {q_fail}"
        )


# ==============================================================================
# RESIDUE TRANSITION
# ==============================================================================

def residue_transition_report(
    levels,
):

    print()
    print("=" * 90)
    print(
        "RESIDUE TREE"
    )
    print("=" * 90)

    for z in range(
        MIN_Z,
        MAX_Z,
    ):

        transitions = defaultdict(
            set
        )

        parent_by_n = {}

        for residue, group in levels[z].items():

            for point in group:

                parent_by_n[
                    point.n
                ] = point.residue

        child_by_n = {}

        for residue, group in levels[z + 1].items():

            for point in group:

                child_by_n[
                    point.n
                ] = point.residue

        for n in (
            set(parent_by_n)
            &
            set(child_by_n)
        ):

            transitions[
                parent_by_n[n]
            ].add(
                child_by_n[n]
            )

        print()
        print(
            f"MOD {1 << z} -> "
            f"MOD {1 << (z+1)}"
        )

        for parent in sorted(
            transitions
        ):

            children = sorted(
                transitions[parent]
            )

            print(
                f"    {parent} -> "
                f"{children}"
            )


# ==============================================================================
# CHILD BIT FROM THE COORDINATE HALVING
# ==============================================================================
#
# Since:
#
#     x_child = x_parent / 2
#
# the transition is only possible when x_parent is even.
#
# The parent coordinate also contains a discarded bit:
#
#     x_parent = 2*x_child + epsilon
#
# where:
#
#     epsilon = x_parent mod 2.
#
# We test whether epsilon predicts the child residue.
#
# ==============================================================================

def discarded_bit_report(
    levels,
):

    print()
    print("=" * 90)
    print(
        "DISCARDED x-BIT -> CHILD RESIDUE"
    )
    print("=" * 90)

    for z in range(
        MIN_Z,
        MAX_Z,
    ):

        table = defaultdict(
            set
        )

        parent_by_n = {}

        for group in levels[z].values():

            for point in group:

                parent_by_n[
                    point.n
                ] = point

        child_by_n = {}

        for group in levels[z + 1].values():

            for point in group:

                child_by_n[
                    point.n
                ] = point

        for n in (
            set(parent_by_n)
            &
            set(child_by_n)
        ):

            parent = parent_by_n[n]
            child = child_by_n[n]

            key = (
                parent.residue,
                parent.x % 2,
                parent.y % 2,
            )

            table[key].add(
                child.residue
            )

        print()
        print(
            f"z={z}"
        )

        deterministic = True

        for key in sorted(
            table
        ):

            children = sorted(
                table[key]
            )

            print(
                f"    "
                f"parent={key[0]} "
                f"xbit={key[1]} "
                f"ybit={key[2]} "
                f"-> {children}"
            )

            if len(children) != 1:

                deterministic = False

        print(
            f"    deterministic="
            f"{deterministic}"
        )


# ==============================================================================
# FUNCTION COEFFICIENT RECURSION
# ==============================================================================

def coefficient_recursion():

    print()
    print("=" * 90)
    print(
        "FUNCTION COEFFICIENT RECURSION"
    )
    print("=" * 90)

    previous_p = None
    previous_q = None

    for z in range(
        MIN_Z,
        MAX_Z + 1,
    ):

        p_rule = symbolic_p_rule(
            z
        )

        q_rule = symbolic_q_rule(
            z
        )

        print()
        print(
            f"z={z}"
        )

        print(
            f"    p coefficients="
            f"{p_rule}"
        )

        print(
            f"    q coefficients="
            f"{q_rule}"
        )

        if previous_p is not None:

            print(
                "    coefficient transition:"
            )

            print(
                f"        p x: "
                f"{previous_p[0]} -> {p_rule[0]}"
            )

            print(
                f"        p y: "
                f"{previous_p[1]} -> {p_rule[1]}"
            )

            print(
                f"        p c: "
                f"{previous_p[2]} -> {p_rule[2]}"
            )

            print(
                f"        q x: "
                f"{previous_q[0]} -> {q_rule[0]}"
            )

            print(
                f"        q y: "
                f"{previous_q[1]} -> {q_rule[1]}"
            )

            print(
                f"        q c: "
                f"{previous_q[2]} -> {q_rule[2]}"
            )

        previous_p = p_rule
        previous_q = q_rule


# ==============================================================================
# EXAMPLES
# ==============================================================================

def examples(
    levels,
):

    print()
    print("=" * 90)
    print(
        "SAME-N RENORMALIZATION EXAMPLES"
    )
    print("=" * 90)

    shown = 0

    parent_by_n = {}

    for group in levels[MIN_Z].values():

        for point in group:

            parent_by_n[
                point.n
            ] = point

    for z in range(
        MIN_Z,
        MAX_Z,
    ):

        child_by_n = {}

        for group in levels[z + 1].values():

            for point in group:

                child_by_n[
                    point.n
                ] = point

        common = sorted(
            set(parent_by_n)
            &
            set(child_by_n)
        )

        print()
        print(
            f"LEVEL {z}->{z+1}"
        )

        local = 0

        for n in common:

            parent = parent_by_n[n]
            child = child_by_n[n]

            print(
                f"    n={n} "
                f""
                f"r={parent.residue}"
                f"->"
                f"{child.residue} "
                f""
                f""
                f"x={parent.x}"
                f"->"
                f"{child.x} "
                f""
                f"y={parent.y}"
                f"->"
                f"{child.y}"
            )

            local += 1
            shown += 1

            if local >= 4:
                break

        if shown >= MAX_EXAMPLES:
            break


# ==============================================================================
# MAIN
# ==============================================================================

def main():

    print("=" * 90)
    print(
        "EXPERIMENT 592 START"
    )
    print("=" * 90)

    print()
    print(
        "SYMBOLIC FUNCTION CONJUGACY "
        "UNDER x,y -> x/2,y/2"
    )

    # --------------------------------------------------------------------------
    # Generate.
    # --------------------------------------------------------------------------

    print()
    print(
        "[1] PRIME SIEVE"
    )

    sieve = prime_sieve(
        MAX_N
    )

    print(
        "[2] SEMIPRIME GENERATION"
    )

    semiprimes = generate_semiprimes(
        MAX_N,
        sieve,
    )

    print(
        f"    semiprimes="
        f"{len(semiprimes)}"
    )

    # --------------------------------------------------------------------------
    # Levels.
    # --------------------------------------------------------------------------

    print()
    print(
        "[3] BUILD ACTIVE LEVELS"
    )

    levels = build_levels(
        semiprimes
    )

    # --------------------------------------------------------------------------
    # Symbolic.
    # --------------------------------------------------------------------------

    test_function_conjugacy()

    # --------------------------------------------------------------------------
    # Empirical.
    # --------------------------------------------------------------------------

    empirical_conjugacy(
        levels
    )

    # --------------------------------------------------------------------------
    # Residue tree.
    # --------------------------------------------------------------------------

    residue_transition_report(
        levels
    )

    # --------------------------------------------------------------------------
    # Discarded bits.
    # --------------------------------------------------------------------------

    discarded_bit_report(
        levels
    )

    # --------------------------------------------------------------------------
    # Coefficients.
    # --------------------------------------------------------------------------

    coefficient_recursion()

    # --------------------------------------------------------------------------
    # Examples.
    # --------------------------------------------------------------------------

    examples(
        levels
    )

    # --------------------------------------------------------------------------
    # Final.
    # --------------------------------------------------------------------------

    print()
    print("=" * 90)
    print(
        "FINAL AUDIT"
    )
    print("=" * 90)

    print(
        """
The central test is now:

    F_(z+1)(x/2,y/2)
        =
    F_z(x,y)

This is stronger than merely observing that x and y halve.

If exact for p and q over all levels, then:

    the FUNCTION changes
        only because
    the COORDINATE SCALE changes.

In other words:

    F_2
       |
       | x -> x/2
       | y -> y/2
       v
    F_3
       |
       | x -> x/2
       | y -> y/2
       v
    F_4
       |
       ...

The residue tree is tested separately.

The discarded low bit is also tested:

    x_z = 2*x_(z+1) + epsilon

to determine whether:

    epsilon
        ->
    child residue

is the branch-selection mechanism.

This directly tests the proposed hierarchical transformation:

    A1
      -> B1 or B2

    A2
      -> B3 or B4

where the child functions are related by a static coordinate
renormalization rather than being unrelated equations.
"""
    )

    print()
    print("=" * 90)
    print(
        "EXPERIMENT 592 FINISHED"
    )
    print("=" * 90)


if __name__ == "__main__":
    main()
