#!/usr/bin/env python3

"""
========================================================================================================================
EXPERIMENT 460
========================================================================================================================

SYMBOLIC IDEAL / J-FIBRE GENERATION AUDIT

QUESTION

  Are the tested low-degree identities actually generated by the
  two fundamental fibre equations, or is there an algebraically
  independent relation hidden among them?

CORE RELATIONS

  g1 = x + d0 - d

  g2 = 4K - r + 2*d*x - x^2

Equivalent quadratic form:

  g2' = 4K + d^2 - r - d0^2

because g1 implies x = d-d0.

PURPOSE

  Experiment 459 established numerically that the known relations
  are either fixed, varying-derived, or zero across the complete
  tested j-fibre.

  Experiment 460 now asks a stronger symbolic question:

      Is each tested zero identity contained in the ideal generated
      by g1 and g2?

  If yes, then the identity is algebraically generated by the
  existing fibre equations and is not a new constraint.

METHOD

  For each instance:

    1. Construct the polynomial ideal

         I = <x+d0-d,
              4K-r+2dx-x^2>

    2. Compute a Groebner basis over Q.

    3. Reduce every candidate polynomial relation modulo that basis.

    4. A zero remainder proves membership in the generated ideal.

    5. Nonzero remainder means the relation is not generated by
       the two existing fibre equations.

  This is symbolic algebra only.

RULES

  exact rational/integer arithmetic
  no factorization
  no giant enumeration
  no CRT Cartesian product
  no hidden values used to construct constraints
========================================================================================================================
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable

import sympy as sp


# ======================================================================================================================
# DATA
# ======================================================================================================================

@dataclass(frozen=True)
class Instance:
    idx: int
    N: int
    S: int
    d: int
    d0_true: int
    x_true: int
    K_true: int
    r: int


INSTANCES = [
    Instance(
        1,
        14246098189,
        333010,
        14245432170,
        14245432180,
        -10,
        -3449849766661475506269,
        -13799399066930810668576,
    ),
    Instance(
        2,
        10139117,
        11022,
        10117074,
        10117091,
        -17,
        -2968347695488785,
        -11873391125935945,
    ),
    Instance(
        3,
        10009330297,
        1010042,
        10007310214,
        10007310238,
        -24,
        -4306289434216722346403,
        -17225157737347240276460,
    ),
    Instance(
        4,
        100460333,
        20046,
        100420242,
        100420273,
        -31,
        -615138736337991015,
        -2460554951578020025,
    ),
    Instance(
        5,
        2503701173,
        100074,
        2503501026,
        2503501064,
        -38,
        -557809093589551261113,
        -2231236374548471123872,
    ),
    Instance(
        6,
        10006200817,
        200062,
        10005800694,
        10005800739,
        -45,
        -12714738365215418549091,
        -50858953461762196260849,
    ),
    Instance(
        7,
        40005200153,
        400026,
        40004400102,
        40004400154,
        -52,
        -305667239831581101061223,
        -1222668959330484861858204,
    ),
    Instance(
        8,
        270017400119,
        1200024,
        270015000072,
        270015000131,
        -59,
        -18737381797403407039327539,
        -74949527189645489927322133,
    ),
]


# ======================================================================================================================
# SYMBOLS
# ======================================================================================================================

x, d0, K = sp.symbols("x d0 K")


# ======================================================================================================================
# REFERENCE
# ======================================================================================================================

def valid_d0_parities(inst: Instance) -> list[int]:
    target = (inst.d * inst.d - inst.r) % 4

    return [
        p
        for p in (0, 1)
        if (p * p) % 4 == target
    ]


def derive_reference(inst: Instance) -> tuple[int, int, int]:

    valid = valid_d0_parities(inst)

    if len(valid) != 1:
        raise AssertionError(
            f"unexpected parity family: "
            f"instance={inst.idx}, valid={valid}"
        )

    parity = valid[0]

    candidates = []

    for x0 in (0, 1):

        d0_ref = inst.d - x0

        if d0_ref % 2 == parity:
            candidates.append((x0, d0_ref))

    if len(candidates) != 1:
        raise AssertionError(
            f"reference ambiguity: instance={inst.idx}"
        )

    x0, d0_ref = candidates[0]

    numerator = (
        inst.r
        + d0_ref * d0_ref
        - inst.d * inst.d
    )

    if numerator % 4 != 0:
        raise AssertionError(
            f"reference K not integral: instance={inst.idx}"
        )

    K_ref = numerator // 4

    return x0, d0_ref, K_ref


# ======================================================================================================================
# SYMBOLIC IDEAL
# ======================================================================================================================

def build_generators(inst: Instance):
    """
    Fundamental fibre equations.

      g1 = x + d0 - d

      g2 = 4K - r + 2dx - x^2
    """

    g1 = x + d0 - sp.Integer(inst.d)

    g2 = (
        4 * K
        - sp.Integer(inst.r)
        + 2 * sp.Integer(inst.d) * x
        - x**2
    )

    return g1, g2


def groebner_basis(inst: Instance):
    """
    Compute an exact Groebner basis over QQ.
    """

    g1, g2 = build_generators(inst)

    return sp.groebner(
        [g1, g2],
        K,
        d0,
        x,
        order="lex",
        domain=sp.QQ,
    )


# ======================================================================================================================
# CANDIDATE RELATIONS
# ======================================================================================================================

def candidate_relations(inst: Instance):

    d = sp.Integer(inst.d)
    r = sp.Integer(inst.r)

    return [
        (
            "N-2S+1-d",
            sp.Integer(inst.N)
            - 2 * sp.Integer(inst.S)
            + 1
            - d,
        ),

        (
            "x+d0-d",
            x + d0 - d,
        ),

        (
            "4K-r+2dx-x^2",
            4 * K
            - r
            + 2 * d * x
            - x**2,
        ),

        (
            "4K+d^2-r-d0^2",
            4 * K
            + d**2
            - r
            - d0**2,
        ),

        (
            "(x+d0)^2-d^2",
            (x + d0)**2 - d**2,
        ),

        (
            "4K+d^2-r-(x+d0)^2",
            4 * K
            + d**2
            - r
            - (x + d0)**2,
        ),

        (
            "d0+x-d",
            d0 + x - d,
        ),

        (
            "x^2-2dx+d^2-d0^2",
            x**2
            - 2 * d * x
            + d**2
            - d0**2,
        ),

        (
            "4K-r+x^2-2dx",
            4 * K
            - r
            + x**2
            - 2 * d * x,
        ),

        (
            "K displacement",
            K - (
                sp.Symbol("Kref")
                + sp.Symbol("d0ref") * sp.Symbol("j")
                + sp.Symbol("j")**2
            ),
        ),
    ]


# ======================================================================================================================
# EXPLICIT SUBSTITUTION TEST
# ======================================================================================================================

def fibre_substitution(
    inst: Instance,
    expr: sp.Expr,
    j_value: int,
):
    """
    Substitute the exact fibre parameterization into a polynomial.

      d0(j) = d0_ref + 2j
      x(j)  = x0 - 2j
      K(j)  = K_ref + d0_ref*j + j^2

    This gives a second, independent verification of the
    Groebner reduction result.
    """

    x0, d0_ref, K_ref = derive_reference(inst)

    j = sp.Integer(j_value)

    substitutions = {
        d0: sp.Integer(d0_ref) + 2 * j,
        x: sp.Integer(x0) - 2 * j,
        K: (
            sp.Integer(K_ref)
            + sp.Integer(d0_ref) * j
            + j * j
        ),
    }

    return sp.expand(expr.subs(substitutions))


# ======================================================================================================================
# MAIN
# ======================================================================================================================

def main() -> None:

    print("=" * 120)
    print("EXPERIMENT 460")
    print("=" * 120)
    print()
    print("SYMBOLIC IDEAL / J-FIBRE GENERATION AUDIT")
    print()

    global_basis_failures = 0
    global_substitution_failures = 0
    global_zero_remainder = 0
    global_nonzero_remainder = 0
    global_candidate_count = 0

    for inst in INSTANCES:

        print("-" * 120)

        print(
            f"INSTANCE {inst.idx}: "
            f"N={inst.N} "
            f"S={inst.S} "
            f"d={inst.d} "
            f"r={inst.r}"
        )
        print()

        x0, d0_ref, K_ref = derive_reference(inst)

        print("KNOWN-DATA REFERENCE")
        print(f"  x0     = {x0}")
        print(f"  d0_ref = {d0_ref}")
        print(f"  K_ref  = {K_ref}")
        print()

        print("POST-HOC DIAGNOSTIC")
        print(f"  true d0 = {inst.d0_true}")
        print(f"  true x  = {inst.x_true}")
        print(f"  true K  = {inst.K_true}")

        if (inst.d0_true - d0_ref) % 2 == 0:
            true_j = (inst.d0_true - d0_ref) // 2
        else:
            true_j = None

        print(f"  true j  = {true_j}")
        print()

        # --------------------------------------------------------------------------------------------------------------
        # Groebner basis
        # --------------------------------------------------------------------------------------------------------------

        basis = groebner_basis(inst)

        print("FUNDAMENTAL IDEAL")

        g1, g2 = build_generators(inst)

        print(f"  g1 = {g1}")
        print(f"  g2 = {g2}")
        print()

        print("GROEBNER BASIS")

        for item in basis.polys:
            print(f"  {item.as_expr()}")

        print()

        # --------------------------------------------------------------------------------------------------------------
        # Candidate relations
        # --------------------------------------------------------------------------------------------------------------

        print("RELATION MEMBERSHIP AUDIT")

        print(
            "  relation"
            + " " * 39
            + "remainder"
            + " " * 22
            + "member-of-I"
            + "  fibre-zero"
        )

        print("  " + "-" * 105)

        candidates = candidate_relations(inst)

        for name, expr in candidates:

            global_candidate_count += 1

            # The final K-displacement expression contains symbolic
            # Kref/d0ref/j and is not part of the x,d0,K ideal.
            # Skip it from ideal membership while still testing the
            # actual fibre substitution separately.
            if name == "K displacement":
                fibre_expr = sp.expand(
                    expr.subs({
                        sp.Symbol("Kref"): sp.Integer(K_ref),
                        sp.Symbol("d0ref"): sp.Integer(d0_ref),
                        sp.Symbol("j"): (
                            (sp.Integer(inst.d0_true)
                             - sp.Integer(d0_ref)) // 2
                        )
                        if true_j is not None
                        else 0,
                    })
                )

                substitution_ok = (
                    sp.expand(fibre_expr) == 0
                )

                if not substitution_ok:
                    global_substitution_failures += 1

                print(
                    f"  {name:<44}"
                    f"{str(fibre_expr):<32}"
                    f"{'N/A':>12}"
                    f"  {substitution_ok}"
                )

                continue

            try:
                remainder = basis.reduce(expr)[1]
            except Exception as exc:
                print(
                    f"  {name:<44}"
                    f"ERROR: {exc}"
                )
                global_basis_failures += 1
                continue

            remainder = sp.expand(remainder)

            member = remainder == 0

            if member:
                global_zero_remainder += 1
            else:
                global_nonzero_remainder += 1
                global_basis_failures += 1

            # Independent fibre substitution check at several j values.
            test_js = [-32, -8, -1, 0, 1, 8, 32]

            zero_on_fibre = True

            for j_value in test_js:

                value = fibre_substitution(
                    inst,
                    expr,
                    j_value,
                )

                if value != 0:
                    zero_on_fibre = False
                    break

            print(
                f"  {name:<44}"
                f"{str(remainder):<32}"
                f"{str(member):>12}"
                f"  {zero_on_fibre}"
            )

            if member != zero_on_fibre:
                global_substitution_failures += 1

        print()

        # --------------------------------------------------------------------------------------------------------------
        # Verify equivalence of the two quadratic forms.
        # --------------------------------------------------------------------------------------------------------------

        print("QUADRATIC-FORM EQUIVALENCE")

        d = sp.Integer(inst.d)
        r = sp.Integer(inst.r)

        form_a = (
            4 * K
            + d**2
            - r
            - d0**2
        )

        form_b = (
            4 * K
            - r
            + 2 * d * x
            - x**2
        )

        conversion_relation = sp.expand(
            form_a - form_b
        )

        remainder = sp.expand(
            basis.reduce(conversion_relation)[1]
        )

        print(
            "  (4K+d^2-r-d0^2)"
        )
        print(
            "    -(4K-r+2dx-x^2)"
        )
        print(
            f"    ideal remainder = {remainder}"
        )
        print(
            f"    generated by ideal = {remainder == 0}"
        )
        print()

        # --------------------------------------------------------------------------------------------------------------
        # Dimension / parameterization audit.
        # --------------------------------------------------------------------------------------------------------------

        print("FIBRE DIMENSION AUDIT")

        # Solve g1 for x and substitute into g2.
        x_solution = d - d0

        reduced_g2 = sp.expand(
            g2.subs(x, x_solution)
        )

        print(
            f"  x = d-d0"
        )
        print(
            f"  reduced quadratic = {reduced_g2}"
        )

        # Solve for K.
        K_solution = sp.solve(
            sp.Eq(reduced_g2, 0),
            K,
        )

        print(
            f"  K(d0) = {K_solution[0]}"
        )

        # Verify this agrees with the reference+j form.
        j = sp.Symbol("j")

        d0_j = sp.Integer(d0_ref) + 2 * j

        x_j = sp.Integer(x0) - 2 * j

        K_j_reference = (
            sp.Integer(K_ref)
            + sp.Integer(d0_ref) * j
            + j**2
        )

        K_j_direct = sp.expand(
            K_solution[0].subs(
                d0,
                d0_j,
            )
        )

        parameter_difference = sp.expand(
            K_j_direct - K_j_reference
        )

        print(
            f"  K_direct(j)-K_reference(j) = "
            f"{parameter_difference}"
        )
        print(
            f"  parameterizations agree = "
            f"{parameter_difference == 0}"
        )

        if parameter_difference != 0:
            global_basis_failures += 1

        print()

        # --------------------------------------------------------------------------------------------------------------
        # True branch consistency.
        # --------------------------------------------------------------------------------------------------------------

        print("TRUE BRANCH POST-HOC")

        if true_j is None:

            print(
                "  true branch parity-compatible = False"
            )

        else:

            d0_check = (
                d0_ref + 2 * true_j
            )

            x_check = (
                x0 - 2 * true_j
            )

            K_check = (
                K_ref
                + d0_ref * true_j
                + true_j**2
            )

            print(
                f"  true j                  = {true_j}"
            )
            print(
                f"  exact d0 reconstruction = "
                f"{d0_check == inst.d0_true}"
            )
            print(
                f"  exact x reconstruction  = "
                f"{x_check == inst.x_true}"
            )
            print(
                f"  exact K reconstruction  = "
                f"{K_check == inst.K_true}"
            )

        print()

    # ==================================================================================================================
    # GLOBAL SUMMARY
    # ==================================================================================================================

    print("=" * 120)
    print("GLOBAL EXPERIMENT 460 SUMMARY")
    print("=" * 120)
    print()

    print(
        f"  instances                     = {len(INSTANCES)}"
    )
    print(
        f"  candidate relations           = {global_candidate_count}"
    )
    print(
        f"  zero Groebner remainders      = {global_zero_remainder}"
    )
    print(
        f"  nonzero Groebner remainders   = {global_nonzero_remainder}"
    )
    print(
        f"  ideal-membership failures    = "
        f"{global_basis_failures}"
    )
    print(
        f"  substitution mismatches      = "
        f"{global_substitution_failures}"
    )
    print()

    print("CENTRAL ALGEBRAIC RESULT")
    print()
    print(
        "  The existing fibre is generated by:"
    )
    print()
    print(
        "      g1 = x + d0 - d"
    )
    print(
        "      g2 = 4K - r + 2dx - x^2"
    )
    print()
    print(
        "  Elimination of x gives:"
    )
    print()
    print(
        "      4K + d^2 - r - d0^2 = 0"
    )
    print()
    print(
        "  Thus the two common quadratic representations are"
    )
    print(
        "  algebraically equivalent modulo g1."
    )
    print()

    print("PARAMETERIZATION")
    print()
    print(
        "      d0(j) = d0_ref + 2j"
    )
    print(
        "      x(j)  = x0 - 2j"
    )
    print(
        "      K(j)  = K_ref + d0_ref*j + j^2"
    )
    print()

    print("INTERPRETATION")
    print()
    print(
        "  A polynomial relation whose Groebner remainder is zero"
    )
    print(
        "  belongs to the algebraic ideal generated by the existing"
    )
    print(
        "  fibre equations."
    )
    print()
    print(
        "  Such a relation does not supply an independent equation"
    )
    print(
        "  unless additional information fixes a quantity outside"
    )
    print(
        "  this ideal."
    )
    print()

    clean = (
        global_basis_failures == 0
        and global_substitution_failures == 0
    )

    print("======================================================================================================================")
    print("EXPERIMENT 460 FINAL STATUS")
    print("======================================================================================================================")
    print(
        f"  IDEAL MEMBERSHIP AUDIT = {global_basis_failures == 0}"
    )
    print(
        f"  FIBRE SUBSTITUTION      = {global_substitution_failures == 0}"
    )
    print(
        f"  PARAMETERIZATION        = {clean}"
    )
    print(
        "  GIANT K ENUMERATION     = False"
    )
    print(
        "  GIANT d0 ENUMERATION    = False"
    )
    print(
        "  CRT CARTESIAN PRODUCT   = False"
    )
    print(
        "  INTEGER-EXACT           = True"
    )
    print(
        "  SYMPY EXACT RATIONALS   = True"
    )
    print()
    print("  CONCLUSION:")
    print(
        "    The next audit is symbolic rather than numerical:"
    )
    print(
        "    it tests whether candidate identities are actually"
    )
    print(
        "    generated by the established j-fibre ideal."
    )
    print("======================================================================================================================")
    print("EXPERIMENT 460 FINISHED")
    print("======================================================================================================================")


if __name__ == "__main__":
    main()
