# =============================================================================
# EXPERIMENT 388 START
# =============================================================================
#
# DIRECT TRACE/NORM REDUCTION OF THE LAYER MAP
#
# Goal:
#
#   Avoid the huge resultant.
#
#   The Kappa equation is
#
#       Q(t) =
#       (K + N^2 + 2)t^2
#       - N(N+3)t
#       + N^2
#       = 0
#
#   Let its two roots be t1,t2.
#
#   Define
#
#       R1 = R(t1)
#       R2 = R(t2)
#
#   The resultant in R has roots R1,R2, therefore:
#
#       R1 + R2
#       R1 * R2
#
#   are the trace and norm of R(t) in the quadratic extension
#   generated by Q(t).
#
#   This experiment computes those directly by reducing the numerator
#   and denominator of R(t) modulo Q(t), without constructing the full
#   20-degree resultant.
#
#   Main questions:
#
#       1. What is the exact reduced form of R(t)?
#       2. What are Trace(R) and Norm(R)?
#       3. Do they have unexpectedly low degree in K?
#       4. Do they factor into simple N,K expressions?
#       5. Do their denominators share a simple factor?
#
#   No floating point.
#   No factoring of N.
#   No candidate-prime search.
#
# =============================================================================

import sympy as sp


# =============================================================================
# SYMBOLS
# =============================================================================

N, K, t = sp.symbols("N K t")


# =============================================================================
# TEST INSTANCES
# =============================================================================

INSTANCES = [
    (50387, 282589),
    (1009, 10007),
    (10007, 1000003),
    (10007, 10009),
    (50021, 50047),
    (100003, 100019),
    (200003, 200009),
    (300007, 900001),
    (500009, 700001),
    (1000003, 1000033),
    (2000003, 3000017),
]


# =============================================================================
# LAYER R(t)
# =============================================================================

def build_R():

    h16 = (
        -9*t**8
        -36*t**7
        -84*t**6
        -126*t**5
        -126*t**4
        -84*t**3
        -36*t**2
        -9*t
        -1
    )

    h15 = (
        88*t**9
        +396*t**8
        +1164*t**7
        +2226*t**6
        +2898*t**5
        +2604*t**4
        +1596*t**3
        +639*t**2
        +151*t
        +16
    )

    h14 = (
        -276*t**10
        -1380*t**9
        -5460*t**8
        -13560*t**7
        -23058*t**6
        -27510*t**5
        -23100*t**4
        -13410*t**3
        -5135*t**2
        -1169*t
        -120
    )

    numerator = sp.expand(
        h15**2 - h16*h14
    )

    denominator = sp.expand(
        h16**2
    )

    return (
        sp.expand(numerator),
        sp.expand(denominator),
    )


R_NUM, R_DEN = build_R()


# =============================================================================
# KAPPA QUADRATIC
# =============================================================================

def kappa_quadratic():

    return sp.expand(
        (K + N**2 + 2) * t**2
        - N * (N + 3) * t
        + N**2
    )


Q = kappa_quadratic()


# =============================================================================
# REDUCE A POLYNOMIAL MODULO THE KAPPA QUADRATIC
# =============================================================================

def reduce_mod_Q(expr):

    return sp.rem(
        sp.Poly(
            sp.expand(expr),
            t,
            domain=sp.QQ.frac_field(N, K),
        ),
        sp.Poly(
            Q,
            t,
            domain=sp.QQ.frac_field(N, K),
        ),
    ).as_expr()


# =============================================================================
# LINEAR POLYNOMIAL COEFFICIENTS
#
# result = a1*t + a0
# =============================================================================

def linear_parts(expr):

    expr = sp.cancel(expr)

    poly = sp.Poly(
        sp.expand(expr),
        t,
        domain=sp.QQ.frac_field(N, K),
    )

    a1 = poly.coeff_monomial(t)
    a0 = poly.coeff_monomial(1)

    return (
        sp.factor(a1),
        sp.factor(a0),
    )


# =============================================================================
# REDUCE R(t)
#
# R(t) = U(t) / V(t)
#
# modulo Q:
#
# U = u1*t + u0
# V = v1*t + v0
#
# Then rationalize the denominator using the quadratic relation.
# =============================================================================

def reduced_layer_map():

    u = reduce_mod_Q(R_NUM)
    v = reduce_mod_Q(R_DEN)

    u1, u0 = linear_parts(u)
    v1, v0 = linear_parts(v)

    return (
        sp.factor(u1),
        sp.factor(u0),
        sp.factor(v1),
        sp.factor(v0),
    )


# =============================================================================
# TRACE AND NORM OF A LINEAR-FRACTIONAL ELEMENT
#
# Let
#
#   R = (u1*t + u0)/(v1*t + v0)
#
# with
#
#   t1+t2 = S
#   t1*t2 = P.
#
# Then
#
#   denominator product:
#
#     D = v1^2 P + v1 v0 S + v0^2
#
#   numerator/denominator conjugate sum:
#
#   Trace(R) =
#
#     [2 u1 v1 P
#      + (u1 v0 + u0 v1) S
#      + 2 u0 v0] / D
#
# and
#
#   Norm(R) =
#
#     [u1^2 P + u1 u0 S + u0^2] / D.
#
# =============================================================================

def trace_norm_from_linear_fraction(
    u1,
    u0,
    v1,
    v0,
):

    # Q(t) = a*t^2 + b*t + c
    a = sp.expand(K + N**2 + 2)
    b = sp.expand(-N * (N + 3))
    c = sp.expand(N**2)

    # Vieta
    S = sp.cancel(-b / a)
    P = sp.cancel(c / a)

    denominator_product = sp.cancel(
        v1**2 * P
        + v1 * v0 * S
        + v0**2
    )

    trace_numerator = sp.cancel(
        2 * u1 * v1 * P
        + (u1 * v0 + u0 * v1) * S
        + 2 * u0 * v0
    )

    norm_numerator = sp.cancel(
        u1**2 * P
        + u1 * u0 * S
        + u0**2
    )

    trace = sp.cancel(
        trace_numerator
        / denominator_product
    )

    norm = sp.cancel(
        norm_numerator
        / denominator_product
    )

    return (
        sp.factor(trace),
        sp.factor(norm),
        sp.factor(denominator_product),
    )


# =============================================================================
# DEGREE INFORMATION
# =============================================================================

def rational_degree(expr):

    expr = sp.cancel(expr)

    num, den = sp.fraction(expr)

    num_poly = sp.Poly(
        sp.expand(num),
        K,
        domain=sp.QQ.frac_field(N),
    )

    den_poly = sp.Poly(
        sp.expand(den),
        K,
        domain=sp.QQ.frac_field(N),
    )

    return (
        num_poly.degree(),
        den_poly.degree(),
    )


def rational_term_count(expr):

    expr = sp.cancel(expr)

    num, den = sp.fraction(expr)

    num_terms = len(
        sp.Poly(
            sp.expand(num),
            K,
            domain=sp.QQ.frac_field(N),
        ).terms()
    )

    den_terms = len(
        sp.Poly(
            sp.expand(den),
            K,
            domain=sp.QQ.frac_field(N),
        ).terms()
    )

    return (
        num_terms,
        den_terms,
    )


# =============================================================================
# NUMERIC INSTANCE SPECIALIZATION
#
# Used only after the symbolic structure has been constructed.
# =============================================================================

def specialize(expr, n_value):

    return sp.factor(
        sp.cancel(
            expr.subs(
                N,
                n_value,
            )
        )
    )


# =============================================================================
# DIRECT TRUE VALUES
# =============================================================================

def direct_true_values(
    p,
    q,
):

    n_value = sp.Integer(p * q)

    x_true = sp.Integer(
        p + q + 1
    )

    k_true = sp.Integer(
        1
    ) - (
        p**2 - p + 1
    ) * (
        q**2 - q + 1
    )

    t_true = sp.cancel(
        n_value / x_true
    )

    # Other Kappa root from Vieta.
    t_other = sp.cancel(
        n_value**2
        / (
            (k_true + n_value**2 + 2)
            * t_true
        )
    )

    return (
        n_value,
        k_true,
        t_true,
        t_other,
    )


# =============================================================================
# MAIN
# =============================================================================

def main():

    print("=" * 110)
    print("EXPERIMENT 388 START")
    print("=" * 110)
    print()
    print("DIRECT TRACE / NORM REDUCTION OF R(t)")
    print()
    print("The full resultant is not constructed.")
    print("R(t) is reduced directly modulo the Kappa quadratic.")
    print()

    # -------------------------------------------------------------------------
    # SYMBOLIC REDUCTION
    # -------------------------------------------------------------------------

    print("=" * 110)
    print("1. SYMBOLIC REDUCTION")
    print("=" * 110)
    print()

    print("Reducing numerator modulo Q(t)...")
    print("Reducing denominator modulo Q(t)...")

    (
        u1,
        u0,
        v1,
        v0,
    ) = reduced_layer_map()

    print()
    print("REDUCED NUMERATOR")
    print(
        "  degree = 1"
    )

    print(
        f"  u1 term count = "
        f"{len(str(u1))}"
    )

    print(
        f"  u0 term count = "
        f"{len(str(u0))}"
    )

    print()

    print("REDUCED DENOMINATOR")
    print(
        "  degree = 1"
    )

    print(
        f"  v1 expression size = "
        f"{len(str(v1))}"
    )

    print(
        f"  v0 expression size = "
        f"{len(str(v0))}"
    )

    # -------------------------------------------------------------------------
    # TRACE / NORM
    # -------------------------------------------------------------------------

    print()
    print("=" * 110)
    print("2. TRACE / NORM")
    print("=" * 110)
    print()

    (
        trace_R,
        norm_R,
        denominator_product,
    ) = trace_norm_from_linear_fraction(
        u1,
        u0,
        v1,
        v0,
    )

    trace_degree = rational_degree(
        trace_R
    )

    norm_degree = rational_degree(
        norm_R
    )

    trace_terms = rational_term_count(
        trace_R
    )

    norm_terms = rational_term_count(
        norm_R
    )

    print("TRACE(R) = R1 + R2")
    print(
        f"  degree numerator/denominator = "
        f"{trace_degree}"
    )
    print(
        f"  term count numerator/denominator = "
        f"{trace_terms}"
    )
    print(
        f"  expression size = "
        f"{len(str(trace_R))}"
    )

    print()

    print("NORM(R) = R1 * R2")
    print(
        f"  degree numerator/denominator = "
        f"{norm_degree}"
    )
    print(
        f"  term count numerator/denominator = "
        f"{norm_terms}"
    )
    print(
        f"  expression size = "
        f"{len(str(norm_R))}"
    )

    print()

    # -------------------------------------------------------------------------
    # SYMBOLIC FACTOR STRUCTURE
    # -------------------------------------------------------------------------

    print("=" * 110)
    print("3. SYMBOLIC FACTOR STRUCTURE")
    print("=" * 110)
    print()

    trace_num, trace_den = sp.fraction(
        trace_R
    )

    norm_num, norm_den = sp.fraction(
        norm_R
    )

    print(
        f"  gcd(Trace numerator, denominator) = "
        f"{sp.gcd(trace_num, trace_den) == 1}"
    )

    print(
        f"  gcd(Norm numerator, denominator) = "
        f"{sp.gcd(norm_num, norm_den) == 1}"
    )

    print()

    print("FACTORIZATION DEGREE SIGNATURE")

    trace_num_fac = sp.factor_list(
        trace_num,
        K,
    )

    trace_den_fac = sp.factor_list(
        trace_den,
        K,
    )

    norm_num_fac = sp.factor_list(
        norm_num,
        K,
    )

    norm_den_fac = sp.factor_list(
        norm_den,
        K,
    )

    print(
        "  Trace numerator factors = "
        f"{len(trace_num_fac[1])}"
    )

    print(
        "  Trace denominator factors = "
        f"{len(trace_den_fac[1])}"
    )

    print(
        "  Norm numerator factors = "
        f"{len(norm_num_fac[1])}"
    )

    print(
        "  Norm denominator factors = "
        f"{len(norm_den_fac[1])}"
    )

    # -------------------------------------------------------------------------
    # INSTANCE TESTS
    # -------------------------------------------------------------------------

    results = []

    for index, (p, q) in enumerate(
        INSTANCES,
        start=1,
    ):

        print()
        print("=" * 110)
        print(f"INSTANCE {index}")
        print("=" * 110)
        print()

        (
            n_value,
            k_true,
            t_true,
            t_other,
        ) = direct_true_values(
            p,
            q,
        )

        # Direct layer roots.
        r1_direct = sp.cancel(
            (
                R_NUM
                / R_DEN
            ).subs(
                t,
                t_true,
            )
        )

        r2_direct = sp.cancel(
            (
                R_NUM
                / R_DEN
            ).subs(
                t,
                t_other,
            )
        )

        direct_sum = sp.cancel(
            r1_direct + r2_direct
        )

        direct_product = sp.cancel(
            r1_direct * r2_direct
        )

        trace_specialized = sp.cancel(
            trace_R.subs(
                N,
                n_value,
            ).subs(
                K,
                k_true,
            )
        )

        norm_specialized = sp.cancel(
            norm_R.subs(
                N,
                n_value,
            ).subs(
                K,
                k_true,
            )
        )

        # ---------------------------------------------------------------------
        # EXACT CHECKS
        # ---------------------------------------------------------------------

        trace_pass = (
            direct_sum == trace_specialized
        )

        norm_pass = (
            direct_product == norm_specialized
        )

        # ---------------------------------------------------------------------
        # Structural sizes
        # ---------------------------------------------------------------------

        trace_num_i, trace_den_i = (
            sp.fraction(
                trace_specialized
            )
        )

        norm_num_i, norm_den_i = (
            sp.fraction(
                norm_specialized
            )
        )

        print("BASIC DATA")
        print(
            f"  N = {n_value}"
        )
        print(
            f"  K_TRUE = {k_true}"
        )

        print()

        print("TRACE TEST")
        print(
            f"  R1 + R2 == Trace(R) : "
            f"{trace_pass}"
        )
        print(
            f"  numerator digits = "
            f"{len(str(abs(int(sp.numer(trace_specialized)))))}"
        )
        print(
            f"  denominator digits = "
            f"{len(str(abs(int(sp.denom(trace_specialized)))))}"
        )

        print()

        print("NORM TEST")
        print(
            f"  R1 * R2 == Norm(R) : "
            f"{norm_pass}"
        )
        print(
            f"  numerator digits = "
            f"{len(str(abs(int(sp.numer(norm_specialized)))))}"
        )
        print(
            f"  denominator digits = "
            f"{len(str(abs(int(sp.denom(norm_specialized)))))}"
        )

        print()

        print("TRUE BRANCH CONSISTENCY")
        print(
            f"  Trace direct == specialized : "
            f"{trace_pass}"
        )
        print(
            f"  Norm direct == specialized  : "
            f"{norm_pass}"
        )

        results.append(
            (
                trace_pass,
                norm_pass,
            )
        )

    # =========================================================================
    # GLOBAL
    # =========================================================================

    print()
    print("=" * 110)
    print("GLOBAL SUMMARY")
    print("=" * 110)
    print()

    print(
        "  all Trace identities pass = "
        f"{all(x[0] for x in results)}"
    )

    print(
        "  all Norm identities pass = "
        f"{all(x[1] for x in results)}"
    )

    print()
    print("=" * 110)
    print("EXPERIMENT 388 FINAL STATUS")
    print("=" * 110)
    print()

    print(
        "The experiment tests whether the two layer branches can be"
    )
    print(
        "compressed directly into their symmetric quantities:"
    )
    print()
    print(
        "    Trace(R) = R(t1) + R(t2)"
    )
    print(
        "    Norm(R)  = R(t1) R(t2)"
    )
    print()
    print(
        "If the resulting N,K expressions are substantially simpler"
    )
    print(
        "than the degree-20 resultant, those are the preferred"
    )
    print(
        "objects for the next elimination stage."
    )
    print()
    print("=" * 110)
    print("EXPERIMENT 388 FINISHED")
    print("=" * 110)


if __name__ == "__main__":
    main()
