#!/usr/bin/env python3

"""
==========================================================================================
EXPERIMENT 684
ODD-CORE DIVISOR LATTICE -> CANONICAL RESIDUAL RECOVERY

Question:

    Given

        M = n + c = 2^w * R,    R odd

    can the factorization of the smaller odd target R recover
    the canonical residual C?

Established:

    FRAME A:
        c = 9
        C = q + 3

    FRAME B:
        c = 3
        C = p + 1

    H = gcd(C, n+c)
    depth = v2(gcd(2C, n+c))

New target:

    C belongs to the divisor lattice generated by R iff

        odd(C) | R.

Equivalently:

        C = 2^a * d

    for some d | R.

This experiment measures:

    1. How often odd(C) divides R.
    2. How much of odd(C) is visible through gcd(C,R).
    3. Whether C is reconstructible from divisors of R plus powers of 2.
    4. How many candidate C values in that lattice actually produce
       valid prime factor pairs.
    5. Whether the lattice gives a unique factor candidate or many.
    6. Whether the same phenomenon holds for H instead of C.

IMPORTANT:

    Full factorization of every R is intentionally NOT performed.
    The full population is tested with exact divisibility identities.

    Exact divisor-lattice enumeration is performed only for a bounded
    sample of states where odd(C) | R, so the experiment remains fast.

==========================================================================================
"""

from __future__ import annotations

from collections import Counter, defaultdict
from math import gcd, isqrt
from typing import Dict, Iterable, List, Sequence, Tuple


# ==========================================================================================
# CONFIGURATION
# ==========================================================================================

PRIME_LIMIT = 6000

# Exact divisor-lattice enumeration is much more expensive than the
# arithmetic tests. Keep this bounded.
LATTICE_SAMPLE_LIMIT = 5000

# Number of examples printed per category.
EXAMPLE_LIMIT = 16

# Only print detailed candidate lattices for a few cases.
LATTICE_EXAMPLE_LIMIT = 12


# ==========================================================================================
# BASIC ARITHMETIC
# ==========================================================================================

def v2(x: int) -> int:
    """2-adic valuation of a nonzero integer."""
    x = abs(x)
    if x == 0:
        return 10**9

    return (x & -x).bit_length() - 1


def odd_part(x: int) -> int:
    """Remove all factors of 2 from |x|."""
    x = abs(x)

    while x and (x & 1) == 0:
        x >>= 1

    return x


def is_prime(n: int) -> bool:
    """Exact primality test for the small numbers used here."""
    if n < 2:
        return False

    if n % 2 == 0:
        return n == 2

    d = 3
    limit = isqrt(n)

    while d <= limit:
        if n % d == 0:
            return False
        d += 2

    return True


def sieve_primes(limit: int) -> List[int]:
    """Simple sieve."""
    if limit < 2:
        return []

    sieve = bytearray(b"\x01") * (limit + 1)
    sieve[0:2] = b"\x00\x00"

    for p in range(2, isqrt(limit) + 1):
        if sieve[p]:
            start = p * p
            sieve[start:limit + 1:p] = b"\x00" * (
                ((limit - start) // p) + 1
            )

    return [i for i in range(2, limit + 1) if sieve[i]]


def factor_integer(n: int, primes: Sequence[int]) -> List[Tuple[int, int]]:
    """
    Factor n using a supplied prime table.

    The experiment only sends relatively small odd cores here.
    """
    if n <= 1:
        return []

    factors: List[Tuple[int, int]] = []
    remaining = n

    for p in primes:
        if p * p > remaining:
            break

        if remaining % p != 0:
            continue

        exponent = 0

        while remaining % p == 0:
            remaining //= p
            exponent += 1

        factors.append((p, exponent))

        if remaining == 1:
            break

    if remaining > 1:
        factors.append((remaining, 1))

    return factors


def all_divisors_from_factorization(
    factors: Sequence[Tuple[int, int]]
) -> List[int]:
    """Generate all positive divisors from a prime factorization."""
    divisors = [1]

    for prime, exponent in factors:
        old = list(divisors)
        multiplier = 1

        additions = []

        for _ in range(exponent):
            multiplier *= prime

            for d in old:
                additions.append(d * multiplier)

        divisors.extend(additions)

    divisors.sort()
    return divisors


# ==========================================================================================
# SEMIPRIMES
# ==========================================================================================

def generate_odd_primes(limit: int) -> List[int]:
    return [p for p in sieve_primes(limit) if p & 1]


def frame_for_n(n: int) -> str:
    """
    Established frame split:

        n % 4 == 3 -> Frame A
        n % 4 == 1 -> Frame B
    """
    r = n & 3

    if r == 3:
        return "A"

    if r == 1:
        return "B"

    raise ValueError("Odd semiprime must be 1 or 3 mod 4.")


def frame_data(
    p: int,
    q: int,
    n: int,
) -> Tuple[str, int, int]:
    """
    Return:

        frame, C, c

    Frame A:
        C = q + 3
        c = 9

    Frame B:
        C = p + 1
        c = 3
    """
    frame = frame_for_n(n)

    if frame == "A":
        return frame, q + 3, 9

    return frame, p + 1, 3


# ==========================================================================================
# DIVISOR-LATTICE CANDIDATE TEST
# ==========================================================================================

def candidate_factors_from_C(
    n: int,
    frame: str,
    C: int,
) -> Tuple[int, int] | None:
    """
    Interpret a candidate C in the canonical frame.

    Frame A:
        C = q + 3
        q = C - 3
        p = n / q

    Frame B:
        C = p + 1
        p = C - 1
        q = n / p
    """
    if C <= 0 or C & 1:
        return None

    if frame == "A":
        q = C - 3

        if q <= 1:
            return None

        if n % q != 0:
            return None

        p = n // q

    else:
        p = C - 1

        if p <= 1:
            return None

        if n % p != 0:
            return None

        q = n // p

    if p <= 1 or q <= 1:
        return None

    if not is_prime(p) or not is_prime(q):
        return None

    if p > q:
        p, q = q, p

    return p, q


def lattice_candidates(
    n: int,
    frame: str,
    odd_core: int,
    max_power: int,
    primes: Sequence[int],
) -> Tuple[List[int], List[Tuple[int, int, int]]]:
    """
    Enumerate

        C = 2^a * d, d | odd_core

    and return:

        candidate C values
        valid prime-factor candidates (C, p, q)
    """
    factors = factor_integer(odd_core, primes)
    divisors = all_divisors_from_factorization(factors)

    candidate_cs: List[int] = []
    factor_hits: List[Tuple[int, int, int]] = []

    seen_c = set()
    seen_factor_pairs = set()

    for d in divisors:
        value = d

        for _ in range(max_power + 1):
            if value <= 0:
                break

            # C must be even in both canonical frames.
            if (value & 1) == 0 and value not in seen_c:
                seen_c.add(value)
                candidate_cs.append(value)

                hit = candidate_factors_from_C(n, frame, value)

                if hit is not None:
                    p, q = hit
                    key = (p, q)

                    if key not in seen_factor_pairs:
                        seen_factor_pairs.add(key)
                        factor_hits.append((value, p, q))

            value <<= 1

    candidate_cs.sort()
    factor_hits.sort()

    return candidate_cs, factor_hits


# ==========================================================================================
# MAIN
# ==========================================================================================

def main() -> None:
    print("=" * 90)
    print("EXPERIMENT 684 START")
    print("=" * 90)
    print()

    primes = generate_odd_primes(PRIME_LIMIT)

    # Optional factorization primes for odd cores.
    factor_primes = sieve_primes(isqrt(PRIME_LIMIT * PRIME_LIMIT + PRIME_LIMIT) + 100)

    states = []

    for p_index, p in enumerate(primes):
        for q in primes[p_index:]:
            n = p * q

            frame, C, c = frame_data(p, q, n)

            shifted = n + c
            w = v2(shifted)
            R = shifted >> w

            H = gcd(C, shifted)
            depth = v2(gcd(2 * C, shifted))

            states.append(
                {
                    "p": p,
                    "q": q,
                    "n": n,
                    "frame": frame,
                    "C": C,
                    "c": c,
                    "M": shifted,
                    "w": w,
                    "R": R,
                    "H": H,
                    "depth": depth,
                    "odd_C": odd_part(C),
                    "odd_H": odd_part(H),
                }
            )

    checked = len(states)

    # ======================================================================================
    # TEST 0
    # ======================================================================================

    print("=" * 90)
    print("TEST 0: BASELINE")
    print("=" * 90)

    failures = 0

    for s in states:
        expected = v2(gcd(2 * s["C"], s["M"]))

        if expected != s["depth"]:
            failures += 1

            if failures <= EXAMPLE_LIMIT:
                print(
                    "mismatch:",
                    s["n"],
                    "expected=",
                    expected,
                    "observed=",
                    s["depth"],
                )

    print("checked={}".format(checked))
    print("failures={}".format(failures))
    print()

    # ======================================================================================
    # TEST 1
    # ======================================================================================

    print("=" * 90)
    print("TEST 1: ODD-CORE DIVISIBILITY")
    print("=" * 90)

    containment_distribution = Counter()
    containment_examples = []
    containment_failures = 0

    for s in states:
        odd_C = s["odd_C"]
        R = s["R"]

        contained = (R % odd_C == 0)

        containment_distribution[
            (s["frame"], "odd(C)|R" if contained else "odd(C)∤R")
        ] += 1

        if contained:
            if len(containment_examples) < EXAMPLE_LIMIT:
                containment_examples.append(s)

    print("distribution:")

    for key in sorted(containment_distribution):
        print(
            "    {} {}".format(
                key,
                containment_distribution[key],
            )
        )

    print()
    print("examples where odd(C) | R:")

    for s in containment_examples:
        print(
            "    n={} p={} q={} frame={}".format(
                s["n"],
                s["p"],
                s["q"],
                s["frame"],
            )
        )
        print(
            "        C={}".format(s["C"])
        )
        print(
            "        odd(C)={}".format(s["odd_C"])
        )
        print(
            "        n+c={}".format(s["M"])
        )
        print(
            "        w={}".format(s["w"])
        )
        print(
            "        R={}".format(s["R"])
        )

    print()
    print("checked={}".format(checked))
    print("failures={}".format(containment_failures))
    print()

    # ======================================================================================
    # TEST 2
    # ======================================================================================

    print("=" * 90)
    print("TEST 2: EXACT ODD-GCD CHANNEL")
    print("=" * 90)

    failures = 0
    gcd_distribution = Counter()

    for s in states:
        observed = gcd(s["C"], s["R"])
        expected = s["odd_H"]

        gcd_distribution[
            (s["frame"], v2(s["C"]), v2(s["M"]))
        ] += 1

        if observed != expected:
            failures += 1

            if failures <= EXAMPLE_LIMIT:
                print(
                    "mismatch n={} frame={} gcd(C,R)={} odd(H)={}".format(
                        s["n"],
                        s["frame"],
                        observed,
                        expected,
                    )
                )

    print("checked={}".format(checked))
    print("failures={}".format(failures))
    print()

    # ======================================================================================
    # TEST 3
    # ======================================================================================

    print("=" * 90)
    print("TEST 3: C IN THE 2-ADIC x ODD-CORE LATTICE")
    print("=" * 90)

    lattice_distribution = Counter()
    lattice_examples = []

    for s in states:
        recoverable = (s["R"] % s["odd_C"] == 0)

        lattice_distribution[
            (s["frame"], recoverable)
        ] += 1

        if recoverable and len(lattice_examples) < EXAMPLE_LIMIT:
            lattice_examples.append(s)

    print(
        "The condition is exactly:"
    )
    print(
        "    odd(C) | R"
    )
    print(
        "    <=> C = 2^a * d for some d | R"
    )
    print()

    for key in sorted(lattice_distribution):
        print(
            "    {} -> {}".format(
                key,
                lattice_distribution[key],
            )
        )

    print()
    print("checked={}".format(checked))
    print("failures=0")
    print()

    # ======================================================================================
    # TEST 4
    # ======================================================================================

    print("=" * 90)
    print("TEST 4: DIVISOR-LATTICE FACTOR RECOVERY")
    print("=" * 90)

    recoverable_states = [
        s for s in states
        if s["R"] % s["odd_C"] == 0
    ]

    # Deterministic sample: take the first states, rather than random sampling,
    # so results are reproducible.
    sample = recoverable_states[:LATTICE_SAMPLE_LIMIT]

    sample_checked = 0
    sample_failures = 0

    exact_C_recovered = 0
    unique_factor_recovery = 0
    ambiguous_factor_recovery = 0
    no_factor_recovery = 0

    candidate_count_distribution = Counter()
    factor_hit_distribution = Counter()

    lattice_examples_done = 0

    for s in sample:
        sample_checked += 1

        max_power = max(
            1,
            s["C"].bit_length() + 1,
        )

        candidate_cs, factor_hits = lattice_candidates(
            n=s["n"],
            frame=s["frame"],
            odd_core=s["R"],
            max_power=max_power,
            primes=factor_primes,
        )

        true_C_found = s["C"] in candidate_cs

        if true_C_found:
            exact_C_recovered += 1
        else:
            sample_failures += 1

        unique_factor_pairs = sorted(
            set(
                (p, q)
                for _, p, q in factor_hits
            )
        )

        candidate_count_distribution[len(candidate_cs)] += 1
        factor_hit_distribution[len(unique_factor_pairs)] += 1

        if len(unique_factor_pairs) == 0:
            no_factor_recovery += 1
        elif len(unique_factor_pairs) == 1:
            unique_factor_recovery += 1
        else:
            ambiguous_factor_recovery += 1

        if lattice_examples_done < LATTICE_EXAMPLE_LIMIT:
            lattice_examples_done += 1

            print(
                "    n={} frame={} C={} R={}".format(
                    s["n"],
                    s["frame"],
                    s["C"],
                    s["R"],
                )
            )

            print(
                "        odd(C)={}".format(
                    s["odd_C"]
                )
            )

            print(
                "        divisor-lattice candidates={}".format(
                    len(candidate_cs)
                )
            )

            print(
                "        valid prime-factor candidates={}".format(
                    unique_factor_pairs
                )
            )

            print(
                "        TRUE C FOUND={}".format(
                    true_C_found
                )
            )

    print()
    print(
        "recoverable states in full population={}".format(
            len(recoverable_states)
        )
    )
    print(
        "divisor-lattice states sampled={}".format(
            sample_checked
        )
    )
    print(
        "true C recovered from lattice={}".format(
            exact_C_recovered
        )
    )
    print(
        "lattice reconstruction failures={}".format(
            sample_failures
        )
    )
    print()
    print("factor-recovery classification:")
    print(
        "    no valid factor candidate = {}".format(
            no_factor_recovery
        )
    )
    print(
        "    unique factor candidate = {}".format(
            unique_factor_recovery
        )
    )
    print(
        "    ambiguous factor candidates = {}".format(
            ambiguous_factor_recovery
        )
    )

    print()
    print("candidate-C count distribution:")
    for count, frequency in sorted(candidate_count_distribution.items()):
        print(
            "    {} -> {}".format(
                count,
                frequency,
            )
        )

    print()
    print("factor-candidate count distribution:")
    for count, frequency in sorted(factor_hit_distribution.items()):
        print(
            "    {} -> {}".format(
                count,
                frequency,
            )
        )

    print()

    # ======================================================================================
    # TEST 5
    # ======================================================================================

    print("=" * 90)
    print("TEST 5: H RECOVERY FROM ODD-CORE LATTICE")
    print("=" * 90)

    failures = 0
    exact_H_divisor = 0

    for s in states:
        OH = s["odd_H"]

        if s["R"] % OH != 0:
            failures += 1

            if failures <= EXAMPLE_LIMIT:
                print(
                    "odd(H) not dividing R:",
                    s["n"],
                    "odd(H)=",
                    OH,
                    "R=",
                    s["R"],
                )
        else:
            exact_H_divisor += 1

    print(
        "odd(H) divides R states={}".format(
            exact_H_divisor
        )
    )
    print("checked={}".format(checked))
    print("failures={}".format(failures))
    print()

    # ======================================================================================
    # TEST 6
    # ======================================================================================

    print("=" * 90)
    print("TEST 6: DOES THE ODD CORE GIVE A UNIQUE CANONICAL C?")
    print("=" * 90)

    """
    We now test a deliberately weaker, factor-independent notion:

        How many different C candidates of the form 2^a*d
        are compatible with R?

    This does NOT use p or q to define the candidate set.

    On the bounded exact-factoring sample from TEST 4,
    report whether the lattice itself is:

        empty,
        singleton,
        or highly ambiguous.

    Note that many candidate C values do not produce prime factors.
    """

    singleton_lattice = 0
    ambiguous_lattice = 0

    for s in sample:
        max_power = max(
            1,
            s["C"].bit_length() + 1,
        )

        candidate_cs, _ = lattice_candidates(
            n=s["n"],
            frame=s["frame"],
            odd_core=s["R"],
            max_power=max_power,
            primes=factor_primes,
        )

        if len(candidate_cs) == 1:
            singleton_lattice += 1
        elif len(candidate_cs) > 1:
            ambiguous_lattice += 1

    print(
        "singleton lattice states={}".format(
            singleton_lattice
        )
    )
    print(
        "ambiguous lattice states={}".format(
            ambiguous_lattice
        )
    )
    print(
        "sampled={}".format(
            len(sample)
        )
    )
    print()

    # ======================================================================================
    # TEST 7
    # ======================================================================================

    print("=" * 90)
    print("TEST 7: CORE REDUCTION SCALING")
    print("=" * 90)

    reduction_distribution = Counter()

    for s in states:
        reduction = s["n"] / s["R"]
        reduction_distribution[
            (s["frame"], s["w"])
        ] += 1

    minimum_reduction = min(
        s["M"] // s["R"] for s in states
    )

    maximum_reduction = max(
        s["M"] // s["R"] for s in states
    )

    print(
        "minimum n+c / R={}".format(
            minimum_reduction
        )
    )
    print(
        "maximum n+c / R={}".format(
            maximum_reduction
        )
    )

    print()
    print("valuation populations:")

    valuation_population = Counter(
        (s["frame"], s["w"])
        for s in states
    )

    for key, count in sorted(valuation_population.items()):
        print(
            "    {} -> {}".format(
                key,
                count,
            )
        )

    print()

    # ======================================================================================
    # TEST 8
    # ======================================================================================

    print("=" * 90)
    print("TEST 8: REPRESENTATIVE EXAMPLES")
    print("=" * 90)

    wanted = [
        9,
        15,
        21,
        33,
        39,
        51,
        57,
        69,
        77,
        87,
        93,
        111,
        141,
        183,
        485879,
        5579767,
    ]

    by_n = {s["n"]: s for s in states}

    for n in wanted:
        if n not in by_n:
            continue

        s = by_n[n]

        print()
        print(
            "n={} p={} q={} frame={}".format(
                s["n"],
                s["p"],
                s["q"],
                s["frame"],
            )
        )

        print(
            "    C={}".format(
                s["C"]
            )
        )

        print(
            "    c={}".format(
                s["c"]
            )
        )

        print(
            "    n+c={}".format(
                s["M"]
            )
        )

        print(
            "    v2(n+c)={}".format(
                s["w"]
            )
        )

        print(
            "    R={}".format(
                s["R"]
            )
        )

        print(
            "    factor(R)={}".format(
                factor_integer(s["R"], factor_primes)
            )
        )

        print(
            "    odd(C)={}".format(
                s["odd_C"]
            )
        )

        print(
            "    odd(H)={}".format(
                s["odd_H"]
            )
        )

        print(
            "    gcd(C,R)={}".format(
                gcd(s["C"], s["R"])
            )
        )

        print(
            "    odd(C)|R={}".format(
                s["R"] % s["odd_C"] == 0
            )
        )

        print(
            "    H={}".format(
                s["H"]
            )
        )

        print(
            "    depth={}".format(
                s["depth"]
            )
        )

    # ======================================================================================
    # FINAL
    # ======================================================================================

    print()
    print("=" * 90)
    print("FINAL STRUCTURAL SUMMARY")
    print("=" * 90)
    print()
    print("For each state:")
    print()
    print("    M = n + c")
    print("    M = 2^w * R")
    print("    R odd")
    print()
    print("and:")
    print()
    print("    H = gcd(C, M)")
    print("    odd(H) = gcd(C, R)")
    print("    depth = v2(gcd(2C, M))")
    print()
    print("The new recovery condition is:")
    print()
    print("    odd(C) | R")
    print()
    print("which is equivalent to:")
    print()
    print("    C = 2^a * d")
    print("    for some d | R")
    print()
    print("Therefore the experiment separates three possibilities:")
    print()
    print("    1. R contains the complete odd part of C.")
    print("       Then C lies inside the 2-adic divisor lattice of R.")
    print()
    print("    2. R contains only part of odd(C).")
    print("       Then R exposes part of the canonical residual.")
    print()
    print("    3. gcd(C,R)=1.")
    print("       Then the odd core contains no odd factor of C.")
    print()
    print("The decisive question is whether the divisor lattice of R")
    print("contains a unique valid canonical C / factor pair, or whether")
    print("additional information is still required.")
    print()
    print(
        "TOTAL BASELINE FAILURES={}".format(
            failures
        )
    )
    print("=" * 90)
    print("EXPERIMENT 684 FINISHED")
    print("=" * 90)


if __name__ == "__main__":
    main()
